CREATE TABLE IF NOT EXISTS `{{prefix}}ai_call_log` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `site_id` int NOT NULL DEFAULT 0 COMMENT '站点ID',
  `request_id` varchar(100) NOT NULL DEFAULT '' COMMENT '请求幂等标识',
  `scene_key` varchar(100) NOT NULL DEFAULT '' COMMENT 'AI场景',
  `source_plugin` varchar(60) NOT NULL DEFAULT '' COMMENT '来源插件',
  `source_type` varchar(80) NOT NULL DEFAULT '' COMMENT '来源业务类型',
  `source_id` varchar(100) NOT NULL DEFAULT '' COMMENT '来源业务ID',
  `operator_uid` int NOT NULL DEFAULT 0 COMMENT '操作人UID',
  `operator_name` varchar(60) NOT NULL DEFAULT '' COMMENT '操作人名称',
  `provider_id` varchar(60) NOT NULL DEFAULT '' COMMENT '模型通道',
  `model` varchar(120) NOT NULL DEFAULT '' COMMENT '模型标识',
  `status` varchar(20) NOT NULL DEFAULT 'pending' COMMENT 'pending/processing/success/failed',
  `prompt_hash` char(64) NOT NULL DEFAULT '' COMMENT '规范化请求哈希',
  `request_meta_json` longtext NULL COMMENT '脱敏请求元数据',
  `response_meta_json` longtext NULL COMMENT '响应元数据',
  `prompt_tokens` int unsigned NOT NULL DEFAULT 0,
  `completion_tokens` int unsigned NOT NULL DEFAULT 0,
  `total_tokens` int unsigned NOT NULL DEFAULT 0,
  `latency_ms` int unsigned NOT NULL DEFAULT 0,
  `error_message` varchar(1000) NOT NULL DEFAULT '',
  `started_at` int NOT NULL DEFAULT 0,
  `finished_at` int NOT NULL DEFAULT 0,
  `create_at` int NOT NULL DEFAULT 0,
  `update_at` int NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_site_request` (`site_id`,`request_id`),
  KEY `idx_site_scene` (`site_id`,`scene_key`,`create_at`),
  KEY `idx_site_status` (`site_id`,`status`,`create_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AI模型调用审计日志';
