CREATE TABLE IF NOT EXISTS `{{prefix}}ai_call_log` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `site_id` int NOT NULL DEFAULT 0 COMMENT '站点ID',
  `request_id` varchar(100) NOT NULL DEFAULT '' COMMENT '请求幂等标识',
  `scene_key` varchar(100) NOT NULL DEFAULT '' COMMENT 'AI场景',
  `source_plugin` varchar(60) NOT NULL DEFAULT '' COMMENT '来源插件',
  `source_type` varchar(80) NOT NULL DEFAULT '' COMMENT '来源业务类型',
  `source_id` varchar(100) NOT NULL DEFAULT '' COMMENT '来源业务ID',
  `operator_uid` int NOT NULL DEFAULT 0 COMMENT '操作人UID',
  `operator_name` varchar(60) NOT NULL DEFAULT '' COMMENT '操作人名称',
  `provider_id` varchar(60) NOT NULL DEFAULT '' COMMENT '模型通道',
  `model` varchar(120) NOT NULL DEFAULT '' COMMENT '模型标识',
  `status` varchar(20) NOT NULL DEFAULT 'pending' COMMENT 'pending/processing/success/failed',
  `prompt_hash` char(64) NOT NULL DEFAULT '' COMMENT '规范化请求哈希',
  `request_meta_json` longtext NULL COMMENT '脱敏请求元数据',
  `response_meta_json` longtext NULL COMMENT '响应元数据',
  `prompt_tokens` int unsigned NOT NULL DEFAULT 0,
  `completion_tokens` int unsigned NOT NULL DEFAULT 0,
  `total_tokens` int unsigned NOT NULL DEFAULT 0,
  `latency_ms` int unsigned NOT NULL DEFAULT 0,
  `error_message` varchar(1000) NOT NULL DEFAULT '',
  `started_at` int NOT NULL DEFAULT 0,
  `finished_at` int NOT NULL DEFAULT 0,
  `create_at` int NOT NULL DEFAULT 0,
  `update_at` int NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_site_request` (`site_id`,`request_id`),
  KEY `idx_site_scene` (`site_id`,`scene_key`,`create_at`),
  KEY `idx_site_status` (`site_id`,`status`,`create_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AI模型调用审计日志';

CREATE TABLE IF NOT EXISTS `{{prefix}}ai_conversation` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `site_id` int NOT NULL DEFAULT 0 COMMENT '站点ID',
  `conversation_no` varchar(60) NOT NULL DEFAULT '' COMMENT '会话编号',
  `actor_type` varchar(20) NOT NULL DEFAULT 'member' COMMENT 'member/admin/guest',
  `actor_id` int NOT NULL DEFAULT 0 COMMENT '会话主体ID',
  `entry_plugin` varchar(60) NOT NULL DEFAULT '' COMMENT '入口插件',
  `scene_key` varchar(100) NOT NULL DEFAULT '' COMMENT '当前AI场景',
  `agent_key` varchar(100) NOT NULL DEFAULT '' COMMENT '当前智能体',
  `title` varchar(120) NOT NULL DEFAULT '' COMMENT '会话标题',
  `summary` varchar(1000) NOT NULL DEFAULT '' COMMENT '会话摘要',
  `last_intent` varchar(80) NOT NULL DEFAULT '' COMMENT '最近意图',
  `message_count` int unsigned NOT NULL DEFAULT 0,
  `last_message_at` int NOT NULL DEFAULT 0,
  `risk_level` tinyint unsigned NOT NULL DEFAULT 0,
  `status` varchar(20) NOT NULL DEFAULT 'active' COMMENT 'active/archived/blocked',
  `create_at` int NOT NULL DEFAULT 0,
  `update_at` int NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_site_conversation` (`site_id`,`conversation_no`),
  KEY `idx_site_actor` (`site_id`,`actor_type`,`actor_id`,`status`,`last_message_at`),
  KEY `idx_site_scene` (`site_id`,`scene_key`,`last_message_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AI会话';

CREATE TABLE IF NOT EXISTS `{{prefix}}ai_message` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `site_id` int NOT NULL DEFAULT 0 COMMENT '站点ID',
  `conversation_id` bigint unsigned NOT NULL DEFAULT 0 COMMENT '会话ID',
  `request_id` varchar(100) NOT NULL DEFAULT '' COMMENT '请求幂等标识',
  `role` varchar(20) NOT NULL DEFAULT '' COMMENT 'user/assistant/system/tool',
  `content_format` varchar(20) NOT NULL DEFAULT 'markdown' COMMENT 'markdown/text',
  `content` longtext NULL COMMENT '消息正文，不保存模型推理过程',
  `blocks_json` longtext NULL COMMENT '结构化内容块',
  `resources_json` longtext NULL COMMENT '业务资源快照',
  `actions_json` longtext NULL COMMENT '服务端批准的动作',
  `provider_id` varchar(60) NOT NULL DEFAULT '',
  `model` varchar(120) NOT NULL DEFAULT '',
  `status` varchar(20) NOT NULL DEFAULT 'success' COMMENT 'pending/success/failed',
  `prompt_tokens` int unsigned NOT NULL DEFAULT 0,
  `completion_tokens` int unsigned NOT NULL DEFAULT 0,
  `total_tokens` int unsigned NOT NULL DEFAULT 0,
  `latency_ms` int unsigned NOT NULL DEFAULT 0,
  `error_message` varchar(1000) NOT NULL DEFAULT '',
  `create_at` int NOT NULL DEFAULT 0,
  `update_at` int NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_conversation_request_role` (`conversation_id`,`request_id`,`role`),
  KEY `idx_site_conversation` (`site_id`,`conversation_id`,`id`),
  KEY `idx_site_request` (`site_id`,`request_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AI会话消息';

CREATE TABLE IF NOT EXISTS `{{prefix}}ai_tool_run` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `site_id` int NOT NULL DEFAULT 0,
  `conversation_id` bigint unsigned NOT NULL DEFAULT 0,
  `message_id` bigint unsigned NOT NULL DEFAULT 0,
  `request_id` varchar(100) NOT NULL DEFAULT '',
  `step_no` int unsigned NOT NULL DEFAULT 0,
  `tool_key` varchar(120) NOT NULL DEFAULT '',
  `source_plugin` varchar(60) NOT NULL DEFAULT '',
  `read_only` tinyint unsigned NOT NULL DEFAULT 1,
  `permission_decision` varchar(30) NOT NULL DEFAULT '',
  `arguments_hash` char(64) NOT NULL DEFAULT '',
  `request_meta_json` longtext NULL,
  `response_meta_json` longtext NULL,
  `status` varchar(20) NOT NULL DEFAULT 'pending',
  `duration_ms` int unsigned NOT NULL DEFAULT 0,
  `error_message` varchar(1000) NOT NULL DEFAULT '',
  `create_at` int NOT NULL DEFAULT 0,
  `update_at` int NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_site_conversation` (`site_id`,`conversation_id`,`id`),
  KEY `idx_site_request` (`site_id`,`request_id`,`step_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AI工具调用审计';

CREATE TABLE IF NOT EXISTS `{{prefix}}ai_risk_event` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `site_id` int NOT NULL DEFAULT 0,
  `conversation_id` bigint unsigned NOT NULL DEFAULT 0,
  `actor_type` varchar(20) NOT NULL DEFAULT '',
  `actor_id` int NOT NULL DEFAULT 0,
  `ip_hash` char(64) NOT NULL DEFAULT '',
  `device_hash` char(64) NOT NULL DEFAULT '',
  `risk_type` varchar(80) NOT NULL DEFAULT '',
  `risk_level` tinyint unsigned NOT NULL DEFAULT 0,
  `risk_score` decimal(6,2) NOT NULL DEFAULT 0.00,
  `evidence_json` longtext NULL,
  `action` varchar(40) NOT NULL DEFAULT '',
  `status` varchar(20) NOT NULL DEFAULT 'open',
  `frozen_until` int NOT NULL DEFAULT 0,
  `reviewer_uid` int NOT NULL DEFAULT 0,
  `reviewer_name` varchar(60) NOT NULL DEFAULT '',
  `reviewed_at` int NOT NULL DEFAULT 0,
  `remark` varchar(1000) NOT NULL DEFAULT '',
  `create_at` int NOT NULL DEFAULT 0,
  `update_at` int NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_site_actor` (`site_id`,`actor_type`,`actor_id`,`status`,`create_at`),
  KEY `idx_site_level` (`site_id`,`risk_level`,`status`,`create_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AI风险事件';

CREATE TABLE IF NOT EXISTS `{{prefix}}ai_demand` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `site_id` int NOT NULL DEFAULT 0,
  `conversation_id` bigint unsigned NOT NULL DEFAULT 0,
  `actor_type` varchar(20) NOT NULL DEFAULT '',
  `actor_id` int NOT NULL DEFAULT 0,
  `intent` varchar(80) NOT NULL DEFAULT '',
  `customer_type` varchar(20) NOT NULL DEFAULT 'unknown' COMMENT 'consumer/peer/unknown',
  `entities_json` longtext NULL,
  `budget_min` decimal(12,2) NOT NULL DEFAULT 0.00,
  `budget_max` decimal(12,2) NOT NULL DEFAULT 0.00,
  `requirements_json` longtext NULL,
  `urgency` varchar(20) NOT NULL DEFAULT 'normal',
  `lead_score` decimal(6,2) NOT NULL DEFAULT 0.00,
  `confidence` decimal(6,4) NOT NULL DEFAULT 0.0000,
  `status` varchar(20) NOT NULL DEFAULT 'open',
  `assignee_uid` int NOT NULL DEFAULT 0,
  `assignee_name` varchar(60) NOT NULL DEFAULT '',
  `source_message_ids_json` longtext NULL,
  `create_at` int NOT NULL DEFAULT 0,
  `update_at` int NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_site_actor` (`site_id`,`actor_type`,`actor_id`,`status`,`create_at`),
  KEY `idx_site_intent` (`site_id`,`intent`,`status`,`create_at`),
  KEY `idx_site_assignee` (`site_id`,`assignee_uid`,`status`,`create_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AI结构化客户需求';
