<?php
return [
    [
        'menu_name' => '会员服务卡',
        'menu_key' => 'hsx_member_card_manage',
        'menu_short_name' => '会员卡',
        'parent_select_key' => '',
        'parent_key' => 'hsx_erp_manage',
        'menu_type' => '0',
        'icon' => 'nc-iconfont nc-icon-huiyuan',
        'api_url' => '',
        'router_path' => 'hsx_member_card',
        'view_path' => '',
        'methods' => '',
        'sort' => '85',
        'status' => '1',
        'is_show' => '1',
        'children' => [
            [
                'menu_name' => '会员卡工作台',
                'menu_key' => 'hsx_member_card_dashboard',
                'menu_short_name' => '工作台',
                'parent_select_key' => '',
                'menu_type' => '1',
                'icon' => '',
                'api_url' => 'member_card/dashboard',
                'router_path' => 'hsx_member_card/dashboard',
                'view_path' => 'dashboard/index',
                'methods' => 'get',
                'sort' => '120',
                'status' => '1',
                'is_show' => '1',
            ],
            [
                'menu_name' => '卡种管理',
                'menu_key' => 'hsx_member_card_product',
                'menu_short_name' => '卡种管理',
                'parent_select_key' => '',
                'menu_type' => '1',
                'icon' => '',
                'api_url' => 'member_card/product/lists',
                'router_path' => 'hsx_member_card/product',
                'view_path' => 'product/index',
                'methods' => 'get',
                'sort' => '110',
                'status' => '1',
                'is_show' => '1',
                'children' => [
                    [
                        'menu_name' => '卡种选项',
                        'menu_key' => 'hsx_member_card_product_options',
                        'menu_short_name' => '卡种选项',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'member_card/product/options',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'get',
                        'sort' => '100',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '卡种详情',
                        'menu_key' => 'hsx_member_card_product_info',
                        'menu_short_name' => '卡种详情',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'member_card/product/<id>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'get',
                        'sort' => '99',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '保存卡种',
                        'menu_key' => 'hsx_member_card_product_save',
                        'menu_short_name' => '保存卡种',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'member_card/product/save',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '98',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '编辑卡种',
                        'menu_key' => 'hsx_member_card_product_update',
                        'menu_short_name' => '编辑卡种',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'member_card/product/save/<id>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '97',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '启停卡种',
                        'menu_key' => 'hsx_member_card_product_status',
                        'menu_short_name' => '启停卡种',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'member_card/product/<id>/enable',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '96',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '停用卡种',
                        'menu_key' => 'hsx_member_card_product_disable',
                        'menu_short_name' => '停用卡种',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'member_card/product/<id>/disable',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '95',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '删除卡种',
                        'menu_key' => 'hsx_member_card_product_delete',
                        'menu_short_name' => '删除卡种',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'member_card/product/<id>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'delete',
                        'sort' => '94',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                ],
            ],
            [
                'menu_name' => '开卡订单',
                'menu_key' => 'hsx_member_card_order',
                'menu_short_name' => '开卡订单',
                'parent_select_key' => '',
                'menu_type' => '1',
                'icon' => '',
                'api_url' => 'member_card/order/lists',
                'router_path' => 'hsx_member_card/order',
                'view_path' => 'order/index',
                'methods' => 'get',
                'sort' => '100',
                'status' => '1',
                'is_show' => '1',
                'children' => [
                    [
                        'menu_name' => '会员卡客户列表',
                        'menu_key' => 'hsx_member_card_member_lists',
                        'menu_short_name' => '会员卡客户列表',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'member_card/member/lists',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'get',
                        'sort' => '101',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '会员选择',
                        'menu_key' => 'hsx_member_card_member_options',
                        'menu_short_name' => '会员选择',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'member_card/member/options',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'get',
                        'sort' => '100',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '快速建客户',
                        'menu_key' => 'hsx_member_card_member_create',
                        'menu_short_name' => '快速建客户',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'member_card/member/quick_create',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '99',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '会员持卡',
                        'menu_key' => 'hsx_member_card_member_cards',
                        'menu_short_name' => '会员持卡',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'member_card/member/<member_id>/cards',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'get',
                        'sort' => '98',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '会员卡客户详情',
                        'menu_key' => 'hsx_member_card_member_info',
                        'menu_short_name' => '会员卡客户详情',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'member_card/member/<member_id>/info',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'get',
                        'sort' => '98',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '订单详情',
                        'menu_key' => 'hsx_member_card_order_info',
                        'menu_short_name' => '订单详情',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'member_card/order/<id>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'get',
                        'sort' => '97',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '快速开卡',
                        'menu_key' => 'hsx_member_card_order_create',
                        'menu_short_name' => '快速开卡',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'member_card/order/create',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '96',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '重试财务',
                        'menu_key' => 'hsx_member_card_order_retry_finance',
                        'menu_short_name' => '重试财务',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'member_card/order/<id>/retry_finance',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '95',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '取消开卡',
                        'menu_key' => 'hsx_member_card_order_cancel',
                        'menu_short_name' => '取消开卡',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'member_card/order/<id>/cancel',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '94',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '申请整卡退款',
                        'menu_key' => 'hsx_member_card_refund_apply',
                        'menu_short_name' => '申请整卡退款',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'member_card/order/<id>/refund/apply',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '93',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                ],
            ],
            [
                'menu_name' => '手机号核销',
                'menu_key' => 'hsx_member_card_card',
                'menu_short_name' => '手机号核销',
                'parent_select_key' => '',
                'menu_type' => '1',
                'icon' => '',
                'api_url' => 'member_card/card/search',
                'router_path' => 'hsx_member_card/card',
                'view_path' => 'card/index',
                'methods' => 'get',
                'sort' => '90',
                'status' => '1',
                'is_show' => '1',
                'children' => [
                    [
                        'menu_name' => '会员卡详情',
                        'menu_key' => 'hsx_member_card_card_info',
                        'menu_short_name' => '会员卡详情',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'member_card/card/<id>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'get',
                        'sort' => '100',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '确认核销',
                        'menu_key' => 'hsx_member_card_redeem',
                        'menu_short_name' => '确认核销',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'member_card/card/<id>/redeem',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '99',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '冻结会员卡',
                        'menu_key' => 'hsx_member_card_card_freeze',
                        'menu_short_name' => '冻结会员卡',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'member_card/card/<id>/freeze',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '98',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '解冻会员卡',
                        'menu_key' => 'hsx_member_card_card_unfreeze',
                        'menu_short_name' => '解冻会员卡',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'member_card/card/<id>/unfreeze',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '97',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                ],
            ],
            [
                'menu_name' => '核销记录',
                'menu_key' => 'hsx_member_card_redemption',
                'menu_short_name' => '核销记录',
                'parent_select_key' => '',
                'menu_type' => '1',
                'icon' => '',
                'api_url' => 'member_card/redemption/lists',
                'router_path' => 'hsx_member_card/redemption',
                'view_path' => 'redemption/index',
                'methods' => 'get',
                'sort' => '80',
                'status' => '1',
                'is_show' => '1',
                'children' => [
                    [
                        'menu_name' => '核销详情',
                        'menu_key' => 'hsx_member_card_redemption_info',
                        'menu_short_name' => '核销详情',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'member_card/redemption/<id>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'get',
                        'sort' => '100',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '核销冲正',
                        'menu_key' => 'hsx_member_card_redeem_reverse',
                        'menu_short_name' => '核销冲正',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'member_card/redemption/<id>/reverse',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '99',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                ],
            ],
            [
                'menu_name' => '退款记录',
                'menu_key' => 'hsx_member_card_refund',
                'menu_short_name' => '退款记录',
                'parent_select_key' => '',
                'menu_type' => '1',
                'icon' => '',
                'api_url' => 'member_card/refund/lists',
                'router_path' => 'hsx_member_card/refund',
                'view_path' => 'refund/index',
                'methods' => 'get',
                'sort' => '75',
                'status' => '1',
                'is_show' => '1',
                'children' => [
                    [
                        'menu_name' => '退款详情',
                        'menu_key' => 'hsx_member_card_refund_info',
                        'menu_short_name' => '退款详情',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'member_card/refund/<id>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'get',
                        'sort' => '100',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '重试退款财务',
                        'menu_key' => 'hsx_member_card_refund_retry',
                        'menu_short_name' => '重试退款财务',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'member_card/refund/<id>/retry_finance',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '99',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                ],
            ],
            [
                'menu_name' => '期初数据迁移',
                'menu_key' => 'hsx_member_card_migration',
                'menu_short_name' => '期初迁移',
                'parent_select_key' => '',
                'menu_type' => '1',
                'icon' => '',
                'api_url' => 'member_card/migration/lists',
                'router_path' => 'hsx_member_card/migration',
                'view_path' => 'migration/index',
                'methods' => 'get',
                'sort' => '72',
                'status' => '1',
                'is_show' => '1',
                'children' => [
                    [
                        'menu_name' => '发起期初同步',
                        'menu_key' => 'hsx_member_card_migration_start',
                        'menu_short_name' => '发起同步',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'member_card/migration/start',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '100',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '同步任务详情',
                        'menu_key' => 'hsx_member_card_migration_info',
                        'menu_short_name' => '任务详情',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'member_card/migration/<id>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'get',
                        'sort' => '99',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '同步明细',
                        'menu_key' => 'hsx_member_card_migration_items',
                        'menu_short_name' => '同步明细',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'member_card/migration/<id>/items',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'get',
                        'sort' => '98',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                ],
            ],
            [
                'menu_name' => '会员卡配置',
                'menu_key' => 'hsx_member_card_config',
                'menu_short_name' => '会员卡配置',
                'parent_select_key' => '',
                'menu_type' => '2',
                'icon' => '',
                'api_url' => 'member_card/config',
                'router_path' => '',
                'view_path' => '',
                'methods' => 'get',
                'sort' => '70',
                'status' => '1',
                'is_show' => '0',
            ],
            [
                'menu_name' => '保存会员卡配置',
                'menu_key' => 'hsx_member_card_config_save',
                'menu_short_name' => '保存会员卡配置',
                'parent_select_key' => '',
                'menu_type' => '2',
                'icon' => '',
                'api_url' => 'member_card/config',
                'router_path' => '',
                'view_path' => '',
                'methods' => 'post',
                'sort' => '69',
                'status' => '1',
                'is_show' => '0',
            ],
            [
                'menu_name' => '保存会员卡收款账户',
                'menu_key' => 'hsx_member_card_capital_account_save',
                'menu_short_name' => '保存收款账户',
                'parent_select_key' => '',
                'menu_type' => '2',
                'icon' => '',
                'api_url' => 'member_card/config/capital_account',
                'router_path' => '',
                'view_path' => '',
                'methods' => 'post',
                'sort' => '68',
                'status' => '1',
                'is_show' => '0',
            ],
            [
                'menu_name' => '删除会员卡收款账户',
                'menu_key' => 'hsx_member_card_capital_account_delete',
                'menu_short_name' => '删除收款账户',
                'parent_select_key' => '',
                'menu_type' => '2',
                'icon' => '',
                'api_url' => 'member_card/config/capital_account/<id>',
                'router_path' => '',
                'view_path' => '',
                'methods' => 'delete',
                'sort' => '67',
                'status' => '1',
                'is_show' => '0',
            ],
            [
                'menu_name' => '会员卡字典',
                'menu_key' => 'hsx_member_card_dicts',
                'menu_short_name' => '会员卡字典',
                'parent_select_key' => '',
                'menu_type' => '2',
                'icon' => '',
                'api_url' => 'member_card/dicts',
                'router_path' => '',
                'view_path' => '',
                'methods' => 'get',
                'sort' => '66',
                'status' => '1',
                'is_show' => '0',
            ],
        ],
    ],
];