<?php
return [
    'sd_xiaoyuan_order_pay_runner' => [
        'addon' => 'sd_xiaoyuan',
        'key' => 'sd_xiaoyuan_order_pay_runner',
        'receiver_type' => 1,
        'name' => '新订单通知接单员',
        'title' => '用户下单支付成功后通知同校接单员',
        'async' => true,
        'variable' => [
            'order_no' => '订单编号',
            'order_amount' => '跑腿费用',
            'order_money' => '订单金额',
            'service_type' => '服务类型',
            'service_name' => '服务名称',
            'delivery_address' => '配送地址',
            'create_time' => '下单时间',
            'url' => '订单链接',
        ],
    ],
    'sd_xiaoyuan_runner_apply' => [
        'addon' => 'sd_xiaoyuan',
        'key' => 'sd_xiaoyuan_runner_apply',
        'receiver_type' => 1,
        'name' => '骑手入驻申请审批通知',
        'title' => '有新骑手申请入驻时通知站点管理员',
        'async' => true,
        'variable' => [
            'real_name' => '申请姓名',
            'mobile' => '联系电话',
            'apply_time' => '申请时间',
            'url' => '审核链接',
        ],
    ],
    'sd_xiaoyuan_order_accept_user' => [
        'addon' => 'sd_xiaoyuan',
        'key' => 'sd_xiaoyuan_order_accept_user',
        'receiver_type' => 1,
        'name' => '跑手已接单提醒',
        'title' => '跑手接单后通知下单用户',
        'async' => true,
        'variable' => [
            'order_no' => '订单号',
            'task_name' => '任务名称',
            'service_type' => '服务类型',
            'runner_name' => '跑手姓名',
            'runner_mobile' => '跑手电话',
            'accept_time' => '接单时间',
            'url' => '订单链接',
        ],
    ],
    'sd_xiaoyuan_order_cancel_user' => [
        'addon' => 'sd_xiaoyuan',
        'key' => 'sd_xiaoyuan_order_cancel_user',
        'receiver_type' => 1,
        'name' => '订单取消通知',
        'title' => '订单取消后通知下单用户',
        'async' => true,
        'variable' => [
            'order_no' => '订单号',
            'cancel_time' => '取消时间',
            'operator' => '操作人',
            'cancel_reason' => '取消原因',
            'url' => '订单链接',
        ],
    ],
];
