CREATE TABLE IF NOT EXISTS `{{prefix}}recycle_quote_spider_source` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `site_id` int NOT NULL DEFAULT '0' COMMENT '站点ID',
  `source_key` varchar(64) NOT NULL DEFAULT '' COMMENT '报价源标识',
  `source_name` varchar(120) NOT NULL DEFAULT '' COMMENT '报价源名称',
  `provider` varchar(64) NOT NULL DEFAULT '' COMMENT '服务商',
  `base_url` varchar(255) NOT NULL DEFAULT '' COMMENT '基础地址',
  `list_path` varchar(255) NOT NULL DEFAULT '' COMMENT '列表接口',
  `detail_path` varchar(255) NOT NULL DEFAULT '' COMMENT '详情接口',
  `request_config` json DEFAULT NULL COMMENT '请求配置',
  `sync_enabled` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否开启自动同步',
  `sync_interval` int NOT NULL DEFAULT '86400' COMMENT '同步间隔秒',
  `timeout` int NOT NULL DEFAULT '15' COMMENT '超时秒',
  `rate_limit` int NOT NULL DEFAULT '300' COMMENT '请求间隔毫秒',
  `retry_times` int NOT NULL DEFAULT '1' COMMENT '重试次数',
  `last_sync_at` int NOT NULL DEFAULT '0' COMMENT '最近同步时间',
  `last_status` tinyint(1) NOT NULL DEFAULT '0' COMMENT '最近同步状态',
  `last_error` varchar(1000) NOT NULL DEFAULT '' COMMENT '最近错误',
  `status` tinyint(1) NOT NULL DEFAULT '1' COMMENT '状态',
  `create_at` int NOT NULL DEFAULT '0',
  `update_at` int NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_site_source_key` (`site_id`,`source_key`),
  KEY `idx_site_status` (`site_id`,`status`),
  KEY `idx_sync` (`sync_enabled`,`last_sync_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='回收报价爬虫源';

CREATE TABLE IF NOT EXISTS `{{prefix}}recycle_quote_spider_category` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `site_id` int NOT NULL DEFAULT '0' COMMENT '站点ID',
  `source_id` int NOT NULL DEFAULT '0' COMMENT '报价源ID',
  `source_category_id` varchar(64) NOT NULL DEFAULT '' COMMENT '第三方分类ID',
  `parent_source_id` varchar(64) NOT NULL DEFAULT '' COMMENT '第三方父级ID',
  `parent_id` int NOT NULL DEFAULT '0' COMMENT '本地父级ID',
  `level` tinyint NOT NULL DEFAULT '1' COMMENT '层级',
  `name` varchar(120) NOT NULL DEFAULT '' COMMENT '分类名称',
  `sort` int NOT NULL DEFAULT '0' COMMENT '排序',
  `source_is_show` tinyint(1) NOT NULL DEFAULT '1' COMMENT '第三方显示状态',
  `source_is_hot` tinyint(1) NOT NULL DEFAULT '0' COMMENT '第三方热门状态',
  `is_show` tinyint(1) NOT NULL DEFAULT '1' COMMENT '本地显示状态',
  `is_hot` tinyint(1) NOT NULL DEFAULT '0' COMMENT '本地热门状态',
  `has_update` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否有更新',
  `last_changed_at` int NOT NULL DEFAULT '0' COMMENT '最近变更时间',
  `icon` varchar(1000) NOT NULL DEFAULT '',
  `image` varchar(1000) NOT NULL DEFAULT '',
  `pic` varchar(1000) NOT NULL DEFAULT '',
  `raw_data` json DEFAULT NULL COMMENT '原始数据',
  `source_hash` varchar(32) NOT NULL DEFAULT '' COMMENT '源数据哈希',
  `create_at` int NOT NULL DEFAULT '0',
  `update_at` int NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_site_source_category` (`site_id`,`source_id`,`source_category_id`),
  KEY `idx_parent` (`source_id`,`parent_id`),
  KEY `idx_show_hot` (`site_id`,`is_show`,`is_hot`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='回收报价爬虫分类';

CREATE TABLE IF NOT EXISTS `{{prefix}}recycle_quote_spider_item` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `site_id` int NOT NULL DEFAULT '0' COMMENT '站点ID',
  `source_id` int NOT NULL DEFAULT '0' COMMENT '报价源ID',
  `category_id` int NOT NULL DEFAULT '0' COMMENT '分类ID',
  `source_item_id` varchar(64) NOT NULL DEFAULT '' COMMENT '第三方报价ID',
  `source_url_id` varchar(64) NOT NULL DEFAULT '' COMMENT '第三方详情分组ID',
  `brand` varchar(120) NOT NULL DEFAULT '',
  `tab` varchar(120) NOT NULL DEFAULT '',
  `name` varchar(180) NOT NULL DEFAULT '' COMMENT '报价名称',
  `parent_name` varchar(180) NOT NULL DEFAULT '',
  `quote_type` varchar(30) NOT NULL DEFAULT '' COMMENT '报价类型',
  `is_image_quote` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否图片报价',
  `image` varchar(1000) NOT NULL DEFAULT '',
  `timage` varchar(1000) NOT NULL DEFAULT '',
  `bimage` varchar(1000) NOT NULL DEFAULT '',
  `icon` varchar(1000) NOT NULL DEFAULT '',
  `notice_text` text COMMENT '报价详情提示文案',
  `keywords` varchar(500) NOT NULL DEFAULT '',
  `index1` varchar(64) NOT NULL DEFAULT '',
  `source_is_show` tinyint(1) NOT NULL DEFAULT '1',
  `source_is_hot` tinyint(1) NOT NULL DEFAULT '0',
  `is_show` tinyint(1) NOT NULL DEFAULT '1',
  `is_hot` tinyint(1) NOT NULL DEFAULT '0',
  `view_count` int NOT NULL DEFAULT '0' COMMENT '浏览量',
  `sort` int NOT NULL DEFAULT '0',
  `follow_source` tinyint(1) NOT NULL DEFAULT '1' COMMENT '是否跟随爬虫数据',
  `adjust_type` tinyint(1) NOT NULL DEFAULT '0' COMMENT '0无 1固定 2比例 3覆盖',
  `adjust_value` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '固定调整/覆盖值',
  `adjust_ratio` decimal(8,4) NOT NULL DEFAULT '1.0000' COMMENT '比例',
  `round_mode` varchar(20) NOT NULL DEFAULT 'round' COMMENT 'round/floor/ceil',
  `columns` json DEFAULT NULL COMMENT '报价列',
  `raw_data` json DEFAULT NULL,
  `source_hash` varchar(32) NOT NULL DEFAULT '',
  `has_update` tinyint(1) NOT NULL DEFAULT '0',
  `last_sync_at` int NOT NULL DEFAULT '0',
  `last_changed_at` int NOT NULL DEFAULT '0',
  `create_at` int NOT NULL DEFAULT '0',
  `update_at` int NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_site_source_item` (`site_id`,`source_id`,`source_item_id`),
  KEY `idx_category` (`category_id`),
  KEY `idx_search` (`site_id`,`is_show`,`is_hot`),
  KEY `idx_name` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='回收报价爬虫报价项';

CREATE TABLE IF NOT EXISTS `{{prefix}}recycle_quote_spider_row` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `site_id` int NOT NULL DEFAULT '0' COMMENT '站点ID',
  `source_id` int NOT NULL DEFAULT '0' COMMENT '报价源ID',
  `item_id` int NOT NULL DEFAULT '0' COMMENT '报价项ID',
  `source_row_id` varchar(64) NOT NULL DEFAULT '' COMMENT '第三方报价行ID',
  `brand` varchar(120) NOT NULL DEFAULT '',
  `tab` varchar(120) NOT NULL DEFAULT '',
  `model_name` varchar(180) NOT NULL DEFAULT '' COMMENT '型号/行名称',
  `keywords` varchar(500) NOT NULL DEFAULT '',
  `index1` varchar(64) NOT NULL DEFAULT '',
  `columns` json DEFAULT NULL COMMENT '列名',
  `source_prices` json DEFAULT NULL COMMENT '源价格',
  `manual_prices` json DEFAULT NULL COMMENT '手工价格',
  `final_prices` json DEFAULT NULL COMMENT '最终价格',
  `remark` text COMMENT '备注',
  `source_is_show` tinyint(1) NOT NULL DEFAULT '1' COMMENT '第三方显示状态',
  `is_show` tinyint(1) NOT NULL DEFAULT '1' COMMENT '本地显示状态',
  `is_hot` tinyint(1) NOT NULL DEFAULT '0' COMMENT '本地热门状态',
  `sort` int NOT NULL DEFAULT '0' COMMENT '排序',
  `follow_source` tinyint(1) NOT NULL DEFAULT '1',
  `adjust_type` tinyint(1) NOT NULL DEFAULT '0',
  `adjust_value` decimal(10,2) NOT NULL DEFAULT '0.00',
  `adjust_ratio` decimal(8,4) NOT NULL DEFAULT '1.0000',
  `round_mode` varchar(20) NOT NULL DEFAULT 'round',
  `has_update` tinyint(1) NOT NULL DEFAULT '0',
  `raw_data` json DEFAULT NULL,
  `source_hash` varchar(32) NOT NULL DEFAULT '',
  `create_at` int NOT NULL DEFAULT '0',
  `update_at` int NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_site_item_row` (`site_id`,`item_id`,`source_row_id`),
  KEY `idx_item` (`item_id`),
  KEY `idx_show_sort` (`site_id`,`item_id`,`is_show`,`sort`),
  KEY `idx_model` (`model_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='回收报价爬虫报价行';

CREATE TABLE IF NOT EXISTS `{{prefix}}recycle_quote_spider_price_history` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `site_id` int NOT NULL DEFAULT '0' COMMENT '站点ID',
  `source_id` int NOT NULL DEFAULT '0' COMMENT '报价源ID',
  `item_id` int NOT NULL DEFAULT '0' COMMENT '报价项ID',
  `row_id` int NOT NULL DEFAULT '0' COMMENT '报价行ID',
  `model_name` varchar(180) NOT NULL DEFAULT '' COMMENT '型号/行名称',
  `columns` json DEFAULT NULL COMMENT '等级列快照',
  `final_prices` json DEFAULT NULL COMMENT '最终价快照',
  `record_date` date NOT NULL COMMENT '快照日期',
  `create_at` int NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_site_row_date` (`site_id`,`row_id`,`record_date`),
  KEY `idx_item_date` (`site_id`,`item_id`,`record_date`),
  KEY `idx_row_date` (`site_id`,`row_id`,`record_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='回收报价历史价格快照';

CREATE TABLE IF NOT EXISTS `{{prefix}}recycle_quote_spider_sync_log` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `site_id` int NOT NULL DEFAULT '0',
  `source_id` int NOT NULL DEFAULT '0',
  `sync_type` varchar(30) NOT NULL DEFAULT 'manual' COMMENT 'manual/auto',
  `status` tinyint(1) NOT NULL DEFAULT '0' COMMENT '0进行中 1成功 2失败 3部分成功',
  `started_at` int NOT NULL DEFAULT '0',
  `finished_at` int NOT NULL DEFAULT '0',
  `total_count` int NOT NULL DEFAULT '0',
  `success_count` int NOT NULL DEFAULT '0',
  `failed_count` int NOT NULL DEFAULT '0',
  `message` varchar(1000) NOT NULL DEFAULT '',
  `error_detail` mediumtext,
  `summary` json DEFAULT NULL,
  `create_at` int NOT NULL DEFAULT '0',
  `update_at` int NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `idx_site_source` (`site_id`,`source_id`),
  KEY `idx_started` (`started_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='回收报价爬虫同步日志';

CREATE TABLE IF NOT EXISTS `{{prefix}}recycle_quote_spider_import_task` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `site_id` int NOT NULL DEFAULT '0',
  `source_id` int NOT NULL DEFAULT '0',
  `file_name` varchar(255) NOT NULL DEFAULT '',
  `file_path` varchar(1000) NOT NULL DEFAULT '',
  `status` tinyint(1) NOT NULL DEFAULT '0' COMMENT '0待确认 1已导入 2失败',
  `sheet_count` int NOT NULL DEFAULT '0',
  `row_count` int NOT NULL DEFAULT '0',
  `error_count` int NOT NULL DEFAULT '0',
  `preview_data` json DEFAULT NULL,
  `mapping` json DEFAULT NULL,
  `message` varchar(1000) NOT NULL DEFAULT '',
  `create_at` int NOT NULL DEFAULT '0',
  `update_at` int NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `idx_site_source` (`site_id`,`source_id`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='回收报价Excel导入任务';
