CREATE TABLE IF NOT EXISTS `{{prefix}}device_asset_item` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT '资产ID',
  `site_id` int NOT NULL DEFAULT '0' COMMENT '站点ID',
  `device_id` int NOT NULL DEFAULT '0' COMMENT '回收设备ID',
  `recycle_order_id` int NOT NULL DEFAULT '0' COMMENT '回收订单ID',
  `asset_no` varchar(64) NOT NULL DEFAULT '' COMMENT '资产编号',
  `imei` varchar(64) NOT NULL DEFAULT '',
  `imei2` varchar(64) NOT NULL DEFAULT '',
  `sn` varchar(128) NOT NULL DEFAULT '',
  `model` varchar(255) NOT NULL DEFAULT '' COMMENT '设备型号',
  `category_id` int NOT NULL DEFAULT '0' COMMENT '设备字典节点ID',
  `source_status` int NOT NULL DEFAULT '0' COMMENT '导入时回收设备状态',
  `recycle_final_price` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '回收最终价',
  `check_summary` text COMMENT '质检摘要',
  `status` varchar(32) NOT NULL DEFAULT 'wait_photo' COMMENT '资产状态',
  `photo_status` varchar(32) NOT NULL DEFAULT 'wait_photo' COMMENT '拍照状态',
  `price_status` varchar(32) NOT NULL DEFAULT 'wait_price' COMMENT '定价状态',
  `export_status` varchar(32) NOT NULL DEFAULT 'pending' COMMENT '导出状态',
  `image_count` int NOT NULL DEFAULT '0' COMMENT '合格图片数量',
  `video_count` int NOT NULL DEFAULT '0' COMMENT '合格视频数量',
  `sale_price` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '销售价',
  `peer_price` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '同行价',
  `min_price` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '最低价',
  `price_remark` varchar(1000) NOT NULL DEFAULT '' COMMENT '定价备注',
  `price_uid` int NOT NULL DEFAULT '0' COMMENT '定价人',
  `imported_by` int NOT NULL DEFAULT '0' COMMENT '导入人',
  `imported_at` int NOT NULL DEFAULT '0' COMMENT '导入时间',
  `photo_confirm_uid` int NOT NULL DEFAULT '0' COMMENT '图片确认人',
  `photo_confirmed_at` int NOT NULL DEFAULT '0' COMMENT '图片确认时间',
  `priced_at` int NOT NULL DEFAULT '0' COMMENT '定价时间',
  `exported_at` int NOT NULL DEFAULT '0' COMMENT '导出时间',
  `listing_status` varchar(32) NOT NULL DEFAULT 'pending' COMMENT '上架状态预留',
  `ext_json` text COMMENT '扩展数据',
  `create_at` int NOT NULL DEFAULT '0',
  `update_at` int NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_site_device` (`site_id`,`device_id`),
  KEY `idx_site_status` (`site_id`,`status`),
  KEY `idx_site_photo_status` (`site_id`,`photo_status`),
  KEY `idx_site_price_status` (`site_id`,`price_status`),
  KEY `idx_site_export_status` (`site_id`,`export_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='设备资产中台-资产档案';

CREATE TABLE IF NOT EXISTS `{{prefix}}device_asset_photo_task` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT '拍照任务ID',
  `site_id` int NOT NULL DEFAULT '0' COMMENT '站点ID',
  `task_no` varchar(64) NOT NULL DEFAULT '' COMMENT '任务编号',
  `asset_id` int NOT NULL DEFAULT '0' COMMENT '资产ID',
  `device_id` int NOT NULL DEFAULT '0' COMMENT '回收设备ID',
  `status` varchar(32) NOT NULL DEFAULT 'pending' COMMENT '任务状态',
  `source` varchar(32) NOT NULL DEFAULT 'manual' COMMENT '来源 pc/mobile/auto/manual',
  `station_id` varchar(64) NOT NULL DEFAULT '' COMMENT '工位ID',
  `camera_job_id` varchar(128) NOT NULL DEFAULT '' COMMENT '拍照服务任务ID',
  `operator_uid` int NOT NULL DEFAULT '0' COMMENT '操作人',
  `started_at` int NOT NULL DEFAULT '0' COMMENT '开始时间',
  `completed_at` int NOT NULL DEFAULT '0' COMMENT '完成时间',
  `remark` varchar(1000) NOT NULL DEFAULT '',
  `create_at` int NOT NULL DEFAULT '0',
  `update_at` int NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_site_task_no` (`site_id`,`task_no`),
  KEY `idx_asset` (`site_id`,`asset_id`),
  KEY `idx_operator` (`site_id`,`operator_uid`),
  KEY `idx_status` (`site_id`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='设备资产中台-拍照任务';

CREATE TABLE IF NOT EXISTS `{{prefix}}device_asset_media` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT '媒体ID',
  `site_id` int NOT NULL DEFAULT '0',
  `asset_id` int NOT NULL DEFAULT '0',
  `device_id` int NOT NULL DEFAULT '0',
  `task_id` int NOT NULL DEFAULT '0',
  `media_type` varchar(20) NOT NULL DEFAULT 'image' COMMENT 'image/video',
  `scene` varchar(64) NOT NULL DEFAULT '' COMMENT '拍摄场景',
  `url` varchar(1000) NOT NULL DEFAULT '',
  `oss_key` varchar(500) NOT NULL DEFAULT '',
  `source` varchar(32) NOT NULL DEFAULT 'manual' COMMENT 'auto/mobile/manual',
  `status` varchar(32) NOT NULL DEFAULT 'pending' COMMENT 'pending/approved/rejected',
  `reject_reason` varchar(500) NOT NULL DEFAULT '',
  `sort` int NOT NULL DEFAULT '0',
  `operator_uid` int NOT NULL DEFAULT '0',
  `create_at` int NOT NULL DEFAULT '0',
  `update_at` int NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `idx_asset` (`site_id`,`asset_id`),
  KEY `idx_task` (`site_id`,`task_id`),
  KEY `idx_operator` (`site_id`,`operator_uid`),
  KEY `idx_status` (`site_id`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='设备资产中台-图片视频';

CREATE TABLE IF NOT EXISTS `{{prefix}}device_asset_price_order` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT '定价工单ID',
  `site_id` int NOT NULL DEFAULT '0',
  `order_no` varchar(64) NOT NULL DEFAULT '',
  `asset_id` int NOT NULL DEFAULT '0',
  `device_id` int NOT NULL DEFAULT '0',
  `status` varchar(32) NOT NULL DEFAULT 'pending' COMMENT 'pending/processing/completed/rejected',
  `assign_uid` int NOT NULL DEFAULT '0' COMMENT '指派人',
  `sale_price` decimal(12,2) NOT NULL DEFAULT '0.00',
  `peer_price` decimal(12,2) NOT NULL DEFAULT '0.00',
  `min_price` decimal(12,2) NOT NULL DEFAULT '0.00',
  `cost_price` decimal(12,2) NOT NULL DEFAULT '0.00',
  `remark` varchar(1000) NOT NULL DEFAULT '',
  `priced_uid` int NOT NULL DEFAULT '0',
  `priced_at` int NOT NULL DEFAULT '0',
  `create_at` int NOT NULL DEFAULT '0',
  `update_at` int NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_site_order_no` (`site_id`,`order_no`),
  KEY `idx_asset` (`site_id`,`asset_id`),
  KEY `idx_status` (`site_id`,`status`),
  KEY `idx_priced_uid` (`site_id`,`priced_uid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='设备资产中台-定价工单';

CREATE TABLE IF NOT EXISTS `{{prefix}}device_asset_operation_log` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT '日志ID',
  `site_id` int NOT NULL DEFAULT '0',
  `asset_id` int NOT NULL DEFAULT '0',
  `device_id` int NOT NULL DEFAULT '0',
  `action` varchar(64) NOT NULL DEFAULT '',
  `action_name` varchar(100) NOT NULL DEFAULT '',
  `operator_uid` int NOT NULL DEFAULT '0',
  `operator_name` varchar(100) NOT NULL DEFAULT '',
  `payload` text COMMENT '操作上下文JSON',
  `ip` varchar(64) NOT NULL DEFAULT '',
  `create_at` int NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `idx_asset` (`site_id`,`asset_id`),
  KEY `idx_device` (`site_id`,`device_id`),
  KEY `idx_operator` (`site_id`,`operator_uid`),
  KEY `idx_action` (`site_id`,`action`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='设备资产中台-操作日志';
