CREATE TABLE IF NOT EXISTS `{{prefix}}recycle_quotation_v2_dataset` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `site_id` int NOT NULL DEFAULT '0' COMMENT '站点ID',
  `quotation_id` int NOT NULL DEFAULT '0' COMMENT '第三方报价单ID',
  `price_name` varchar(100) NOT NULL DEFAULT '' COMMENT '第三方报价名称',
  `dataset_name` varchar(100) NOT NULL DEFAULT '' COMMENT '数据集名称',
  `channel_key` varchar(50) NOT NULL DEFAULT 'chaoniu' COMMENT '渠道标识',
  `sort` int NOT NULL DEFAULT '0' COMMENT '排序',
  `status` tinyint(1) NOT NULL DEFAULT '1' COMMENT '状态',
  `follow_crawler` tinyint(1) NOT NULL DEFAULT '1' COMMENT '是否跟随爬虫',
  `request_params` json DEFAULT NULL COMMENT '请求参数覆盖',
  `parse_rule` json DEFAULT NULL COMMENT '解析规则',
  `remark` varchar(500) NOT NULL DEFAULT '' COMMENT '备注',
  `last_sync_at` int NOT NULL DEFAULT '0' COMMENT '最近同步时间',
  `last_sync_status` tinyint(1) NOT NULL DEFAULT '0' COMMENT '最近同步状态',
  `last_sync_message` varchar(500) NOT NULL DEFAULT '' COMMENT '最近同步说明',
  `last_sync_summary` json DEFAULT NULL COMMENT '最近同步统计',
  `create_at` int NOT NULL DEFAULT '0',
  `update_at` int NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_site_quotation` (`site_id`,`quotation_id`),
  KEY `idx_site_status` (`site_id`,`status`),
  KEY `idx_sort` (`sort`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='报价2.0数据集';

CREATE TABLE IF NOT EXISTS `{{prefix}}recycle_quotation_v2_model` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `site_id` int NOT NULL DEFAULT '0',
  `dataset_id` int NOT NULL DEFAULT '0' COMMENT '报价数据集ID',
  `quotation_id` int NOT NULL DEFAULT '0',
  `price_name` varchar(100) NOT NULL DEFAULT '' COMMENT '报价名称',
  `channel_key` varchar(50) NOT NULL DEFAULT 'chaoniu',
  `external_goods_id` int NOT NULL DEFAULT '0' COMMENT '第三方型号ID',
  `model_name` varchar(120) NOT NULL DEFAULT '' COMMENT '型号名称',
  `group_key` int NOT NULL DEFAULT '0' COMMENT '第三方分组',
  `sort` int NOT NULL DEFAULT '0',
  `status` tinyint(1) NOT NULL DEFAULT '1',
  `follow_crawler` tinyint(1) NOT NULL DEFAULT '1',
  `raw_data` json DEFAULT NULL,
  `create_at` int NOT NULL DEFAULT '0',
  `update_at` int NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_site_dataset_goods` (`site_id`,`dataset_id`,`external_goods_id`),
  KEY `idx_dataset` (`dataset_id`),
  KEY `idx_model_name` (`model_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='报价2.0型号';

CREATE TABLE IF NOT EXISTS `{{prefix}}recycle_quotation_v2_capacity` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `site_id` int NOT NULL DEFAULT '0',
  `dataset_id` int NOT NULL DEFAULT '0',
  `quotation_id` int NOT NULL DEFAULT '0',
  `model_id` int NOT NULL DEFAULT '0',
  `external_goods_id` int NOT NULL DEFAULT '0',
  `capacity_answer_id` int NOT NULL DEFAULT '0' COMMENT '第三方容量ID',
  `capacity_name` varchar(50) NOT NULL DEFAULT '',
  `sort` int NOT NULL DEFAULT '0',
  `status` tinyint(1) NOT NULL DEFAULT '1',
  `follow_crawler` tinyint(1) NOT NULL DEFAULT '1',
  `raw_data` json DEFAULT NULL,
  `create_at` int NOT NULL DEFAULT '0',
  `update_at` int NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_site_dataset_model_capacity` (`site_id`,`dataset_id`,`model_id`,`capacity_answer_id`),
  KEY `idx_dataset` (`dataset_id`),
  KEY `idx_model` (`model_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='报价2.0容量';

CREATE TABLE IF NOT EXISTS `{{prefix}}recycle_quotation_v2_field` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `site_id` int NOT NULL DEFAULT '0',
  `dataset_id` int NOT NULL DEFAULT '0',
  `quotation_id` int NOT NULL DEFAULT '0',
  `question_id` int NOT NULL DEFAULT '0' COMMENT '第三方字段ID',
  `field_name` varchar(100) NOT NULL DEFAULT '',
  `field_type` varchar(30) NOT NULL DEFAULT '' COMMENT 'price/adjustment/note/remark',
  `sort` int NOT NULL DEFAULT '0',
  `status` tinyint(1) NOT NULL DEFAULT '1',
  `follow_crawler` tinyint(1) NOT NULL DEFAULT '1',
  `raw_data` json DEFAULT NULL,
  `create_at` int NOT NULL DEFAULT '0',
  `update_at` int NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_site_dataset_field` (`site_id`,`dataset_id`,`question_id`,`field_type`,`field_name`),
  KEY `idx_dataset_type` (`dataset_id`,`field_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='报价2.0字段项';

CREATE TABLE IF NOT EXISTS `{{prefix}}recycle_quotation_v2_price` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `site_id` int NOT NULL DEFAULT '0',
  `dataset_id` int NOT NULL DEFAULT '0',
  `quotation_id` int NOT NULL DEFAULT '0',
  `model_id` int NOT NULL DEFAULT '0',
  `capacity_id` int NOT NULL DEFAULT '0',
  `field_id` int NOT NULL DEFAULT '0',
  `external_goods_id` int NOT NULL DEFAULT '0',
  `capacity_answer_id` int NOT NULL DEFAULT '0',
  `field_name` varchar(100) NOT NULL DEFAULT '',
  `crawler_price` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '爬虫原价',
  `adjust_type` tinyint(1) NOT NULL DEFAULT '1' COMMENT '1固定差价 2百分比 3覆盖',
  `adjust_value` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '价格差',
  `final_price` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '最终价',
  `price_date` date NOT NULL,
  `is_current` tinyint(1) NOT NULL DEFAULT '1',
  `locked` tinyint(1) NOT NULL DEFAULT '0' COMMENT '锁定后不被爬虫覆盖',
  `raw_item` json DEFAULT NULL,
  `create_at` int NOT NULL DEFAULT '0',
  `update_at` int NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_site_dataset_price` (`site_id`,`dataset_id`,`model_id`,`capacity_id`,`field_id`,`price_date`),
  KEY `idx_dataset` (`dataset_id`),
  KEY `idx_model_capacity` (`model_id`,`capacity_id`),
  KEY `idx_field` (`field_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='报价2.0价格';

CREATE TABLE IF NOT EXISTS `{{prefix}}recycle_quotation_v2_note` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `site_id` int NOT NULL DEFAULT '0',
  `dataset_id` int NOT NULL DEFAULT '0',
  `quotation_id` int NOT NULL DEFAULT '0',
  `model_id` int NOT NULL DEFAULT '0',
  `capacity_id` int NOT NULL DEFAULT '0',
  `field_id` int NOT NULL DEFAULT '0',
  `external_goods_id` int NOT NULL DEFAULT '0',
  `capacity_answer_id` int NOT NULL DEFAULT '0',
  `field_name` varchar(100) NOT NULL DEFAULT '',
  `content_html` mediumtext COMMENT 'HTML内容',
  `content_text` mediumtext COMMENT '纯文本内容',
  `merge_items` json DEFAULT NULL COMMENT '第三方适用范围',
  `status` tinyint(1) NOT NULL DEFAULT '1',
  `follow_crawler` tinyint(1) NOT NULL DEFAULT '1',
  `raw_item` json DEFAULT NULL,
  `create_at` int NOT NULL DEFAULT '0',
  `update_at` int NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_site_dataset_note` (`site_id`,`dataset_id`,`model_id`,`capacity_id`,`field_id`),
  KEY `idx_dataset` (`dataset_id`),
  KEY `idx_model_capacity` (`model_id`,`capacity_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='报价2.0附加说明';

CREATE TABLE IF NOT EXISTS `{{prefix}}recycle_quotation_v2_sync_log` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `site_id` int NOT NULL DEFAULT '0',
  `dataset_id` int NOT NULL DEFAULT '0',
  `quotation_id` int NOT NULL DEFAULT '0',
  `channel_key` varchar(50) NOT NULL DEFAULT 'chaoniu',
  `request_url` varchar(1000) NOT NULL DEFAULT '',
  `request_params` json DEFAULT NULL,
  `http_code` int NOT NULL DEFAULT '0',
  `duration` int NOT NULL DEFAULT '0',
  `raw_response` json DEFAULT NULL,
  `parsed_preview` json DEFAULT NULL,
  `stats` json DEFAULT NULL,
  `warnings` json DEFAULT NULL,
  `status` tinyint(1) NOT NULL DEFAULT '0',
  `imported` tinyint(1) NOT NULL DEFAULT '0',
  `error_message` varchar(1000) NOT NULL DEFAULT '',
  `create_at` int NOT NULL DEFAULT '0',
  `update_at` int NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `idx_site_dataset` (`site_id`,`dataset_id`),
  KEY `idx_create_at` (`create_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='报价2.0同步日志';
