<?php
return [
    [
        'menu_name' => '校园帮',
        'menu_key' => 'sd_xiaoyuan',
        'menu_short_name' => '校园帮',
        'parent_select_key' => '',
        'parent_key' => '',
        'menu_type' => '0',
        'icon' => 'iconfont iconshangchengshequ',
        'api_url' => '',
        'router_path' => '',
        'view_path' => '',
        'methods' => '',
        'sort' => '90',
        'status' => '1',
        'is_show' => '1',
        'children' => [
            [
                'menu_name' => '数据概览',
                'menu_key' => 'sd_xiaoyuan_dashboard',
                'menu_short_name' => '数据概览',
                'parent_select_key' => '',
                'menu_type' => '1',
                'icon' => 'iconfont icongaikuang1',
                'api_url' => 'sd_xiaoyuan/dashboard/stat',
                'router_path' => 'sd_xiaoyuan/dashboard',
                'view_path' => 'dashboard/index',
                'methods' => 'get',
                'sort' => '100',
                'status' => '1',
                'is_show' => '1',
            ],
            [
                'menu_name' => '学校管理',
                'menu_key' => 'sd_xiaoyuan_school_group',
                'menu_short_name' => '学校管理',
                'parent_select_key' => '',
                'menu_type' => '0',
                'icon' => '',
                'api_url' => '',
                'router_path' => '',
                'view_path' => '',
                'methods' => '',
                'sort' => '99',
                'status' => '1',
                'is_show' => '1',
                'children' => [
                    [
                        'menu_name' => '学校列表',
                        'menu_key' => 'sd_xiaoyuan_school',
                        'menu_short_name' => '学校列表',
                        'parent_select_key' => '',
                        'menu_type' => '1',
                        'icon' => '',
                        'api_url' => 'sd_xiaoyuan/school/lists',
                        'router_path' => 'sd_xiaoyuan/school/list',
                        'view_path' => 'school/list',
                        'methods' => 'get',
                        'sort' => '90',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                    [
                        'menu_name' => '快递驿站',
                        'menu_key' => 'sd_xiaoyuan_express_station',
                        'menu_short_name' => '快递驿站',
                        'parent_select_key' => '',
                        'menu_type' => '1',
                        'icon' => '',
                        'api_url' => 'sd_xiaoyuan/express_station/lists',
                        'router_path' => 'sd_xiaoyuan/express_station/list',
                        'view_path' => 'express_station/list',
                        'methods' => 'get',
                        'sort' => '89',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                    [
                        'menu_name' => '班级管理',
                        'menu_key' => 'sd_xiaoyuan_school_class',
                        'menu_short_name' => '班级管理',
                        'parent_select_key' => '',
                        'menu_type' => '1',
                        'icon' => '',
                        'api_url' => 'sd_xiaoyuan/school_class/list',
                        'router_path' => 'sd_xiaoyuan/school_class/list',
                        'view_path' => 'school_class/list',
                        'methods' => 'get',
                        'sort' => '88',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                    [
                        'menu_name' => '班级课表',
                        'menu_key' => 'sd_xiaoyuan_class_schedule',
                        'menu_short_name' => '班级课表',
                        'parent_select_key' => '',
                        'menu_type' => '1',
                        'icon' => '',
                        'api_url' => 'sd_xiaoyuan/class_schedule/list',
                        'router_path' => 'sd_xiaoyuan/class_schedule/list',
                        'view_path' => 'class_schedule/list',
                        'methods' => 'get',
                        'sort' => '87',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                    [
                        'menu_name' => '导入课表',
                        'menu_key' => 'sd_xiaoyuan_class_schedule_import',
                        'menu_short_name' => '导入课表',
                        'parent_select_key' => '',
                        'menu_type' => '1',
                        'icon' => '',
                        'api_url' => 'sd_xiaoyuan/class_schedule/import',
                        'router_path' => 'sd_xiaoyuan/class_schedule/import',
                        'view_path' => 'class_schedule/import',
                        'methods' => 'post',
                        'sort' => '86',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                ],
            ],
            [
                'menu_name' => '基础设置',
                'menu_key' => 'sd_xiaoyuan_setting_group',
                'menu_short_name' => '基础设置',
                'parent_select_key' => '',
                'menu_type' => '0',
                'icon' => 'iconfont iconjichushen1',
                'api_url' => '',
                'router_path' => '',
                'view_path' => '',
                'methods' => '',
                'sort' => '90',
                'status' => '1',
                'is_show' => '1',
                'children' => [
                    [
                        'menu_name' => '系统配置',
                        'menu_key' => 'sd_xiaoyuan_config',
                        'menu_short_name' => '系统配置',
                        'parent_select_key' => '',
                        'menu_type' => '1',
                        'icon' => '',
                        'api_url' => 'sd_xiaoyuan/config/info',
                        'router_path' => 'sd_xiaoyuan/config/index',
                        'view_path' => 'config/index',
                        'methods' => 'get',
                        'sort' => '90',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                ],
            ],
            [
                'menu_name' => '表白墙管理',
                'menu_key' => 'sd_xiaoyuan_confession_group',
                'menu_short_name' => '表白墙管理',
                'parent_select_key' => '',
                'menu_type' => '0',
                'icon' => '',
                'api_url' => '',
                'router_path' => '',
                'view_path' => '',
                'methods' => '',
                'sort' => '90',
                'status' => '1',
                'is_show' => '1',
                'children' => [
                    [
                        'menu_name' => '表白列表',
                        'menu_key' => 'sd_xiaoyuan_confession',
                        'menu_short_name' => '表白列表',
                        'parent_select_key' => '',
                        'menu_type' => '1',
                        'icon' => '',
                        'api_url' => 'sd_xiaoyuan/confession/lists',
                        'router_path' => 'sd_xiaoyuan/confession/list',
                        'view_path' => 'confession/list',
                        'methods' => 'get',
                        'sort' => '90',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                    [
                        'menu_name' => '表白墙评论',
                        'menu_key' => 'sd_xiaoyuan_confession_comment',
                        'menu_short_name' => '表白墙评论',
                        'parent_select_key' => '',
                        'menu_type' => '1',
                        'icon' => '',
                        'api_url' => 'sd_xiaoyuan/comment/confession',
                        'router_path' => 'sd_xiaoyuan/comment/confession',
                        'view_path' => 'comment/confession',
                        'methods' => 'get',
                        'sort' => '2',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                ],
            ],
            [
                'menu_name' => '房屋租赁',
                'menu_key' => 'sd_xiaoyuan_house_group',
                'menu_short_name' => '房屋租赁',
                'parent_select_key' => '',
                'menu_type' => '0',
                'icon' => '',
                'api_url' => '',
                'router_path' => '',
                'view_path' => '',
                'methods' => '',
                'sort' => '90',
                'status' => '1',
                'is_show' => '1',
                'children' => [
                    [
                        'menu_name' => '房源列表',
                        'menu_key' => 'sd_xiaoyuan_house',
                        'menu_short_name' => '房源列表',
                        'parent_select_key' => '',
                        'menu_type' => '1',
                        'icon' => '',
                        'api_url' => 'sd_xiaoyuan/house/lists',
                        'router_path' => 'sd_xiaoyuan/house/list',
                        'view_path' => 'house/list',
                        'methods' => 'get',
                        'sort' => '90',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                    [
                        'menu_name' => '房源订单',
                        'menu_key' => 'sd_xiaoyuan_house_order',
                        'menu_short_name' => '房源订单',
                        'parent_select_key' => '',
                        'menu_type' => '1',
                        'icon' => '',
                        'api_url' => 'sd_xiaoyuan/house_order/list',
                        'router_path' => 'sd_xiaoyuan/house/order',
                        'view_path' => 'house/order',
                        'methods' => 'get',
                        'sort' => '2',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                ],
            ],
            [
                'menu_name' => '游戏陪玩',
                'menu_key' => 'sd_xiaoyuan_game_group',
                'menu_short_name' => '游戏陪玩',
                'parent_select_key' => '',
                'menu_type' => '0',
                'icon' => '',
                'api_url' => '',
                'router_path' => '',
                'view_path' => '',
                'methods' => '',
                'sort' => '90',
                'status' => '1',
                'is_show' => '1',
                'children' => [
                    [
                        'menu_name' => '陪玩管理',
                        'menu_key' => 'sd_xiaoyuan_game_companion',
                        'menu_short_name' => '陪玩管理',
                        'parent_select_key' => '',
                        'menu_type' => '1',
                        'icon' => '',
                        'api_url' => 'sd_xiaoyuan/game_companion/list',
                        'router_path' => 'sd_xiaoyuan/game/index',
                        'view_path' => 'game/index',
                        'methods' => 'get',
                        'sort' => '90',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                    [
                        'menu_name' => '游戏类型',
                        'menu_key' => 'sd_xiaoyuan_game_category',
                        'menu_short_name' => '游戏类型',
                        'parent_select_key' => '',
                        'menu_type' => '1',
                        'icon' => '',
                        'api_url' => 'sd_xiaoyuan/game_category/lists',
                        'router_path' => 'sd_xiaoyuan/game/category',
                        'view_path' => 'game/category',
                        'methods' => 'get',
                        'sort' => '89',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                ],
            ],
            [
                'menu_name' => '接单员管理',
                'menu_key' => 'sd_xiaoyuan_runner_group',
                'menu_short_name' => '接单员管理',
                'parent_select_key' => '',
                'menu_type' => '0',
                'icon' => '',
                'api_url' => '',
                'router_path' => '',
                'view_path' => '',
                'methods' => '',
                'sort' => '90',
                'status' => '1',
                'is_show' => '1',
                'children' => [
                    [
                        'menu_name' => '接单员列表',
                        'menu_key' => 'sd_xiaoyuan_runner',
                        'menu_short_name' => '接单员列表',
                        'parent_select_key' => '',
                        'menu_type' => '1',
                        'icon' => '',
                        'api_url' => 'sd_xiaoyuan/runner/lists',
                        'router_path' => 'sd_xiaoyuan/runner/list',
                        'view_path' => 'runner/list',
                        'methods' => 'get',
                        'sort' => '90',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                    [
                        'menu_name' => '接单员等级',
                        'menu_key' => 'sd_xiaoyuan_runner_level',
                        'menu_short_name' => '接单员等级',
                        'parent_select_key' => '',
                        'menu_type' => '1',
                        'icon' => '',
                        'api_url' => 'sd_xiaoyuan/runner_level/lists',
                        'router_path' => 'sd_xiaoyuan/runner/level',
                        'view_path' => 'runner/level',
                        'methods' => 'get',
                        'sort' => '2',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                ],
            ],
            [
                'menu_name' => '用户管理',
                'menu_key' => 'sd_xiaoyuan_member_group',
                'menu_short_name' => '用户管理',
                'parent_select_key' => '',
                'menu_type' => '0',
                'icon' => 'iconfont iconhuiyuanguanli1',
                'api_url' => '',
                'router_path' => '',
                'view_path' => '',
                'methods' => '',
                'sort' => '90',
                'status' => '1',
                'is_show' => '1',
                'children' => [
                    [
                        'menu_name' => '校园认证',
                        'menu_key' => 'sd_xiaoyuan_campus_auth',
                        'menu_short_name' => '校园认证',
                        'parent_select_key' => '',
                        'menu_type' => '1',
                        'icon' => '',
                        'api_url' => 'sd_xiaoyuan/campus_auth/lists',
                        'router_path' => 'sd_xiaoyuan/campus_auth/list',
                        'view_path' => 'campus_auth/list',
                        'methods' => 'get',
                        'sort' => '90',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                    [
                        'menu_name' => '信誉分管理',
                        'menu_key' => 'sd_xiaoyuan_credit',
                        'menu_short_name' => '信誉分管理',
                        'parent_select_key' => '',
                        'menu_type' => '1',
                        'icon' => '',
                        'api_url' => 'sd_xiaoyuan/credit/lists',
                        'router_path' => 'sd_xiaoyuan/credit/list',
                        'view_path' => 'credit/list',
                        'methods' => 'get',
                        'sort' => '90',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                    [
                        'menu_name' => '系统消息',
                        'menu_key' => 'sd_xiaoyuan_message',
                        'menu_short_name' => '系统消息',
                        'parent_select_key' => '',
                        'menu_type' => '1',
                        'icon' => '',
                        'api_url' => 'sd_xiaoyuan/message/lists',
                        'router_path' => 'sd_xiaoyuan/message/list',
                        'view_path' => 'message/list',
                        'methods' => 'get',
                        'sort' => '90',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                ],
            ],
            [
                'menu_name' => '积分商城',
                'menu_key' => 'sd_xiaoyuan_points_group',
                'menu_short_name' => '积分商城',
                'parent_select_key' => '',
                'menu_type' => '0',
                'icon' => 'iconfont iconjifen',
                'api_url' => '',
                'router_path' => '',
                'view_path' => '',
                'methods' => '',
                'sort' => '90',
                'status' => '1',
                'is_show' => '1',
                'children' => [
                    [
                        'menu_name' => '积分商品',
                        'menu_key' => 'sd_xiaoyuan_points_goods',
                        'menu_short_name' => '积分商品',
                        'parent_select_key' => '',
                        'menu_type' => '1',
                        'icon' => '',
                        'api_url' => 'sd_xiaoyuan/points/goods_list',
                        'router_path' => 'sd_xiaoyuan/points/goods',
                        'view_path' => 'points/goods',
                        'methods' => 'get',
                        'sort' => '90',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                    [
                        'menu_name' => '兑换记录',
                        'menu_key' => 'sd_xiaoyuan_points_orders',
                        'menu_short_name' => '兑换记录',
                        'parent_select_key' => '',
                        'menu_type' => '1',
                        'icon' => '',
                        'api_url' => 'sd_xiaoyuan/points/order_list',
                        'router_path' => 'sd_xiaoyuan/points/orders',
                        'view_path' => 'points/orders',
                        'methods' => 'get',
                        'sort' => '2',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                ],
            ],
            [
                'menu_name' => '失物招领',
                'menu_key' => 'sd_xiaoyuan_lost_found_group',
                'menu_short_name' => '失物招领',
                'parent_select_key' => '',
                'menu_type' => '0',
                'icon' => '',
                'api_url' => '',
                'router_path' => '',
                'view_path' => '',
                'methods' => '',
                'sort' => '90',
                'status' => '1',
                'is_show' => '1',
                'children' => [
                    [
                        'menu_name' => '失物列表',
                        'menu_key' => 'sd_xiaoyuan_lost_found',
                        'menu_short_name' => '失物列表',
                        'parent_select_key' => '',
                        'menu_type' => '1',
                        'icon' => '',
                        'api_url' => 'sd_xiaoyuan/lost_found/lists',
                        'router_path' => 'sd_xiaoyuan/lost_found/list',
                        'view_path' => 'lost_found/list',
                        'methods' => 'get',
                        'sort' => '90',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                    [
                        'menu_name' => '分类管理',
                        'menu_key' => 'sd_xiaoyuan_lost_found_category',
                        'menu_short_name' => '分类管理',
                        'parent_select_key' => '',
                        'menu_type' => '1',
                        'icon' => '',
                        'api_url' => 'sd_xiaoyuan/lost_found_category/lists',
                        'router_path' => 'sd_xiaoyuan/lost_found/category',
                        'view_path' => 'lost_found/category',
                        'methods' => 'get',
                        'sort' => '89',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                ],
            ],
            [
                'menu_name' => '二手交易',
                'menu_key' => 'sd_xiaoyuan_secondhand_group',
                'menu_short_name' => '二手交易',
                'parent_select_key' => '',
                'menu_type' => '0',
                'icon' => '',
                'api_url' => '',
                'router_path' => '',
                'view_path' => '',
                'methods' => '',
                'sort' => '90',
                'status' => '1',
                'is_show' => '1',
                'children' => [
                    [
                        'menu_name' => '分类管理',
                        'menu_key' => 'sd_xiaoyuan_secondhand_category',
                        'menu_short_name' => '分类管理',
                        'parent_select_key' => '',
                        'menu_type' => '1',
                        'icon' => '',
                        'api_url' => 'sd_xiaoyuan/secondhand/category_list',
                        'router_path' => 'sd_xiaoyuan/secondhand/category',
                        'view_path' => 'secondhand/category',
                        'methods' => 'get',
                        'sort' => '90',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                    [
                        'menu_name' => '商品列表',
                        'menu_key' => 'sd_xiaoyuan_secondhand',
                        'menu_short_name' => '商品列表',
                        'parent_select_key' => '',
                        'menu_type' => '1',
                        'icon' => '',
                        'api_url' => 'sd_xiaoyuan/secondhand/lists',
                        'router_path' => 'sd_xiaoyuan/secondhand/list',
                        'view_path' => 'secondhand/list',
                        'methods' => 'get',
                        'sort' => '90',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                ],
            ],
            [
                'menu_name' => '拼单好饭',
                'menu_key' => 'sd_xiaoyuan_group_order_group',
                'menu_short_name' => '拼单好饭',
                'parent_select_key' => '',
                'menu_type' => '0',
                'icon' => '',
                'api_url' => '',
                'router_path' => '',
                'view_path' => '',
                'methods' => '',
                'sort' => '90',
                'status' => '1',
                'is_show' => '1',
                'children' => [
                    [
                        'menu_name' => '拼单列表',
                        'menu_key' => 'sd_xiaoyuan_group_order',
                        'menu_short_name' => '拼单列表',
                        'parent_select_key' => '',
                        'menu_type' => '1',
                        'icon' => '',
                        'api_url' => 'sd_xiaoyuan/group_order/lists',
                        'router_path' => 'sd_xiaoyuan/group_order/list',
                        'view_path' => 'group_order/list',
                        'methods' => 'get',
                        'sort' => '90',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                ],
            ],
            [
                'menu_name' => '树洞管理',
                'menu_key' => 'sd_xiaoyuan_community_group',
                'menu_short_name' => '树洞管理',
                'parent_select_key' => '',
                'menu_type' => '0',
                'icon' => '',
                'api_url' => '',
                'router_path' => '',
                'view_path' => '',
                'methods' => '',
                'sort' => '90',
                'status' => '1',
                'is_show' => '1',
                'children' => [
                    [
                        'menu_name' => '树洞列表',
                        'menu_key' => 'sd_xiaoyuan_community',
                        'menu_short_name' => '树洞列表',
                        'parent_select_key' => '',
                        'menu_type' => '1',
                        'icon' => '',
                        'api_url' => 'sd_xiaoyuan/community/lists',
                        'router_path' => 'sd_xiaoyuan/community/list',
                        'view_path' => 'community/list',
                        'methods' => 'get',
                        'sort' => '90',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                    [
                        'menu_name' => '树洞评论',
                        'menu_key' => 'sd_xiaoyuan_community_comment',
                        'menu_short_name' => '树洞评论',
                        'parent_select_key' => '',
                        'menu_type' => '1',
                        'icon' => '',
                        'api_url' => 'sd_xiaoyuan/comment/community',
                        'router_path' => 'sd_xiaoyuan/comment/community',
                        'view_path' => 'comment/community',
                        'methods' => 'get',
                        'sort' => '3',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                    [
                        'menu_name' => '树洞分类',
                        'menu_key' => 'sd_xiaoyuan_community_category',
                        'menu_short_name' => '树洞分类',
                        'parent_select_key' => '',
                        'menu_type' => '1',
                        'icon' => '',
                        'api_url' => 'sd_xiaoyuan/community_category/lists',
                        'router_path' => 'sd_xiaoyuan/community/category',
                        'view_path' => 'community/category',
                        'methods' => 'get',
                        'sort' => '2',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                ],
            ],
            [
                'menu_name' => '订单管理',
                'menu_key' => 'sd_xiaoyuan_order_group',
                'menu_short_name' => '订单管理',
                'parent_select_key' => '',
                'menu_type' => '0',
                'icon' => 'iconfont iconshangpinguanli1',
                'api_url' => '',
                'router_path' => '',
                'view_path' => '',
                'methods' => '',
                'sort' => '90',
                'status' => '1',
                'is_show' => '1',
                'children' => [
                    [
                        'menu_name' => '订单列表',
                        'menu_key' => 'sd_xiaoyuan_order',
                        'menu_short_name' => '订单列表',
                        'parent_select_key' => '',
                        'menu_type' => '1',
                        'icon' => '',
                        'api_url' => 'sd_xiaoyuan/order/lists',
                        'router_path' => 'sd_xiaoyuan/order/list',
                        'view_path' => 'order/list',
                        'methods' => 'get',
                        'sort' => '90',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                ],
            ],
            [
                'menu_name' => '评价管理',
                'menu_key' => 'sd_xiaoyuan_evaluate_group',
                'menu_short_name' => '评价管理',
                'parent_select_key' => '',
                'menu_type' => '0',
                'icon' => 'iconfont iconpingjiaguanli1',
                'api_url' => '',
                'router_path' => '',
                'view_path' => '',
                'methods' => '',
                'sort' => '90',
                'status' => '1',
                'is_show' => '1',
                'children' => [
                    [
                        'menu_name' => '评价管理',
                        'menu_key' => 'sd_xiaoyuan_evaluate',
                        'menu_short_name' => '评价管理',
                        'parent_select_key' => '',
                        'menu_type' => '1',
                        'icon' => '',
                        'api_url' => 'sd_xiaoyuan/evaluate/lists',
                        'router_path' => 'sd_xiaoyuan/evaluate/list',
                        'view_path' => 'evaluate/list',
                        'methods' => 'get',
                        'sort' => '90',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                    [
                        'menu_name' => '申诉管理',
                        'menu_key' => 'sd_xiaoyuan_appeal',
                        'menu_short_name' => '申诉管理',
                        'parent_select_key' => '',
                        'menu_type' => '1',
                        'icon' => '',
                        'api_url' => 'sd_xiaoyuan/appeal/lists',
                        'router_path' => 'sd_xiaoyuan/appeal/list',
                        'view_path' => 'appeal/list',
                        'methods' => 'get',
                        'sort' => '90',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                ],
            ],
            [
                'menu_name' => '营销管理',
                'menu_key' => 'sd_xiaoyuan_marketing_group',
                'menu_short_name' => '营销管理',
                'parent_select_key' => '',
                'menu_type' => '0',
                'icon' => 'iconfont iconyingxiaoguanli1',
                'api_url' => '',
                'router_path' => '',
                'view_path' => '',
                'methods' => '',
                'sort' => '90',
                'status' => '1',
                'is_show' => '1',
                'children' => [
                    [
                        'menu_name' => '签到管理',
                        'menu_key' => 'sd_xiaoyuan_sign',
                        'menu_short_name' => '签到管理',
                        'parent_select_key' => '',
                        'menu_type' => '1',
                        'icon' => '',
                        'api_url' => 'sd_xiaoyuan/sign/lists',
                        'router_path' => 'sd_xiaoyuan/sign/index',
                        'view_path' => 'sign/index',
                        'methods' => 'get',
                        'sort' => '90',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                    [
                        'menu_name' => '邀请分销',
                        'menu_key' => 'sd_xiaoyuan_invite',
                        'menu_short_name' => '邀请分销',
                        'parent_select_key' => '',
                        'menu_type' => '1',
                        'icon' => '',
                        'api_url' => 'sd_xiaoyuan/invite/lists',
                        'router_path' => 'sd_xiaoyuan/invite/index',
                        'view_path' => 'invite/index',
                        'methods' => 'get',
                        'sort' => '90',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                ],
            ],
        ],
    ],
];