<?php
return [
    [
        "name" => "校园帮邀请海报模板",
        'type' => 'xiaoyuan_invite',
        "data" => [
            "global" => [
                "bgType" => "color",
                "bgColor" => "#ffffff",
                "bgUrl" => "",
                "width" => 750,
                "height" => 1334
            ],
            "value" => [
                [
                    "id" => "bg_image",
                    "componentName" => "BgImage",
                    "componentTitle" => "背景图",
                    "type" => "image",
                    "path" => "bg-image",
                    "uses" => 1,
                    "relate" => "custom_image",
                    "value" => "addon/sd_xiaoyuan/poster/invite_bg.png",
                    "width" => 750,
                    "height" => 1334,
                    "minWidth" => 750,
                    "minHeight" => 1334,
                    "x" => 0,
                    "y" => 0,
                    "angle" => 0,
                    "zIndex" => 0
                ],
                [
                    "id" => "xiaoyuan_slogan",
                    "componentName" => "Slogan",
                    "componentTitle" => "广告语",
                    "type" => "text",
                    "path" => "slogan",
                    "uses" => 1,
                    "relate" => "slogan",
                    "value" => "校园帮 · 互助共赢",
                    "width" => 750,
                    "height" => 60,
                    "minWidth" => 120,
                    "minHeight" => 44,
                    "x" => "center",
                    "y" => 760,
                    "angle" => 0,
                    "zIndex" => 2,
                    "fontFamily" => "",
                    "fontSize" => 36,
                    "weight" => true,
                    "space" => 0,
                    "lineHeight" => 1,
                    "fontColor" => "#333333",
                    "textAlign" => "center"
                ],
                [
                    "id" => "xiaoyuan_nickname",
                    "componentName" => "MemberNickname",
                    "componentTitle" => "邀请人昵称",
                    "type" => "text",
                    "path" => "member-nickname",
                    "uses" => 1,
                    "relate" => "nickname",
                    "value" => "",
                    "width" => 750,
                    "height" => 50,
                    "minWidth" => 120,
                    "minHeight" => 44,
                    "x" => "center",
                    "y" => 700,
                    "angle" => 0,
                    "zIndex" => 3,
                    "fontFamily" => "",
                    "fontSize" => 28,
                    "weight" => false,
                    "space" => 0,
                    "lineHeight" => 1,
                    "fontColor" => "#666666",
                    "textAlign" => "center"
                ],
                [
                    "id" => "xiaoyuan_headimg",
                    "componentName" => "MemberHeadimg",
                    "componentTitle" => "邀请人头像",
                    "type" => "image",
                    "path" => "member-headimg",
                    "uses" => 1,
                    "relate" => "headimg",
                    "value" => "static/resource/images/default_headimg.png",
                    "width" => 120,
                    "height" => 120,
                    "minWidth" => 60,
                    "minHeight" => 60,
                    "x" => 315,
                    "y" => 560,
                    "angle" => 0,
                    "zIndex" => 2,
                    "borderRadius" => 60
                ],
                [
                    "id" => "xiaoyuan_qrcode",
                    "componentName" => "Qrcode",
                    "componentTitle" => "二维码",
                    "type" => "qrcode",
                    "path" => "qrcode",
                    "uses" => 1,
                    "relate" => "url",
                    "value" => "",
                    "width" => 200,
                    "height" => 200,
                    "minWidth" => 100,
                    "minHeight" => 100,
                    "x" => 275,
                    "y" => 900,
                    "angle" => 0,
                    "zIndex" => 4
                ]
            ]
        ]
    ]
];
