<?php

return [
    'DIY_HOME_SERVICE_INDEX' => [
        'home_service_index' => [ // 页面标识
            "title" => "上门家政", // 页面名称
            'cover' => '', // 页面封面图
            'preview' => '', // 页面预览图
            'desc' => '', // 页面描述
            'mode' => 'diy', // 页面模式：diy：自定义，fixed：固定
            // 页面数据源
            "data" => [
                'global' => [
                    'title' => '首页',
                    'pageStartBgColor' => 'rgba(247, 247, 247, 1)',
                    'pageEndBgColor' => '',
                    'pageGradientAngle' => 'to bottom',
                    'bgUrl' => '',
                    'bgHeightScale' => 0,
                    'imgWidth' => '',
                    'imgHeight' => '',
                    'topStatusBar' => [
                        'control' => true,
                        'isShow' => false,
                        'bgColor' => '#ffffff',
                        'rollBgColor' => '#ffffff',
                        'style' => 'style-1',
                        'styleName' => '风格1',
                        'textColor' => '#333333',
                        'rollTextColor' => '#333333',
                        'textAlign' => 'center',
                        'inputPlaceholder' => '请输入搜索关键词',
                        'imgUrl' => '',
                        'link' => [
                            'name' => '',
                        ],
                    ],
                    'bottomTabBar' => [
                        'control' => true,
                        'isShow' => true,
                        'designNav' => [
                            'title' => '',
                            'key' => ''
                        ]
                    ],
                    "copyright" => [
                        'control' => true,
                        'isShow' => false
                    ],
                    'popWindow' => [
                        'imgUrl' => '',
                        'imgWidth' => '',
                        'imgHeight' => '',
                        'count' => 'once',
                        'show' => false,
                        'link' => [
                            'name' => '',
                        ],
                    ],
                    'template' => [
                        'textColor' => '#303133',
                        'pageStartBgColor' => '',
                        'pageEndBgColor' => '',
                        'pageGradientAngle' => 'to bottom',
                        'componentBgUrl' => '',
                        'componentBgAlpha' => 2,
                        'componentStartBgColor' => '',
                        'componentEndBgColor' => '',
                        'componentGradientAngle' => 'to bottom',
                        'topRounded' => 0,
                        'bottomRounded' => 0,
                        'elementBgColor' => '',
                        'topElementRounded' => 0,
                        'bottomElementRounded' => 0,
                        'margin' => [
                            'top' => 0,
                            'bottom' => 0,
                            'both' => 0,
                        ],
                    ],
                ],
                'value' => [
                    [
                        'path' => 'edit-homeService-carousel-search',
                        'uses' => 1,
                        'id' => '4proyjsubts',
                        'componentName' => 'HomeServiceCarouselSearch',
                        'componentTitle' => '顶部导航',
                        'ignore' => [
                            'componentBgColor',
                            'componentBgUrl',
                            'marginTop',
                            'marginBottom',
                            'topRounded',
                            'bottomRounded',
                            'pageBgColor',
                            'marginBoth',
                        ],
                        'positionWay' => 'static',
                        'fixedBgColor' => '',
                        'bgGradient' => false,
                        'search' => [
                            'logo' => '',
                            'text' => '请输入搜索关键词',
                            'link' => [
                                'parent' => 'HOME_SERVICE_LINK',
                                'name' => 'HOME_SERVICE_GOODS_SEARCH',
                                'title' => '商品列表',
                                'url' => '/addon/home_service/user/pages/goods/list',
                                'action' => '',
                            ],
                            'style' => 'style-2',
                            'styleName' => '风格2',
                            'subTitle' => [
                                'text' => '本地好价·优选生活',
                                'textColor' => '#000000',
                                'startColor' => 'rgba(255,255,255,0.7)',
                                'endColor' => '',
                            ],
                            'positionColor' => 'rgba(16, 15, 15, 1)',
                            'hotWord' => [
                                'interval' => 3,
                                'list' => [
                                ],
                            ],
                            'color' => '#999999',
                            'btnColor' => '#ffffff',
                            'bgColor' => '#ffffff',
                            'btnBgColor' => 'rgba(38, 221, 0, 1)',
                        ],
                        'tab' => [
                            'control' => true,
                            'noColor' => '',
                            'selectColor' => '',
                            'fixedNoColor' => '',
                            'fixedSelectColor' => '',
                            'list' => [
                                [
                                    'text' => '分类名称',
                                    'source' => 'diy_page',
                                    'diy_id' => '',
                                    'diy_title' => '',
                                    'id' => '1v0dvi3fwlls',
                                ],
                                [
                                    'text' => '分类名称',
                                    'source' => 'diy_page',
                                    'diy_id' => '',
                                    'diy_title' => '',
                                    'id' => '13oxdbj931pc',
                                ],
                                [
                                    'text' => '分类名称',
                                    'source' => 'diy_page',
                                    'diy_id' => '',
                                    'diy_title' => '',
                                    'id' => '5ct4zx5l0nk0',
                                ],
                                [
                                    'text' => '分类名称',
                                    'source' => 'diy_page',
                                    'diy_id' => '',
                                    'diy_title' => '',
                                    'id' => '5lgkwak2mag0',
                                ],
                            ],
                        ],
                        'swiper' => [
                            'control' => true,
                            'interval' => 5,
                            'indicatorColor' => 'rgba(0, 0, 0, 0.3)',
                            'indicatorActiveColor' => '#FF0E0E',
                            'indicatorStyle' => 'style-1',
                            'indicatorAlign' => 'center',
                            'swiperStyle' => 'style-1',
                            'imageHeight' => 211,
                            'topRounded' => 0,
                            'bottomRounded' => 0,
                            'list' => [
                                [
                                    'imageUrl' => 'addon/home_service/diy/index/diy_img/17612692790a88b82c47849201c9e68c24c6283080_local.png',
                                    'imgWidth' => 750,
                                    'imgHeight' => 460,
                                    'link' => [
                                        'name' => '',
                                    ],
                                    'id' => '4avql2lmbg40',
                                    'width' => 345,
                                    'height' => 211.6,
                                ],
                            ],
                        ],
                        'textColor' => '#303133',
                        'pageStartBgColor' => '',
                        'pageEndBgColor' => '',
                        'pageGradientAngle' => 'to bottom',
                        'componentBgUrl' => '',
                        'componentBgAlpha' => 2,
                        'componentStartBgColor' => '',
                        'componentEndBgColor' => '',
                        'componentGradientAngle' => 'to bottom',
                        'topRounded' => 0,
                        'bottomRounded' => 0,
                        'elementBgColor' => '',
                        'topElementRounded' => 0,
                        'bottomElementRounded' => 0,
                        'margin' => [
                            'top' => 0,
                            'bottom' => 0,
                            'both' => 0,
                        ],
                        'pageStyle' => 'padding-top:2rpx;padding-bottom:0rpx;padding-right:0rpx;padding-left:0rpx;',
                        'componentIsShow' => true,
                    ],
                    [
                        'path' => 'edit-homeServicemember-card',
                        'uses' => 1,
                        'id' => '4w6a3uvjy5q0',
                        'componentName' => 'HomeServiceGuarantee',
                        'componentTitle' => '服务保障',
                        'ignore' => [
                            'componentBgUrl',
                        ],
                        'style' => 'style-1',
                        'styleName' => '风格1',
                        'bgUrl' => 'addon/home_service/diy/index/diy_img/17585947551c38487a41d51a7ec0e76d1fb656caf1_local.png',
                        'bgColorStart' => '',
                        'bgColorEnd' => '',
                        'textColor' => '#303133',
                        'pageStartBgColor' => '',
                        'pageEndBgColor' => '',
                        'pageGradientAngle' => 'to bottom',
                        'componentBgUrl' => '',
                        'componentBgAlpha' => 2,
                        'componentStartBgColor' => '',
                        'componentEndBgColor' => '',
                        'componentGradientAngle' => 'to bottom',
                        'topRounded' => 0,
                        'bottomRounded' => 0,
                        'elementBgColor' => '',
                        'topElementRounded' => 0,
                        'bottomElementRounded' => 0,
                        'margin' => [
                            'top' => -9,
                            'bottom' => -9,
                            'both' => 0,
                        ],
                        'pageStyle' => 'padding-top:2rpx;padding-bottom:0rpx;padding-right:0rpx;padding-left:0rpx;',
                        'componentIsShow' => true,
                    ],
                    [
                        'path' => 'edit-graphic-nav',
                        'uses' => 0,
                        'id' => '7c75avfhswo0',
                        'componentName' => 'GraphicNav',
                        'componentTitle' => '图文导航',
                        'ignore' => [
                        ],
                        'layout' => 'horizontal',
                        'mode' => 'graphic',
                        'showStyle' => 'fixed',
                        'rowCount' => 5,
                        'pageCount' => 2,
                        'carousel' => [
                            'type' => 'circle',
                            'color' => '#FFFFFF',
                        ],
                        'imageSize' => 30,
                        'aroundRadius' => 0,
                        'font' => [
                            'size' => 12,
                            'weight' => 'normal',
                            'color' => '#303133',
                        ],
                        'list' => [
                            [
                                'title' => '次卡套餐',
                                'link' => [
                                    'parent' => 'HOME_SERVICE_LINK',
                                    'name' => 'HOME_SERVICE_CARD_LIST',
                                    'title' => '次卡列表',
                                    'url' => '/addon/home_service/user/pages/card/list',
                                    'action' => '',
                                ],
                                'imageUrl' => 'addon/home_service/diy/index/diy_img/176069781261ff43f82289b8edacf3ea5dbd2c291c_local.png',
                                'label' => [
                                    'control' => false,
                                    'text' => '热门',
                                    'textColor' => '#FFFFFF',
                                    'bgColorStart' => '#F83287',
                                    'bgColorEnd' => '#FE3423',
                                ],
                                'id' => '86mcxqg7ycg',
                                'imgWidth' => 180,
                                'imgHeight' => 180,
                            ],
                            [
                                'title' => '领券中心',
                                'link' => [
                                    'parent' => 'HOME_SERVICE_LINK',
                                    'name' => 'HOME_SERVICE_COUPON',
                                    'title' => '优惠券',
                                    'url' => '/addon/home_service/user/pages/coupon/coupon',
                                    'action' => '',
                                ],
                                'imageUrl' => 'addon/home_service/diy/index/diy_img/176069781249bef76a21f530416aa62dac5d12367a_local.png',
                                'label' => [
                                    'control' => false,
                                    'text' => '热门',
                                    'textColor' => '#FFFFFF',
                                    'bgColorStart' => '#F83287',
                                    'bgColorEnd' => '#FE3423',
                                ],
                                'id' => '4ylm8o81jr80',
                                'imgWidth' => 180,
                                'imgHeight' => 180,
                            ],
                            [
                                'title' => '家电清洗',
                                'link' => [
                                    'parent' => 'HOME_SERVICE_LINK',
                                    'name' => 'HOME_SERVICE_CATEGORY',
                                    'title' => '分类',
                                    'url' => '/addon/home_service/user/pages/goods/category',
                                    'action' => '',
                                ],
                                'imageUrl' => 'addon/home_service/diy/index/diy_img/17606978121e10202fae46c70ec7dbc023f25e1577_local.png',
                                'label' => [
                                    'control' => false,
                                    'text' => '热门',
                                    'textColor' => '#FFFFFF',
                                    'bgColorStart' => '#F83287',
                                    'bgColorEnd' => '#FE3423',
                                ],
                                'id' => '6wp1x2w81a40',
                                'imgWidth' => 180,
                                'imgHeight' => 180,
                            ],
                            [
                                'id' => '6jyeoqb04io0',
                                'title' => '收纳整理',
                                'imageUrl' => 'addon/home_service/diy/index/diy_img/1760697812c7d5b382f702f804ef4a49b068cacbe8_local.png',
                                'imgWidth' => 180,
                                'imgHeight' => 180,
                                'link' => [
                                    'parent' => 'HOME_SERVICE_LINK',
                                    'name' => 'HOME_SERVICE_CATEGORY',
                                    'title' => '项目分类',
                                    'url' => '/addon/home_service/pages/goods/category',
                                    'action' => '',
                                ],
                                'label' => [
                                    'control' => false,
                                    'text' => '热门',
                                    'textColor' => '#FFFFFF',
                                    'bgColorStart' => '#F83287',
                                    'bgColorEnd' => '#FE3423',
                                ],
                            ],
                            [
                                'title' => '家政保洁',
                                'link' => [
                                    'parent' => 'HOME_SERVICE_LINK',
                                    'name' => 'HOME_SERVICE_CATEGORY',
                                    'title' => '项目分类',
                                    'url' => '/addon/home_service/pages/goods/category',
                                    'action' => '',
                                ],
                                'imageUrl' => 'addon/home_service/diy/index/diy_img/1760697812a98303514ccb9a97c858075b0abf844e_local.png',
                                'label' => [
                                    'control' => false,
                                    'text' => '热门',
                                    'textColor' => '#FFFFFF',
                                    'bgColorStart' => '#F83287',
                                    'bgColorEnd' => '#FE3423',
                                ],
                                'id' => '57bbo260q4k0',
                                'imgWidth' => 180,
                                'imgHeight' => 180,
                            ],
                            [
                                'id' => '7fihi2yqzcs0',
                                'title' => '月嫂保姆',
                                'imageUrl' => 'addon/home_service/diy/index/diy_img/1760697812d682b9091189c02c3cb95d2002cd8393_local.png',
                                'imgWidth' => 180,
                                'imgHeight' => 180,
                                'link' => [
                                    'parent' => 'HOME_SERVICE_LINK',
                                    'name' => 'HOME_SERVICE_CATEGORY',
                                    'title' => '分类',
                                    'url' => '/addon/home_service/user/pages/goods/category',
                                    'action' => '',
                                ],
                                'label' => [
                                    'control' => false,
                                    'text' => '热门',
                                    'textColor' => '#FFFFFF',
                                    'bgColorStart' => '#F83287',
                                    'bgColorEnd' => '#FE3423',
                                ],
                            ],
                            [
                                'id' => '6crxuv6l8240',
                                'title' => '新居搬迁',
                                'imageUrl' => 'addon/home_service/diy/index/diy_img/1760697812b7a00091d37b6d42b12f8f1a035b691a_local.png',
                                'imgWidth' => 180,
                                'imgHeight' => 180,
                                'link' => [
                                    'parent' => 'HOME_SERVICE_LINK',
                                    'name' => 'HOME_SERVICE_CATEGORY',
                                    'title' => '分类',
                                    'url' => '/addon/home_service/user/pages/goods/category',
                                    'action' => '',
                                ],
                                'label' => [
                                    'control' => false,
                                    'text' => '热门',
                                    'textColor' => '#FFFFFF',
                                    'bgColorStart' => '#F83287',
                                    'bgColorEnd' => '#FE3423',
                                ],
                            ],
                            [
                                'id' => '6tifwh4690w0',
                                'title' => '保健按摩',
                                'imageUrl' => 'addon/home_service/diy/index/diy_img/176069781201afdf2a246982d4320dc67ea26d5e8d_local.png',
                                'imgWidth' => 180,
                                'imgHeight' => 180,
                                'link' => [
                                    'parent' => 'HOME_SERVICE_LINK',
                                    'name' => 'HOME_SERVICE_CATEGORY',
                                    'title' => '分类',
                                    'url' => '/addon/home_service/user/pages/goods/category',
                                    'action' => '',
                                ],
                                'label' => [
                                    'control' => false,
                                    'text' => '热门',
                                    'textColor' => '#FFFFFF',
                                    'bgColorStart' => '#F83287',
                                    'bgColorEnd' => '#FE3423',
                                ],
                            ],
                            [
                                'id' => 'wugz49y4u2o',
                                'title' => '收纳整理',
                                'imageUrl' => 'addon/home_service/diy/index/diy_img/1760697812c6626329b087da0c5815093e91b6ec56_local.png',
                                'imgWidth' => 180,
                                'imgHeight' => 180,
                                'link' => [
                                    'parent' => 'HOME_SERVICE_LINK',
                                    'name' => 'HOME_SERVICE_CATEGORY',
                                    'title' => '分类',
                                    'url' => '/addon/home_service/user/pages/goods/category',
                                    'action' => '',
                                ],
                                'label' => [
                                    'control' => false,
                                    'text' => '热门',
                                    'textColor' => '#FFFFFF',
                                    'bgColorStart' => '#F83287',
                                    'bgColorEnd' => '#FE3423',
                                ],
                            ],
                            [
                                'id' => '5tk17yu2v9s0',
                                'title' => '其他服务',
                                'imageUrl' => 'addon/home_service/diy/index/diy_img/17606978129a7e005349f66a6241f914472aa60970_local.png',
                                'imgWidth' => 180,
                                'imgHeight' => 180,
                                'link' => [
                                    'parent' => 'HOME_SERVICE_LINK',
                                    'title' => '分类',
                                    'url' => '/addon/home_service/user/pages/goods/category',
                                    'name' => 'HOME_SERVICE_CATEGORY',
                                    'action' => '',
                                ],
                                'label' => [
                                    'control' => false,
                                    'text' => '热门',
                                    'textColor' => '#FFFFFF',
                                    'bgColorStart' => '#F83287',
                                    'bgColorEnd' => '#FE3423',
                                ],
                            ],
                        ],
                        'swiper' => [
                            'indicatorColor' => 'rgba(0, 0, 0, 0.3)',
                            'indicatorActiveColor' => '#FF0E0E',
                            'indicatorStyle' => 'style-1',
                            'indicatorAlign' => 'center',
                        ],
                        'textColor' => '#303133',
                        'pageStartBgColor' => 'rgba(255, 255, 255, 1)',
                        'pageEndBgColor' => 'rgba(201, 53, 53, 0)',
                        'pageGradientAngle' => 'to bottom',
                        'componentBgUrl' => '',
                        'componentBgAlpha' => 2,
                        'componentStartBgColor' => 'rgba(255, 255, 255, 1)',
                        'componentEndBgColor' => '',
                        'componentGradientAngle' => 'to bottom',
                        'topRounded' => 10,
                        'bottomRounded' => 10,
                        'elementBgColor' => '',
                        'topElementRounded' => 0,
                        'bottomElementRounded' => 0,
                        'margin' => [
                            'top' => -10,
                            'bottom' => 10,
                            'both' => 10,
                        ],
                        'pageStyle' => 'background:linear-gradient(to bottom,rgba(246, 246, 246, 1),rgba(201, 53, 53, 0));padding-top:2rpx;padding-bottom:20rpx;padding-right:20rpx;padding-left:20rpx;',
                        'componentIsShow' => true,
                    ],
                    [
                        'path' => 'edit-homeServicemember-subguarantee',
                        'uses' => 1,
                        'id' => '5iic5szmlyg0',
                        'componentName' => 'HomeServiceSubguarantee',
                        'componentTitle' => '售后保障',
                        'ignore' => [
                            'componentBgUrl',
                        ],
                        'style' => 'style-1',
                        'styleName' => '风格1',
                        'bgUrl' => 'addon/home_service/diy/index/diy_img/1758596927c855e8b6fbd3cfb79d6d202869036b37_local.png',
                        'bgColorStart' => '',
                        'bgColorEnd' => '',
                        'textColor' => '#000000',
                        'pageStartBgColor' => NULL,
                        'pageEndBgColor' => '',
                        'pageGradientAngle' => 'to right',
                        'componentBgUrl' => '',
                        'componentBgAlpha' => 2,
                        'componentStartBgColor' => 'rgba(255, 255, 255, 1)',
                        'componentEndBgColor' => '',
                        'componentGradientAngle' => 'to bottom',
                        'topRounded' => 5,
                        'bottomRounded' => 5,
                        'elementBgColor' => '',
                        'topElementRounded' => 0,
                        'bottomElementRounded' => 0,
                        'margin' => [
                            'top' => 6,
                            'bottom' => 0,
                            'both' => 10,
                        ],
                        'leftDesc' => '价格透明 · 专业服',
                        'desc' => '价格透明·专业服务·售后保障',
                        'title' => '家政保洁',
                        'titleTextColor' => '#2BF103',
                        'titleBgColor' => '#EBFFEA',
                        'pageStyle' => 'padding-top:12rpx;padding-bottom:0rpx;padding-right:20rpx;padding-left:20rpx;',
                        'componentIsShow' => true,
                    ],
                    [
                        'path' => 'edit-homeServicemember-panicBuying',
                        'uses' => 1,
                        'id' => '2m3rppuylqw0',
                        'componentName' => 'HomeServicePanicBuying',
                        'componentTitle' => '新人抢购',
                        'ignore' => [
                        ],
                        'style' => 'style-1',
                        'styleName' => '风格1',
                        'bgUrl' => 'addon/home_service/diy/index/diy_img/1758600689625a67f81be9ddbd1ed495291a6814cc_local.png',
                        'bgColorStart' => '',
                        'bgColorEnd' => '',
                        'desc' => '',
                        'textColor' => '#FFFFFF',
                        'titleTextColor' => '',
                        'titleBgColor' => '',
                        'pageStartBgColor' => '',
                        'pageEndBgColor' => '',
                        'pageGradientAngle' => 'to bottom',
                        'componentBgUrl' => '',
                        'componentBgAlpha' => 2,
                        'componentStartBgColor' => '',
                        'componentEndBgColor' => '',
                        'componentGradientAngle' => 'to bottom',
                        'topRounded' => 0,
                        'bottomRounded' => 0,
                        'elementBgColor' => '',
                        'topElementRounded' => 0,
                        'bottomElementRounded' => 0,
                        'margin' => [
                            'top' => 12,
                            'bottom' => 0,
                            'both' => 12,
                        ],
                        'pageStyle' => 'padding-top:24rpx;padding-bottom:0rpx;padding-right:24rpx;padding-left:24rpx;',
                        'componentIsShow' => true,
                        'goods_ids' => [
                        ],
                        'imageUrl' => '',
                        'source' => 'all',
                        'num' => 4,
                    ],
                    [
                        'path' => 'edit-homeServicemember-cardList',
                        'uses' => 1,
                        'id' => '2ntb5k8h6kw0',
                        'componentName' => 'HomeServiceCardList',
                        'componentTitle' => '次卡列表',
                        'ignore' => [
                        ],
                        'style' => 'style-1',
                        'source' => 'all',
                        'num' => 3,
                        'leftBg' => 'addon/home_service/diy/index/diy_img/card_bg.png',
                        'goods_category' => '',
                        'goods_category_name' => '请选择',
                        'goods_ids' => [
                        ],
                        'bgUrl' => 'addon/home_service/diy/index/diy_img/17586275504260817ed1482bcd9f2f0ade3d3cb83e_local.png',
                        'sortWay' => 'default',
                        'goodsNameStyle' => [
                            'color' => '#303133',
                            'control' => true,
                            'fontWeight' => 'normal',
                            'isShow' => true,
                        ],
                        'priceStyle' => [
                            'color' => '#FF4142',
                            'control' => true,
                            'isShow' => true,
                        ],
                        'saleStyle' => [
                            'color' => '#999999',
                            'control' => true,
                            'isShow' => true,
                        ],
                        'labelStyle' => [
                            'control' => true,
                            'isShow' => true,
                        ],
                        'btnStyle' => [
                            'fontWeight' => false,
                            'padding' => 0,
                            'aroundRadius' => 25,
                            'cartEvent' => 'detail',
                            'text' => '购买',
                            'textColor' => '#FFFFFF',
                            'startBgColor' => '#FF4142',
                            'endBgColor' => '#FF4142',
                            'style' => 'button',
                            'control' => true,
                        ],
                        'imgElementRounded' => 10,
                        'textColor' => '#303133',
                        'pageStartBgColor' => '',
                        'pageEndBgColor' => '',
                        'pageGradientAngle' => 'to bottom',
                        'componentBgUrl' => '',
                        'componentBgAlpha' => 2,
                        'componentStartBgColor' => '',
                        'componentEndBgColor' => '',
                        'componentGradientAngle' => 'to bottom',
                        'topRounded' => 12,
                        'bottomRounded' => 12,
                        'elementBgColor' => '',
                        'topElementRounded' => 0,
                        'bottomElementRounded' => 0,
                        'margin' => [
                            'top' => 12,
                            'bottom' => 0,
                            'both' => 12,
                        ],
                    ],
                    [
                        'path' => 'edit-homeService-rubik-cube',
                        'uses' => 0,
                        'id' => '1r8bn6r6nz3',
                        'componentName' => 'HomeServiceRubikCube',
                        'componentTitle' => '魔方',
                        'ignore' => [
                            'componentBgUrl',
                        ],
                        'bgUrl' => 'addon/home_service/diy/index/diy_img/1760757786bd8ff92e8586b2a75be917dbfc8ff77f_local.png',
                        'topBgUrl' => 'addon/home_service/diy/index/diy_img/1758610876a24d41a4d56a505c9f821420a5ff27a0_local.png',
                        'topLink' => [
                            'name' => '',
                        ],
                        'leftLink' => [
                            'name' => '',
                        ],
                        'rightLink' => [
                            'name' => '',
                        ],
                        'bottomLeftBgUrl' => 'addon/home_service/diy/index/diy_img/175861088869a9905eb837f03e7319a9e6fdb8dde7_local.png',
                        'bottomRightBgUrl' => 'addon/home_service/diy/index/diy_img/1758610911abbbc85659892fd18e48e975be4d63b2_local.png',
                        'textColor' => '#303133',
                        'pageStartBgColor' => '',
                        'pageEndBgColor' => '',
                        'pageGradientAngle' => 'to bottom',
                        'componentBgUrl' => '',
                        'componentBgAlpha' => 2,
                        'componentStartBgColor' => 'rgba(255, 255, 255, 1)',
                        'componentEndBgColor' => '',
                        'componentGradientAngle' => 'to bottom',
                        'topRounded' => 12,
                        'bottomRounded' => 12,
                        'elementBgColor' => '',
                        'topElementRounded' => 0,
                        'bottomElementRounded' => 0,
                        'margin' => [
                            'top' => 12,
                            'bottom' => 0,
                            'both' => 12,
                        ],
                    ],
                    [
                        'path' => 'edit-homeServicemember-lowCost',
                        'uses' => 1,
                        'id' => '2dtbps3dclxc',
                        'componentName' => 'HomeServiceLowCost',
                        'componentTitle' => '本地低价购',
                        'ignore' => [
                        ],
                        'style' => 'style-1',
                        'source' => 'all',
                        'num' => 3,
                        'goods_category' => '',
                        'goods_category_name' => '请选择',
                        'goods_ids' => [
                        ],
                        'sortWay' => 'default',
                        'goodsNameStyle' => [
                            'color' => '#303133',
                            'control' => true,
                            'fontWeight' => 'normal',
                            'isShow' => true,
                        ],
                        'priceStyle' => [
                            'color' => '#FF4142',
                            'control' => true,
                            'isShow' => true,
                        ],
                        'saleStyle' => [
                            'color' => '#999999',
                            'control' => true,
                            'isShow' => true,
                        ],
                        'labelStyle' => [
                            'control' => true,
                            'isShow' => true,
                        ],
                        'btnStyle' => [
                            'fontWeight' => false,
                            'padding' => 0,
                            'aroundRadius' => 25,
                            'cartEvent' => 'detail',
                            'text' => '购买',
                            'textColor' => '#FFFFFF',
                            'startBgColor' => '#FF4142',
                            'endBgColor' => '#FF4142',
                            'style' => 'button',
                            'control' => true,
                        ],
                        'imgElementRounded' => 10,
                        'textColor' => '#303133',
                        'pageStartBgColor' => '',
                        'pageEndBgColor' => '',
                        'pageGradientAngle' => 'to bottom',
                        'componentBgUrl' => '',
                        'componentBgAlpha' => 2,
                        'componentStartBgColor' => '',
                        'componentEndBgColor' => '',
                        'componentGradientAngle' => 'to bottom',
                        'topRounded' => 12,
                        'bottomRounded' => 12,
                        'elementBgColor' => '',
                        'topElementRounded' => 10,
                        'bottomElementRounded' => 10,
                        'margin' => [
                            'top' => 12,
                            'bottom' => 12,
                            'both' => 10,
                        ],
                        'bgUrl' => 'addon/home_service/diy/index/diy_img/1758615490f1ae2fa154052d09c482f4691215d07b_local.jpg',
                        'imageUrl' => '',
                    ],
                    [
                        'path' => 'edit-homeService-many-goods-list',
                        'uses' => 0,
                        'id' => '4zp3op79k440',
                        'componentName' => 'HomeServiceManyGoodsList',
                        'componentTitle' => '多商品组',
                        'ignore' => [
                            'componentBgUrl',
                        ],
                        'style' => 'style-2',
                        'num' => 6,
                        'sortWay' => 'default',
                        'headStyle' => 'style-1',
                        'aroundRadius' => 25,
                        'source' => 'goods_category',
                        'goods_category' => 96,
                        'goods_category_name' => '上门回收',
                        'goodsNameStyle' => [
                            'color' => '#303133',
                            'control' => true,
                            'fontWeight' => 'normal',
                            'isShow' => true,
                        ],
                        'priceStyle' => [
                            'color' => '#FF4142',
                            'control' => true,
                            'isShow' => true,
                        ],
                        'saleStyle' => [
                            'color' => '#999999',
                            'control' => true,
                            'isShow' => true,
                        ],
                        'labelStyle' => [
                            'control' => true,
                            'isShow' => true,
                        ],
                        'btnStyle' => [
                            'fontWeight' => false,
                            'padding' => 0,
                            'aroundRadius' => 25,
                            'cartEvent' => 'detail',
                            'text' => '购买',
                            'textColor' => '#FFFFFF',
                            'startBgColor' => NULL,
                            'endBgColor' => NULL,
                            'style' => 'nc-icon-jiahaoV6xx',
                            'control' => true,
                        ],
                        'list' => [
                            [
                                'title' => '今天推荐',
                                'desc' => '猜你喜欢',
                                'source' => 'all',
                                'goods_category' => '',
                                'goods_category_name' => '请选择',
                                'goods_ids' => [
                                ],
                                'imageUrl' => '',
                                'id' => 'gonbh19jjko',
                                'bgUrl' => 'addon/home_service/diy/index/diy_img/17606893721f251a0d3b335459f826d8b398e519ad_local.png,addon/home_service/diy/index/diy_img/176120076637536766c6d92d7f4fcf3a22776d23dc_local.jpg',
                                'num' => 5,
                            ],
                            [
                                'id' => '6rtb7ticmb0',
                                'title' => '分享好物',
                                'desc' => '分类描述',
                                'source' => 'all',
                                'goods_category' => '',
                                'goods_category_name' => '请选择',
                                'goods_ids' => [
                                ],
                                'imageUrl' => '',
                                'bgUrl' => 'addon/home_service/diy/index/diy_img/17612683891205634433ce1fd5960240177074c96f_local.jpg',
                                'num' => 5,
                            ],
                            [
                                'id' => '3vl4lm7mtjc0',
                                'title' => '猜你喜欢',
                                'desc' => '分类描述',
                                'source' => 'all',
                                'goods_category' => '',
                                'goods_category_name' => '请选择',
                                'goods_ids' => [
                                ],
                                'imageUrl' => '',
                                'bgUrl' => 'addon/home_service/diy/index/diy_img/17606893726163a5234efbc5c0f8f30252ca980b99_local.jpg',
                                'num' => 5,
                            ],
                        ],
                        'imgElementRounded' => 0,
                        'textColor' => '#303133',
                        'pageStartBgColor' => NULL,
                        'pageEndBgColor' => '',
                        'pageGradientAngle' => 'to bottom',
                        'componentBgUrl' => '',
                        'componentBgAlpha' => 2,
                        'componentStartBgColor' => 'rgba(255, 255, 255, 1)',
                        'componentEndBgColor' => '',
                        'componentGradientAngle' => 'to bottom',
                        'topRounded' => 0,
                        'bottomRounded' => 0,
                        'elementBgColor' => '',
                        'topElementRounded' => 0,
                        'bottomElementRounded' => 0,
                        'margin' => [
                            'top' => 0,
                            'bottom' => 0,
                            'both' => 12,
                        ],
                        'bgUrl' => 'addon/home_service/diy/index/diy_img/175862546020b9dfbf2ad4c887670d2aa99ad7e8af_local.png',
                    ],
                ],
            ]
        ]
    ],
    'DIY_HOME_SERVICE_MEMBER_INDEX' => [
        'home_service_member_index' => [
            "title" => "上门服务个人中心", // 页面名称
            'cover' => '', // 页面封面图
            'preview' => '', // 页面预览图
            'desc' => '个人中心', // 页面描述
            'mode' => 'diy', // 页面模式：diy：自定义，fixed：固定
            'data' => [
                'global' => [
                    'title' => '个人中心',
                    'pageStartBgColor' => '#F8F8F8',
                    'pageEndBgColor' => '',
                    'pageGradientAngle' => 'to bottom',
                    'bgUrl' => 'addon/home_service/diy/member/diy_img/member_bg1.png',
                    'bgHeightScale' => 0,
                    'imgWidth' => 1500,
                    'imgHeight' => 1210,
                    'bottomTabBar' => [
                        'control' => true,
                        'isShow' => true,
                        'designNav' => [
                            'title' => '',
                            'key' => ''
                        ]
                    ],
                    "copyright" => [
                        'control' => true,
                        'isShow' => false
                    ],
                    'template' => [
                        'textColor' => '#303133',
                        'pageStartBgColor' => '',
                        'pageEndBgColor' => '',
                        'pageGradientAngle' => 'to bottom',
                        'componentBgUrl' => '',
                        'componentBgAlpha' => 2,
                        'componentStartBgColor' => '',
                        'componentEndBgColor' => '',
                        'componentGradientAngle' => 'to bottom',
                        'topRounded' => 0,
                        'bottomRounded' => 0,
                        'elementBgColor' => '',
                        'topElementRounded' => 0,
                        'bottomElementRounded' => 0,
                        'margin' => [
                            'top' => 0,
                            'bottom' => 0,
                            'both' => 12,
                        ],
                    ],
                    'topStatusBar' => [
                        'control' => true,
                        'isShow' => false,
                        'bgColor' => '#ffffff',
                        'rollBgColor' => '#ffffff',
                        'style' => 'style-1',
                        'styleName' => '风格1',
                        'textColor' => '#333333',
                        'rollTextColor' => '#333333',
                        'textAlign' => 'center',
                        'inputPlaceholder' => '请输入搜索关键词',
                        'imgUrl' => '',
                        'link' => [
                            'name' => '',
                        ],
                    ],
                    'popWindow' => [
                        'imgUrl' => '',
                        'imgWidth' => '',
                        'imgHeight' => '',
                        'count' => 'once',
                        'show' => false,
                        'link' => [
                            'name' => '',
                        ],
                    ],
                ],
                'value' => [
                    [
                        'path' => 'edit-homeServicemember-info',
                        'uses' => 1,
                        'id' => '1c1ft1phpdcw',
                        'componentName' => 'HomeServiceMemberInfo',
                        'componentTitle' => '会员信息',
                        'ignore' => [
                            'componentBgUrl',
                        ],
                        'style' => 'style-1',
                        'styleName' => '风格1',
                        'bgUrl' => '',
                        'bgColorStart' => '',
                        'bgColorEnd' => '',
                        'textColor' => '#303133',
                        'pageStartBgColor' => '',
                        'pageEndBgColor' => '',
                        'pageGradientAngle' => 'to bottom',
                        'componentBgUrl' => '',
                        'componentBgAlpha' => 2,
                        'componentStartBgColor' => '',
                        'componentEndBgColor' => '',
                        'componentGradientAngle' => 'to bottom',
                        'topRounded' => 0,
                        'bottomRounded' => 0,
                        'elementBgColor' => '',
                        'topElementRounded' => 0,
                        'bottomElementRounded' => 0,
                        'margin' => [
                            'top' => 0,
                            'bottom' => 0,
                            'both' => 12,
                        ],
                        'pageStyle' => 'padding-top:2rpx;padding-bottom:0rpx;padding-right:24rpx;padding-left:24rpx;',
                        'componentIsShow' => true,
                    ],
                    [
                        'path' => 'edit-homeService-order-info',
                        'uses' => 1,
                        'id' => '1b5556icvmxs',
                        'componentName' => 'HomeServiceOrderInfo',
                        'componentTitle' => '订单中心',
                        'ignore' => [
                            'componentBgUrl',
                        ],
                        'textColor' => '#303133',
                        'fontSize' => 16,
                        'fontWeight' => 'normal',
                        'text' => '我的订单',
                        'more' => [
                            'text' => '全部订单',
                            'color' => '#999999',
                        ],
                        'item' => [
                            'fontSize' => 12,
                            'fontWeight' => 'normal',
                            'color' => '#303133',
                        ],
                        'pageStartBgColor' => 'rgba(255, 255, 255, 0)',
                        'pageEndBgColor' => 'rgba(144, 238, 144, 0)',
                        'pageGradientAngle' => 'to bottom',
                        'componentBgUrl' => '',
                        'componentBgAlpha' => 2,
                        'componentStartBgColor' => 'rgba(255, 255, 255, 1)',
                        'componentEndBgColor' => 'rgba(255, 255, 255, 1)',
                        'componentGradientAngle' => 'to bottom',
                        'topRounded' => 10,
                        'bottomRounded' => 10,
                        'elementBgColor' => '',
                        'topElementRounded' => 0,
                        'bottomElementRounded' => 0,
                        'margin' => [
                            'top' => 0,
                            'bottom' => 0,
                            'both' => 12,
                        ],
                        'pageStyle' => 'padding-top:2rpx;padding-bottom:0rpx;padding-right:24rpx;padding-left:24rpx;',
                        'componentIsShow' => true,
                    ],
                    [
                        'path' => 'edit-homeServicemember-card',
                        'uses' => 1,
                        'id' => '4ncxix0depw0',
                        'componentName' => 'HomeServiceCard',
                        'componentTitle' => '次卡管理',
                        'ignore' => [
                            'componentBgUrl',
                        ],
                        'style' => 'style-1',
                        'styleName' => '风格1',
                        'bgUrl' => 'addon/home_service/diy/member/diy_img/member_card_bg1.png',
                        'bgColorStart' => '',
                        'bgColorEnd' => '',
                        'textColor' => '#FFFFFF',
                        'pageStartBgColor' => '',
                        'pageEndBgColor' => '',
                        'pageGradientAngle' => 'to bottom',
                        'componentBgUrl' => '',
                        'componentBgAlpha' => 2,
                        'componentStartBgColor' => '',
                        'componentEndBgColor' => '',
                        'componentGradientAngle' => 'to bottom',
                        'topRounded' => 0,
                        'bottomRounded' => 0,
                        'elementBgColor' => '',
                        'topElementRounded' => 0,
                        'bottomElementRounded' => 0,
                        'margin' => [
                            'top' => 12,
                            'bottom' => 0,
                            'both' => 12,
                        ],
                        'pageStyle' => 'padding-top:2rpx;padding-bottom:0rpx;padding-right:24rpx;padding-left:24rpx;',
                        'componentIsShow' => true,
                    ],
                    [
                        'path' => 'edit-rubik-cube',
                        'uses' => 0,
                        'id' => '39u541m5dos0',
                        'componentName' => 'RubikCube',
                        'componentTitle' => '魔方',
                        'ignore' => [
                        ],
                        'mode' => 'row1-of3',
                        'imageGap' => 12,
                        'list' => [
                            [
                                'imageUrl' => 'addon/home_service/diy/member/diy_img/collect_goods.png',
                                'imgWidth' => 448,
                                'imgHeight' => 248,
                                'link' => [
                                    'parent' => 'DIY_LINK',
                                    'title' => '收藏',
                                    'url' => '/addon/home_service/user/pages/member/collect/goods',
                                    'name' => 'DIY_LINK',
                                    'action' => '',
                                ],
                            ],
                            [
                                'imageUrl' => 'addon/home_service/diy/member/diy_img/evaluate_list.png',
                                'imgWidth' => 448,
                                'imgHeight' => 248,
                                'link' => [
                                    'parent' => 'DIY_LINK',
                                    'title' => '评价列表',
                                    'url' => '/addon/home_service/user/pages/order/evaluate/list',
                                    'name' => 'DIY_LINK',
                                    'action' => '',
                                ],
                            ],
                            [
                                'imageUrl' => 'addon/home_service/diy/member/diy_img/member_history.png',
                                'imgWidth' => 448,
                                'imgHeight' => 248,
                                'link' => [
                                    'parent' => 'DIY_LINK',
                                    'url' => '/addon/home_service/user/pages/member/history',
                                    'title' => '我的足迹',
                                    'name' => 'DIY_LINK',
                                    'action' => '',
                                ],
                            ],
                        ],
                        'textColor' => '#303133',
                        'pageStartBgColor' => '',
                        'pageEndBgColor' => '',
                        'pageGradientAngle' => 'to bottom',
                        'componentBgUrl' => '',
                        'componentBgAlpha' => 2,
                        'componentStartBgColor' => '',
                        'componentEndBgColor' => '',
                        'componentGradientAngle' => 'to bottom',
                        'topRounded' => 0,
                        'bottomRounded' => 0,
                        'elementBgColor' => '',
                        'topElementRounded' => 12,
                        'bottomElementRounded' => 12,
                        'margin' => [
                            'top' => 12,
                            'bottom' => 12,
                            'both' => 12,
                        ],
                    ],
                    [
                        'path' => 'edit-homeServicemember-banner',
                        'uses' => 1,
                        'id' => '16kphkf7wu0w',
                        'componentName' => 'HomeServiceBanner',
                        'componentTitle' => '广告图片',
                        'ignore' => [
                            'componentBgUrl',
                        ],
                        'style' => 'style-1',
                        'styleName' => '风格1',
                        'bgUrl' => 'addon/home_service/diy/member/diy_img/banner1.png',
                        'bgColorStart' => '',
                        'bgColorEnd' => '',
                        'textColor' => '#303133',
                        'pageStartBgColor' => '',
                        'pageEndBgColor' => '',
                        'pageGradientAngle' => 'to bottom',
                        'componentBgUrl' => '',
                        'componentBgAlpha' => 2,
                        'componentStartBgColor' => '',
                        'componentEndBgColor' => '',
                        'componentGradientAngle' => 'to bottom',
                        'topRounded' => 12,
                        'bottomRounded' => 12,
                        'elementBgColor' => '',
                        'topElementRounded' => 0,
                        'bottomElementRounded' => 0,
                        'margin' => [
                            'top' => 0,
                            'bottom' => 12,
                            'both' => 12,
                        ],
                        'pageStyle' => 'padding-top:2rpx;padding-bottom:0rpx;padding-right:24rpx;padding-left:24rpx;',
                        'componentIsShow' => true,
                    ],
                    [
                        'path' => 'edit-homeServicemember-settle',
                        'uses' => 1,
                        'id' => '3wii95h8k9k0',
                        'componentName' => 'HomeServiceSettle',
                        'componentTitle' => '入驻模块',
                        'ignore' => [
                            'componentBgUrl',
                        ],
                        'style' => 'style-1',
                        'styleName' => '风格1',
                        'bgUrl' => '',
                        'bgColorStart' => '',
                        'bgColorEnd' => '',
                        'textColor' => '#303133',
                        'pageStartBgColor' => '',
                        'pageEndBgColor' => '',
                        'pageGradientAngle' => 'to bottom',
                        'componentBgUrl' => '',
                        'componentBgAlpha' => 2,
                        'componentStartBgColor' => '',
                        'componentEndBgColor' => '',
                        'componentGradientAngle' => 'to bottom',
                        'topRounded' => 0,
                        'bottomRounded' => 0,
                        'elementBgColor' => '',
                        'topElementRounded' => 0,
                        'bottomElementRounded' => 0,
                        'margin' => [
                            'top' => 0,
                            'bottom' => 0,
                            'both' => 12,
                        ],
                        'pageStyle' => 'padding-top:2rpx;padding-bottom:0rpx;padding-right:24rpx;padding-left:24rpx;',
                        'componentIsShow' => true,
                        'fontSize' => 12,
                        'leftText' => '技师管理',
                        'rightText' => '门店管理',
                        'leftDesc' => '全量技师信息总览',
                        'rightDesc' => '门店日常运营规范',
                    ],
                    [
                        'path' => 'edit-horz-blank',
                        'uses' => 0,
                        'id' => '22jcwfaoomv4',
                        'componentName' => 'HorzBlank',
                        'componentTitle' => '辅助空白',
                        'ignore' => [
                            'pageBgColor',
                            'componentBgUrl',
                        ],
                        'height' => 20,
                        'textColor' => '#303133',
                        'pageStartBgColor' => '',
                        'pageEndBgColor' => '',
                        'pageGradientAngle' => 'to bottom',
                        'componentBgUrl' => '',
                        'componentBgAlpha' => 2,
                        'componentStartBgColor' => 'rgba(255, 255, 255, 1)',
                        'componentEndBgColor' => 'rgba(255, 255, 255, 1)',
                        'componentGradientAngle' => 'to bottom',
                        'topRounded' => 10,
                        'bottomRounded' => 0,
                        'elementBgColor' => '',
                        'topElementRounded' => 0,
                        'bottomElementRounded' => 0,
                        'margin' => [
                            'top' => 12,
                            'bottom' => 0,
                            'both' => 12,
                        ],
                    ],
                    [
                        'path' => 'edit-text',
                        'uses' => 0,
                        'position' => '',
                        'id' => '4k7lkk0ac780',
                        'componentName' => 'Text',
                        'componentTitle' => '标题',
                        'ignore' => [
                        ],
                        'style' => 'style-1',
                        'styleName' => '风格1',
                        'text' => '常用工具',
                        'link' => [
                            'name' => '',
                        ],
                        'textColor' => '#303133',
                        'fontSize' => 14,
                        'fontWeight' => 'normal',
                        'textAlign' => 'left',
                        'subTitle' => [
                            'text' => '',
                            'color' => '#999999',
                            'fontSize' => 14,
                            'control' => false,
                            'fontWeight' => 'normal',
                        ],
                        'more' => [
                            'text' => '查看更多',
                            'control' => false,
                            'isShow' => false,
                            'link' => [
                                'name' => '',
                            ],
                            'color' => '#999999',
                        ],
                        'pageStartBgColor' => '',
                        'pageEndBgColor' => '',
                        'pageGradientAngle' => 'to bottom',
                        'componentBgUrl' => '',
                        'componentBgAlpha' => 2,
                        'componentStartBgColor' => 'rgba(255, 255, 255, 1)',
                        'componentEndBgColor' => '',
                        'componentGradientAngle' => 'to bottom',
                        'topRounded' => 0,
                        'bottomRounded' => 0,
                        'elementBgColor' => '',
                        'topElementRounded' => 0,
                        'bottomElementRounded' => 0,
                        'margin' => [
                            'top' => 0,
                            'bottom' => 0,
                            'both' => 12,
                        ],
                        'pageStyle' => 'padding-top:2rpx;padding-bottom:0rpx;padding-right:0rpx;padding-left:0rpx;',
                        'componentIsShow' => true,
                    ],
                    [
                        'path' => 'edit-graphic-nav',
                        'uses' => 0,
                        'id' => '33yn28534fs0',
                        'componentName' => 'GraphicNav',
                        'componentTitle' => '图文导航',
                        'ignore' => [
                        ],
                        'layout' => 'horizontal',
                        'mode' => 'graphic',
                        'showStyle' => 'fixed',
                        'rowCount' => 4,
                        'pageCount' => 2,
                        'carousel' => [
                            'type' => 'circle',
                            'color' => '#FFFFFF',
                        ],
                        'imageSize' => 25,
                        'aroundRadius' => 7,
                        'font' => [
                            'size' => 12,
                            'weight' => 'normal',
                            'color' => '#303133',
                        ],
                        'list' => [
                            [
                                'id' => '3yytuqlcknu0',
                                'title' => '技师入驻',
                                'imageUrl' => 'addon/home_service/diy/member/diy_img/technician.png',
                                'imgWidth' => 92,
                                'imgHeight' => 92,
                                'link' => [
                                    'parent' => 'DIY_LINK',
                                    'url' => '/addon/home_service/user/pages/settle/technician',
                                    'title' => '技师入驻',
                                    'name' => 'DIY_LINK',
                                    'action' => '',
                                ],
                                'label' => [
                                    'control' => false,
                                    'text' => '热门',
                                    'textColor' => '#FFFFFF',
                                    'bgColorStart' => '#F83287',
                                    'bgColorEnd' => '#FE3423',
                                ],
                            ],
                            [
                                'id' => '6t6izqiucao0',
                                'title' => '门店入驻',
                                'imageUrl' => 'addon/home_service/diy/member/diy_img/store.png',
                                'imgWidth' => 94,
                                'imgHeight' => 92,
                                'link' => [
                                    'parent' => 'DIY_LINK',
                                    'url' => '/addon/home_service/user/pages/settle/store',
                                    'title' => '门店入驻',
                                    'name' => 'DIY_LINK',
                                    'action' => '',
                                ],
                                'label' => [
                                    'control' => false,
                                    'text' => '热门',
                                    'textColor' => '#FFFFFF',
                                    'bgColorStart' => '#F83287',
                                    'bgColorEnd' => '#FE3423',
                                ],
                            ],
                            [
                                'id' => '5nz60xfvtig0',
                                'title' => '添加地址',
                                'imageUrl' => 'addon/home_service/diy/member/diy_img/address_edit.png',
                                'imgWidth' => 47,
                                'imgHeight' => 46,
                                'link' => [
                                    'parent' => 'DIY_LINK',
                                    'url' => '/addon/home_service/user/pages/address/address_edit',
                                    'title' => '添加地址',
                                    'name' => 'DIY_LINK',
                                    'action' => '',
                                ],
                                'label' => [
                                    'control' => false,
                                    'text' => '热门',
                                    'textColor' => '#FFFFFF',
                                    'bgColorStart' => '#F83287',
                                    'bgColorEnd' => '#FE3423',
                                ],
                            ],
                            [
                                'id' => '2x2tng3f95s',
                                'title' => '联系客服',
                                'imageUrl' => 'addon/home_service/diy/member/diy_img/contact.png',
                                'imgWidth' => 46,
                                'imgHeight' => 46,
                                'link' => [
                                    'parent' => 'MEMBER_LINK',
                                    'name' => 'MEMBER_CONTACT',
                                    'title' => '客服',
                                    'url' => '/app/pages/member/contact',
                                    'action' => '',
                                ],
                                'label' => [
                                    'control' => false,
                                    'text' => '热门',
                                    'textColor' => '#FFFFFF',
                                    'bgColorStart' => '#F83287',
                                    'bgColorEnd' => '#FE3423',
                                ],
                            ],
                            [
                                'id' => '3eynvyr7ah80',
                                'title' => '开票中心',
                                'imageUrl' => 'addon/home_service/diy/member/diy_img/invoice_list.png',
                                'imgWidth' => 92,
                                'imgHeight' => 92,
                                'link' => [
                                    'parent' => 'DIY_LINK',
                                    'url' => '/addon/home_service/user/pages/member/invoice/list',
                                    'title' => '发票',
                                    'name' => 'DIY_LINK',
                                    'action' => '',
                                ],
                                'label' => [
                                    'control' => false,
                                    'text' => '热门',
                                    'textColor' => '#FFFFFF',
                                    'bgColorStart' => '#F83287',
                                    'bgColorEnd' => '#FE3423',
                                ],
                            ],
                            [
                                'id' => '39b1ftwpcku0',
                                'title' => '常见问题',
                                'imageUrl' => 'addon/home_service/diy/member/diy_img/help.png',
                                'imgWidth' => 92,
                                'imgHeight' => 92,
                                'link' => [
                                    'parent' => 'DIY_LINK',
                                    'url' => '/addon/home_service/user/pages/member/help/help',
                                    'title' => '帮助',
                                    'name' => 'DIY_LINK',
                                    'action' => '',
                                ],
                                'label' => [
                                    'control' => false,
                                    'text' => '热门',
                                    'textColor' => '#FFFFFF',
                                    'bgColorStart' => '#F83287',
                                    'bgColorEnd' => '#FE3423',
                                ],
                            ],
                            [
                                'id' => '181s30d2ogsg',
                                'title' => '投诉建议',
                                'imageUrl' => 'addon/home_service/diy/member/diy_img/feedback.png',
                                'imgWidth' => 92,
                                'imgHeight' => 92,
                                'link' => [
                                    'parent' => 'DIY_LINK',
                                    'title' => '投诉建议',
                                    'url' => '/addon/home_service/user/pages/member/feedback/feedback',
                                    'name' => 'DIY_LINK',
                                    'action' => '',
                                ],
                                'label' => [
                                    'control' => false,
                                    'text' => '热门',
                                    'textColor' => '#FFFFFF',
                                    'bgColorStart' => '#F83287',
                                    'bgColorEnd' => '#FE3423',
                                ],
                            ],
                            [
                                'id' => '12m4r9pr2etc',
                                'title' => '地址管理',
                                'imageUrl' => 'addon/home_service/diy/member/diy_img/address_index.png',
                                'imgWidth' => 80,
                                'imgHeight' => 80,
                                'link' => [
                                    'parent' => 'DIY_LINK',
                                    'url' => '/addon/home_service/user/pages/address/index',
                                    'title' => '地址管理',
                                    'name' => 'DIY_LINK',
                                    'action' => '',
                                ],
                                'label' => [
                                    'control' => false,
                                    'text' => '热门',
                                    'textColor' => '#FFFFFF',
                                    'bgColorStart' => '#F83287',
                                    'bgColorEnd' => '#FE3423',
                                ],
                            ],
                        ],
                        'pageStartBgColor' => '',
                        'pageEndBgColor' => '',
                        'pageGradientAngle' => 'to bottom',
                        'componentBgUrl' => '',
                        'componentBgAlpha' => 2,
                        'componentStartBgColor' => 'rgba(255, 255, 255, 1)',
                        'componentEndBgColor' => '',
                        'componentGradientAngle' => 'to bottom',
                        'topRounded' => 0,
                        'bottomRounded' => 0,
                        'elementBgColor' => '',
                        'topElementRounded' => 0,
                        'bottomElementRounded' => 0,
                        'margin' => [
                            'top' => 0,
                            'bottom' => 10,
                            'both' => 12,
                        ],
                        'pageStyle' => 'padding-top:2rpx;padding-bottom:20rpx;padding-right:0rpx;padding-left:0rpx;',
                        'swiper' => [
                            'indicatorColor' => 'rgba(0, 0, 0, 0.3)',
                            'indicatorActiveColor' => '#FF0E0E',
                            'indicatorStyle' => 'style-1',
                            'indicatorAlign' => 'center',
                        ],
                        'componentIsShow' => true,
                    ],
                ],
            ]
        ]
    ]
];
