import request from '@/utils/request'

export const getWecomConfig = () => request.get('wecom/config')
export const saveWecomConfig = (data: Record<string, any>) => request.post('wecom/config', data)
export const testWecomConnection = () => request.post('wecom/config/test')
export const getWecomProviderConfig = () => request.get('wecom/provider/config')
export const saveWecomProviderConfig = (data: Record<string, any>) => request.post('wecom/provider/config', data)
export const testWecomProviderConnection = () => request.post('wecom/provider/test')
export const startWecomAuthorization = () => request.post('wecom/authorization/start')
export const checkWecomAuthorization = () => request.post('wecom/authorization/check')
export const getWecomStaff = () => request.get('wecom/staff')
export const saveWecomStaff = (uid: number, data: Record<string, any>) => request.put(`wecom/staff/${uid}`, data)
export const getWecomStaffBindUrl = (uid: number) => request.post(`wecom/staff/${uid}/bind-url`)
export const getWecomMessages = (params: Record<string, any>) => request.get('wecom/messages', { params })
export const retryWecomMessage = (id: number) => request.post(`wecom/messages/${id}/retry`)
export const testWecomMessage = (data: Record<string, any>) => request.post('wecom/messages/test', data)
