CREATE TABLE IF NOT EXISTS `{{prefix}}member_card_product` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `site_id` int NOT NULL DEFAULT 0,
  `product_no` varchar(40) NOT NULL DEFAULT '',
  `product_name` varchar(100) NOT NULL DEFAULT '',
  `cover_url` varchar(500) NOT NULL DEFAULT '',
  `sale_price` decimal(12,2) NOT NULL DEFAULT 0.00,
  `market_price` decimal(12,2) NOT NULL DEFAULT 0.00,
  `effective_mode` varchar(20) NOT NULL DEFAULT 'immediate',
  `validity_mode` varchar(20) NOT NULL DEFAULT 'permanent',
  `duration_value` int NOT NULL DEFAULT 0,
  `duration_unit` varchar(10) NOT NULL DEFAULT 'day',
  `fixed_start_at` int NOT NULL DEFAULT 0,
  `fixed_end_at` int NOT NULL DEFAULT 0,
  `usage_notice` text NULL,
  `status` varchar(20) NOT NULL DEFAULT 'draft',
  `sort` int NOT NULL DEFAULT 0,
  `create_uid` int NOT NULL DEFAULT 0,
  `create_name` varchar(60) NOT NULL DEFAULT '',
  `update_uid` int NOT NULL DEFAULT 0,
  `update_name` varchar(60) NOT NULL DEFAULT '',
  `create_at` int NOT NULL DEFAULT 0,
  `update_at` int NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_site_no` (`site_id`,`product_no`),
  KEY `idx_site_status_sort` (`site_id`,`status`,`sort`),
  KEY `idx_site_name` (`site_id`,`product_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='会员服务卡-卡种';

CREATE TABLE IF NOT EXISTS `{{prefix}}member_card_product_item` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `site_id` int NOT NULL DEFAULT 0,
  `product_id` int NOT NULL DEFAULT 0,
  `item_code` varchar(40) NOT NULL DEFAULT 'film_service',
  `item_name` varchar(100) NOT NULL DEFAULT '贴膜服务',
  `binding_mode` varchar(20) NOT NULL DEFAULT 'member' COMMENT 'member/imei/model',
  `usage_mode` varchar(20) NOT NULL DEFAULT 'limited',
  `total_times` int NOT NULL DEFAULT 0,
  `daily_limit` int NOT NULL DEFAULT 0,
  `reference_price` decimal(12,2) NOT NULL DEFAULT 0.00,
  `recognition_mode` varchar(20) NOT NULL DEFAULT 'average',
  `recognition_amount` decimal(12,2) NOT NULL DEFAULT 0.00,
  `consumable_code` varchar(60) NOT NULL DEFAULT '' COMMENT '耗材稳定编码',
  `consumable_name` varchar(100) NOT NULL DEFAULT '' COMMENT '默认耗材名称',
  `consumable_unit` varchar(20) NOT NULL DEFAULT '张' COMMENT '耗材单位',
  `standard_consumable_qty` decimal(12,3) NOT NULL DEFAULT 1.000 COMMENT '单次核销标准耗材数量',
  `sort` int NOT NULL DEFAULT 0,
  `status` tinyint(1) NOT NULL DEFAULT 1,
  `create_at` int NOT NULL DEFAULT 0,
  `update_at` int NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_site_product_code` (`site_id`,`product_id`,`item_code`),
  KEY `idx_site_product` (`site_id`,`product_id`,`status`,`sort`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='会员服务卡-卡种权益';

CREATE TABLE IF NOT EXISTS `{{prefix}}member_card_order` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `site_id` int NOT NULL DEFAULT 0,
  `order_no` varchar(40) NOT NULL DEFAULT '',
  `request_id` varchar(80) NOT NULL,
  `member_id` int NOT NULL DEFAULT 0,
  `holder_name` varchar(100) NOT NULL DEFAULT '',
  `holder_mobile` varchar(20) NOT NULL DEFAULT '',
  `holder_mobile_last4` char(4) NOT NULL DEFAULT '',
  `party_id` int NOT NULL DEFAULT 0,
  `party_name` varchar(100) NOT NULL DEFAULT '',
  `product_id` int NOT NULL DEFAULT 0,
  `product_no` varchar(40) NOT NULL DEFAULT '',
  `product_name` varchar(100) NOT NULL DEFAULT '',
  `product_snapshot` longtext NULL,
  `order_amount` decimal(12,2) NOT NULL DEFAULT 0.00,
  `paid_amount` decimal(12,2) NOT NULL DEFAULT 0.00,
  `refunded_amount` decimal(12,2) NOT NULL DEFAULT 0.00,
  `settlement_mode` varchar(20) NOT NULL DEFAULT 'receivable',
  `capital_account_id` int NOT NULL DEFAULT 0,
  `capital_account_name` varchar(100) NOT NULL DEFAULT '',
  `business_status` varchar(20) NOT NULL DEFAULT 'processing',
  `finance_status` varchar(20) NOT NULL DEFAULT 'processing',
  `issuer_uid` int NOT NULL DEFAULT 0,
  `issuer_name` varchar(60) NOT NULL DEFAULT '',
  `confirmed_at` int NOT NULL DEFAULT 0,
  `cancelled_at` int NOT NULL DEFAULT 0,
  `remark` varchar(255) NOT NULL DEFAULT '',
  `last_error` varchar(1000) NOT NULL DEFAULT '',
  `create_at` int NOT NULL DEFAULT 0,
  `update_at` int NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_site_no` (`site_id`,`order_no`),
  UNIQUE KEY `uk_site_request` (`site_id`,`request_id`),
  KEY `idx_site_member_status` (`site_id`,`member_id`,`business_status`),
  KEY `idx_site_mobile` (`site_id`,`holder_mobile`),
  KEY `idx_site_last4_status` (`site_id`,`holder_mobile_last4`,`business_status`),
  KEY `idx_site_issuer_time` (`site_id`,`issuer_uid`,`confirmed_at`),
  KEY `idx_site_finance_time` (`site_id`,`finance_status`,`create_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='会员服务卡-开卡订单';

CREATE TABLE IF NOT EXISTS `{{prefix}}member_card_card` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `site_id` int NOT NULL DEFAULT 0,
  `card_no` varchar(40) NOT NULL DEFAULT '',
  `order_id` int NOT NULL DEFAULT 0,
  `order_no` varchar(40) NOT NULL DEFAULT '',
  `member_id` int NOT NULL DEFAULT 0,
  `holder_name` varchar(100) NOT NULL DEFAULT '',
  `holder_mobile` varchar(20) NOT NULL DEFAULT '',
  `holder_mobile_last4` char(4) NOT NULL DEFAULT '',
  `product_id` int NOT NULL DEFAULT 0,
  `product_no` varchar(40) NOT NULL DEFAULT '',
  `product_name` varchar(100) NOT NULL DEFAULT '',
  `rule_snapshot` longtext NULL,
  `status` varchar(20) NOT NULL DEFAULT 'pending',
  `finance_status` varchar(20) NOT NULL DEFAULT 'processing',
  `effective_mode` varchar(20) NOT NULL DEFAULT 'immediate',
  `activated_at` int NOT NULL DEFAULT 0,
  `first_used_at` int NOT NULL DEFAULT 0,
  `valid_start_at` int NOT NULL DEFAULT 0,
  `valid_end_at` int NOT NULL DEFAULT 0,
  `freeze_reason` varchar(255) NOT NULL DEFAULT '',
  `issuer_uid` int NOT NULL DEFAULT 0,
  `issuer_name` varchar(60) NOT NULL DEFAULT '',
  `create_at` int NOT NULL DEFAULT 0,
  `update_at` int NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_site_no` (`site_id`,`card_no`),
  UNIQUE KEY `uk_site_order` (`site_id`,`order_id`),
  KEY `idx_site_member_status` (`site_id`,`member_id`,`status`),
  KEY `idx_site_mobile` (`site_id`,`holder_mobile`),
  KEY `idx_site_last4_status` (`site_id`,`holder_mobile_last4`,`status`),
  KEY `idx_site_expiry_status` (`site_id`,`valid_end_at`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='会员服务卡-会员持卡';

CREATE TABLE IF NOT EXISTS `{{prefix}}member_card_card_item` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `site_id` int NOT NULL DEFAULT 0,
  `card_id` int NOT NULL DEFAULT 0,
  `product_item_id` int NOT NULL DEFAULT 0,
  `item_code` varchar(40) NOT NULL DEFAULT '',
  `item_name` varchar(100) NOT NULL DEFAULT '',
  `binding_mode` varchar(20) NOT NULL DEFAULT 'member' COMMENT 'member/imei/model',
  `bound_imei` varchar(40) NOT NULL DEFAULT '',
  `bound_model` varchar(100) NOT NULL DEFAULT '',
  `usage_mode` varchar(20) NOT NULL DEFAULT 'limited',
  `granted_times` int NOT NULL DEFAULT 0,
  `used_times` int NOT NULL DEFAULT 0,
  `remaining_times` int NOT NULL DEFAULT 0,
  `reversed_times` int NOT NULL DEFAULT 0,
  `daily_limit` int NOT NULL DEFAULT 0,
  `allocated_amount` decimal(12,2) NOT NULL DEFAULT 0.00,
  `recognized_amount` decimal(12,2) NOT NULL DEFAULT 0.00,
  `consumable_code` varchar(60) NOT NULL DEFAULT '',
  `consumable_name` varchar(100) NOT NULL DEFAULT '',
  `consumable_unit` varchar(20) NOT NULL DEFAULT '张',
  `standard_consumable_qty` decimal(12,3) NOT NULL DEFAULT 0.000,
  `status` tinyint(1) NOT NULL DEFAULT 1,
  `create_at` int NOT NULL DEFAULT 0,
  `update_at` int NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_site_card_code` (`site_id`,`card_id`,`item_code`),
  KEY `idx_site_card` (`site_id`,`card_id`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='会员服务卡-持卡权益';

CREATE TABLE IF NOT EXISTS `{{prefix}}member_card_redemption` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `site_id` int NOT NULL DEFAULT 0,
  `redeem_no` varchar(40) NOT NULL DEFAULT '',
  `request_id` varchar(80) NOT NULL,
  `card_id` int NOT NULL DEFAULT 0,
  `card_no` varchar(40) NOT NULL DEFAULT '',
  `card_item_id` int NOT NULL DEFAULT 0,
  `member_id` int NOT NULL DEFAULT 0,
  `holder_name` varchar(100) NOT NULL DEFAULT '',
  `holder_mobile` varchar(20) NOT NULL DEFAULT '',
  `item_code` varchar(40) NOT NULL DEFAULT '',
  `item_name` varchar(100) NOT NULL DEFAULT '',
  `binding_mode` varchar(20) NOT NULL DEFAULT 'member',
  `service_imei` varchar(40) NOT NULL DEFAULT '',
  `service_model` varchar(100) NOT NULL DEFAULT '',
  `redeem_times` int NOT NULL DEFAULT 1,
  `before_remaining` int NOT NULL DEFAULT 0,
  `after_remaining` int NOT NULL DEFAULT 0,
  `recognized_amount` decimal(12,2) NOT NULL DEFAULT 0.00,
  `inventory_mode` varchar(20) NOT NULL DEFAULT 'none' COMMENT 'none/auto/strict',
  `consumable_code` varchar(60) NOT NULL DEFAULT '',
  `consumable_name` varchar(100) NOT NULL DEFAULT '',
  `consumable_unit` varchar(20) NOT NULL DEFAULT '张',
  `standard_consumable_qty` decimal(12,3) NOT NULL DEFAULT 0.000,
  `actual_consumable_qty` decimal(12,3) NOT NULL DEFAULT 0.000,
  `loss_consumable_qty` decimal(12,3) NOT NULL DEFAULT 0.000,
  `inventory_status` varchar(20) NOT NULL DEFAULT 'not_managed' COMMENT 'not_managed/deducted/negative/failed/restored/restore_failed',
  `inventory_product_id` int NOT NULL DEFAULT 0,
  `inventory_warehouse_id` int NOT NULL DEFAULT 0,
  `inventory_warehouse_name` varchar(100) NOT NULL DEFAULT '',
  `inventory_location_id` int NOT NULL DEFAULT 0,
  `inventory_location_name` varchar(100) NOT NULL DEFAULT '',
  `inventory_stock_before` decimal(12,3) NOT NULL DEFAULT 0.000,
  `inventory_stock_after` decimal(12,3) NOT NULL DEFAULT 0.000,
  `inventory_message` varchar(255) NOT NULL DEFAULT '',
  `verification_mode` varchar(30) NOT NULL DEFAULT 'mobile_name_manual',
  `verification_confirmed` tinyint(1) NOT NULL DEFAULT 0,
  `operator_uid` int NOT NULL DEFAULT 0,
  `operator_name` varchar(60) NOT NULL DEFAULT '',
  `status` varchar(20) NOT NULL DEFAULT 'success',
  `reversed_at` int NOT NULL DEFAULT 0,
  `reverse_uid` int NOT NULL DEFAULT 0,
  `reverse_name` varchar(60) NOT NULL DEFAULT '',
  `reverse_reason` varchar(255) NOT NULL DEFAULT '',
  `remark` varchar(255) NOT NULL DEFAULT '',
  `occurred_at` int NOT NULL DEFAULT 0,
  `create_at` int NOT NULL DEFAULT 0,
  `update_at` int NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_site_no` (`site_id`,`redeem_no`),
  UNIQUE KEY `uk_site_request` (`site_id`,`request_id`),
  KEY `idx_site_card_time` (`site_id`,`card_id`,`status`,`occurred_at`),
  KEY `idx_site_member_time` (`site_id`,`member_id`,`occurred_at`),
  KEY `idx_site_service_imei` (`site_id`,`service_imei`),
  KEY `idx_site_operator_time` (`site_id`,`operator_uid`,`occurred_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='会员服务卡-核销及冲正';

CREATE TABLE IF NOT EXISTS `{{prefix}}member_card_refund` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `site_id` int NOT NULL DEFAULT 0,
  `refund_no` varchar(40) NOT NULL DEFAULT '',
  `request_id` varchar(80) NOT NULL,
  `order_id` int NOT NULL DEFAULT 0,
  `order_no` varchar(40) NOT NULL DEFAULT '',
  `card_id` int NOT NULL DEFAULT 0,
  `card_no` varchar(40) NOT NULL DEFAULT '',
  `member_id` int NOT NULL DEFAULT 0,
  `party_id` int NOT NULL DEFAULT 0,
  `party_name` varchar(100) NOT NULL DEFAULT '',
  `original_amount` decimal(12,2) NOT NULL DEFAULT 0.00,
  `refund_amount` decimal(12,2) NOT NULL DEFAULT 0.00,
  `refund_mode` varchar(20) NOT NULL DEFAULT 'finance',
  `capital_account_id` int NOT NULL DEFAULT 0,
  `capital_account_name` varchar(100) NOT NULL DEFAULT '',
  `status` varchar(20) NOT NULL DEFAULT 'processing',
  `apply_uid` int NOT NULL DEFAULT 0,
  `apply_name` varchar(60) NOT NULL DEFAULT '',
  `reason` varchar(255) NOT NULL DEFAULT '',
  `last_error` varchar(1000) NOT NULL DEFAULT '',
  `paid_at` int NOT NULL DEFAULT 0,
  `create_at` int NOT NULL DEFAULT 0,
  `update_at` int NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_site_no` (`site_id`,`refund_no`),
  UNIQUE KEY `uk_site_request` (`site_id`,`request_id`),
  KEY `idx_site_order_status` (`site_id`,`order_id`,`status`),
  KEY `idx_site_card_status` (`site_id`,`card_id`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='会员服务卡-退款';

CREATE TABLE IF NOT EXISTS `{{prefix}}member_card_finance_link` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `site_id` int NOT NULL DEFAULT 0,
  `biz_type` varchar(30) NOT NULL DEFAULT '',
  `biz_id` int NOT NULL DEFAULT 0,
  `biz_no` varchar(40) NOT NULL DEFAULT '',
  `event_id` varchar(80) NOT NULL,
  `target_type` varchar(20) NOT NULL DEFAULT '',
  `target_id` int NOT NULL DEFAULT 0,
  `target_no` varchar(40) NOT NULL DEFAULT '',
  `amount` decimal(12,2) NOT NULL DEFAULT 0.00,
  `settled_amount` decimal(12,2) NOT NULL DEFAULT 0.00,
  `remaining_amount` decimal(12,2) NOT NULL DEFAULT 0.00,
  `finance_status` varchar(20) NOT NULL DEFAULT 'processing',
  `settlement_no` varchar(40) NOT NULL DEFAULT '',
  `payload_hash` char(64) NOT NULL DEFAULT '',
  `retry_count` int NOT NULL DEFAULT 0,
  `last_error` varchar(1000) NOT NULL DEFAULT '',
  `last_sync_at` int NOT NULL DEFAULT 0,
  `create_at` int NOT NULL DEFAULT 0,
  `update_at` int NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_site_event` (`site_id`,`event_id`),
  UNIQUE KEY `uk_site_biz_target` (`site_id`,`biz_type`,`biz_id`,`target_type`),
  KEY `idx_site_target` (`site_id`,`target_type`,`target_id`),
  KEY `idx_site_finance_time` (`site_id`,`finance_status`,`update_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='会员服务卡-ERP财务关联';

CREATE TABLE IF NOT EXISTS `{{prefix}}member_card_staff_fact` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `site_id` int NOT NULL DEFAULT 0,
  `event_id` varchar(80) NOT NULL,
  `fact_type` varchar(30) NOT NULL DEFAULT '',
  `biz_type` varchar(30) NOT NULL DEFAULT '',
  `biz_id` int NOT NULL DEFAULT 0,
  `biz_no` varchar(40) NOT NULL DEFAULT '',
  `staff_role` varchar(30) NOT NULL DEFAULT '',
  `staff_uid` int NOT NULL DEFAULT 0,
  `staff_name` varchar(60) NOT NULL DEFAULT '',
  `metric_key` varchar(40) NOT NULL DEFAULT '',
  `quantity` decimal(14,2) NOT NULL DEFAULT 0.00,
  `amount` decimal(12,2) NOT NULL DEFAULT 0.00,
  `direction` tinyint NOT NULL DEFAULT 1,
  `reversal_of_event_id` varchar(80) NOT NULL DEFAULT '',
  `occurred_at` int NOT NULL DEFAULT 0,
  `create_at` int NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_site_event` (`site_id`,`event_id`),
  KEY `idx_site_staff_time` (`site_id`,`staff_uid`,`occurred_at`),
  KEY `idx_site_metric_time` (`site_id`,`metric_key`,`occurred_at`),
  KEY `idx_site_biz` (`site_id`,`biz_type`,`biz_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='会员服务卡-员工事实';

CREATE TABLE IF NOT EXISTS `{{prefix}}member_card_operation_log` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `site_id` int NOT NULL DEFAULT 0,
  `biz_type` varchar(30) NOT NULL DEFAULT '',
  `biz_id` int NOT NULL DEFAULT 0,
  `biz_no` varchar(40) NOT NULL DEFAULT '',
  `action` varchar(40) NOT NULL DEFAULT '',
  `before_json` longtext NULL,
  `after_json` longtext NULL,
  `operator_uid` int NOT NULL DEFAULT 0,
  `operator_name` varchar(60) NOT NULL DEFAULT '',
  `ip` varchar(45) NOT NULL DEFAULT '',
  `occurred_at` int NOT NULL DEFAULT 0,
  `create_at` int NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_site_biz_time` (`site_id`,`biz_type`,`biz_id`,`occurred_at`),
  KEY `idx_site_operator_time` (`site_id`,`operator_uid`,`occurred_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='会员服务卡-操作审计';

CREATE TABLE IF NOT EXISTS `{{prefix}}member_card_inbox_event` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `site_id` int NOT NULL DEFAULT 0,
  `event_id` varchar(100) NOT NULL,
  `event_name` varchar(100) NOT NULL DEFAULT '',
  `payload_json` longtext NULL,
  `status` varchar(20) NOT NULL DEFAULT 'processing',
  `attempts` int NOT NULL DEFAULT 0,
  `error` varchar(1000) NOT NULL DEFAULT '',
  `occurred_at` int NOT NULL DEFAULT 0,
  `create_at` int NOT NULL DEFAULT 0,
  `update_at` int NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_site_event` (`site_id`,`event_id`),
  KEY `idx_site_status` (`site_id`,`status`,`update_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='会员服务卡-事件收件箱';

CREATE TABLE IF NOT EXISTS `{{prefix}}member_card_outbox_event` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `site_id` int NOT NULL DEFAULT 0,
  `event_id` varchar(100) NOT NULL,
  `event_name` varchar(100) NOT NULL DEFAULT '',
  `aggregate_type` varchar(40) NOT NULL DEFAULT '',
  `aggregate_id` int NOT NULL DEFAULT 0,
  `payload_json` longtext NULL,
  `status` varchar(20) NOT NULL DEFAULT 'pending',
  `attempts` int NOT NULL DEFAULT 0,
  `next_retry_at` int NOT NULL DEFAULT 0,
  `error` varchar(1000) NOT NULL DEFAULT '',
  `occurred_at` int NOT NULL DEFAULT 0,
  `create_at` int NOT NULL DEFAULT 0,
  `update_at` int NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_site_event` (`site_id`,`event_id`),
  KEY `idx_status_retry` (`status`,`next_retry_at`),
  KEY `idx_site_aggregate` (`site_id`,`aggregate_type`,`aggregate_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='会员服务卡-事件发件箱';

CREATE TABLE IF NOT EXISTS `{{prefix}}member_card_migration_task` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `site_id` int NOT NULL DEFAULT 0,
  `source_key` varchar(40) NOT NULL DEFAULT 'dianddnet',
  `source_account` varchar(40) NOT NULL DEFAULT '' COMMENT '脱敏后的来源账号',
  `source_store_id` varchar(80) NOT NULL DEFAULT '',
  `credential_ciphertext` text NULL COMMENT '仅保存加密后的临时Token，不保存密码',
  `status` varchar(20) NOT NULL DEFAULT 'pending' COMMENT 'pending/queued/processing/completed/partial/failed',
  `queue_enabled` tinyint(1) NOT NULL DEFAULT 0,
  `product_total` int NOT NULL DEFAULT 0,
  `customer_total` int NOT NULL DEFAULT 0,
  `card_total` int NOT NULL DEFAULT 0,
  `processed_count` int NOT NULL DEFAULT 0,
  `created_count` int NOT NULL DEFAULT 0,
  `updated_count` int NOT NULL DEFAULT 0,
  `reused_count` int NOT NULL DEFAULT 0,
  `skipped_count` int NOT NULL DEFAULT 0,
  `conflict_count` int NOT NULL DEFAULT 0,
  `error_count` int NOT NULL DEFAULT 0,
  `summary_json` longtext NULL,
  `result_json` longtext NULL,
  `message` varchar(500) NOT NULL DEFAULT '',
  `error_message` varchar(1000) NOT NULL DEFAULT '',
  `operator_uid` int NOT NULL DEFAULT 0,
  `operator_name` varchar(60) NOT NULL DEFAULT '',
  `start_at` int NOT NULL DEFAULT 0,
  `finish_at` int NOT NULL DEFAULT 0,
  `create_at` int NOT NULL DEFAULT 0,
  `update_at` int NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_site_status` (`site_id`,`status`,`create_at`),
  KEY `idx_site_source` (`site_id`,`source_key`,`source_store_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='会员服务卡-第三方期初同步任务';

CREATE TABLE IF NOT EXISTS `{{prefix}}member_card_migration_item` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `site_id` int NOT NULL DEFAULT 0,
  `task_id` int NOT NULL DEFAULT 0,
  `source_key` varchar(40) NOT NULL DEFAULT 'dianddnet',
  `entity_type` varchar(20) NOT NULL DEFAULT '' COMMENT 'product/customer/card',
  `external_id` varchar(100) NOT NULL DEFAULT '',
  `display_name` varchar(150) NOT NULL DEFAULT '',
  `mobile` varchar(30) NOT NULL DEFAULT '',
  `action` varchar(20) NOT NULL DEFAULT '' COMMENT 'created/updated/reused/skipped/conflict/failed',
  `status` varchar(20) NOT NULL DEFAULT 'pending',
  `local_type` varchar(30) NOT NULL DEFAULT '',
  `local_id` bigint NOT NULL DEFAULT 0,
  `payload_hash` char(64) NOT NULL DEFAULT '',
  `snapshot_json` longtext NULL,
  `message` varchar(1000) NOT NULL DEFAULT '',
  `create_at` int NOT NULL DEFAULT 0,
  `update_at` int NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_task_entity` (`task_id`,`entity_type`,`external_id`),
  KEY `idx_task_status` (`site_id`,`task_id`,`status`,`entity_type`),
  KEY `idx_task_mobile` (`site_id`,`task_id`,`mobile`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='会员服务卡-第三方同步明细';

CREATE TABLE IF NOT EXISTS `{{prefix}}member_card_external_binding` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `site_id` int NOT NULL DEFAULT 0,
  `source_key` varchar(40) NOT NULL DEFAULT 'dianddnet',
  `entity_type` varchar(20) NOT NULL DEFAULT '',
  `external_id` varchar(100) NOT NULL DEFAULT '',
  `local_type` varchar(30) NOT NULL DEFAULT '',
  `local_id` bigint NOT NULL DEFAULT 0,
  `payload_hash` char(64) NOT NULL DEFAULT '',
  `external_updated_at` int NOT NULL DEFAULT 0,
  `last_task_id` int NOT NULL DEFAULT 0,
  `last_sync_at` int NOT NULL DEFAULT 0,
  `status` varchar(20) NOT NULL DEFAULT 'active',
  `create_at` int NOT NULL DEFAULT 0,
  `update_at` int NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_site_source_entity` (`site_id`,`source_key`,`entity_type`,`external_id`),
  KEY `idx_local` (`site_id`,`local_type`,`local_id`),
  KEY `idx_task` (`site_id`,`last_task_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='会员服务卡-第三方数据映射';
