<?php
declare(strict_types=1);
use app\adminapi\middleware\AdminCheckRole;
use app\adminapi\middleware\AdminCheckToken;
use app\adminapi\middleware\AdminLog;
use think\facade\Route;
Route::group('project-center', function () {
    Route::get('projects/metadata', 'addon\hsx_project_center\app\adminapi\controller\Project@metadata');
    Route::get('projects', 'addon\hsx_project_center\app\adminapi\controller\Project@lists');
    Route::get('projects/:id', 'addon\hsx_project_center\app\adminapi\controller\Project@info');
    Route::post('projects', 'addon\hsx_project_center\app\adminapi\controller\Project@add');
    Route::put('projects/:id', 'addon\hsx_project_center\app\adminapi\controller\Project@edit');
    Route::delete('projects/:id', 'addon\hsx_project_center\app\adminapi\controller\Project@delete');
    Route::get('groups', 'addon\hsx_project_center\app\adminapi\controller\Group@lists');
    Route::post('groups/reserve', 'addon\hsx_project_center\app\adminapi\controller\Group@reserve');
    Route::put('groups/:id/group-no', 'addon\hsx_project_center\app\adminapi\controller\Group@correctGroupNo');
    Route::get('wecom/readiness', 'addon\hsx_project_center\app\adminapi\controller\Group@wecomReadiness');
    Route::get('wecom/oauth-url', 'addon\hsx_project_center\app\adminapi\controller\Group@wecomOauthUrl');
    Route::post('wecom/bind-identity', 'addon\hsx_project_center\app\adminapi\controller\Group@bindWecomIdentity');
    Route::post('wecom/selector-config', 'addon\hsx_project_center\app\adminapi\controller\Group@wecomSelectorConfig');
    Route::post('groups/:id/wecom/prepare', 'addon\hsx_project_center\app\adminapi\controller\Group@prepareWecom');
    Route::put('groups/:id/wecom/complete', 'addon\hsx_project_center\app\adminapi\controller\Group@completeWecom');
    Route::put('groups/:id/wecom/fail', 'addon\hsx_project_center\app\adminapi\controller\Group@failWecom');
    Route::put('groups/:id/wecom', 'addon\hsx_project_center\app\adminapi\controller\Group@bindWecom');
    Route::put('groups/:id/close', 'addon\hsx_project_center\app\adminapi\controller\Group@close');
    Route::get('groups/:id/refund', 'addon\hsx_project_center\app\adminapi\controller\Group@refundInfo');
    Route::post('groups/:id/refund', 'addon\hsx_project_center\app\adminapi\controller\Group@requestRefund');
    Route::put('groups/:id/refund/complete', 'addon\hsx_project_center\app\adminapi\controller\Group@completeRefund');
    Route::put('groups/:id/refund/cancel', 'addon\hsx_project_center\app\adminapi\controller\Group@cancelRefund');
    Route::get('applications', 'addon\hsx_project_center\app\adminapi\controller\Application@lists');
    Route::get('applications/review-reasons', 'addon\hsx_project_center\app\adminapi\controller\Application@reviewReasons');
    Route::put('applications/review-reasons', 'addon\hsx_project_center\app\adminapi\controller\Application@saveReviewReasons');
    Route::get('applications/:id', 'addon\hsx_project_center\app\adminapi\controller\Application@info');
    Route::put('applications/:id/review', 'addon\hsx_project_center\app\adminapi\controller\Application@review');
    Route::put('applications/:id/group-no', 'addon\hsx_project_center\app\adminapi\controller\Application@correctGroupNo');
    Route::get('applications/:id/archive', 'addon\hsx_project_center\app\adminapi\controller\Application@archive');
    Route::get('income-board', 'addon\hsx_project_center\app\adminapi\controller\Income@lists');
    Route::post('income-board/replace', 'addon\hsx_project_center\app\adminapi\controller\Income@replace');
    Route::get('distribution/overview', 'addon\hsx_project_center\app\adminapi\controller\Distribution@overview');
    Route::get('distribution/projects', 'addon\hsx_project_center\app\adminapi\controller\Distribution@projects');
    Route::get('distribution/orders', 'addon\hsx_project_center\app\adminapi\controller\Distribution@lists');
    Route::get('distribution/orders/:id', 'addon\hsx_project_center\app\adminapi\controller\Distribution@info');
    Route::post('distribution/orders/:id/settle', 'addon\hsx_project_center\app\adminapi\controller\Distribution@settle');
})->middleware([AdminCheckToken::class, AdminCheckRole::class, AdminLog::class]);
