CREATE TABLE IF NOT EXISTS `{{prefix}}marketing_campaign` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `site_id` int NOT NULL DEFAULT 0,
  `campaign_no` varchar(40) NOT NULL DEFAULT '',
  `title` varchar(120) NOT NULL DEFAULT '',
  `subtitle` varchar(255) NOT NULL DEFAULT '',
  `status` tinyint unsigned NOT NULL DEFAULT 0 COMMENT '0草稿1进行中2暂停3结束',
  `participation_mode` varchar(20) NOT NULL DEFAULT 'manual' COMMENT 'manual/auto',
  `cycle_type` varchar(30) NOT NULL DEFAULT 'calendar_month' COMMENT 'calendar_month/fixed/rolling_days',
  `cycle_days` int NOT NULL DEFAULT 30,
  `start_at` int NOT NULL DEFAULT 0,
  `end_at` int NOT NULL DEFAULT 0,
  `allowed_level_ids` longtext NULL COMMENT '允许参与的会员等级ID，空为不限',
  `qualification_key` varchar(80) NOT NULL DEFAULT '' COMMENT '跨插件参与资格契约键，空为不限',
  `ineligible_action` varchar(30) NOT NULL DEFAULT 'level_apply' COMMENT '不满足等级时动作',
  `application_url` varchar(500) NOT NULL DEFAULT '',
  `fact_key` varchar(80) NOT NULL DEFAULT 'recycle_device_delivered',
  `fact_filter_json` longtext NULL COMMENT '事实过滤规则，如回收设备成交价区间',
  `target_value` decimal(14,2) NOT NULL DEFAULT 1.00,
  `target_unit` varchar(20) NOT NULL DEFAULT '台',
  `grant_mode` varchar(20) NOT NULL DEFAULT 'manual' COMMENT 'manual/auto',
  `claim_valid_days` int NOT NULL DEFAULT 7 COMMENT '达标后奖励领取有效天数',
  `expire_notice_days` longtext NULL COMMENT '如[7,3,1]',
  `notice_channels` longtext NULL,
  `description` text NULL,
  `sort` int NOT NULL DEFAULT 0,
  `create_at` int NOT NULL DEFAULT 0,
  `update_at` int NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_site_no` (`site_id`,`campaign_no`),
  KEY `idx_site_status` (`site_id`,`status`,`sort`),
  KEY `idx_fact_time` (`site_id`,`fact_key`,`status`,`start_at`,`end_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='营销任务活动';

CREATE TABLE IF NOT EXISTS `{{prefix}}marketing_campaign_reward` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `site_id` int NOT NULL DEFAULT 0,
  `campaign_id` bigint unsigned NOT NULL DEFAULT 0,
  `provider_key` varchar(60) NOT NULL DEFAULT '',
  `reward_type` varchar(60) NOT NULL DEFAULT '',
  `reward_name` varchar(120) NOT NULL DEFAULT '',
  `reward_value` decimal(14,2) NOT NULL DEFAULT 0.00,
  `reward_quantity` int NOT NULL DEFAULT 1,
  `reward_config_json` longtext NULL,
  `status` tinyint unsigned NOT NULL DEFAULT 1,
  `sort` int NOT NULL DEFAULT 0,
  `create_at` int NOT NULL DEFAULT 0,
  `update_at` int NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_campaign` (`site_id`,`campaign_id`,`status`,`sort`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='营销活动奖励配置';

CREATE TABLE IF NOT EXISTS `{{prefix}}marketing_claim` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `site_id` int NOT NULL DEFAULT 0,
  `claim_no` varchar(40) NOT NULL DEFAULT '',
  `campaign_id` bigint unsigned NOT NULL DEFAULT 0,
  `member_id` int NOT NULL DEFAULT 0,
  `member_name` varchar(100) NOT NULL DEFAULT '',
  `member_mobile` varchar(30) NOT NULL DEFAULT '',
  `claimed_level_id` int NOT NULL DEFAULT 0,
  `cycle_key` varchar(60) NOT NULL DEFAULT '',
  `cycle_start_at` int NOT NULL DEFAULT 0,
  `cycle_end_at` int NOT NULL DEFAULT 0,
  `status` varchar(24) NOT NULL DEFAULT 'running' COMMENT 'running/completed/rewarded/expired/cancelled',
  `progress_value` decimal(14,2) NOT NULL DEFAULT 0.00,
  `target_value` decimal(14,2) NOT NULL DEFAULT 0.00,
  `completed_at` int NOT NULL DEFAULT 0,
  `rewarded_at` int NOT NULL DEFAULT 0,
  `create_at` int NOT NULL DEFAULT 0,
  `update_at` int NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_member_cycle` (`site_id`,`campaign_id`,`member_id`,`cycle_key`),
  UNIQUE KEY `uk_claim_no` (`site_id`,`claim_no`),
  KEY `idx_member_status` (`site_id`,`member_id`,`status`,`update_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='会员营销任务领取与进度';

CREATE TABLE IF NOT EXISTS `{{prefix}}marketing_fact` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `site_id` int NOT NULL DEFAULT 0,
  `event_id` varchar(120) NOT NULL DEFAULT '',
  `event_name` varchar(100) NOT NULL DEFAULT '',
  `source_plugin` varchar(60) NOT NULL DEFAULT '',
  `fact_key` varchar(80) NOT NULL DEFAULT '',
  `fact_type` varchar(20) NOT NULL DEFAULT 'original' COMMENT 'original/reversal',
  `direction` tinyint NOT NULL DEFAULT 1,
  `reversal_of_event_id` varchar(120) NOT NULL DEFAULT '',
  `business_type` varchar(60) NOT NULL DEFAULT '',
  `business_id` varchar(80) NOT NULL DEFAULT '',
  `business_no` varchar(80) NOT NULL DEFAULT '',
  `member_id` int NOT NULL DEFAULT 0,
  `quantity` decimal(14,2) NOT NULL DEFAULT 0.00,
  `payload_json` longtext NULL,
  `occurred_at` int NOT NULL DEFAULT 0,
  `received_at` int NOT NULL DEFAULT 0,
  `process_status` varchar(20) NOT NULL DEFAULT 'pending' COMMENT 'pending/processing/success/failed',
  `retry_count` int NOT NULL DEFAULT 0,
  `next_retry_at` int NOT NULL DEFAULT 0,
  `error_message` varchar(500) NOT NULL DEFAULT '',
  `processed_at` int NOT NULL DEFAULT 0,
  `create_at` int NOT NULL DEFAULT 0,
  `update_at` int NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_site_event` (`site_id`,`event_id`),
  KEY `idx_member_fact` (`site_id`,`member_id`,`fact_key`,`occurred_at`),
  KEY `idx_reversal` (`site_id`,`reversal_of_event_id`),
  KEY `idx_process_retry` (`process_status`,`next_retry_at`,`retry_count`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='跨插件营销事实台账';

CREATE TABLE IF NOT EXISTS `{{prefix}}marketing_reward_order` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `site_id` int NOT NULL DEFAULT 0,
  `reward_no` varchar(40) NOT NULL DEFAULT '',
  `request_id` varchar(100) NOT NULL DEFAULT '',
  `campaign_id` bigint unsigned NOT NULL DEFAULT 0,
  `claim_id` bigint unsigned NOT NULL DEFAULT 0,
  `campaign_reward_id` bigint unsigned NOT NULL DEFAULT 0,
  `member_id` int NOT NULL DEFAULT 0,
  `provider_key` varchar(60) NOT NULL DEFAULT '',
  `reward_type` varchar(60) NOT NULL DEFAULT '',
  `reward_name` varchar(120) NOT NULL DEFAULT '',
  `reward_value` decimal(14,2) NOT NULL DEFAULT 0.00,
  `reward_quantity` int NOT NULL DEFAULT 1,
  `reward_config_json` longtext NULL,
  `grant_mode` varchar(20) NOT NULL DEFAULT 'manual',
  `status` varchar(24) NOT NULL DEFAULT 'claimable' COMMENT 'claimable/pending/processing/success/failed/expired/cancelled',
  `claim_expire_at` int NOT NULL DEFAULT 0,
  `claimed_at` int NOT NULL DEFAULT 0,
  `granted_at` int NOT NULL DEFAULT 0,
  `reward_expire_at` int NOT NULL DEFAULT 0,
  `provider_no` varchar(120) NOT NULL DEFAULT '',
  `provider_result_json` longtext NULL,
  `retry_count` int NOT NULL DEFAULT 0,
  `next_retry_at` int NOT NULL DEFAULT 0,
  `failure_code` varchar(80) NOT NULL DEFAULT '',
  `failure_reason` varchar(500) NOT NULL DEFAULT '',
  `create_at` int NOT NULL DEFAULT 0,
  `update_at` int NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_request` (`site_id`,`request_id`),
  UNIQUE KEY `uk_reward_no` (`site_id`,`reward_no`),
  KEY `idx_member_status` (`site_id`,`member_id`,`status`,`update_at`),
  KEY `idx_retry` (`status`,`next_retry_at`,`retry_count`),
  KEY `idx_expire` (`status`,`claim_expire_at`,`reward_expire_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='营销奖励发放单';

CREATE TABLE IF NOT EXISTS `{{prefix}}marketing_notice_log` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `site_id` int NOT NULL DEFAULT 0,
  `reward_order_id` bigint unsigned NOT NULL DEFAULT 0,
  `member_id` int NOT NULL DEFAULT 0,
  `notice_type` varchar(60) NOT NULL DEFAULT '',
  `notice_key` varchar(120) NOT NULL DEFAULT '',
  `status` varchar(20) NOT NULL DEFAULT 'pending',
  `result_json` longtext NULL,
  `error_message` varchar(500) NOT NULL DEFAULT '',
  `sent_at` int NOT NULL DEFAULT 0,
  `create_at` int NOT NULL DEFAULT 0,
  `update_at` int NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_notice` (`site_id`,`reward_order_id`,`notice_type`,`notice_key`),
  KEY `idx_status` (`status`,`update_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='营销奖励通知留痕';
