<template>
    <div class="main-container"><el-card class="!border-none" shadow="never"><div class="redeem-page">
        <div class="page-head"><div><div class="text-page-title">手机号核销</div><p>客户报手机号后四位即可检索；命中后必须再口头核对购卡姓名。</p></div></div>
        <div class="search-panel"><el-input v-model="form.mobile_keyword" maxlength="11" size="large" placeholder="输入完整手机号或后四位" @keyup.enter="search"><template #prefix><el-icon><Search/></el-icon></template></el-input><el-input v-model="form.name" size="large" placeholder="重名或多人命中时填写姓名（可选）" @keyup.enter="search"/><el-button type="primary" size="large" :loading="loading" @click="search">查询可用会员卡</el-button></div>
        <el-alert v-if="searched&&!candidates.length" title="没有找到可核销会员卡，请检查手机号或卡片状态" type="info" :closable="false" show-icon/>
        <div v-for="candidate in candidates" :key="candidate.member_id" class="candidate"><div class="candidate-head"><div><span>核对姓名</span><h3>{{ candidate.holder_name }} <small>{{ candidate.mobile_masked }}</small></h3></div><el-tag :type="candidate.available_card_count?'success':'info'">可用 {{ candidate.available_card_count }} 张</el-tag></div><div class="cards"><div v-for="card in candidate.cards" :key="card.card_id" class="card" :class="{disabled:!card.available}"><div class="card-top"><div><b>{{ card.product_name }}</b><p>{{ card.item_name }} · {{ card.validity_text }}</p><small v-if="card.binding_mode!=='member'" class="binding-line">{{ card.binding_mode==='imei'?`绑定 IMEI：${card.bound_imei}`:`适用型号：${card.bound_model}` }}</small></div><MemberCardStatusTag :value="card.status"/></div><div class="card-bottom"><span>{{ card.usage_mode==='unlimited'?'不限次数':`剩余 ${card.remaining_times} 次` }}</span><el-button type="primary" :disabled="!card.available" @click="openConfirm(candidate,card)">{{ card.recommended?'推荐核销':'核销 1 次' }}</el-button></div></div></div></div>
        <el-dialog v-model="confirmVisible" title="确认核销 1 次" width="500px" :close-on-click-modal="false"><div v-if="selected" class="confirm-box"><span>请向客户询问购卡姓名</span><strong>{{ selected.candidate.holder_name }}</strong><small>{{ selected.candidate.mobile_masked }} · {{ selected.card.product_name }}</small></div><div v-if="selected&&selected.card.binding_mode!=='member'" class="device-check"><el-input v-if="selected.card.binding_mode==='imei'" v-model="serviceImei" maxlength="40" placeholder="输入或粘贴本次设备 IMEI"/><el-input v-else v-model="serviceModel" maxlength="100" :placeholder="`请输入设备型号：${selected.card.bound_model}`"/><small>系统将校验绑定设备，信息不一致不会扣减次数。</small></div><div v-if="selected&&inventoryMode!=='none'&&selected.card.consumable_name" class="inventory-check"><div><b>实际耗材</b><span>{{ selected.card.consumable_name }} · 标准 {{ standardConsumableQty }} {{ selected.card.consumable_unit || '件' }}</span></div><el-input-number v-model="actualConsumableQty" :min="0.001" :max="9999" :precision="3" :step="1"/><el-alert v-if="actualConsumableQty>standardConsumableQty" title="超出标准数量的部分将记录为损耗/返工" type="warning" :closable="false" show-icon/></div><el-checkbox v-model="confirmed" class="confirm-check">我已当面核对手机号与购卡姓名，信息一致</el-checkbox><el-input v-model="remark" type="textarea" :rows="2" placeholder="选填：本次服务说明"/><template #footer><el-button @click="confirmVisible=false">取消</el-button><el-button type="primary" :disabled="!confirmed" :loading="redeeming" @click="redeem">确认核销</el-button></template></el-dialog>
    </div></el-card></div>
</template>
<script setup lang="ts">
import { computed,reactive,ref } from 'vue';import { ElMessage,ElMessageBox } from 'element-plus';import { Search } from '@element-plus/icons-vue';import { memberCardRequestId,redeemMemberCard,searchMemberCards } from '../../api';import MemberCardStatusTag from '../../components/MemberCardStatusTag.vue';
const form=reactive({mobile_keyword:'',name:''}),loading=ref(false),searched=ref(false),candidates=ref<any[]>([]),confirmVisible=ref(false),selected=ref<any>(null),confirmed=ref(false),remark=ref(''),serviceImei=ref(''),serviceModel=ref(''),redeeming=ref(false),inventoryMode=ref('none'),actualConsumableQty=ref(1);
const standardConsumableQty=computed(()=>Math.max(.001,Number(selected.value?.card?.standard_consumable_qty||1)));
const search=async()=>{if(!/^\d{4}$|^1\d{10}$/.test(form.mobile_keyword))return ElMessage.warning('请输入完整11位手机号或后四位');loading.value=true;try{const data=(await searchMemberCards(form) as any).data||{};candidates.value=data.candidates||[];inventoryMode.value=data.inventory_config?.mode||'none';searched.value=true}finally{loading.value=false}};
const openConfirm=(candidate:any,card:any)=>{selected.value={candidate,card};confirmed.value=false;remark.value='';serviceImei.value='';serviceModel.value='';actualConsumableQty.value=Math.max(.001,Number(card.standard_consumable_qty||1));confirmVisible.value=true};
const redeem=async()=>{if(!confirmed.value)return;if(selected.value?.card?.binding_mode==='imei'&&!serviceImei.value.trim())return ElMessage.warning('请输入本次设备 IMEI');if(selected.value?.card?.binding_mode==='model'&&!serviceModel.value.trim())return ElMessage.warning('请输入本次设备型号');await ElMessageBox.confirm('确认本次贴膜服务已经完成？核销后将扣减 1 次并记录操作人。','核销确认',{type:'warning'});redeeming.value=true;try{const result:any=(await redeemMemberCard(selected.value.card.card_id,{request_id:memberCardRequestId('redeem'),card_item_id:selected.value.card.item_id,service_imei:serviceImei.value,service_model:serviceModel.value,verification_confirmed:1,actual_consumable_qty:actualConsumableQty.value,remark:remark.value})).data;const inventoryStatus=result.inventory_status||'';if(['negative','failed'].includes(inventoryStatus))ElMessage.warning(result.inventory_message||result.message||'核销成功，库存需处理');else ElMessage.success(result.message||'核销成功');confirmVisible.value=false;await search()}finally{redeeming.value=false}}
</script>
<style scoped>.page-head{margin-bottom:20px}.page-head p{margin:6px 0 0;color:var(--el-text-color-secondary)}.search-panel{display:grid;grid-template-columns:minmax(240px,1fr) minmax(240px,1fr) auto;gap:10px;margin-bottom:18px;padding:14px 16px;border-radius:4px;background:var(--el-fill-color-lighter)}.candidate{margin-top:14px;border:1px solid var(--el-border-color-lighter);border-radius:4px;overflow:hidden}.candidate-head,.card-top,.card-bottom{display:flex;align-items:center;justify-content:space-between;gap:12px}.candidate-head{padding:15px 17px;background:var(--el-fill-color-light)}.candidate-head span{color:var(--el-text-color-secondary);font-size:12px}.candidate-head h3{margin:5px 0 0}.candidate-head small{font-weight:400;color:var(--el-text-color-secondary)}.cards{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px;padding:14px}.card{padding:16px;border:1px solid var(--el-border-color-lighter);border-radius:4px}.card.disabled{opacity:.6;background:var(--el-fill-color-light)}.card p{margin:7px 0;color:var(--el-text-color-secondary)}.binding-line{display:block;margin:-2px 0 8px;color:#2563eb}.card-bottom{padding-top:13px;border-top:1px solid var(--el-border-color-lighter)}.confirm-box{display:flex;margin-bottom:16px;padding:16px;border-radius:4px;background:var(--el-fill-color-light);flex-direction:column;gap:6px}.confirm-box span,.confirm-box small{color:var(--el-text-color-secondary)}.confirm-box strong{font-size:24px}.device-check{display:flex;margin-bottom:14px;padding:14px;border:1px solid #dbeafe;border-radius:4px;background:#f8fbff;flex-direction:column;gap:8px}.device-check small{color:var(--el-text-color-secondary)}.inventory-check{display:grid;grid-template-columns:1fr auto;align-items:center;gap:12px;margin-bottom:14px;padding:14px;border:1px solid #dcfce7;border-radius:4px;background:#f7fef9}.inventory-check>div{display:flex;flex-direction:column;gap:5px}.inventory-check span{color:var(--el-text-color-secondary);font-size:13px}.inventory-check .el-alert{grid-column:1/-1}.confirm-check{margin-bottom:16px}@media(max-width:900px){.search-panel{grid-template-columns:1fr}.cards{grid-template-columns:1fr}}</style>
