import request from '@/utils/request'

export const getProjectCenterProjects = (params: any) => request.get('/project-center/projects', { params })
export const getProjectCenterProject = (id: number) => request.get(`/project-center/projects/${id}`)
export const getProjectCenterMetadata = () => request.get('/project-center/projects/metadata')
export const addProjectCenterProject = (data: any) => request.post('/project-center/projects', data)
export const editProjectCenterProject = (id: number, data: any) => request.put(`/project-center/projects/${id}`, data)
export const deleteProjectCenterProject = (id: number) => request.delete(`/project-center/projects/${id}`)
export const getProjectCenterGroups = (params: any) => request.get('/project-center/groups', { params })
export const reserveProjectCenterGroup = (data: any) => request.post('/project-center/groups/reserve', data)
export const correctProjectCenterGroupNo = (id: number, data: any) => request.put(`/project-center/groups/${id}/group-no`, data)
export const getProjectCenterWecomReadiness = () => request.get('/project-center/wecom/readiness')
export const getProjectCenterWecomOauthUrl = (params: any) => request.get('/project-center/wecom/oauth-url', { params })
export const bindProjectCenterWecomIdentity = (data: any) => request.post('/project-center/wecom/bind-identity', data)
export const prepareProjectCenterWecom = (id: number, data: any) => request.post(`/project-center/groups/${id}/wecom/prepare`, data)
export const completeProjectCenterWecom = (id: number, data: any) => request.put(`/project-center/groups/${id}/wecom/complete`, data)
export const failProjectCenterWecom = (id: number, data: any) => request.put(`/project-center/groups/${id}/wecom/fail`, data)
export const bindProjectCenterWecom = (id: number, data: any) => request.put(`/project-center/groups/${id}/wecom`, data)
export const closeProjectCenterGroup = (id: number, data: any) => request.put(`/project-center/groups/${id}/close`, data)
export const getProjectCenterRefund = (id: number) => request.get(`/project-center/groups/${id}/refund`)
export const requestProjectCenterRefund = (id: number, data: any) => request.post(`/project-center/groups/${id}/refund`, data)
export const completeProjectCenterRefund = (id: number, data: any) => request.put(`/project-center/groups/${id}/refund/complete`, data)
export const cancelProjectCenterRefund = (id: number, data: any) => request.put(`/project-center/groups/${id}/refund/cancel`, data)
export const getProjectCenterApplications = (params: any) => request.get('/project-center/applications', { params })
export const getProjectCenterReviewReasons = (projectId: number) => request.get('/project-center/applications/review-reasons', { params: { project_id: projectId } })
export const saveProjectCenterReviewReasons = (projectId: number, reasons: any[]) => request.put('/project-center/applications/review-reasons', { project_id: projectId, reasons })
export const getProjectCenterApplication = (id: number) => request.get(`/project-center/applications/${id}`)
export const reviewProjectCenterApplication = (id: number, data: any) => request.put(`/project-center/applications/${id}/review`, data)
export const correctProjectCenterApplicationGroupNo = (id: number, data: any) => request.put(`/project-center/applications/${id}/group-no`, data)
export const downloadProjectCenterApplicationArchive = (id: number) => request.get(`/project-center/applications/${id}/archive`, { responseType: 'blob' })
export const getProjectCenterIncomeBoard = (params: any) => request.get('/project-center/income-board', { params })
export const replaceProjectCenterIncomeBoard = (data: any) => request.post('/project-center/income-board/replace', data)
export const getProjectCenterDistributionOverview = () => request.get('/project-center/distribution/overview')
export const getProjectCenterDistributionProjects = () => request.get('/project-center/distribution/projects')
export const getProjectCenterDistributionOrders = (params: any) => request.get('/project-center/distribution/orders', { params })
export const getProjectCenterDistributionOrder = (id: number) => request.get(`/project-center/distribution/orders/${id}`)
export const settleProjectCenterDistributionOrder = (id: number) => request.post(`/project-center/distribution/orders/${id}/settle`)
