<?php

return [
    'hsx_phone_query_report' => [
        'title' => '设备查询组件',
        'support' => ['hsx_phone_query_report'],
        'list' => [
            'QueryBrandName' => [
                'title' => '品牌名称',
                'type' => 'text',
                'icon' => 'iconfont iconbiaoti',
                'path' => 'text',
                'uses' => 1,
                'sort' => 10100,
                'relate' => 'brand_name',
                'value' => '手机查询报告',
                'template' => ['width' => 300, 'height' => 55],
            ],
            'QueryReportTitle' => [
                'title' => '设备标题',
                'type' => 'text',
                'icon' => 'iconfont iconbiaoti',
                'path' => 'text',
                'uses' => 1,
                'sort' => 10101,
                'relate' => 'report_title',
                'value' => '设备查询报告',
                'template' => ['width' => 420, 'height' => 60],
            ],
            'QueryServiceName' => [
                'title' => '查询项目',
                'type' => 'text',
                'icon' => 'iconfont iconbiaoti',
                'path' => 'text',
                'uses' => 1,
                'sort' => 10102,
                'relate' => 'service_name',
                'value' => '查询项目',
                'template' => ['width' => 260, 'height' => 48],
            ],
            'QueryCodeText' => [
                'title' => 'IMEI/SN',
                'type' => 'text',
                'icon' => 'iconfont iconbiaoti',
                'path' => 'text',
                'uses' => 1,
                'sort' => 10103,
                'relate' => 'query_code_text',
                'value' => 'IMEI/SN：',
                'template' => ['width' => 420, 'height' => 48],
            ],
            'QuerySummaryLine1' => [
                'title' => '摘要一',
                'type' => 'text',
                'icon' => 'iconfont iconbiaoti',
                'path' => 'text',
                'uses' => 1,
                'sort' => 10104,
                'relate' => 'summary_line_1',
                'value' => '激活状态：已激活',
                'template' => ['width' => 460, 'height' => 44],
            ],
            'QuerySummaryLine2' => [
                'title' => '摘要二',
                'type' => 'text',
                'icon' => 'iconfont iconbiaoti',
                'path' => 'text',
                'uses' => 1,
                'sort' => 10105,
                'relate' => 'summary_line_2',
                'value' => '激活日期：2026-01-01',
                'template' => ['width' => 460, 'height' => 44],
            ],
            'QuerySummaryLine3' => [
                'title' => '摘要三',
                'type' => 'text',
                'icon' => 'iconfont iconbiaoti',
                'path' => 'text',
                'uses' => 1,
                'sort' => 10106,
                'relate' => 'summary_line_3',
                'value' => '保修状态：保修中',
                'template' => ['width' => 460, 'height' => 44],
            ],
            'QuerySummaryLine4' => [
                'title' => '摘要四',
                'type' => 'text',
                'icon' => 'iconfont iconbiaoti',
                'path' => 'text',
                'uses' => 1,
                'sort' => 10107,
                'relate' => 'summary_line_4',
                'value' => '保修到期：2027-01-01',
                'template' => ['width' => 460, 'height' => 44],
            ],
            'QueryTime' => [
                'title' => '查询时间',
                'type' => 'text',
                'icon' => 'iconfont iconbiaoti',
                'path' => 'text',
                'uses' => 1,
                'sort' => 10108,
                'relate' => 'query_time',
                'value' => '2026-01-01 12:00',
                'template' => ['width' => 280, 'height' => 40],
            ],
            'QuerySupportText' => [
                'title' => '报告说明',
                'type' => 'text',
                'icon' => 'iconfont iconbiaoti',
                'path' => 'text',
                'uses' => 1,
                'sort' => 10109,
                'relate' => 'support_text',
                'value' => '查询结果仅供交易验机参考',
                'template' => ['width' => 460, 'height' => 40],
            ],
            'QueryFooterText' => [
                'title' => '页脚文案',
                'type' => 'text',
                'icon' => 'iconfont iconbiaoti',
                'path' => 'text',
                'uses' => 1,
                'sort' => 10110,
                'relate' => 'footer_text',
                'value' => '报告由系统自动生成',
                'template' => ['width' => 460, 'height' => 40],
            ],
            'QueryCustomerPhone' => [
                'title' => '客服电话',
                'type' => 'text',
                'icon' => 'iconfont iconbiaoti',
                'path' => 'text',
                'uses' => 1,
                'sort' => 10111,
                'relate' => 'customer_phone',
                'value' => '客服电话',
                'template' => ['width' => 300, 'height' => 40],
            ],
        ],
    ],
];
