<?php

return [
    [
        'name' => '设备查询报告海报模板',
        'type' => 'hsx_phone_query_report',
        'data' => [
            'global' => [
                'bgType' => 'color',
                'bgColor' => '#FFFFFF',
                'bgUrl' => '',
                'width' => 750,
                'height' => 1334,
            ],
            'value' => [
                [
                    'id' => 'brand_name',
                    'componentName' => 'BrandName',
                    'componentTitle' => '品牌名称',
                    'type' => 'text',
                    'path' => 'text',
                    'uses' => 1,
                    'relate' => 'brand_name',
                    'value' => '手机查询报告',
                    'width' => 560,
                    'height' => 54,
                    'minWidth' => 120,
                    'minHeight' => 44,
                    'x' => 72,
                    'y' => 90,
                    'angle' => 0,
                    'zIndex' => 3,
                    'fontFamily' => '',
                    'fontSize' => 34,
                    'weight' => true,
                    'space' => 0,
                    'lineHeight' => 0,
                    'fontColor' => '#111827',
                    'textAlign' => 'left',
                ],
                [
                    'id' => 'poster_intro',
                    'componentName' => 'PosterIntro',
                    'componentTitle' => '海报说明',
                    'type' => 'text',
                    'path' => 'text',
                    'uses' => 1,
                    'relate' => '',
                    'value' => '扫码查看完整设备查询报告',
                    'width' => 560,
                    'height' => 42,
                    'minWidth' => 120,
                    'minHeight' => 36,
                    'x' => 72,
                    'y' => 145,
                    'angle' => 0,
                    'zIndex' => 3,
                    'fontFamily' => '',
                    'fontSize' => 24,
                    'weight' => false,
                    'space' => 0,
                    'lineHeight' => 0,
                    'fontColor' => '#667085',
                    'textAlign' => 'left',
                ],
                [
                    'id' => 'report_title',
                    'componentName' => 'ReportTitle',
                    'componentTitle' => '报告标题',
                    'type' => 'text',
                    'path' => 'text',
                    'uses' => 1,
                    'relate' => 'report_title',
                    'value' => '设备查询报告',
                    'width' => 610,
                    'height' => 64,
                    'minWidth' => 120,
                    'minHeight' => 44,
                    'x' => 72,
                    'y' => 240,
                    'angle' => 0,
                    'zIndex' => 4,
                    'fontFamily' => '',
                    'fontSize' => 38,
                    'weight' => true,
                    'space' => 0,
                    'lineHeight' => 0,
                    'fontColor' => '#111827',
                    'textAlign' => 'left',
                ],
                [
                    'id' => 'service_name',
                    'componentName' => 'ServiceName',
                    'componentTitle' => '查询项目',
                    'type' => 'text',
                    'path' => 'text',
                    'uses' => 1,
                    'relate' => 'service_name',
                    'value' => '查询项目',
                    'width' => 610,
                    'height' => 44,
                    'minWidth' => 120,
                    'minHeight' => 36,
                    'x' => 72,
                    'y' => 320,
                    'angle' => 0,
                    'zIndex' => 4,
                    'fontFamily' => '',
                    'fontSize' => 26,
                    'weight' => true,
                    'space' => 0,
                    'lineHeight' => 0,
                    'fontColor' => '#1F6FEB',
                    'textAlign' => 'left',
                ],
                [
                    'id' => 'query_code_text',
                    'componentName' => 'QueryCodeText',
                    'componentTitle' => '查询码',
                    'type' => 'text',
                    'path' => 'text',
                    'uses' => 1,
                    'relate' => 'query_code_text',
                    'value' => 'IMEI/SN：',
                    'width' => 610,
                    'height' => 42,
                    'minWidth' => 120,
                    'minHeight' => 36,
                    'x' => 72,
                    'y' => 380,
                    'angle' => 0,
                    'zIndex' => 4,
                    'fontFamily' => '',
                    'fontSize' => 24,
                    'weight' => false,
                    'space' => 0,
                    'lineHeight' => 0,
                    'fontColor' => '#475467',
                    'textAlign' => 'left',
                ],
                [
                    'id' => 'summary_title',
                    'componentName' => 'SummaryTitle',
                    'componentTitle' => '摘要标题',
                    'type' => 'text',
                    'path' => 'text',
                    'uses' => 1,
                    'relate' => '',
                    'value' => '报告摘要',
                    'width' => 610,
                    'height' => 42,
                    'minWidth' => 120,
                    'minHeight' => 36,
                    'x' => 72,
                    'y' => 480,
                    'angle' => 0,
                    'zIndex' => 4,
                    'fontFamily' => '',
                    'fontSize' => 28,
                    'weight' => true,
                    'space' => 0,
                    'lineHeight' => 0,
                    'fontColor' => '#111827',
                    'textAlign' => 'left',
                ],
                [
                    'id' => 'summary_line_1',
                    'componentName' => 'SummaryLine1',
                    'componentTitle' => '摘要一',
                    'type' => 'text',
                    'path' => 'text',
                    'uses' => 1,
                    'relate' => 'summary_line_1',
                    'value' => '',
                    'width' => 610,
                    'height' => 38,
                    'minWidth' => 120,
                    'minHeight' => 34,
                    'x' => 72,
                    'y' => 540,
                    'angle' => 0,
                    'zIndex' => 4,
                    'fontFamily' => '',
                    'fontSize' => 24,
                    'weight' => false,
                    'space' => 0,
                    'lineHeight' => 0,
                    'fontColor' => '#475467',
                    'textAlign' => 'left',
                ],
                [
                    'id' => 'summary_line_2',
                    'componentName' => 'SummaryLine2',
                    'componentTitle' => '摘要二',
                    'type' => 'text',
                    'path' => 'text',
                    'uses' => 1,
                    'relate' => 'summary_line_2',
                    'value' => '',
                    'width' => 610,
                    'height' => 38,
                    'minWidth' => 120,
                    'minHeight' => 34,
                    'x' => 72,
                    'y' => 590,
                    'angle' => 0,
                    'zIndex' => 4,
                    'fontFamily' => '',
                    'fontSize' => 24,
                    'weight' => false,
                    'space' => 0,
                    'lineHeight' => 0,
                    'fontColor' => '#475467',
                    'textAlign' => 'left',
                ],
                [
                    'id' => 'summary_line_3',
                    'componentName' => 'SummaryLine3',
                    'componentTitle' => '摘要三',
                    'type' => 'text',
                    'path' => 'text',
                    'uses' => 1,
                    'relate' => 'summary_line_3',
                    'value' => '',
                    'width' => 610,
                    'height' => 38,
                    'minWidth' => 120,
                    'minHeight' => 34,
                    'x' => 72,
                    'y' => 640,
                    'angle' => 0,
                    'zIndex' => 4,
                    'fontFamily' => '',
                    'fontSize' => 24,
                    'weight' => false,
                    'space' => 0,
                    'lineHeight' => 0,
                    'fontColor' => '#475467',
                    'textAlign' => 'left',
                ],
                [
                    'id' => 'summary_line_4',
                    'componentName' => 'SummaryLine4',
                    'componentTitle' => '摘要四',
                    'type' => 'text',
                    'path' => 'text',
                    'uses' => 1,
                    'relate' => 'summary_line_4',
                    'value' => '',
                    'width' => 610,
                    'height' => 38,
                    'minWidth' => 120,
                    'minHeight' => 34,
                    'x' => 72,
                    'y' => 690,
                    'angle' => 0,
                    'zIndex' => 4,
                    'fontFamily' => '',
                    'fontSize' => 24,
                    'weight' => false,
                    'space' => 0,
                    'lineHeight' => 0,
                    'fontColor' => '#475467',
                    'textAlign' => 'left',
                ],
                [
                    'id' => 'qrcode',
                    'componentName' => 'Qrcode',
                    'componentTitle' => '二维码',
                    'type' => 'qrcode',
                    'path' => 'qrcode',
                    'uses' => 1,
                    'relate' => 'url',
                    'value' => '',
                    'width' => 170,
                    'height' => 170,
                    'minWidth' => 100,
                    'minHeight' => 100,
                    'x' => 72,
                    'y' => 810,
                    'angle' => 0,
                    'zIndex' => 5,
                ],
                [
                    'id' => 'qr_tip',
                    'componentName' => 'QrTip',
                    'componentTitle' => '扫码提示',
                    'type' => 'text',
                    'path' => 'text',
                    'uses' => 1,
                    'relate' => '',
                    'value' => '长按识别二维码',
                    'width' => 330,
                    'height' => 42,
                    'minWidth' => 120,
                    'minHeight' => 36,
                    'x' => 285,
                    'y' => 840,
                    'angle' => 0,
                    'zIndex' => 4,
                    'fontFamily' => '',
                    'fontSize' => 28,
                    'weight' => true,
                    'space' => 0,
                    'lineHeight' => 0,
                    'fontColor' => '#111827',
                    'textAlign' => 'left',
                ],
                [
                    'id' => 'query_time',
                    'componentName' => 'QueryTime',
                    'componentTitle' => '查询时间',
                    'type' => 'text',
                    'path' => 'text',
                    'uses' => 1,
                    'relate' => 'query_time',
                    'value' => '',
                    'width' => 330,
                    'height' => 38,
                    'minWidth' => 120,
                    'minHeight' => 34,
                    'x' => 285,
                    'y' => 895,
                    'angle' => 0,
                    'zIndex' => 4,
                    'fontFamily' => '',
                    'fontSize' => 22,
                    'weight' => false,
                    'space' => 0,
                    'lineHeight' => 0,
                    'fontColor' => '#667085',
                    'textAlign' => 'left',
                ],
                [
                    'id' => 'support_text',
                    'componentName' => 'SupportText',
                    'componentTitle' => '说明文案',
                    'type' => 'text',
                    'path' => 'text',
                    'uses' => 1,
                    'relate' => 'support_text',
                    'value' => '查询结果仅供交易验机参考',
                    'width' => 620,
                    'height' => 40,
                    'minWidth' => 120,
                    'minHeight' => 36,
                    'x' => 65,
                    'y' => 1070,
                    'angle' => 0,
                    'zIndex' => 4,
                    'fontFamily' => '',
                    'fontSize' => 22,
                    'weight' => false,
                    'space' => 0,
                    'lineHeight' => 0,
                    'fontColor' => '#667085',
                    'textAlign' => 'center',
                ],
                [
                    'id' => 'footer_text',
                    'componentName' => 'FooterText',
                    'componentTitle' => '页脚',
                    'type' => 'text',
                    'path' => 'text',
                    'uses' => 1,
                    'relate' => 'footer_text',
                    'value' => '报告由系统自动生成',
                    'width' => 620,
                    'height' => 40,
                    'minWidth' => 120,
                    'minHeight' => 36,
                    'x' => 65,
                    'y' => 1120,
                    'angle' => 0,
                    'zIndex' => 4,
                    'fontFamily' => '',
                    'fontSize' => 22,
                    'weight' => false,
                    'space' => 0,
                    'lineHeight' => 0,
                    'fontColor' => '#98A2B3',
                    'textAlign' => 'center',
                ],
                [
                    'id' => 'customer_phone',
                    'componentName' => 'CustomerPhone',
                    'componentTitle' => '客服电话',
                    'type' => 'text',
                    'path' => 'text',
                    'uses' => 1,
                    'relate' => 'customer_phone',
                    'value' => '',
                    'width' => 620,
                    'height' => 40,
                    'minWidth' => 120,
                    'minHeight' => 36,
                    'x' => 65,
                    'y' => 1170,
                    'angle' => 0,
                    'zIndex' => 4,
                    'fontFamily' => '',
                    'fontSize' => 22,
                    'weight' => false,
                    'space' => 0,
                    'lineHeight' => 0,
                    'fontColor' => '#98A2B3',
                    'textAlign' => 'center',
                ],
            ],
        ],
    ],
];
