<script lang="ts">export default { name: 'HsxTimeline' }</script>
<script setup lang="ts">
import { computed } from 'vue'
import HsxTag from '../HsxTag/index.vue'
import type { MobileTimelineItem } from '../../types'
const props = withDefaults(defineProps<{ items?: MobileTimelineItem[], reverse?: boolean, compact?: boolean }>(), { items: () => [], reverse: false, compact: false })
const actualItems = computed(() => props.reverse ? [...props.items].reverse() : props.items)
function tagOf(item: MobileTimelineItem) { return typeof item.tag === 'string' ? { label: item.tag, tone: item.tone || 'primary' } : item.tag }
</script>
<template><view class="hsx-mobile-timeline" :class="{ 'hsx-mobile-timeline--compact': compact }"><view v-for="(item, index) in actualItems" :key="item.id ?? index" class="hsx-mobile-timeline__item"><view class="hsx-mobile-timeline__rail"><view class="hsx-mobile-timeline__dot" :class="`hsx-mobile-timeline__dot--${item.tone || tagOf(item)?.tone || 'primary'}`" /></view><view class="hsx-mobile-timeline__main"><slot name="header" :item="item" :index="index"><view class="hsx-mobile-timeline__header"><view><text>{{ item.actor || item.title }}</text><HsxTag v-if="tagOf(item)" :text="tagOf(item)?.label" :tone="tagOf(item)?.tone" size="small" /></view><text>{{ item.time }}</text></view></slot><slot name="content" :item="item" :index="index"><view v-if="item.content || item.details?.length" class="hsx-mobile-timeline__content"><text v-if="item.content">{{ item.content }}</text><view v-for="detail in item.details" :key="detail.label"><text>{{ detail.label }}</text><text>{{ detail.value }}</text></view></view></slot></view></view></view></template>
<style scoped lang="scss">
.hsx-mobile-timeline__item { display: grid; grid-template-columns: 18px minmax(0,1fr); gap: 8px; }.hsx-mobile-timeline__rail { position: relative; display: flex; justify-content: center; }.hsx-mobile-timeline__rail::after { position: absolute; top: 16px; bottom: -6px; left: 50%; border-left: 1px dashed var(--hsx-mobile-border-strong); content: ''; }.hsx-mobile-timeline__item:last-child .hsx-mobile-timeline__rail::after { display: none; }.hsx-mobile-timeline__dot { z-index: 1; width: 7px; height: 7px; margin-top: 6px; border: 4px solid var(--hsx-mobile-primary); border-radius: 50%; background: var(--hsx-mobile-bg-surface); }.hsx-mobile-timeline__dot--success { border-color: var(--hsx-mobile-success); }.hsx-mobile-timeline__dot--warning { border-color: var(--hsx-mobile-warning); }.hsx-mobile-timeline__dot--danger { border-color: var(--hsx-mobile-danger); }
.hsx-mobile-timeline__main { min-width: 0; padding-bottom: 20px; }.hsx-mobile-timeline__header { display: flex; justify-content: space-between; gap: 12px; }.hsx-mobile-timeline__header > view { display: flex; min-width: 0; align-items: center; gap: 8px; }.hsx-mobile-timeline__header > view > text { overflow: hidden; color: var(--hsx-mobile-text-primary); font-size: var(--hsx-mobile-font-body, 14px); font-weight: 650; text-overflow: ellipsis; white-space: nowrap; }.hsx-mobile-timeline__header > text { flex: none; color: var(--hsx-mobile-text-secondary); font-size: var(--hsx-mobile-font-caption, 12px); }.hsx-mobile-timeline__content { padding: 12px 14px; margin-top: 8px; border-radius: 12px; color: var(--hsx-mobile-text-regular); background: var(--hsx-mobile-bg-muted); font-size: var(--hsx-mobile-font-body, 14px); }.hsx-mobile-timeline__content > text { display: block; }.hsx-mobile-timeline__content > view { display: grid; grid-template-columns: max-content minmax(0,1fr); gap: 10px; margin-top: 5px; }.hsx-mobile-timeline__content > view > text:first-child { color: var(--hsx-mobile-text-primary); font-weight: 600; }.hsx-mobile-timeline--compact .hsx-mobile-timeline__main { padding-bottom: 12px; }
</style>
