CREATE TABLE IF NOT EXISTS `{{prefix}}hsx_express_task` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `site_id` int unsigned NOT NULL,
  `task_no` varchar(64) NOT NULL,
  `business_type` varchar(60) NOT NULL,
  `business_id` varchar(100) NOT NULL,
  `attempt` int unsigned NOT NULL DEFAULT 1,
  `business_order_id` bigint unsigned NOT NULL DEFAULT 0,
  `business_refs_json` text NULL,
  `payload_hash` char(64) NOT NULL,
  `provider` varchar(32) NOT NULL DEFAULT 'kuaidi100',
  `carrier` varchar(40) NOT NULL,
  `exp_type` varchar(100) NOT NULL,
  `print_type` varchar(20) NOT NULL,
  `state` varchar(30) NOT NULL DEFAULT 'creating',
  `provider_task_id` varchar(100) NOT NULL DEFAULT '',
  `waybill_no` varchar(100) NOT NULL DEFAULT '',
  `provider_order_no` varchar(100) NOT NULL DEFAULT '',
  `label` text NULL,
  `snapshot_cipher` longtext NOT NULL COMMENT '账号及收发地址加密快照，不进入接口或日志',
  `logs_json` longtext NULL COMMENT '脱敏操作记录',
  `message` varchar(1000) NOT NULL DEFAULT '',
  `last_code` varchar(40) NOT NULL DEFAULT '',
  `reprint_count` int unsigned NOT NULL DEFAULT 0,
  `create_at` int unsigned NOT NULL DEFAULT 0,
  `update_at` int unsigned NOT NULL DEFAULT 0,
  `submitted_at` int unsigned NOT NULL DEFAULT 0,
  `last_callback_at` int unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_site_business` (`site_id`,`business_type`,`business_id`,`attempt`),
  UNIQUE KEY `uk_task_no` (`task_no`),
  KEY `idx_site_state` (`site_id`,`state`,`id`),
  KEY `idx_business_order` (`site_id`,`business_type`,`business_order_id`),
  KEY `idx_provider_task` (`provider_task_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='物流服务运单与打印任务';
