<?php
declare(strict_types=1);

$root = dirname(__DIR__);
$read = static function (string $path) use ($root): string {
    $content = file_get_contents($root . '/' . $path);
    if ($content === false) throw new RuntimeException('无法读取 ' . $path);
    return $content;
};
$assertContains = static function (string $needle, string $content, string $message): void {
    if (!str_contains($content, $needle)) throw new RuntimeException($message);
};
$assertNotContains = static function (string $needle, string $content, string $message): void {
    if (str_contains($content, $needle)) throw new RuntimeException($message);
};

$group = $read('app/service/core/ProjectCenterGroupService.php');
$application = $read('app/service/core/ProjectCenterApplicationService.php');
$portal = $read('app/service/api/ProjectCenterPortalService.php');
$projectAdmin = $read('app/service/admin/ProjectCenterProjectAdminService.php');
$review = $read('app/service/core/ProjectCenterReviewService.php');
$routes = $read('app/adminapi/route/route.php');
$wecom = $read('app/service/admin/ProjectCenterWecomAdminService.php');
$applicationAdmin = $read('app/service/admin/ProjectCenterApplicationAdminService.php');
$archive = $read('app/service/admin/ProjectCenterApplicationArchiveService.php');
$schema = $read('app/support/ProjectCenterSchema.php');
$addon = $read('Addon.php');
$installSql = $read('sql/install.sql');
$apiRoutes = $read('app/api/route/route.php');
$projectPage = $read('uni-app/pages/project/detail.vue');
$formProgress = $read('uni-app/components/ProjectFormProgress.vue');
$locationField = $read('uni-app/components/diy/project-form-location/index.vue');
$groupView = $read('admin/views/group/index.vue');
$correctGroupNoDialog = $read('admin/components/CorrectGroupNoDialog.vue');
$diyLinks = $read('app/dict/diy/links.php');

$assertContains("['project_id', '=', 0]", $group, '群编号必须使用站点级日序列，避免不同项目重复编号');
$assertContains('请填写客户群编号', $group, '进入资料步骤后客户群编号必须填写');
$assertContains('当前账号手机号与群内登记手机号不一致', $group, '首次提交必须校验预留手机号');
$assertContains('该客户群尚未绑定客户手机号', $group, '仅有企微 external_userid 的群不得被猜号抢占');
$assertContains("['reserved', 'create_failed', 'created', 'active']", $group, '企微自动建群失败不得阻断普通微信群继续办理');
$assertContains('该客户群已完成办理，无需重复提交资料', $group, '真正完成的客户群必须保持终态并给出明确提示');
$assertContains('请先确认已按项目说明完成付款', $application, '提交资料前必须明确完成线下付款声明');
$assertContains('$groupService->requireAvailableByNo', $application, '新资料工单必须在核心服务内强制校验群编号');
$assertContains('$groupId = (int)$group->id', $application, '新资料工单必须绑定真实客户群，不能写 group_id=0');
$assertContains("'direct:' . \$projectId . ':' . \$memberId", $application, '历史直达工单的只读幂等键仍需兼容');
$assertContains("['site_id', '=', \$siteId], ['idempotency_key', '=', \$idempotencyKey]", $application, '资料工单必须通过业务幂等键防止并发重复');
$assertContains('资料已提交审核，不能用另一份表单覆盖', $application, '审核中的工单必须禁止换记录覆盖');
$assertContains("['reserved', 'create_failed', 'created']", $application, '资料提交成功后必须把技术失败或待建群状态归一为办理中');
$assertNotContains("unset(\$row['payment_qrcode']", $portal, '启用项目必须向客户入口下发付款码');
$assertContains('public function checkGroup', $portal, '显示资料表单前必须提供登录态群号核验接口');
$assertContains("'legacy_direct' =>", $portal, '历史 group_id=0 工单必须明确标为只读兼容数据');
$assertContains("\$row['intro_diy']", $portal, '项目门户必须返回可安全嵌入的 DIY 介绍');
$assertContains("'ProjectCenterIncomeBoard'", $portal, '项目门户必须允许收益榜单低代码组件');
$assertContains("\$name === 'AiAssistantEntry' && !\$aiEnabled", $portal, 'AI 默认关闭时不得下发 AI 入口组件');
$assertContains("\$submittedValue = \$snapshot['value']", $application, '项目审核必须以本次表单主快照为事实，不得信任可能残留的子表行');
$assertContains("\$snapshot['recordsFieldList'] = \$canonicalRecords", $application, '审核和 ZIP 必须消费同一份规范化快照');
$assertContains("['type', '=', 'DIY_PAGE']", $projectAdmin, '项目配置只能选择本站 DIY 微页面');
$assertContains("NoticeService::send", $review, '审核结果必须接入牛云通知系统');
$assertContains("groups/:id/close", $routes, '客户放弃或群解散必须有正式结束入口');
$assertContains("groups/:id/group-no", $routes, '管理员必须能通过受控接口更正客户误填的群编号');
$assertContains("applications/:id/group-no", $routes, '资料审核员必须通过工单权限更正客户误填的群编号');
$assertContains("groups/:id/wecom/prepare", $routes, '自动建群必须有服务端准备接口');
$assertContains("wecom/selector-config", $routes, '原生选客必须能在生成群编号前初始化企微 JS-SDK');
$assertContains("groups/:id/wecom/complete", $routes, '自动建群必须回写企业微信 chat_id');
$assertContains("wecom/oauth-url", $routes, '员工必须能通过企业微信静默授权绑定本人身份');
$assertContains("wecom/bind-identity", $routes, '企业微信 OAuth 身份必须回写系统员工绑定');
$assertContains('jsSdkConfig', $wecom, '项目中心必须通过企微插件生成 JS-SDK 签名');
$assertContains('userIdByOauthCode', $wecom, '项目中心必须使用企微 OAuth code 识别当前员工');
$assertContains('openEnterpriseChat', $groupView, '客户群台账必须提供企业微信原生建群入口');
$assertContains('selectExternalContact', $groupView, '建群前必须选择并核对外部联系人');
$assertContains('config_js_api_list', $groupView, 'wx.config 必须使用独立的企业身份 JSAPI 清单');
$assertContains('agent_js_api_list', $groupView, 'agentConfig 必须使用独立的应用身份 JSAPI 清单');
$assertContains('jwxwork-1.0.0.js', $groupView, '企业微信应用级 JSAPI 必须加载官方 jwxwork 兼容 SDK');
$assertContains('completeSelfBindFromUrl', $groupView, '企业微信工作台入口必须自动完成当前员工身份绑定');
$assertContains('CorrectGroupNoDialog', $groupView, '客户群台账必须复用群编号更正组件');
$assertContains('correctProjectCenterGroupNo', $correctGroupNoDialog, '群编号更正组件必须调用受控后台接口');
$assertContains('correctProjectCenterApplicationGroupNo', $correctGroupNoDialog, '审核工作台必须使用工单范围的群编号更正接口');
$assertContains('public function correctGroupNo', $group, '更正群编号必须复用核心唯一性与日期序列规则');
$assertContains("['reserved', 'create_failed']", $wecom, '企微失败回调不得把办理中或已结束的普通微信群降级');
$assertContains("whereIn('group_id', \$groupIds, 'OR')", $applicationAdmin, '资料工单可见范围必须使用 ThinkORM 支持的 OR IN 写法');
$assertNotContains('whereOrIn(', $applicationAdmin, 'ThinkORM 会把 whereOrIn 误解析为 GROUP_ID 查询表达式');
$assertContains('reviewerProjectIds', $applicationAdmin, '项目配置的多名审核员必须都能看到并处理工单');
$assertContains("Member::where", $applicationAdmin, '直达工单必须支持会员姓名和手机号检索');
$assertContains("projects/:id/revise", $apiRoutes, '驳回重提必须使用项目插件修订入口');
$assertContains("projects/:id/group-check", $apiRoutes, '客户群号必须在显示资料表单前通过登录态接口核验');
$assertContains("projects/:id/group-resolve", $apiRoutes, '客户确认群编号时必须通过写语义接口自动建账或绑定');
$assertContains("middleware(ApiCheckToken::class, false)", $apiRoutes, '游客项目入口必须先识别并校验站点，不能按 site_id=0 查询');
$assertContains('revision_value', $portal, '驳回状态必须返回原资料用于预填');
$assertContains('CoreDiyFormRecordsService())->edit', $portal, '驳回重提必须修订原万能表单记录');
$assertContains('validateFormValue', $portal, '驳回资料必须在覆盖原记录前完成权威校验');
$assertNotContains("'update_time' => time()", $portal, '万能表单主记录没有 update_time 字段，修订时不能写入不存在的列');
$assertContains("validTime: Math.floor(Date.now() / 1000) + 3600", $projectPage, '驳回资料必须在表单渲染前写入预填缓存');
$assertContains("subscribe.request('project_center_application_approved,project_center_application_rejected,project_center_refund_completed')", $projectPage, '每次提交和重提前都必须重新申请审核及退款结果通知');
$assertContains("'refund_pending','refunded'", $projectPage, '待退款和已退款必须冻结客户资料表单');
$assertContains(':show-menu-by-longpress="true"', $projectPage, '客户付款码必须支持长按识别');
$assertContains('我已付款，下一步', $projectPage, '付款与资料填写必须分成清晰的前后步骤');
$assertContains('填写您所在的运营群数字编号', $projectPage, '资料步骤必须明确要求填写运营群编号');
$assertContains('编号核对通过后，才能进入资料填写', $projectPage, '群编号必须表现为进入资料步骤前的强制关卡');
$assertContains('确认编号，进入资料填写', $projectPage, '群编号关卡必须提供明确的下一步动作');
$assertContains('resolveProjectCenterGroup', $projectPage, '万能表单渲染前必须确认群号并自动建立客户群台账');
$assertContains('legacyDirect', $projectPage, '历史无群工单在客户页面必须只读展示');
$assertContains('<ProjectFormProgress :components="formComponents" />', $projectPage, '客户进入资料表单后必须显示实时填写进度');
$assertContains('formRef.value?.getData?.()?.value', $projectPage, '填写进度必须复用万能表单的响应式数据，不能另造副本');
$assertContains("item.componentName === 'ProjectCenterIncomeBoard'", $projectPage, '项目页必须向收益榜单组件注入当前项目最新数据');
$assertContains('e?.msg || e?.data?.msg || e?.message', $projectPage, '客户提交失败必须展示后端真实原因，不能统一覆盖为请重试');
$assertContains('submit-error-panel', $projectPage, '客户提交失败原因必须在表单内持续展示，避免瞬时提示丢失');
$assertContains('资料填写进度', $formProgress, '项目中心必须提供插件级可复用的资料进度组件');
$assertContains('item.componentIsShow !== false', $formProgress, '条件联动隐藏的字段不得计入当前填写进度');
$assertContains("name === 'ProjectFormLocation'", $formProgress, '精准定位必须按经纬度与地址规则计算填写状态');
$assertContains('handleCurrentLocationFailure', $locationField, '浏览器定位失败必须提供清晰原因与地图选择兜底');
$assertContains('启用项目前请配置客户付款码', $projectAdmin, '启用项目必须配置对客付款码');
$assertContains("sprintf('%03d_%s_%s_%02d'", $archive, '资料 ZIP 图片必须使用稳定序号和字段键命名');
$assertContains('ProjectCenterSchema::migrate()', $addon, '安装和升级必须执行项目中心结构迁移');
$assertContains('project_center_group_no_alias', $schema, '群编号更正必须创建历史别名表，保证旧入口不断链');
$assertContains('project_center_group_no_change_log', $schema, '每次群编号更正必须写入独立的永久审计日志');
$assertContains('project_center_group_no_alias', $group, '群编号核验必须兼容管理员更正前的旧编号');
$assertContains('for ($offset = 0; $offset < 999; $offset++)', $group, '自动群编号必须跳过当前编号和历史编号，避免序列污染后不可用');
$assertContains('expectedGroupNoFull', $group, '管理员更正群编号必须通过乐观锁防止相互覆盖');
$assertContains('resolveForMember', $group, '客户输入有效群编号后系统必须自动建账并绑定当前账号');
$assertContains('group -> application', $review, '审核和结束群必须使用一致的数据库加锁顺序');
$assertContains('历史无群工单仅供查看', $review, '历史 group_id=0 工单必须在核心审核层保持只读');
$assertContains('uk_site_idempotency', $schema, '迁移必须补建资料工单唯一幂等索引');
$assertContains('uk_site_idempotency', $installSql, '全新安装必须带资料工单唯一幂等索引');
$assertContains('HSX_PROJECT_CENTER_PROJECT_DETAIL', $diyLinks, '项目参与页必须注册到自定义路由字典');
$assertContains("'is_share' => 1", $diyLinks, '项目参与页必须允许在后台配置分享卡片');
$assertContains('useShare', $projectPage, '项目参与页必须接入框架分享能力');
$assertContains('setProjectShare()', $projectPage, '项目加载后必须初始化动态分享卡片');
$assertContains('不携带客户群编号', $projectPage, '公开分享链接不得泄露客户群编号和办理步骤');

echo "project center workflow contract smoke passed\n";
