<?php
declare(strict_types=1);

return [
    'HSX_PROJECT_CENTER_COMPONENT' => [
        'title' => '项目中心组件',
        'list' => [
            'ProjectCenterCollapse' => [
                'title' => '项目折叠内容',
                'icon' => 'iconfont iconbiaotipc',
                'path' => 'edit-project-center-collapse',
                // 留空后普通微页面和万能表单装修页都可以使用。
                'support_page' => [],
                'uses' => 1,
                'sort' => 10200,
                'value' => [
                    'title' => '项目说明',
                    'subtitle' => '点击标题查看详细内容',
                    'accordion' => 1,
                    'items' => [
                        [
                            'id' => 'project_intro',
                            'title' => '项目介绍',
                            'summary' => '了解项目内容、参与条件与服务范围',
                            'content' => '请在这里填写项目的详细介绍。',
                            'defaultOpen' => 1,
                        ],
                        [
                            'id' => 'project_process',
                            'title' => '办理流程',
                            'summary' => '付款、资料提交、审核与后续安排',
                            'content' => '请在这里填写项目的办理流程。',
                            'defaultOpen' => 0,
                        ],
                    ],
                    'panelColor' => '#FFFFFF',
                    'titleColor' => '#26334D',
                    'textColor' => '#667085',
                    'accentColor' => '#315CF5',
                ],
                'template' => [
                    'pageStartBgColor' => '',
                    'pageEndBgColor' => '',
                    'pageGradientAngle' => 'to bottom',
                    'componentStartBgColor' => '',
                    'componentEndBgColor' => '',
                    'componentGradientAngle' => 'to bottom',
                    'componentBgUrl' => '',
                    'componentBgAlpha' => 0,
                    'topRounded' => 12,
                    'bottomRounded' => 12,
                    'margin' => [
                        'top' => 10,
                        'bottom' => 10,
                        'both' => 12,
                    ],
                ],
            ],
            'ProjectCenterReferenceGallery' => [
                'title' => '资料参考图片',
                'icon' => 'iconfont icontupian1',
                'path' => 'edit-project-center-reference-gallery',
                'support_page' => [],
                'uses' => 1,
                'sort' => 10201,
                'value' => [
                    'title' => '资料拍摄参考',
                    'subtitle' => '点击图片可查看大图，请按正确示例拍摄',
                    'columns' => 2,
                    'imageMode' => 'aspectFill',
                    'items' => [
                        [
                            'id' => 'reference_1',
                            'title' => '正确示例',
                            'description' => '画面清晰、边缘完整、文字可辨认',
                            'imageUrl' => '',
                            'type' => 'correct',
                        ],
                    ],
                    'panelColor' => '#FFFFFF',
                    'titleColor' => '#26334D',
                    'textColor' => '#667085',
                    'accentColor' => '#12B76A',
                ],
                'template' => [
                    'pageStartBgColor' => '',
                    'pageEndBgColor' => '',
                    'pageGradientAngle' => 'to bottom',
                    'componentStartBgColor' => '',
                    'componentEndBgColor' => '',
                    'componentGradientAngle' => 'to bottom',
                    'componentBgUrl' => '',
                    'componentBgAlpha' => 0,
                    'topRounded' => 12,
                    'bottomRounded' => 12,
                    'margin' => [
                        'top' => 10,
                        'bottom' => 10,
                        'both' => 12,
                    ],
                ],
            ],
            'ProjectCenterIncomeBoard' => [
                'title' => '项目收益榜单',
                'icon' => 'iconfont iconshujutongji',
                'path' => 'edit-project-center-income-board',
                'support_page' => [],
                'uses' => 1,
                'sort' => 10202,
                'value' => [
                    'title' => '门店收益榜',
                    'subtitle' => '每日运营数据，持续更新',
                    'badgeText' => '每日更新',
                    'visibleRows' => 3,
                    'autoplay' => 1,
                    'interval' => 2600,
                    'manualSwipe' => 0,
                    'showDate' => 1,
                    'showDisclaimer' => 1,
                    'disclaimer' => '展示数据由运营录入，仅作项目案例展示，不构成收益承诺',
                    'panelColor' => '#FFFFFF',
                    'titleColor' => '#26334D',
                    'textColor' => '#667085',
                    'accentColor' => '#315CF5',
                    'amountColor' => '#F04438',
                    'previewItems' => [
                        ['rank_no' => 1, 'store_name' => '宇通配件（城隍庙商城店）', 'income_amount' => '915.17'],
                        ['rank_no' => 2, 'store_name' => '志辉数码商城（环城西路店）', 'income_amount' => '526.01'],
                        ['rank_no' => 3, 'store_name' => '中国移动5G（黄麓镇新街店）', 'income_amount' => '459.87'],
                        ['rank_no' => 4, 'store_name' => '汇成数码（北滘镇店）', 'income_amount' => '456.21'],
                        ['rank_no' => 5, 'store_name' => '大强通讯（金谷花园店）', 'income_amount' => '454.08'],
                    ],
                ],
                'template' => [
                    'pageStartBgColor' => '',
                    'pageEndBgColor' => '',
                    'pageGradientAngle' => 'to bottom',
                    'componentStartBgColor' => '',
                    'componentEndBgColor' => '',
                    'componentGradientAngle' => 'to bottom',
                    'componentBgUrl' => '',
                    'componentBgAlpha' => 0,
                    'topRounded' => 12,
                    'bottomRounded' => 12,
                    'margin' => [
                        'top' => 10,
                        'bottom' => 10,
                        'both' => 12,
                    ],
                ],
            ],
            'ProjectCenterAreaEligibility' => [
                'title' => '地区参与查询器',
                'icon' => 'iconfont icondizhi',
                'path' => 'edit-project-center-area-eligibility',
                'support_page' => [],
                'uses' => 1,
                'sort' => 10203,
                'value' => [
                    'title' => '查询所在地区是否可参与',
                    'subtitle' => '选择门店所在省、市、区，立即查看参与资格',
                    'fieldLabel' => '门店所在地区',
                    'placeholder' => '请选择省 / 市 / 区',
                    'buttonText' => '立即查询',
                    'showRuleHint' => 1,
                    'ruleHint' => '实际结果以当前项目后台配置的可参与地区为准',
                    'panelColor' => '#FFFFFF',
                    'titleColor' => '#26334D',
                    'textColor' => '#667085',
                    'accentColor' => '#FEE502',
                    'buttonTextColor' => '#181818',
                ],
                'template' => [
                    'pageStartBgColor' => '',
                    'pageEndBgColor' => '',
                    'pageGradientAngle' => 'to bottom',
                    'componentStartBgColor' => '',
                    'componentEndBgColor' => '',
                    'componentGradientAngle' => 'to bottom',
                    'componentBgUrl' => '',
                    'componentBgAlpha' => 0,
                    'topRounded' => 12,
                    'bottomRounded' => 12,
                    'margin' => [
                        'top' => 10,
                        'bottom' => 10,
                        'both' => 12,
                    ],
                ],
            ],
        ],
    ],
];
