<?php

return [
    'RECYCLE_QUOTE_SPIDER_COMPONENT' => [
        'title' => '爬虫报价组件',
        'list' => [
            'RecycleSpiderQuotationList' => [
                'title' => '爬虫报价单',
                'icon' => 'iconfont iconshangpinliebiaopc',
                'path' => 'edit-recycle-spider-quotation-list',
                'support_page' => [],
                'uses' => 0,
                'sort' => 10006,
                'value' => [
                    'title' => '实时报价',
                    'subtitle' => '按数据源同步展示回收报价',
                    'showHeader' => true,
                    'actionText' => '查看',
                    'sourceId' => 0,
                    'limit' => 6,
                    'onlyHot' => false,
                    'showCategoryTabs' => true,
                    'categoryDefaultMode' => 'first',
                    'tabStyleType' => 'pill',
                    'showTabScrollCue' => true,
                    'stickyTabs' => false,
                    'stickyTabsOffsetMode' => 'auto',
                    'stickyTabsOffset' => 0,
                    'tabThemeColor' => '#2563EB',
                    'tabActiveBgColor' => '',
                    'tabInactiveBgColor' => '',
                    'tabActiveTextColor' => '',
                    'tabInactiveTextColor' => '#475569',
                    'tabHeight' => 64,
                    'tabRadius' => 32,
                    'tabFontSize' => 26,
                    'tabFontWeight' => 600,
                    'tabSidePadding' => 18,
                    'secondaryTabCustom' => false,
                    'secondaryTabStyleType' => 'pill',
                    'secondaryTabThemeColor' => '#2563EB',
                    'secondaryTabActiveBgColor' => '',
                    'secondaryTabInactiveBgColor' => '',
                    'secondaryTabActiveTextColor' => '',
                    'secondaryTabInactiveTextColor' => '#475569',
                    'secondaryTabHeight' => 64,
                    'secondaryTabRadius' => 32,
                    'secondaryTabFontSize' => 26,
                    'secondaryTabFontWeight' => 600,
                    'secondaryTabSidePadding' => 18,
                    'flatGroupMode' => 'level2',
                    'showGroupCount' => true,
                    'showRefresh' => true,
                    'displayStyle' => 'list',
                    'navRowCount' => 4,
                    'navImageSize' => 40,
                    'navAroundRadius' => 20,
                    'componentStartBgColor' => '',
                    'componentEndBgColor' => '',
                    'componentGradientAngle' => 'to bottom',
                    'componentBgUrl' => '',
                    'componentBgAlpha' => 0,
                    'topRounded' => 0,
                    'bottomRounded' => 0,
                    'titleColor' => '#111827',
                    'subtitleColor' => '#6B7280',
                    'buttonColor' => '#2563EB',
                    'showGroupTitle' => true,
                    'groupTitleColor' => '#111827',
                    'groupTitleBgColor' => 'transparent',
                    'groupCountColor' => '#94A3B8',
                    'groupTitleSize' => 22,
                    'groupTitleWeight' => 500,
                    'groupTitleAlign' => 'left',
                    'groupTitleRadius' => 0,
                    'groupTitlePaddingX' => 0,
                    'groupTitlePaddingY' => 0,
                    'showHotBadge' => true,
                    'hotBadgeImage' => '',
                    'hotBadgeSize' => 38,
                    'itemTitleColor' => '#111827',
                    'itemTitleSize' => 28,
                    'itemMetaColor' => '#6B7280',
                    'itemImageRadius' => 20,
                    'margin' => [
                        'top' => 10,
                        'bottom' => 10,
                        'both' => 12,
                    ],
                ],
            ],
        ],
    ],
];
