<?php
return [
    [
        'menu_name' => '营销中心',
        'menu_key' => 'hsx_marketing',
        'menu_short_name' => '营销中心',
        'parent_select_key' => '',
        'parent_key' => '',
        'menu_type' => '0',
        'icon' => 'nc-iconfont nc-icon-yingxiao',
        'api_url' => '',
        'router_path' => '',
        'view_path' => '',
        'methods' => '',
        'sort' => '170',
        'status' => '1',
        'is_show' => '1',
        'children' => [
            [
                'menu_name' => '任务活动',
                'menu_key' => 'hsx_marketing_campaign',
                'menu_short_name' => '任务活动',
                'parent_select_key' => '',
                'menu_type' => '1',
                'icon' => '',
                'api_url' => 'marketing/campaigns',
                'router_path' => 'hsx_marketing/campaign',
                'view_path' => 'campaign/index',
                'methods' => 'get',
                'sort' => '100',
                'status' => '1',
                'is_show' => '1',
                'children' => [
                    [
                        'menu_name' => '活动详情',
                        'menu_key' => 'hsx_marketing_campaign_info',
                        'menu_short_name' => '活动详情',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'marketing/campaigns/<id>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'get',
                        'sort' => '100',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '活动配置元数据',
                        'menu_key' => 'hsx_marketing_campaign_metadata',
                        'menu_short_name' => '配置元数据',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'marketing/campaigns/metadata',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'get',
                        'sort' => '95',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '奖励选项',
                        'menu_key' => 'hsx_marketing_campaign_provider_options',
                        'menu_short_name' => '奖励选项',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'marketing/campaigns/provider-options',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'get',
                        'sort' => '90',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '新增活动',
                        'menu_key' => 'hsx_marketing_campaign_add',
                        'menu_short_name' => '新增活动',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'marketing/campaigns',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '80',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '编辑活动',
                        'menu_key' => 'hsx_marketing_campaign_edit',
                        'menu_short_name' => '编辑活动',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'marketing/campaigns/<id>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'put',
                        'sort' => '70',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '活动状态',
                        'menu_key' => 'hsx_marketing_campaign_status',
                        'menu_short_name' => '活动状态',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'marketing/campaigns/<id>/status',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'put',
                        'sort' => '60',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '删除活动',
                        'menu_key' => 'hsx_marketing_campaign_delete',
                        'menu_short_name' => '删除活动',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'marketing/campaigns/<id>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'delete',
                        'sort' => '50',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                ],
            ],
            [
                'menu_name' => '奖励台账',
                'menu_key' => 'hsx_marketing_reward',
                'menu_short_name' => '奖励台账',
                'parent_select_key' => '',
                'menu_type' => '1',
                'icon' => '',
                'api_url' => 'marketing/rewards',
                'router_path' => 'hsx_marketing/reward',
                'view_path' => 'reward/index',
                'methods' => 'get',
                'sort' => '90',
                'status' => '1',
                'is_show' => '1',
                'children' => [
                    [
                        'menu_name' => '重试奖励',
                        'menu_key' => 'hsx_marketing_reward_retry',
                        'menu_short_name' => '重试奖励',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'marketing/rewards/<id>/retry',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '100',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                ],
            ],
            [
                'menu_name' => '事实台账',
                'menu_key' => 'hsx_marketing_fact',
                'menu_short_name' => '事实台账',
                'parent_select_key' => '',
                'menu_type' => '1',
                'icon' => '',
                'api_url' => 'marketing/facts',
                'router_path' => 'hsx_marketing/fact',
                'view_path' => 'fact/index',
                'methods' => 'get',
                'sort' => '80',
                'status' => '1',
                'is_show' => '1',
                'children' => [
                    [
                        'menu_name' => '重试事实',
                        'menu_key' => 'hsx_marketing_fact_retry',
                        'menu_short_name' => '重试事实',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'marketing/facts/<id>/retry',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '100',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                ],
            ],
        ],
    ],
];