<?php
return [
    [
        'menu_name' => '企业微信服务商',
        'menu_key' => 'hsx_wecom_provider',
        'menu_short_name' => '企微服务商',
        'parent_key' => 'setting_manage',
        'menu_type' => '1',
        'icon' => 'iconfont iconweixin',
        'api_url' => 'wecom/config',
        'router_path' => 'setting/hsx-wecom/provider',
        'view_path' => 'config/index',
        'methods' => 'get',
        'sort' => '55',
        'status' => '1',
        'is_show' => '1',
        'children' => [
            [
                'menu_name' => '读取服务商配置',
                'menu_key' => 'hsx_wecom_provider_config',
                'menu_short_name' => '读取配置',
                'menu_type' => '2',
                'icon' => '',
                'api_url' => 'wecom/provider/config',
                'router_path' => '',
                'view_path' => '',
                'methods' => 'get',
                'sort' => '100',
                'status' => '1',
                'is_show' => '0',
            ],
            [
                'menu_name' => '保存服务商配置',
                'menu_key' => 'hsx_wecom_provider_config_save',
                'menu_short_name' => '保存配置',
                'menu_type' => '2',
                'icon' => '',
                'api_url' => 'wecom/provider/config',
                'router_path' => '',
                'view_path' => '',
                'methods' => 'post',
                'sort' => '90',
                'status' => '1',
                'is_show' => '0',
            ],
            [
                'menu_name' => '验证服务商通道',
                'menu_key' => 'hsx_wecom_provider_test',
                'menu_short_name' => '验证通道',
                'menu_type' => '2',
                'icon' => '',
                'api_url' => 'wecom/provider/test',
                'router_path' => '',
                'view_path' => '',
                'methods' => 'post',
                'sort' => '80',
                'status' => '1',
                'is_show' => '0',
            ],
        ],
    ],
];
