<?php
return [
    [
        'menu_name' => '企业微信',
        'menu_key' => 'hsx_wecom',
        'menu_short_name' => '企业微信',
        'parent_select_key' => '',
        'parent_key' => '',
        'menu_type' => '0',
        'icon' => 'iconfont iconweixin',
        'api_url' => '',
        'router_path' => '',
        'view_path' => '',
        'methods' => '',
        'sort' => '180',
        'status' => '1',
        'is_show' => '1',
        'children' => [
            [
                'menu_name' => '协同配置',
                'menu_key' => 'hsx_wecom_config',
                'menu_short_name' => '协同配置',
                'parent_select_key' => '',
                'menu_type' => '1',
                'icon' => '',
                'api_url' => 'wecom/config',
                'router_path' => 'hsx_wecom/config',
                'view_path' => 'config/index',
                'methods' => 'get',
                'sort' => '100',
                'status' => '1',
                'is_show' => '1',
                'children' => [
                    [
                        'menu_name' => '保存配置',
                        'menu_key' => 'hsx_wecom_config_save',
                        'menu_short_name' => '保存配置',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'wecom/config',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '100',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '测试连接',
                        'menu_key' => 'hsx_wecom_config_test',
                        'menu_short_name' => '测试连接',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'wecom/config/test',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '90',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '员工绑定',
                        'menu_key' => 'hsx_wecom_staff',
                        'menu_short_name' => '员工绑定',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'wecom/staff',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'get',
                        'sort' => '80',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '保存员工绑定',
                        'menu_key' => 'hsx_wecom_staff_save',
                        'menu_short_name' => '保存员工绑定',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'wecom/staff/<uid>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'put',
                        'sort' => '70',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '消息日志',
                        'menu_key' => 'hsx_wecom_message',
                        'menu_short_name' => '消息日志',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'wecom/messages',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'get',
                        'sort' => '60',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '重试消息',
                        'menu_key' => 'hsx_wecom_message_retry',
                        'menu_short_name' => '重试消息',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'wecom/messages/<id>/retry',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '50',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                ],
            ],
        ],
    ],
];