CREATE TABLE IF NOT EXISTS `{{prefix}}project_center_project` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `site_id` int NOT NULL DEFAULT 0,
  `project_no` varchar(40) NOT NULL DEFAULT '',
  `title` varchar(120) NOT NULL DEFAULT '',
  `subtitle` varchar(255) NOT NULL DEFAULT '',
  `cover` varchar(1000) NOT NULL DEFAULT '',
  `status` tinyint unsigned NOT NULL DEFAULT 0 COMMENT '0草稿1启用2停用',
  `sort` int NOT NULL DEFAULT 0,
  `intro_page_id` int NOT NULL DEFAULT 0 COMMENT '项目介绍DIY页面',
  `form_id` int NOT NULL DEFAULT 0 COMMENT '万能表单ID',
  `payment_qrcode` varchar(1000) NOT NULL DEFAULT '',
  `payment_amount` decimal(12,2) NOT NULL DEFAULT 0.00,
  `payment_tips` varchar(1000) NOT NULL DEFAULT '',
  `reviewer_uids` longtext NULL COMMENT '资料审核员UID列表',
  `reviewer_role_ids` longtext NULL COMMENT '资料审核角色列表',
  `ai_enabled` tinyint unsigned NOT NULL DEFAULT 0,
  `ai_scene` varchar(80) NOT NULL DEFAULT '',
  `distribution_enabled` tinyint unsigned NOT NULL DEFAULT 0,
  `config_json` longtext NULL,
  `create_at` int NOT NULL DEFAULT 0,
  `update_at` int NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_site_project_no` (`site_id`,`project_no`),
  KEY `idx_site_status_sort` (`site_id`,`status`,`sort`,`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='项目合作中心-项目';

CREATE TABLE IF NOT EXISTS `{{prefix}}project_center_daily_sequence` (
  `site_id` int NOT NULL DEFAULT 0,
  `project_id` bigint unsigned NOT NULL DEFAULT 0 COMMENT 'V1固定为0，群编号按站点全局日序列生成',
  `stat_date` int NOT NULL DEFAULT 0 COMMENT 'Ymd整数',
  `current_seq` int unsigned NOT NULL DEFAULT 0,
  `update_at` int NOT NULL DEFAULT 0,
  PRIMARY KEY (`site_id`,`project_id`,`stat_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='项目合作中心-每日群编号序列';

CREATE TABLE IF NOT EXISTS `{{prefix}}project_center_group` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `site_id` int NOT NULL DEFAULT 0,
  `project_id` bigint unsigned NOT NULL DEFAULT 0,
  `group_no` varchar(20) NOT NULL DEFAULT '' COMMENT '对外编号，如0819-1',
  `group_no_full` varchar(40) NOT NULL DEFAULT '' COMMENT '跨年唯一编号，如20260819-1',
  `member_id` int NOT NULL DEFAULT 0,
  `member_name` varchar(100) NOT NULL DEFAULT '',
  `member_mobile` varchar(30) NOT NULL DEFAULT '',
  `store_name` varchar(150) NOT NULL DEFAULT '',
  `wecom_chat_id` varchar(120) NOT NULL DEFAULT '',
  `wecom_external_userid` varchar(120) NOT NULL DEFAULT '',
  `owner_uid` int NOT NULL DEFAULT 0,
  `collaborator_uids` longtext NULL,
  `create_mode` varchar(20) NOT NULL DEFAULT 'manual' COMMENT 'manual/wecom',
  `status` varchar(24) NOT NULL DEFAULT 'reserved' COMMENT 'reserved/created/active/completed/create_failed/refund_pending/refunded/abandoned/dissolved',
  `error_message` varchar(500) NOT NULL DEFAULT '',
  `created_at` int NOT NULL DEFAULT 0,
  `completed_at` int NOT NULL DEFAULT 0,
  `dissolved_at` int NOT NULL DEFAULT 0,
  `create_at` int NOT NULL DEFAULT 0,
  `update_at` int NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_site_group_no` (`site_id`,`group_no_full`),
  KEY `idx_project_status` (`site_id`,`project_id`,`status`,`id`),
  KEY `idx_member` (`site_id`,`member_id`,`id`),
  KEY `idx_mobile` (`site_id`,`member_mobile`,`id`),
  KEY `idx_wecom_chat` (`site_id`,`wecom_chat_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='项目合作中心-客户群绑定';

CREATE TABLE IF NOT EXISTS `{{prefix}}project_center_group_no_alias` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `site_id` int NOT NULL DEFAULT 0,
  `project_id` bigint unsigned NOT NULL DEFAULT 0,
  `group_id` bigint unsigned NOT NULL DEFAULT 0,
  `old_group_no` varchar(20) NOT NULL DEFAULT '' COMMENT '历史展示编号',
  `old_group_no_full` varchar(40) NOT NULL DEFAULT '' COMMENT '历史跨年编号',
  `new_group_no` varchar(20) NOT NULL DEFAULT '' COMMENT '首次更正后的展示编号',
  `new_group_no_full` varchar(40) NOT NULL DEFAULT '' COMMENT '首次更正后的跨年编号',
  `reason` varchar(500) NOT NULL DEFAULT '',
  `source` varchar(24) NOT NULL DEFAULT 'group_ledger' COMMENT 'group_ledger/application',
  `application_id` bigint unsigned NOT NULL DEFAULT 0,
  `operator_id` int NOT NULL DEFAULT 0,
  `operator_name` varchar(100) NOT NULL DEFAULT '',
  `create_at` int NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_site_old_group_no` (`site_id`,`old_group_no_full`),
  KEY `idx_group` (`site_id`,`group_id`,`id`),
  KEY `idx_project` (`site_id`,`project_id`,`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='项目合作中心-客户群历史编号别名';

CREATE TABLE IF NOT EXISTS `{{prefix}}project_center_group_no_change_log` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `site_id` int NOT NULL DEFAULT 0,
  `project_id` bigint unsigned NOT NULL DEFAULT 0,
  `group_id` bigint unsigned NOT NULL DEFAULT 0,
  `old_group_no` varchar(20) NOT NULL DEFAULT '',
  `old_group_no_full` varchar(40) NOT NULL DEFAULT '',
  `new_group_no` varchar(20) NOT NULL DEFAULT '',
  `new_group_no_full` varchar(40) NOT NULL DEFAULT '',
  `reason` varchar(500) NOT NULL DEFAULT '',
  `source` varchar(24) NOT NULL DEFAULT 'group_ledger' COMMENT 'group_ledger/application',
  `application_id` bigint unsigned NOT NULL DEFAULT 0,
  `operator_id` int NOT NULL DEFAULT 0,
  `operator_name` varchar(100) NOT NULL DEFAULT '',
  `create_at` int NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_group_time` (`site_id`,`group_id`,`id`),
  KEY `idx_application` (`site_id`,`application_id`,`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='项目合作中心-客户群编号更正日志';

CREATE TABLE IF NOT EXISTS `{{prefix}}project_center_application` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `site_id` int NOT NULL DEFAULT 0,
  `application_no` varchar(40) NOT NULL DEFAULT '',
  `project_id` bigint unsigned NOT NULL DEFAULT 0,
  `group_id` bigint unsigned NOT NULL DEFAULT 0,
  `member_id` int NOT NULL DEFAULT 0,
  `idempotency_key` varchar(160) NULL DEFAULT NULL COMMENT '工单业务幂等键',
  `form_id` int NOT NULL DEFAULT 0,
  `form_record_id` int NOT NULL DEFAULT 0,
  `submit_version` int unsigned NOT NULL DEFAULT 1,
  `status` varchar(24) NOT NULL DEFAULT 'submitted' COMMENT 'draft/submitted/reviewing/rejected/approved/refund_pending/refunded/abandoned',
  `assignee_uid` int NOT NULL DEFAULT 0,
  `assignee_name` varchar(100) NOT NULL DEFAULT '',
  `payment_declared_at` int NOT NULL DEFAULT 0 COMMENT '客户声明已付款，不代表财务确认',
  `payment_confirmed_at` int NOT NULL DEFAULT 0 COMMENT '审核员核对群内流水时间',
  `payment_confirmed_uid` int NOT NULL DEFAULT 0 COMMENT '核对流水的管理员',
  `payment_confirmed_name` varchar(100) NOT NULL DEFAULT '' COMMENT '核对流水的管理员名称',
  `eligibility_snapshot` longtext NULL COMMENT '付款前地区参与资格查询快照',
  `last_reject_summary` varchar(1000) NOT NULL DEFAULT '',
  `submitted_at` int NOT NULL DEFAULT 0,
  `reviewed_at` int NOT NULL DEFAULT 0,
  `approved_at` int NOT NULL DEFAULT 0,
  `create_at` int NOT NULL DEFAULT 0,
  `update_at` int NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_site_application_no` (`site_id`,`application_no`),
  UNIQUE KEY `uk_site_idempotency` (`site_id`,`idempotency_key`),
  KEY `idx_project_status` (`site_id`,`project_id`,`status`,`update_at`),
  KEY `idx_group` (`site_id`,`group_id`,`id`),
  KEY `idx_member` (`site_id`,`member_id`,`id`),
  KEY `idx_assignee` (`site_id`,`assignee_uid`,`status`,`update_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='项目合作中心-资料工单';

CREATE TABLE IF NOT EXISTS `{{prefix}}project_center_refund` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `site_id` int NOT NULL DEFAULT 0,
  `refund_no` varchar(40) NOT NULL DEFAULT '',
  `project_id` bigint unsigned NOT NULL DEFAULT 0,
  `group_id` bigint unsigned NOT NULL DEFAULT 0,
  `application_id` bigint unsigned NOT NULL DEFAULT 0,
  `member_id` int NOT NULL DEFAULT 0,
  `amount` decimal(12,2) NOT NULL DEFAULT 0.00,
  `status` varchar(24) NOT NULL DEFAULT 'pending' COMMENT 'pending/refunded/cancelled',
  `origin_group_status` varchar(24) NOT NULL DEFAULT '',
  `origin_application_status` varchar(24) NOT NULL DEFAULT '',
  `reason` varchar(1000) NOT NULL DEFAULT '',
  `proof` varchar(1000) NOT NULL DEFAULT '' COMMENT '退款凭证图片或文件地址',
  `remark` varchar(1000) NOT NULL DEFAULT '',
  `requested_at` int NOT NULL DEFAULT 0,
  `refunded_at` int NOT NULL DEFAULT 0,
  `cancelled_at` int NOT NULL DEFAULT 0,
  `request_operator_id` int NOT NULL DEFAULT 0,
  `request_operator_name` varchar(100) NOT NULL DEFAULT '',
  `complete_operator_id` int NOT NULL DEFAULT 0,
  `complete_operator_name` varchar(100) NOT NULL DEFAULT '',
  `create_at` int NOT NULL DEFAULT 0,
  `update_at` int NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_site_refund_no` (`site_id`,`refund_no`),
  UNIQUE KEY `uk_site_group` (`site_id`,`group_id`),
  KEY `idx_status_time` (`site_id`,`status`,`requested_at`),
  KEY `idx_application` (`site_id`,`application_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='项目合作中心-退款闭环台账';

CREATE TABLE IF NOT EXISTS `{{prefix}}project_center_review_log` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `site_id` int NOT NULL DEFAULT 0,
  `application_id` bigint unsigned NOT NULL DEFAULT 0,
  `submit_version` int unsigned NOT NULL DEFAULT 1,
  `action` varchar(24) NOT NULL DEFAULT '' COMMENT 'submit/reviewing/approve/reject/resubmit/abandon/refund_request/refund_complete/refund_cancel/correct_group_no',
  `from_status` varchar(24) NOT NULL DEFAULT '',
  `to_status` varchar(24) NOT NULL DEFAULT '',
  `field_issues_json` longtext NULL COMMENT '逐字段问题列表',
  `form_snapshot_json` longtext NULL COMMENT '提交时表单快照',
  `remark` varchar(1000) NOT NULL DEFAULT '',
  `operator_type` varchar(20) NOT NULL DEFAULT 'admin' COMMENT 'member/admin/system',
  `operator_id` int NOT NULL DEFAULT 0,
  `operator_name` varchar(100) NOT NULL DEFAULT '',
  `create_at` int NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_application` (`site_id`,`application_id`,`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='项目合作中心-审核日志';

CREATE TABLE IF NOT EXISTS `{{prefix}}project_center_income_board` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `site_id` int NOT NULL DEFAULT 0,
  `project_id` bigint unsigned NOT NULL DEFAULT 0,
  `stat_date` int NOT NULL DEFAULT 0 COMMENT 'Ymd整数',
  `rank_no` int unsigned NOT NULL DEFAULT 0,
  `store_name` varchar(150) NOT NULL DEFAULT '',
  `income_amount` decimal(12,2) NOT NULL DEFAULT 0.00,
  `source_text` varchar(500) NOT NULL DEFAULT '',
  `sort` int NOT NULL DEFAULT 0,
  `status` tinyint unsigned NOT NULL DEFAULT 1,
  `create_at` int NOT NULL DEFAULT 0,
  `update_at` int NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_project_date_rank` (`site_id`,`project_id`,`stat_date`,`rank_no`),
  KEY `idx_project_date` (`site_id`,`project_id`,`stat_date`,`status`,`sort`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='项目合作中心-外部收益展示';

CREATE TABLE IF NOT EXISTS `{{prefix}}project_center_invite` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `site_id` int NOT NULL DEFAULT 0,
  `project_id` bigint unsigned NOT NULL DEFAULT 0,
  `inviter_member_id` int NOT NULL DEFAULT 0,
  `token` varchar(64) NOT NULL DEFAULT '',
  `status` tinyint unsigned NOT NULL DEFAULT 1,
  `use_count` int unsigned NOT NULL DEFAULT 0,
  `last_used_at` int NOT NULL DEFAULT 0,
  `create_at` int NOT NULL DEFAULT 0,
  `update_at` int NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_site_project_inviter` (`site_id`,`project_id`,`inviter_member_id`),
  UNIQUE KEY `uk_site_token` (`site_id`,`token`),
  KEY `idx_project_status` (`site_id`,`project_id`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='项目合作中心-分销邀请凭证';

CREATE TABLE IF NOT EXISTS `{{prefix}}project_center_relation_log` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `site_id` int NOT NULL DEFAULT 0,
  `project_id` bigint unsigned NOT NULL DEFAULT 0,
  `member_id` int NOT NULL DEFAULT 0,
  `inviter_member_id` int NOT NULL DEFAULT 0,
  `invite_id` bigint unsigned NOT NULL DEFAULT 0,
  `action` varchar(24) NOT NULL DEFAULT 'bind' COMMENT 'bind/keep/reject/admin_correct',
  `source` varchar(24) NOT NULL DEFAULT 'project_share',
  `remark` varchar(500) NOT NULL DEFAULT '',
  `operator_type` varchar(20) NOT NULL DEFAULT 'member',
  `operator_id` int NOT NULL DEFAULT 0,
  `operator_name` varchar(100) NOT NULL DEFAULT '',
  `create_at` int NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_member_time` (`site_id`,`member_id`,`id`),
  KEY `idx_inviter_time` (`site_id`,`inviter_member_id`,`id`),
  KEY `idx_project` (`site_id`,`project_id`,`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='项目合作中心-推荐关系审计日志';

CREATE TABLE IF NOT EXISTS `{{prefix}}project_center_distribution_order` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `site_id` int NOT NULL DEFAULT 0,
  `order_no` varchar(40) NOT NULL DEFAULT '',
  `project_id` bigint unsigned NOT NULL DEFAULT 0,
  `application_id` bigint unsigned NOT NULL DEFAULT 0,
  `buyer_member_id` int NOT NULL DEFAULT 0,
  `base_amount` decimal(12,2) NOT NULL DEFAULT 0.00,
  `rule_snapshot` longtext NULL COMMENT '项目规则和计算结果快照',
  `status` varchar(24) NOT NULL DEFAULT 'pending' COMMENT 'pending/frozen/settled/cancelled/partial_reversed/reversed/exception',
  `settle_at` int NOT NULL DEFAULT 0,
  `settled_at` int NOT NULL DEFAULT 0,
  `frozen_at` int NOT NULL DEFAULT 0,
  `cancelled_at` int NOT NULL DEFAULT 0,
  `refund_amount` decimal(12,2) NOT NULL DEFAULT 0.00,
  `error_message` varchar(1000) NOT NULL DEFAULT '',
  `create_at` int NOT NULL DEFAULT 0,
  `update_at` int NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_site_application` (`site_id`,`application_id`),
  UNIQUE KEY `uk_site_order_no` (`site_id`,`order_no`),
  KEY `idx_settle` (`site_id`,`status`,`settle_at`),
  KEY `idx_project` (`site_id`,`project_id`,`id`),
  KEY `idx_buyer` (`site_id`,`buyer_member_id`,`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='项目合作中心-分销业务佣金单';

CREATE TABLE IF NOT EXISTS `{{prefix}}project_center_distribution_detail` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `site_id` int NOT NULL DEFAULT 0,
  `order_id` bigint unsigned NOT NULL DEFAULT 0,
  `application_id` bigint unsigned NOT NULL DEFAULT 0,
  `project_id` bigint unsigned NOT NULL DEFAULT 0,
  `beneficiary_member_id` int NOT NULL DEFAULT 0,
  `relation_level` tinyint unsigned NOT NULL DEFAULT 1 COMMENT '1一级/2二级',
  `beneficiary_level_id` int NOT NULL DEFAULT 0,
  `beneficiary_level_name` varchar(100) NOT NULL DEFAULT '',
  `level_snapshot` longtext NULL COMMENT '会员等级权益快照',
  `base_commission` decimal(12,2) NOT NULL DEFAULT 0.00,
  `coefficient` decimal(8,2) NOT NULL DEFAULT 100.00,
  `commission_amount` decimal(12,2) NOT NULL DEFAULT 0.00,
  `debt_offset_amount` decimal(12,2) NOT NULL DEFAULT 0.00,
  `settled_amount` decimal(12,2) NOT NULL DEFAULT 0.00,
  `reversed_amount` decimal(12,2) NOT NULL DEFAULT 0.00,
  `debt_amount` decimal(12,2) NOT NULL DEFAULT 0.00,
  `status` varchar(24) NOT NULL DEFAULT 'pending' COMMENT 'pending/frozen/settled/cancelled/partial_reversed/reversed/exception',
  `account_log_id` bigint unsigned NOT NULL DEFAULT 0,
  `reverse_log_id` bigint unsigned NOT NULL DEFAULT 0,
  `settle_at` int NOT NULL DEFAULT 0,
  `settled_at` int NOT NULL DEFAULT 0,
  `create_at` int NOT NULL DEFAULT 0,
  `update_at` int NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_order_relation_level` (`order_id`,`relation_level`),
  KEY `idx_member_status` (`site_id`,`beneficiary_member_id`,`status`,`settle_at`),
  KEY `idx_application` (`site_id`,`application_id`,`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='项目合作中心-一级二级佣金明细';

CREATE TABLE IF NOT EXISTS `{{prefix}}project_center_distribution_debt` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `site_id` int NOT NULL DEFAULT 0,
  `member_id` int NOT NULL DEFAULT 0,
  `detail_id` bigint unsigned NOT NULL DEFAULT 0,
  `amount` decimal(12,2) NOT NULL DEFAULT 0.00,
  `offset_amount` decimal(12,2) NOT NULL DEFAULT 0.00,
  `status` varchar(20) NOT NULL DEFAULT 'pending' COMMENT 'pending/settled',
  `reason` varchar(500) NOT NULL DEFAULT '',
  `create_at` int NOT NULL DEFAULT 0,
  `update_at` int NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_detail` (`detail_id`),
  KEY `idx_member_status` (`site_id`,`member_id`,`status`,`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='项目合作中心-退款佣金欠款';
