CREATE TABLE IF NOT EXISTS `{{prefix}}performance_report` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `site_id` int NOT NULL DEFAULT 0 COMMENT '站点ID',
  `report_no` varchar(40) NOT NULL DEFAULT '' COMMENT '报告编号',
  `report_type` varchar(20) NOT NULL DEFAULT 'daily' COMMENT 'daily/weekly/monthly/custom',
  `period_key` varchar(40) NOT NULL DEFAULT '' COMMENT '周期稳定键',
  `title` varchar(120) NOT NULL DEFAULT '' COMMENT '报告标题',
  `start_at` int NOT NULL DEFAULT 0,
  `end_at` int NOT NULL DEFAULT 0,
  `summary_json` longtext NULL COMMENT '核心指标快照',
  `providers_json` longtext NULL COMMENT '各插件采集结果',
  `snapshot_json` longtext NULL COMMENT '完整报告快照',
  `notify_status` varchar(20) NOT NULL DEFAULT 'pending' COMMENT 'pending/success/failed/skipped',
  `notify_attempts` int NOT NULL DEFAULT 0,
  `notify_error` varchar(500) NOT NULL DEFAULT '',
  `notified_at` int NOT NULL DEFAULT 0,
  `generated_at` int NOT NULL DEFAULT 0,
  `create_at` int NOT NULL DEFAULT 0,
  `update_at` int NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_site_period` (`site_id`,`report_type`,`period_key`),
  UNIQUE KEY `uk_site_no` (`site_id`,`report_no`),
  KEY `idx_notify` (`notify_status`,`update_at`),
  KEY `idx_site_time` (`site_id`,`generated_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='绩效经营报告快照与通知发件箱';

CREATE TABLE IF NOT EXISTS `{{prefix}}performance_fact` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `site_id` int NOT NULL DEFAULT 0,
  `event_id` varchar(100) NOT NULL DEFAULT '' COMMENT '跨插件幂等ID',
  `event_name` varchar(80) NOT NULL DEFAULT 'performance.fact.recorded.v1' COMMENT '契约事件名称',
  `event_version` smallint unsigned NOT NULL DEFAULT 1 COMMENT '契约版本',
  `payload_hash` char(64) NOT NULL DEFAULT '' COMMENT '规范化载荷SHA256',
  `source_plugin` varchar(50) NOT NULL DEFAULT '',
  `business_chain` varchar(40) NOT NULL DEFAULT '',
  `action_key` varchar(80) NOT NULL DEFAULT '',
  `metric_name` varchar(80) NOT NULL DEFAULT '' COMMENT '指标名称快照',
  `fact_scope` varchar(20) NOT NULL DEFAULT 'action' COMMENT 'action/outcome/quality',
  `fact_type` varchar(20) NOT NULL DEFAULT 'original' COMMENT 'original/reversal',
  `direction` tinyint NOT NULL DEFAULT 1 COMMENT '1正向/-1冲红',
  `reversal_of_event_id` varchar(100) NOT NULL DEFAULT '' COMMENT '被冲红事件ID',
  `employee_uid` int NOT NULL DEFAULT 0,
  `employee_name` varchar(60) NOT NULL DEFAULT '',
  `role_key` varchar(50) NOT NULL DEFAULT '',
  `business_type` varchar(50) NOT NULL DEFAULT '',
  `business_id` varchar(80) NOT NULL DEFAULT '',
  `business_no` varchar(80) NOT NULL DEFAULT '',
  `asset_id` int NOT NULL DEFAULT 0,
  `imei` varchar(64) NOT NULL DEFAULT '',
  `quantity` decimal(12,2) NOT NULL DEFAULT 0.00,
  `amount` decimal(14,2) NOT NULL DEFAULT 0.00,
  `profit` decimal(14,2) NOT NULL DEFAULT 0.00,
  `duration_seconds` int NOT NULL DEFAULT 0 COMMENT '处理时长，冲红为负数',
  `quality_score` decimal(12,4) NOT NULL DEFAULT 0.0000 COMMENT '质量分值',
  `unit` varchar(20) NOT NULL DEFAULT 'item' COMMENT '计量单位',
  `dimensions_json` longtext NULL COMMENT '筛选维度快照',
  `source_route_json` longtext NULL COMMENT '业务追溯入口',
  `payload_json` longtext NULL,
  `business_date` varchar(10) NOT NULL DEFAULT '' COMMENT '业务日期YYYY-MM-DD',
  `occurred_at` int NOT NULL DEFAULT 0,
  `received_at` int NOT NULL DEFAULT 0,
  `create_at` int NOT NULL DEFAULT 0,
  `update_at` int NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_site_event` (`site_id`,`event_id`),
  KEY `idx_site_employee` (`site_id`,`employee_uid`,`occurred_at`),
  KEY `idx_site_action` (`site_id`,`action_key`,`occurred_at`),
  KEY `idx_site_business` (`site_id`,`source_plugin`,`business_type`,`business_id`),
  KEY `idx_site_date_metric` (`site_id`,`business_date`,`action_key`,`fact_scope`),
  KEY `idx_site_reversal` (`site_id`,`reversal_of_event_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='跨插件员工工作事实账本（预留薪酬规则）';

CREATE TABLE IF NOT EXISTS `{{prefix}}performance_metric` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `site_id` int NOT NULL DEFAULT 0,
  `source_plugin` varchar(50) NOT NULL DEFAULT '',
  `business_chain` varchar(40) NOT NULL DEFAULT '',
  `metric_key` varchar(80) NOT NULL DEFAULT '',
  `metric_name` varchar(80) NOT NULL DEFAULT '',
  `fact_scope` varchar(20) NOT NULL DEFAULT 'action',
  `unit` varchar(20) NOT NULL DEFAULT 'item',
  `description` varchar(255) NOT NULL DEFAULT '',
  `status` tinyint unsigned NOT NULL DEFAULT 1,
  `sort` int NOT NULL DEFAULT 0,
  `create_at` int NOT NULL DEFAULT 0,
  `update_at` int NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_site_metric` (`site_id`,`source_plugin`,`metric_key`),
  KEY `idx_site_chain` (`site_id`,`business_chain`,`status`,`sort`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='员工产出指标目录';

CREATE TABLE IF NOT EXISTS `{{prefix}}performance_employee_daily` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `site_id` int NOT NULL DEFAULT 0,
  `business_date` varchar(10) NOT NULL DEFAULT '',
  `employee_uid` int NOT NULL DEFAULT 0,
  `employee_name` varchar(60) NOT NULL DEFAULT '',
  `source_plugin` varchar(50) NOT NULL DEFAULT '',
  `business_chain` varchar(40) NOT NULL DEFAULT '',
  `metric_key` varchar(80) NOT NULL DEFAULT '',
  `metric_name` varchar(80) NOT NULL DEFAULT '',
  `fact_scope` varchar(20) NOT NULL DEFAULT 'action',
  `role_key` varchar(50) NOT NULL DEFAULT '',
  `unit` varchar(20) NOT NULL DEFAULT 'item',
  `quantity` decimal(18,4) NOT NULL DEFAULT 0.0000,
  `amount` decimal(18,2) NOT NULL DEFAULT 0.00,
  `profit` decimal(18,2) NOT NULL DEFAULT 0.00,
  `duration_seconds` bigint NOT NULL DEFAULT 0,
  `quality_score` decimal(18,4) NOT NULL DEFAULT 0.0000,
  `fact_count` int NOT NULL DEFAULT 0,
  `effective_fact_count` int NOT NULL DEFAULT 0,
  `original_count` int NOT NULL DEFAULT 0,
  `reversal_count` int NOT NULL DEFAULT 0,
  `last_occurred_at` int NOT NULL DEFAULT 0,
  `create_at` int NOT NULL DEFAULT 0,
  `update_at` int NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_daily_metric` (`site_id`,`business_date`,`employee_uid`,`source_plugin`,`metric_key`,`fact_scope`,`role_key`),
  KEY `idx_site_date` (`site_id`,`business_date`,`employee_uid`),
  KEY `idx_site_metric` (`site_id`,`metric_key`,`business_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='员工产出日汇总投影';

CREATE TABLE IF NOT EXISTS `{{prefix}}performance_anomaly` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `site_id` int NOT NULL DEFAULT 0,
  `event_id` varchar(100) NOT NULL DEFAULT '',
  `anomaly_type` varchar(50) NOT NULL DEFAULT '',
  `severity` varchar(20) NOT NULL DEFAULT 'error',
  `message` varchar(500) NOT NULL DEFAULT '',
  `payload_json` longtext NULL,
  `status` varchar(20) NOT NULL DEFAULT 'open' COMMENT 'open/resolved/ignored',
  `occurrence_count` int NOT NULL DEFAULT 1,
  `resolved_at` int NOT NULL DEFAULT 0,
  `create_at` int NOT NULL DEFAULT 0,
  `update_at` int NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_site_status` (`site_id`,`status`,`update_at`),
  KEY `idx_site_event` (`site_id`,`event_id`,`anomaly_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='员工产出数据异常';
