CREATE TABLE IF NOT EXISTS `{{prefix}}performance_report` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `site_id` int NOT NULL DEFAULT 0 COMMENT '站点ID',
  `report_no` varchar(40) NOT NULL DEFAULT '' COMMENT '报告编号',
  `report_type` varchar(20) NOT NULL DEFAULT 'daily' COMMENT 'daily/weekly/monthly/custom',
  `period_key` varchar(40) NOT NULL DEFAULT '' COMMENT '周期稳定键',
  `title` varchar(120) NOT NULL DEFAULT '' COMMENT '报告标题',
  `start_at` int NOT NULL DEFAULT 0,
  `end_at` int NOT NULL DEFAULT 0,
  `summary_json` longtext NULL COMMENT '核心指标快照',
  `providers_json` longtext NULL COMMENT '各插件采集结果',
  `snapshot_json` longtext NULL COMMENT '完整报告快照',
  `notify_status` varchar(20) NOT NULL DEFAULT 'pending' COMMENT 'pending/success/failed/skipped',
  `notify_attempts` int NOT NULL DEFAULT 0,
  `notify_error` varchar(500) NOT NULL DEFAULT '',
  `notified_at` int NOT NULL DEFAULT 0,
  `generated_at` int NOT NULL DEFAULT 0,
  `create_at` int NOT NULL DEFAULT 0,
  `update_at` int NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_site_period` (`site_id`,`report_type`,`period_key`),
  UNIQUE KEY `uk_site_no` (`site_id`,`report_no`),
  KEY `idx_notify` (`notify_status`,`update_at`),
  KEY `idx_site_time` (`site_id`,`generated_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='绩效经营报告快照与通知发件箱';

CREATE TABLE IF NOT EXISTS `{{prefix}}performance_fact` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `site_id` int NOT NULL DEFAULT 0,
  `event_id` varchar(100) NOT NULL DEFAULT '' COMMENT '跨插件幂等ID',
  `source_plugin` varchar(50) NOT NULL DEFAULT '',
  `business_chain` varchar(40) NOT NULL DEFAULT '',
  `action_key` varchar(80) NOT NULL DEFAULT '',
  `employee_uid` int NOT NULL DEFAULT 0,
  `employee_name` varchar(60) NOT NULL DEFAULT '',
  `role_key` varchar(50) NOT NULL DEFAULT '',
  `business_type` varchar(50) NOT NULL DEFAULT '',
  `business_id` varchar(80) NOT NULL DEFAULT '',
  `business_no` varchar(80) NOT NULL DEFAULT '',
  `asset_id` int NOT NULL DEFAULT 0,
  `imei` varchar(64) NOT NULL DEFAULT '',
  `quantity` decimal(12,2) NOT NULL DEFAULT 0.00,
  `amount` decimal(14,2) NOT NULL DEFAULT 0.00,
  `profit` decimal(14,2) NOT NULL DEFAULT 0.00,
  `payload_json` longtext NULL,
  `occurred_at` int NOT NULL DEFAULT 0,
  `create_at` int NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_site_event` (`site_id`,`event_id`),
  KEY `idx_site_employee` (`site_id`,`employee_uid`,`occurred_at`),
  KEY `idx_site_action` (`site_id`,`action_key`,`occurred_at`),
  KEY `idx_site_business` (`site_id`,`source_plugin`,`business_type`,`business_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='跨插件员工工作事实账本（预留薪酬规则）';
