<?php
return [
    [
        'menu_name' => 'AI设计',
        'menu_key' => 'ai_image',
        'menu_short_name' => '设计',
        'parent_key' => '',
        'menu_type' => '0',
        'icon' => 'nc-iconfont nc-icon-daifahuoV6xx-1',
        'api_url' => '',
        'router_path' => '',
        'view_path' => '',
        'methods' => '',
        'sort' => '100',
        'status' => '1',
        'is_show' => '1',
        'children' => [
            [
                'menu_name' => '基础设置',
                'menu_key' => 'ai_image_hello_world',
                'menu_short_name' => '设置',
                'menu_type' => '1',
                'icon' => 'nc-iconfont nc-icon-shezhiV6xx1',
                'api_url' => '',
                'router_path' => 'ai_image/config',
                'view_path' => 'config/index',
                'methods' => 'get',
                'sort' => '100',
                'status' => '1',
                'is_show' => '1',
            ],
            [
                'menu_name' => '智能体',
                'menu_key' => 'ai_image_aiimage_model_aiimagemodel_aiimageModel',
                'menu_short_name' => '智能体',
                'menu_type' => '0',
                'icon' => '',
                'api_url' => '',
                'router_path' => 'aiimagemodel',
                'view_path' => '',
                'methods' => '',
                'sort' => '100',
                'status' => '1',
                'is_show' => '0',
                'children' => [
                    [
                        'menu_name' => '智能体添加',
                        'menu_key' => 'ai_image_aiimage_model_aiimagemodel_aiimageModel_add',
                        'menu_short_name' => '智能体添加',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'ai_image/aiimagemodel',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '70',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '智能体编辑',
                        'menu_key' => 'ai_image_aiimage_model_aiimagemodel_aiimageModel_edit',
                        'menu_short_name' => '智能体编辑',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'ai_image/aiimagemodel/<id>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'put',
                        'sort' => '60',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '智能体删除',
                        'menu_key' => 'ai_image_aiimage_model_aiimagemodel_aiimageModel_delete',
                        'menu_short_name' => '智能体删除',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'ai_image/aiimagemodel/<id>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'delete',
                        'sort' => '50',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                ],
            ],
            [
                'menu_name' => '卡密兑换',
                'menu_key' => 'ai_image_aiimage_card_aiimagecard_aiimageCard',
                'menu_short_name' => '卡密兑换',
                'menu_type' => '0',
                'icon' => '',
                'api_url' => '',
                'router_path' => 'aiimagecard',
                'view_path' => '',
                'methods' => '',
                'sort' => '100',
                'status' => '1',
                'is_show' => '0',
                'children' => [
                    [
                        'menu_name' => '卡密兑换添加',
                        'menu_key' => 'ai_image_aiimage_card_aiimagecard_aiimageCard_add',
                        'menu_short_name' => '卡密兑换添加',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'ai_image/aiimagecard',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '70',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '卡密兑换编辑',
                        'menu_key' => 'ai_image_aiimage_card_aiimagecard_aiimageCard_edit',
                        'menu_short_name' => '卡密兑换编辑',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'ai_image/aiimagecard/<id>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'put',
                        'sort' => '60',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '卡密兑换删除',
                        'menu_key' => 'ai_image_aiimage_card_aiimagecard_aiimageCard_delete',
                        'menu_short_name' => '卡密兑换删除',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'ai_image/aiimagecard/<id>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'delete',
                        'sort' => '50',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                ],
            ],
            [
                'menu_name' => '套餐列',
                'menu_key' => 'ai_image_aiimage_package_aiimagepackage_aiimagePackage',
                'menu_short_name' => '套餐列',
                'menu_type' => '0',
                'icon' => '',
                'api_url' => '',
                'router_path' => 'aiimagepackage',
                'view_path' => '',
                'methods' => '',
                'sort' => '100',
                'status' => '1',
                'is_show' => '0',
                'children' => [
                    [
                        'menu_name' => '套餐列添加',
                        'menu_key' => 'ai_image_aiimage_package_aiimagepackage_aiimagePackage_add',
                        'menu_short_name' => '套餐列添加',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'ai_image/aiimagepackage',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '70',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '套餐列编辑',
                        'menu_key' => 'ai_image_aiimage_package_aiimagepackage_aiimagePackage_edit',
                        'menu_short_name' => '套餐列编辑',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'ai_image/aiimagepackage/<id>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'put',
                        'sort' => '60',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '套餐列删除',
                        'menu_key' => 'ai_image_aiimage_package_aiimagepackage_aiimagePackage_delete',
                        'menu_short_name' => '套餐列删除',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'ai_image/aiimagepackage/<id>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'delete',
                        'sort' => '50',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                ],
            ],
            [
                'menu_name' => '订单列',
                'menu_key' => 'ai_image_aiimage_order_aiimageorder_aiimageOrder',
                'menu_short_name' => '订单列',
                'menu_type' => '0',
                'icon' => '',
                'api_url' => '',
                'router_path' => 'aiimageorder',
                'view_path' => '',
                'methods' => '',
                'sort' => '100',
                'status' => '1',
                'is_show' => '0',
                'children' => [
                    [
                        'menu_name' => '订单列添加',
                        'menu_key' => 'ai_image_aiimage_order_aiimageorder_aiimageOrder_add',
                        'menu_short_name' => '订单列添加',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'ai_image/aiimageorder',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '70',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '订单列编辑',
                        'menu_key' => 'ai_image_aiimage_order_aiimageorder_aiimageOrder_edit',
                        'menu_short_name' => '订单列编辑',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'ai_image/aiimageorder/<id>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'put',
                        'sort' => '60',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '订单列删除',
                        'menu_key' => 'ai_image_aiimage_order_aiimageorder_aiimageOrder_delete',
                        'menu_short_name' => '订单列删除',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'ai_image/aiimageorder/<id>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'delete',
                        'sort' => '50',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                ],
            ],
            [
                'menu_name' => '作品列',
                'menu_key' => 'ai_image_aiimage_create_aiimagecreate_aiimageCreate',
                'menu_short_name' => '作品列',
                'menu_type' => '0',
                'icon' => '',
                'api_url' => '',
                'router_path' => 'aiimagecreate',
                'view_path' => '',
                'methods' => '',
                'sort' => '100',
                'status' => '1',
                'is_show' => '0',
                'children' => [
                    [
                        'menu_name' => '作品列添加',
                        'menu_key' => 'ai_image_aiimage_create_aiimagecreate_aiimageCreate_add',
                        'menu_short_name' => '作品列添加',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'ai_image/aiimagecreate',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '70',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '作品列编辑',
                        'menu_key' => 'ai_image_aiimage_create_aiimagecreate_aiimageCreate_edit',
                        'menu_short_name' => '作品列编辑',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'ai_image/aiimagecreate/<id>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'put',
                        'sort' => '60',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '作品列删除',
                        'menu_key' => 'ai_image_aiimage_create_aiimagecreate_aiimageCreate_delete',
                        'menu_short_name' => '作品列删除',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'ai_image/aiimagecreate/<id>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'delete',
                        'sort' => '50',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                ],
            ],
            [
                'menu_name' => '帮助中心',
                'menu_key' => 'ai_image_aiimage_help_aiimagehelp_aiimageHelp',
                'menu_short_name' => '帮助中心',
                'menu_type' => '0',
                'icon' => '',
                'api_url' => '',
                'router_path' => 'aiimagehelp',
                'view_path' => '',
                'methods' => '',
                'sort' => '100',
                'status' => '1',
                'is_show' => '0',
                'children' => [
                    [
                        'menu_name' => '帮助中心添加',
                        'menu_key' => 'ai_image_aiimage_help_aiimagehelp_aiimageHelp_add',
                        'menu_short_name' => '帮助中心添加',
                        'menu_type' => '1',
                        'icon' => '',
                        'api_url' => 'ai_image/aiimagehelp',
                        'router_path' => 'aiimagehelp/aiimagehelp_edit',
                        'view_path' => 'aiimagehelp/aiimagehelp_edit',
                        'methods' => 'post',
                        'sort' => '70',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '帮助中心编辑',
                        'menu_key' => 'ai_image_aiimage_help_aiimagehelp_aiimageHelp_edit',
                        'menu_short_name' => '帮助中心编辑',
                        'menu_type' => '1',
                        'icon' => '',
                        'api_url' => 'ai_image/aiimagehelp/<id>',
                        'router_path' => 'aiimagehelp/aiimagehelp_edit',
                        'view_path' => 'aiimagehelp/aiimagehelp_edit',
                        'methods' => 'put',
                        'sort' => '60',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '帮助中心删除',
                        'menu_key' => 'ai_image_aiimage_help_aiimagehelp_aiimageHelp_delete',
                        'menu_short_name' => '帮助中心删除',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'ai_image/aiimagehelp/<id>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'delete',
                        'sort' => '50',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                ],
            ],
            [
                'menu_name' => '智能体',
                'menu_key' => 'ai_image_aiimage_model_aiimagemodel_aiimageModel_list',
                'menu_short_name' => '智能体',
                'menu_type' => '1',
                'icon' => 'nc-iconfont nc-icon-tuiguangV6xx',
                'api_url' => 'ai_image/aiimagemodel',
                'router_path' => 'aiimagemodel/aiimagemodel',
                'view_path' => 'aiimagemodel/aiimagemodel',
                'methods' => 'get',
                'sort' => '90',
                'status' => '1',
                'is_show' => '1',
            ],
            [
                'menu_name' => '卡密列表',
                'menu_key' => 'ai_image_aiimage_card_aiimagecard_aiimageCard_list',
                'menu_short_name' => '卡密',
                'menu_type' => '1',
                'icon' => 'nc-iconfont nc-icon-youhuiquanV6xx-11',
                'api_url' => 'ai_image/aiimagecard',
                'router_path' => 'aiimagecard/aiimagecard',
                'view_path' => 'aiimagecard/aiimagecard',
                'methods' => 'get',
                'sort' => '90',
                'status' => '1',
                'is_show' => '1',
            ],
            [
                'menu_name' => '套餐列表',
                'menu_key' => 'ai_image_aiimage_package_aiimagepackage_aiimagePackage_list',
                'menu_short_name' => '套餐',
                'menu_type' => '1',
                'icon' => 'nc-iconfont nc-icon-liebiaoV6xx',
                'api_url' => 'ai_image/aiimagepackage',
                'router_path' => 'aiimagepackage/aiimagepackage',
                'view_path' => 'aiimagepackage/aiimagepackage',
                'methods' => 'get',
                'sort' => '90',
                'status' => '1',
                'is_show' => '1',
            ],
            [
                'menu_name' => '订单列表',
                'menu_key' => 'ai_image_aiimage_order_aiimageorder_aiimageOrder_list',
                'menu_short_name' => '订单',
                'menu_type' => '1',
                'icon' => 'nc-iconfont nc-icon-zhankai-yousuojinV6xx',
                'api_url' => 'ai_image/aiimageorder',
                'router_path' => 'aiimageorder/aiimageorder',
                'view_path' => 'aiimageorder/aiimageorder',
                'methods' => 'get',
                'sort' => '90',
                'status' => '1',
                'is_show' => '1',
            ],
            [
                'menu_name' => '作品列表',
                'menu_key' => 'ai_image_aiimage_create_aiimagecreate_aiimageCreate_list',
                'menu_short_name' => '作品',
                'menu_type' => '1',
                'icon' => 'nc-iconfont nc-icon-shezhiV6xx-2',
                'api_url' => 'ai_image/aiimagecreate',
                'router_path' => 'aiimagecreate/aiimagecreate',
                'view_path' => 'aiimagecreate/aiimagecreate',
                'methods' => 'get',
                'sort' => '90',
                'status' => '1',
                'is_show' => '1',
            ],
            [
                'menu_name' => '帮助列表',
                'menu_key' => 'ai_image_aiimage_help_aiimagehelp_aiimageHelp_list',
                'menu_short_name' => '帮助',
                'menu_type' => '1',
                'icon' => 'nc-iconfont nc-icon-bianjiV6xx',
                'api_url' => 'ai_image/aiimagehelp',
                'router_path' => 'aiimagehelp/aiimagehelp',
                'view_path' => 'aiimagehelp/aiimagehelp',
                'methods' => 'get',
                'sort' => '90',
                'status' => '1',
                'is_show' => '1',
            ],
        ],
    ],
];