<?php
return [
    [
        'menu_name' => '经营分析',
        'menu_key' => 'hsx_performance',
        'menu_short_name' => '经营分析',
        'parent_select_key' => '',
        'parent_key' => '',
        'menu_type' => '0',
        'icon' => 'nc-iconfont nc-icon-wendangV6xx',
        'api_url' => '',
        'router_path' => '',
        'view_path' => '',
        'methods' => '',
        'sort' => '175',
        'status' => '1',
        'is_show' => '1',
        'children' => [
            [
                'menu_name' => '员工产出',
                'menu_key' => 'hsx_performance_output',
                'menu_short_name' => '员工产出',
                'parent_select_key' => '',
                'menu_type' => '1',
                'icon' => '',
                'api_url' => 'performance/output/overview',
                'router_path' => 'hsx_performance/output',
                'view_path' => 'output/index',
                'methods' => 'get',
                'sort' => '110',
                'status' => '1',
                'is_show' => '1',
                'children' => [
                    [
                        'menu_name' => '员工产出列表',
                        'menu_key' => 'hsx_performance_output_employees',
                        'menu_short_name' => '员工列表',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'performance/output/employees',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'get',
                        'sort' => '100',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '员工产出详情',
                        'menu_key' => 'hsx_performance_output_employee',
                        'menu_short_name' => '员工详情',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'performance/output/employees/<uid>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'get',
                        'sort' => '90',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '产出事实明细',
                        'menu_key' => 'hsx_performance_output_facts',
                        'menu_short_name' => '事实明细',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'performance/output/facts',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'get',
                        'sort' => '80',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '产出数据异常',
                        'menu_key' => 'hsx_performance_output_anomalies',
                        'menu_short_name' => '数据异常',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'performance/output/anomalies',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'get',
                        'sort' => '70',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '处理产出异常',
                        'menu_key' => 'hsx_performance_output_anomaly_resolve',
                        'menu_short_name' => '处理异常',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'performance/output/anomalies/<id>/resolve',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '60',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '重建产出汇总',
                        'menu_key' => 'hsx_performance_output_rebuild',
                        'menu_short_name' => '重建汇总',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'performance/output/rebuild',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '50',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '产出数据对账',
                        'menu_key' => 'hsx_performance_output_reconcile',
                        'menu_short_name' => '数据对账',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'performance/output/reconcile',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '40',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                ],
            ],
            [
                'menu_name' => '经营报告',
                'menu_key' => 'hsx_performance_report',
                'menu_short_name' => '经营报告',
                'parent_select_key' => '',
                'menu_type' => '1',
                'icon' => '',
                'api_url' => 'performance/reports',
                'router_path' => 'hsx_performance/report',
                'view_path' => 'report/index',
                'methods' => 'get',
                'sort' => '100',
                'status' => '1',
                'is_show' => '1',
                'children' => [
                    [
                        'menu_name' => '报告配置',
                        'menu_key' => 'hsx_performance_config',
                        'menu_short_name' => '报告配置',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'performance/config',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'get',
                        'sort' => '100',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '保存报告配置',
                        'menu_key' => 'hsx_performance_config_save',
                        'menu_short_name' => '保存配置',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'performance/config',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '90',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '报告详情',
                        'menu_key' => 'hsx_performance_report_info',
                        'menu_short_name' => '报告详情',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'performance/reports/<id>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'get',
                        'sort' => '80',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '生成报告',
                        'menu_key' => 'hsx_performance_report_generate',
                        'menu_short_name' => '生成报告',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'performance/reports/generate',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '70',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '重试报告通知',
                        'menu_key' => 'hsx_performance_report_retry',
                        'menu_short_name' => '重试通知',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'performance/reports/<id>/retry',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '60',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                ],
            ],
        ],
    ],
];