<?php
return [
    [
        'menu_name' => '快递API',
        'menu_key' => 'kd_api',
        'menu_short_name' => '快递API',
        'parent_key' => '',
        'menu_type' => '0',
        'icon' => '',
        'api_url' => '',
        'router_path' => '',
        'view_path' => '',
        'methods' => '',
        'sort' => '100',
        'status' => '1',
        'is_show' => '1',
        'children' => [
            [
                'menu_name' => '订单列',
                'menu_key' => 'kd_api_kdapi_order_kdapi_order_kdapi_order',
                'menu_short_name' => '订单列',
                'menu_type' => '0',
                'icon' => '',
                'api_url' => '',
                'router_path' => 'kdapi_order',
                'view_path' => '',
                'methods' => '',
                'sort' => '100',
                'status' => '1',
                'is_show' => '0',
                'children' => [
                    [
                        'menu_name' => '订单列添加',
                        'menu_key' => 'kd_api_kdapi_order_kdapi_order_kdapi_order_add',
                        'menu_short_name' => '订单列添加',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'kd_api/kdapi_order',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '70',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '订单列编辑',
                        'menu_key' => 'kd_api_kdapi_order_kdapi_order_kdapi_order_edit',
                        'menu_short_name' => '订单列编辑',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'kd_api/kdapi_order/<id>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'put',
                        'sort' => '60',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '订单列删除',
                        'menu_key' => 'kd_api_kdapi_order_kdapi_order_kdapi_order_delete',
                        'menu_short_name' => '订单列删除',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'kd_api/kdapi_order/<id>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'delete',
                        'sort' => '50',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                ],
            ],
            [
                'menu_name' => 'api对接',
                'menu_key' => 'kd_api_kdapi_api_kdapi_api_kdapi_api',
                'menu_short_name' => 'api对接',
                'menu_type' => '0',
                'icon' => '',
                'api_url' => '',
                'router_path' => 'kdapi_api',
                'view_path' => '',
                'methods' => '',
                'sort' => '100',
                'status' => '1',
                'is_show' => '0',
                'children' => [
                    [
                        'menu_name' => 'api对接添加',
                        'menu_key' => 'kd_api_kdapi_api_kdapi_api_kdapi_api_add',
                        'menu_short_name' => 'api对接添加',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'kd_api/kdapi_api',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '70',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => 'api对接编辑',
                        'menu_key' => 'kd_api_kdapi_api_kdapi_api_kdapi_api_edit',
                        'menu_short_name' => 'api对接编辑',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'kd_api/kdapi_api/<id>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'put',
                        'sort' => '60',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => 'api对接删除',
                        'menu_key' => 'kd_api_kdapi_api_kdapi_api_kdapi_api_delete',
                        'menu_short_name' => 'api对接删除',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'kd_api/kdapi_api/<id>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'delete',
                        'sort' => '50',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                ],
            ],
            [
                'menu_name' => 'api对接',
                'menu_key' => 'kd_api_kdapi_api_kdapi_api_kdapi_api_list',
                'menu_short_name' => 'api对接',
                'menu_type' => '1',
                'icon' => 'nc-iconfont nc-icon-shezhiV6xx1',
                'api_url' => 'kd_api/kdapi_api',
                'router_path' => 'kdapi_api/kdapi_api',
                'view_path' => 'kdapi_api/kdapi_api',
                'methods' => 'get',
                'sort' => '90',
                'status' => '1',
                'is_show' => '1',
            ],
            [
                'menu_name' => '订单列表',
                'menu_key' => 'kd_api_kdapi_order_kdapi_order_kdapi_order_list',
                'menu_short_name' => '订单列表',
                'menu_type' => '1',
                'icon' => 'nc-iconfont nc-icon-yingyongzhongxinV6xx-1',
                'api_url' => 'kd_api/kdapi_order',
                'router_path' => 'kdapi_order/kdapi_order',
                'view_path' => 'kdapi_order/kdapi_order',
                'methods' => 'get',
                'sort' => '0',
                'status' => '1',
                'is_show' => '1',
            ],
        ],
    ],
];