const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const vm = require('node:vm')
const resolve = name => require(require.resolve(name, { paths: [process.cwd(), path.resolve(process.cwd(), 'admin')] }))
const ts = resolve('typescript')
const compiler = resolve('@vue/compiler-sfc')
const sass = resolve('sass')
const api = {}
const source = fs.readFileSync(path.join(__dirname, 'cashier-layout.ts'), 'utf8')
vm.runInNewContext(ts.transpileModule(source, { compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2020 } }).outputText, { exports: api })

for (const [width, height] of [[320, 420], [700, 460], [1040, 640], [1480, 1010]]) {
    const layout = api.cashierGridLayout(width, height)
    assert.equal(layout.limit, layout.columns * layout.rows)
    assert.ok(layout.columns * 168 + (layout.columns - 1) * 12 <= width)
    assert.ok(layout.rows * 220 + (layout.rows - 1) * 12 <= height)
}
assert.ok(api.cashierGridLayout(1000, 640).limit > api.cashierGridLayout(740, 640).limit)
assert.ok(api.cashierGridLayout(10000, 10000).limit <= 120)
assert.equal(api.cashierSelectionIndex([{ sku_id: '12' }], 12), 0)
assert.equal(api.cashierSelectionIndex([{ sku_id: 12 }], 13), -1)
assert.equal(JSON.stringify(api.cashierImages({ goods_cover: 'a.jpg', goods_image: 'a.jpg,b.jpg' })), '["a.jpg","b.jpg"]')
assert.equal(JSON.stringify(api.cashierImages({ goods_cover: 'a.jpg', goods_image: '["b.jpg",null,"c.jpg"]' })), '["a.jpg","b.jpg","c.jpg"]')
assert.equal(api.cashierImages(null).length, 0)

const file = path.join(__dirname, '../views/cashier/index.vue')
const content = fs.readFileSync(file, 'utf8')
const { descriptor, errors } = compiler.parse(content, { filename: file })
assert.equal(errors.length, 0)
const script = compiler.compileScript(descriptor, { id: 'cashier-test' })
const template = compiler.compileTemplate({ source: descriptor.template.content, filename: file, id: 'cashier-test', compilerOptions: { bindingMetadata: script.bindings } })
assert.deepEqual(template.errors, [])
assert.ok(sass.compileString(descriptor.styles[0].content).css.length > 0)
assert.match(content, /sort_by: sortBy.value, sort_direction: sortDirection.value/)
assert.match(content, /requestId !== goodsRequest/)
assert.match(content, /await fitLayout\(\)[\s\S]*initialized = true/)
assert.match(content, /v-show="!cartCollapsed"/)
assert.match(content, /@click.stop="toggleCart\(g\)"/)
assert.match(content, /:preview-src-list="imageUrls\(g\)"/)
assert.doesNotMatch(content, /loadMore|limit: 18|background: #fff;/)
console.log('Cashier layout, images, selection, request guards, SFC and SCSS checks passed')
