<?php
return [
    [
        'menu_name' => '设备资产中台',
        'menu_key' => 'device_asset_manage',
        'menu_short_name' => '资产中台',
        'parent_select_key' => '',
        'parent_key' => 'recycle',
        'menu_type' => '1',
        'icon' => 'nc-iconfont nc-icon-dingdanV6xx',
        'api_url' => 'device_asset/lists',
        'router_path' => 'device_asset/list',
        'view_path' => 'asset/list',
        'methods' => 'get',
        'sort' => '92',
        'status' => '1',
        'is_show' => '1',
        'children' => [
            [
                'menu_name' => '设备池',
                'menu_key' => 'device_asset_pool',
                'menu_short_name' => '设备池',
                'parent_select_key' => '',
                'menu_type' => '2',
                'icon' => '',
                'api_url' => 'device_asset/pool',
                'router_path' => '',
                'view_path' => '',
                'methods' => 'get',
                'sort' => '100',
                'status' => '1',
                'is_show' => '0',
            ],
            [
                'menu_name' => '导入资产',
                'menu_key' => 'device_asset_import',
                'menu_short_name' => '导入资产',
                'parent_select_key' => '',
                'menu_type' => '2',
                'icon' => '',
                'api_url' => 'device_asset/import',
                'router_path' => '',
                'view_path' => '',
                'methods' => 'post',
                'sort' => '90',
                'status' => '1',
                'is_show' => '0',
            ],
            [
                'menu_name' => '扫码导入',
                'menu_key' => 'device_asset_scan',
                'menu_short_name' => '扫码导入',
                'parent_select_key' => '',
                'menu_type' => '2',
                'icon' => '',
                'api_url' => 'device_asset/scan',
                'router_path' => '',
                'view_path' => '',
                'methods' => 'post',
                'sort' => '80',
                'status' => '1',
                'is_show' => '0',
            ],
            [
                'menu_name' => '拍照任务',
                'menu_key' => 'device_asset_photo_task',
                'menu_short_name' => '拍照任务',
                'parent_select_key' => '',
                'menu_type' => '2',
                'icon' => '',
                'api_url' => 'device_asset/photo_task/<id>',
                'router_path' => '',
                'view_path' => '',
                'methods' => 'post',
                'sort' => '70',
                'status' => '1',
                'is_show' => '0',
            ],
            [
                'menu_name' => '保存媒体',
                'menu_key' => 'device_asset_media_save',
                'menu_short_name' => '保存媒体',
                'parent_select_key' => '',
                'menu_type' => '2',
                'icon' => '',
                'api_url' => 'device_asset/media/<id>',
                'router_path' => '',
                'view_path' => '',
                'methods' => 'post',
                'sort' => '60',
                'status' => '1',
                'is_show' => '0',
            ],
            [
                'menu_name' => '复检媒体',
                'menu_key' => 'device_asset_media_review',
                'menu_short_name' => '复检媒体',
                'parent_select_key' => '',
                'menu_type' => '2',
                'icon' => '',
                'api_url' => 'device_asset/media/review/<media_id>',
                'router_path' => '',
                'view_path' => '',
                'methods' => 'post',
                'sort' => '50',
                'status' => '1',
                'is_show' => '0',
            ],
            [
                'menu_name' => '确认图片',
                'menu_key' => 'device_asset_photos_confirm',
                'menu_short_name' => '确认图片',
                'parent_select_key' => '',
                'menu_type' => '2',
                'icon' => '',
                'api_url' => 'device_asset/photos/confirm/<id>',
                'router_path' => '',
                'view_path' => '',
                'methods' => 'post',
                'sort' => '40',
                'status' => '1',
                'is_show' => '0',
            ],
            [
                'menu_name' => '完成定价',
                'menu_key' => 'device_asset_price',
                'menu_short_name' => '完成定价',
                'parent_select_key' => '',
                'menu_type' => '2',
                'icon' => '',
                'api_url' => 'device_asset/price/<id>',
                'router_path' => '',
                'view_path' => '',
                'methods' => 'post',
                'sort' => '30',
                'status' => '1',
                'is_show' => '0',
            ],
            [
                'menu_name' => '导出资产',
                'menu_key' => 'device_asset_export',
                'menu_short_name' => '导出资产',
                'parent_select_key' => '',
                'menu_type' => '2',
                'icon' => '',
                'api_url' => 'device_asset/export',
                'router_path' => '',
                'view_path' => '',
                'methods' => 'post',
                'sort' => '20',
                'status' => '1',
                'is_show' => '0',
            ],
        ],
    ],
];
