// Generated by 'unplugin-auto-import'
export {}
declare global {
  const ElButton: typeof import('element-plus/es')['ElButton']
  const ElCascader: typeof import('element-plus/es')['ElCascader']
  const ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
  const ElInput: typeof import('element-plus/es')['ElInput']
  const ElMessage: typeof import('element-plus/es')['ElMessage']
  const ElMessageBox: typeof import('element-plus/es')['ElMessageBox']
  const ElNotification: typeof import('element-plus/es')['ElNotification']
  const ElSelect: typeof import('element-plus/es')['ElSelect']
}
