// Generated by 'unplugin-auto-import'
export {}
declare global {
  const ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
  const ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
  const ElMessage: typeof import('element-plus/es')['ElMessage']
  const ElMessageBox: typeof import('element-plus/es')['ElMessageBox']
  const ElNotification: typeof import('element-plus/es')['ElNotification']
}
