// Generated by 'unplugin-auto-import'
export {}
declare global {
  const ElCascader: typeof import('element-plus/es')['ElCascader']
  const ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
  const ElInput: typeof import('element-plus/es')['ElInput']
  const ElMessage: typeof import('element-plus/es')['ElMessage']
  const ElNotification: typeof import('element-plus/es')['ElNotification']
  const ElSelect: typeof import('element-plus/es')['ElSelect']
}
