import request from '@/utils/request'

export const getPerformanceOutputOverview = (params: Record<string, any>) => request.get('performance/output/overview', { params })
export const getPerformanceOutputEmployees = (params: Record<string, any>) => request.get('performance/output/employees', { params })
export const getPerformanceOutputEmployee = (uid: number, params: Record<string, any>) => request.get(`performance/output/employees/${uid}`, { params })
export const getPerformanceOutputFacts = (params: Record<string, any>) => request.get('performance/output/facts', { params })
export const getPerformanceOutputAnomalies = (params: Record<string, any>) => request.get('performance/output/anomalies', { params })
export const resolvePerformanceOutputAnomaly = (id: number, status = 'resolved') => request.post(`performance/output/anomalies/${id}/resolve`, { status })
export const rebuildPerformanceOutput = (data: Record<string, any>) => request.post('performance/output/rebuild', data)
export const reconcilePerformanceOutput = (data: Record<string, any>) => request.post('performance/output/reconcile', data)
export const getPerformanceConfig = () => request.get('performance/config')
export const savePerformanceConfig = (data: Record<string, any>) => request.post('performance/config', data)
export const getPerformanceReports = (params: Record<string, any>) => request.get('performance/reports', { params })
export const getPerformanceReport = (id: number) => request.get(`performance/reports/${id}`)
export const generatePerformanceReport = (report_type: string) => request.post('performance/reports/generate', { report_type })
export const retryPerformanceReport = (id: number) => request.post(`performance/reports/${id}/retry`)
