<?php
return [
    [
        'menu_name' => '旧书回收系统',
        'menu_key' => 'wj_books_system',
        'menu_short_name' => '旧书管理',
        'parent_select_key' => '',
        'parent_key' => '',
        'menu_type' => '0',
        'icon' => 'nc-iconfont nc-icon-wendangV6xx1',
        'api_url' => '',
        'router_path' => '',
        'view_path' => '',
        'methods' => '',
        'sort' => '100',
        'status' => '1',
        'is_show' => '1',
        'children' => [
            [
                'menu_name' => '图书管理',
                'menu_key' => 'wj_books_wj_books_config_wj_books_config_wj_books_config',
                'menu_short_name' => '系统设置',
                'parent_select_key' => '',
                'menu_type' => '0',
                'icon' => 'nc-iconfont nc-icon-shezhi-1V6xx',
                'api_url' => '',
                'router_path' => 'wj_books_config',
                'view_path' => '',
                'methods' => '',
                'sort' => '100',
                'status' => '1',
                'is_show' => '1',
                'children' => [
                    [
                        'menu_name' => '回收设置',
                        'menu_key' => 'wj_books_wj_books_config_wj_books_config_wj_books_config_list',
                        'menu_short_name' => '旧书回收设置',
                        'parent_select_key' => '',
                        'menu_type' => '1',
                        'icon' => '',
                        'api_url' => 'wj_books/wj_books_config',
                        'router_path' => 'wj_books_config/wj_books_config',
                        'view_path' => 'wj_books_config/wj_books_config',
                        'methods' => 'get',
                        'sort' => '90',
                        'status' => '1',
                        'is_show' => '1',
                        'children' => [
                            [
                                'menu_name' => '更新系统设置',
                                'menu_key' => 'wj_books_wj_books_config_wj_books_config_wj_books_config_update',
                                'menu_short_name' => '更新系统设置',
                                'parent_select_key' => '',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'wj_books/wj_books_config',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'put',
                                'sort' => '80',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                        ],
                    ],
                    [
                        'menu_name' => '图书信息',
                        'menu_key' => 'wj_books_wj_books_info_wj_books_info_wj_books_info_list',
                        'menu_short_name' => '图书信息列表',
                        'parent_select_key' => '',
                        'menu_type' => '1',
                        'icon' => '',
                        'api_url' => 'wj_books/wj_books_info',
                        'router_path' => 'wj_books_info/wj_books_info',
                        'view_path' => 'wj_books_info/wj_books_info',
                        'methods' => 'get',
                        'sort' => '90',
                        'status' => '1',
                        'is_show' => '1',
                        'children' => [
                            [
                                'menu_name' => '图书信息添加',
                                'menu_key' => 'wj_books_wj_books_info_wj_books_info_wj_books_info_add',
                                'menu_short_name' => '图书信息添加',
                                'parent_select_key' => '',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'wj_books/wj_books_info',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'post',
                                'sort' => '70',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                            [
                                'menu_name' => '图书信息编辑',
                                'menu_key' => 'wj_books_wj_books_info_wj_books_info_wj_books_info_edit',
                                'menu_short_name' => '图书信息编辑',
                                'parent_select_key' => '',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'wj_books/wj_books_info/<id>',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'put',
                                'sort' => '60',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                            [
                                'menu_name' => '图书信息删除',
                                'menu_key' => 'wj_books_wj_books_info_wj_books_info_wj_books_info_delete',
                                'menu_short_name' => '图书信息删除',
                                'parent_select_key' => '',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'wj_books/wj_books_info/<id>',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'delete',
                                'sort' => '50',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                        ],
                    ],
                    [
                        'menu_name' => '扫描记录',
                        'menu_key' => 'wj_books_wj_books_scan_records_wj_books_scan_records_wj_books_scan_records_list',
                        'menu_short_name' => '图书扫描记录列表',
                        'parent_select_key' => '',
                        'menu_type' => '1',
                        'icon' => '',
                        'api_url' => 'wj_books/wj_books_scan_records',
                        'router_path' => 'wj_books_scan_records/wj_books_scan_records',
                        'view_path' => 'wj_books_scan_records/wj_books_scan_records',
                        'methods' => 'get',
                        'sort' => '90',
                        'status' => '1',
                        'is_show' => '1',
                        'children' => [
                            [
                                'menu_name' => '图书扫描记录添加',
                                'menu_key' => 'wj_books_wj_books_scan_records_wj_books_scan_records_wj_books_scan_records_add',
                                'menu_short_name' => '图书扫描记录添加',
                                'parent_select_key' => '',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'wj_books/wj_books_scan_records',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'post',
                                'sort' => '70',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                            [
                                'menu_name' => '图书扫描记录编辑',
                                'menu_key' => 'wj_books_wj_books_scan_records_wj_books_scan_records_wj_books_scan_records_edit',
                                'menu_short_name' => '图书扫描记录编辑',
                                'parent_select_key' => '',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'wj_books/wj_books_scan_records/<id>',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'put',
                                'sort' => '60',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                            [
                                'menu_name' => '图书扫描记录删除',
                                'menu_key' => 'wj_books_wj_books_scan_records_wj_books_scan_records_wj_books_scan_records_delete',
                                'menu_short_name' => '图书扫描记录删除',
                                'parent_select_key' => '',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'wj_books/wj_books_scan_records/<id>',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'delete',
                                'sort' => '50',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                        ],
                    ],
                ],
            ],
            [
                'menu_name' => '订单管理',
                'menu_key' => 'wj_books_orders',
                'menu_short_name' => '订单管理',
                'parent_select_key' => '',
                'menu_type' => '0',
                'icon' => 'nc-iconfont nc-icon-bianjiV6xx',
                'api_url' => '',
                'router_path' => '',
                'view_path' => '',
                'methods' => '',
                'sort' => '90',
                'status' => '1',
                'is_show' => '1',
                'children' => [
                    [
                        'menu_name' => '物流回调日志',
                        'menu_key' => 'wj_books_wj_books_express_log_wj_books_express_log_wj_books_express_log_list',
                        'menu_short_name' => '物流回调日志列表',
                        'parent_select_key' => '',
                        'menu_type' => '1',
                        'icon' => '',
                        'api_url' => 'wj_books/wj_books_express_log',
                        'router_path' => 'wj_books_express_log/list',
                        'view_path' => 'wj_books_express_log/list',
                        'methods' => 'get',
                        'sort' => '90',
                        'status' => '1',
                        'is_show' => '1',
                        'children' => [
                            [
                                'menu_name' => '物流回调日志详情',
                                'menu_key' => 'wj_books_wj_books_express_log_wj_books_express_log_wj_books_express_log_detail',
                                'menu_short_name' => '物流回调日志详情',
                                'parent_select_key' => '',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'wj_books/wj_books_express_log/<id>',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'get',
                                'sort' => '80',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                            [
                                'menu_name' => '物流回调日志删除',
                                'menu_key' => 'wj_books_wj_books_express_log_wj_books_express_log_wj_books_express_log_delete',
                                'menu_short_name' => '物流回调日志删除',
                                'parent_select_key' => '',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'wj_books/wj_books_express_log/<id>',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'delete',
                                'sort' => '70',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                            [
                                'menu_name' => '清空物流回调日志',
                                'menu_key' => 'wj_books_wj_books_express_log_wj_books_express_log_wj_books_express_log_clear',
                                'menu_short_name' => '清空物流回调日志',
                                'parent_select_key' => '',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'wj_books/wj_books_express_log/clear',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'delete',
                                'sort' => '60',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                        ],
                    ],
                    [
                        'menu_name' => '取回申请',
                        'menu_key' => 'wj_books_wj_books_retrieve_apply_wj_books_retrieve_apply_wj_books_retrieve_apply_list',
                        'menu_short_name' => '取回申请列表',
                        'parent_select_key' => '',
                        'menu_type' => '1',
                        'icon' => '',
                        'api_url' => 'wj_books/wj_books_retrieve_apply',
                        'router_path' => 'wj_books_retrieve_apply/wj_books_retrieve_apply',
                        'view_path' => 'wj_books_retrieve_apply/wj_books_retrieve_apply',
                        'methods' => 'get',
                        'sort' => '90',
                        'status' => '1',
                        'is_show' => '1',
                        'children' => [
                            [
                                'menu_name' => '申请发货',
                                'menu_key' => 'wj_books_wj_books_retrieve_apply_wj_books_retrieve_apply_wj_books_retrieve_apply_ship',
                                'menu_short_name' => '申请发货',
                                'parent_select_key' => '',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'wj_books/wj_books_retrieve_apply/<id>/ship',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'put',
                                'sort' => '70',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                            [
                                'menu_name' => '完成申请',
                                'menu_key' => 'wj_books_wj_books_retrieve_apply_wj_books_retrieve_apply_wj_books_retrieve_apply_complete',
                                'menu_short_name' => '完成申请',
                                'parent_select_key' => '',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'wj_books/wj_books_retrieve_apply/<id>/complete',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'put',
                                'sort' => '60',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                            [
                                'menu_name' => '取消申请',
                                'menu_key' => 'wj_books_wj_books_retrieve_apply_wj_books_retrieve_apply_wj_books_retrieve_apply_cancel',
                                'menu_short_name' => '取消申请',
                                'parent_select_key' => '',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'wj_books/wj_books_retrieve_apply/<id>/cancel',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'put',
                                'sort' => '50',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                            [
                                'menu_name' => '删除申请',
                                'menu_key' => 'wj_books_wj_books_retrieve_apply_wj_books_retrieve_apply_wj_books_retrieve_apply_delete',
                                'menu_short_name' => '删除申请',
                                'parent_select_key' => '',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'wj_books/wj_books_retrieve_apply/<id>',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'delete',
                                'sort' => '40',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                        ],
                    ],
                    [
                        'menu_name' => '回收订单',
                        'menu_key' => 'wj_books_wj_books_order_wj_books_order_wj_books_order_list',
                        'menu_short_name' => '订单列表',
                        'parent_select_key' => '',
                        'menu_type' => '1',
                        'icon' => '',
                        'api_url' => 'wj_books/wj_books_order',
                        'router_path' => 'wj_books_order/wj_books_order',
                        'view_path' => 'wj_books_order/wj_books_order',
                        'methods' => 'get',
                        'sort' => '90',
                        'status' => '1',
                        'is_show' => '1',
                        'children' => [
                            [
                                'menu_name' => '订单详情',
                                'menu_key' => 'wj_books_wj_books_order_wj_books_order_wj_books_order_detail',
                                'menu_short_name' => '订单详情',
                                'parent_select_key' => '',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'wj_books/wj_books_order/<id>',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'get',
                                'sort' => '80',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                            [
                                'menu_name' => '更新订单状态',
                                'menu_key' => 'wj_books_wj_books_order_wj_books_order_wj_books_order_update_status',
                                'menu_short_name' => '更新订单状态',
                                'parent_select_key' => '',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'wj_books/wj_books_order/<id>/status',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'put',
                                'sort' => '70',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                            [
                                'menu_name' => '完成订单',
                                'menu_key' => 'wj_books_wj_books_order_wj_books_order_wj_books_order_complete',
                                'menu_short_name' => '完成订单',
                                'parent_select_key' => '',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'wj_books/wj_books_order/<id>/complete',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'put',
                                'sort' => '60',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                            [
                                'menu_name' => '取消订单',
                                'menu_key' => 'wj_books_wj_books_order_wj_books_order_wj_books_order_cancel',
                                'menu_short_name' => '取消订单',
                                'parent_select_key' => '',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'wj_books/wj_books_order/<id>/cancel',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'put',
                                'sort' => '50',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                            [
                                'menu_name' => '更新物流信息',
                                'menu_key' => 'wj_books_wj_books_order_wj_books_order_wj_books_order_update_express',
                                'menu_short_name' => '更新物流信息',
                                'parent_select_key' => '',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'wj_books/wj_books_order/<id>/express',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'put',
                                'sort' => '40',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                        ],
                    ],
                    [
                        'menu_name' => '取回申请详情',
                        'menu_key' => 'wj_books_wj_books_retrieve_apply_wj_books_retrieve_apply_wj_books_retrieve_apply_detail',
                        'menu_short_name' => '取回申请详情',
                        'parent_select_key' => '',
                        'menu_type' => '1',
                        'icon' => '',
                        'api_url' => 'wj_books/wj_books_retrieve_apply/<id>',
                        'router_path' => 'wj_books/wj_books_retrieve_apply/detail',
                        'view_path' => 'wj_books_retrieve_apply/detail',
                        'methods' => 'get',
                        'sort' => '80',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                ],
            ],
        ],
    ],
];