<?php
return [
    [
        'menu_name' => '项目合作中心',
        'menu_key' => 'hsx_project_center',
        'menu_short_name' => '项目中心',
        'parent_select_key' => '',
        'parent_key' => 'addon',
        'menu_type' => '0',
        'icon' => 'nc-iconfont nc-icon-yingxiao',
        'api_url' => '',
        'router_path' => '',
        'view_path' => '',
        'methods' => '',
        'sort' => '165',
        'status' => '1',
        'is_show' => '1',
        'children' => [
            [
                'menu_name' => '项目配置',
                'menu_key' => 'hsx_project_center_project',
                'menu_short_name' => '项目配置',
                'parent_select_key' => '',
                'menu_type' => '1',
                'icon' => '',
                'api_url' => 'project-center/projects',
                'router_path' => 'hsx_project_center/project',
                'view_path' => 'project/index',
                'methods' => 'get',
                'sort' => '100',
                'status' => '1',
                'is_show' => '1',
                'children' => [
                    [
                        'menu_name' => '项目元数据',
                        'menu_key' => 'hsx_project_center_project_metadata',
                        'menu_short_name' => '项目元数据',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'project-center/projects/metadata',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'get',
                        'sort' => '100',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '新增项目',
                        'menu_key' => 'hsx_project_center_project_add',
                        'menu_short_name' => '新增项目',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'project-center/projects',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '100',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '编辑项目',
                        'menu_key' => 'hsx_project_center_project_edit',
                        'menu_short_name' => '编辑项目',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'project-center/projects/<id>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'put',
                        'sort' => '100',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '删除项目',
                        'menu_key' => 'hsx_project_center_project_delete',
                        'menu_short_name' => '删除项目',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'project-center/projects/<id>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'delete',
                        'sort' => '100',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '项目详情',
                        'menu_key' => 'hsx_project_center_project_info',
                        'menu_short_name' => '项目详情',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'project-center/projects/<id>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'get',
                        'sort' => '100',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                ],
            ],
            [
                'menu_name' => '客户群台账',
                'menu_key' => 'hsx_project_center_group',
                'menu_short_name' => '客户群台账',
                'parent_select_key' => '',
                'menu_type' => '1',
                'icon' => '',
                'api_url' => 'project-center/groups',
                'router_path' => 'hsx_project_center/group',
                'view_path' => 'group/index',
                'methods' => 'get',
                'sort' => '90',
                'status' => '1',
                'is_show' => '1',
                'children' => [
                    [
                        'menu_name' => '完成企微建群',
                        'menu_key' => 'hsx_project_center_wecom_complete',
                        'menu_short_name' => '完成企微建群',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'project-center/groups/<id>/wecom/complete',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'put',
                        'sort' => '100',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '生成群编号',
                        'menu_key' => 'hsx_project_center_group_reserve',
                        'menu_short_name' => '生成群编号',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'project-center/groups/reserve',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '100',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '企微建群配置检查',
                        'menu_key' => 'hsx_project_center_wecom_readiness',
                        'menu_short_name' => '企微建群配置检查',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'project-center/wecom/readiness',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'get',
                        'sort' => '100',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '获取企微身份授权地址',
                        'menu_key' => 'hsx_project_center_wecom_oauth_url',
                        'menu_short_name' => '获取企微身份授权地址',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'project-center/wecom/oauth-url',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'get',
                        'sort' => '100',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '绑定当前企微员工',
                        'menu_key' => 'hsx_project_center_wecom_bind_identity',
                        'menu_short_name' => '绑定当前企微员工',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'project-center/wecom/bind-identity',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '100',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '准备企微建群',
                        'menu_key' => 'hsx_project_center_wecom_prepare',
                        'menu_short_name' => '准备企微建群',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'project-center/groups/<id>/wecom/prepare',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '100',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '记录企微建群失败',
                        'menu_key' => 'hsx_project_center_wecom_fail',
                        'menu_short_name' => '记录企微建群失败',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'project-center/groups/<id>/wecom/fail',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'put',
                        'sort' => '100',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '绑定企微群',
                        'menu_key' => 'hsx_project_center_group_wecom',
                        'menu_short_name' => '绑定企微群',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'project-center/groups/<id>/wecom',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'put',
                        'sort' => '100',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '结束群流程',
                        'menu_key' => 'hsx_project_center_group_close',
                        'menu_short_name' => '结束群流程',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'project-center/groups/<id>/close',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'put',
                        'sort' => '100',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                ],
            ],
            [
                'menu_name' => '资料审核',
                'menu_key' => 'hsx_project_center_application',
                'menu_short_name' => '资料审核',
                'parent_select_key' => '',
                'menu_type' => '1',
                'icon' => '',
                'api_url' => 'project-center/applications',
                'router_path' => 'hsx_project_center/application',
                'view_path' => 'application/index',
                'methods' => 'get',
                'sort' => '80',
                'status' => '1',
                'is_show' => '1',
                'children' => [
                    [
                        'menu_name' => '资料详情',
                        'menu_key' => 'hsx_project_center_application_info',
                        'menu_short_name' => '资料详情',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'project-center/applications/<id>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'get',
                        'sort' => '100',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '审核资料',
                        'menu_key' => 'hsx_project_center_application_review',
                        'menu_short_name' => '审核资料',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'project-center/applications/<id>/review',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'put',
                        'sort' => '100',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                ],
            ],
            [
                'menu_name' => '分销佣金',
                'menu_key' => 'hsx_project_center_distribution',
                'menu_short_name' => '分销佣金',
                'parent_select_key' => '',
                'menu_type' => '1',
                'icon' => '',
                'api_url' => 'project-center/distribution/orders',
                'router_path' => 'hsx_project_center/distribution',
                'view_path' => 'distribution/index',
                'methods' => 'get',
                'sort' => '75',
                'status' => '1',
                'is_show' => '1',
                'children' => [
                    [
                        'menu_name' => '分销项目选项',
                        'menu_key' => 'hsx_project_center_distribution_projects',
                        'menu_short_name' => '分销项目选项',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'project-center/distribution/projects',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'get',
                        'sort' => '100',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '立即结算佣金',
                        'menu_key' => 'hsx_project_center_distribution_settle',
                        'menu_short_name' => '立即结算佣金',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'project-center/distribution/orders/<id>/settle',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '100',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '佣金单详情',
                        'menu_key' => 'hsx_project_center_distribution_info',
                        'menu_short_name' => '佣金单详情',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'project-center/distribution/orders/<id>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'get',
                        'sort' => '100',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '分销概览',
                        'menu_key' => 'hsx_project_center_distribution_overview',
                        'menu_short_name' => '分销概览',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'project-center/distribution/overview',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'get',
                        'sort' => '100',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                ],
            ],
            [
                'menu_name' => '收益展示',
                'menu_key' => 'hsx_project_center_income',
                'menu_short_name' => '收益展示',
                'parent_select_key' => '',
                'menu_type' => '1',
                'icon' => '',
                'api_url' => 'project-center/income-board',
                'router_path' => 'hsx_project_center/income',
                'view_path' => 'income/index',
                'methods' => 'get',
                'sort' => '70',
                'status' => '1',
                'is_show' => '1',
                'children' => [
                    [
                        'menu_name' => '粘贴收益榜',
                        'menu_key' => 'hsx_project_center_income_replace',
                        'menu_short_name' => '粘贴收益榜',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'project-center/income-board/replace',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '100',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                ],
            ],
        ],
    ],
];