<?php
return [
    [
        'menu_name' => '回收报价增强',
        'menu_key' => 'recycle_quote_spider',
        'menu_short_name' => '报价增强',
        'parent_select_key' => '',
        'parent_key' => 'recycle_category_manage',
        'menu_type' => '0',
        'icon' => 'nc-iconfont nc-icon-yunfuwuV6xx1',
        'api_url' => '',
        'router_path' => '',
        'view_path' => '',
        'methods' => '',
        'sort' => '97',
        'status' => '1',
        'is_show' => '0',
    ],
    [
        'menu_name' => '回收报价增强',
        'menu_key' => 'recycle_quote_spider_manage',
        'menu_short_name' => '报价增强',
        'parent_select_key' => '',
        'parent_key' => 'recycle_category_manage',
        'menu_type' => '1',
        'icon' => '',
        'api_url' => 'recycle_quote_spider/source',
        'router_path' => 'recycle_quote_spider',
        'view_path' => 'index',
        'methods' => 'get',
        'sort' => '96',
        'status' => '1',
        'is_show' => '1',
        'children' => [
            [
                'menu_name' => '报价源列表',
                'menu_key' => 'recycle_quote_spider_source_list',
                'menu_short_name' => '报价源列表',
                'parent_select_key' => '',
                'menu_type' => '2',
                'icon' => '',
                'api_url' => 'recycle_quote_spider/source',
                'router_path' => '',
                'view_path' => '',
                'methods' => 'get',
                'sort' => '100',
                'status' => '1',
                'is_show' => '0',
            ],
            [
                'menu_name' => '保存报价源',
                'menu_key' => 'recycle_quote_spider_source_save',
                'menu_short_name' => '保存报价源',
                'parent_select_key' => '',
                'menu_type' => '2',
                'icon' => '',
                'api_url' => 'recycle_quote_spider/source',
                'router_path' => '',
                'view_path' => '',
                'methods' => 'post',
                'sort' => '90',
                'status' => '1',
                'is_show' => '0',
            ],
            [
                'menu_name' => '同步报价源',
                'menu_key' => 'recycle_quote_spider_source_sync',
                'menu_short_name' => '同步报价源',
                'parent_select_key' => '',
                'menu_type' => '2',
                'icon' => '',
                'api_url' => 'recycle_quote_spider/source/<id>/sync',
                'router_path' => '',
                'view_path' => '',
                'methods' => 'post',
                'sort' => '80',
                'status' => '1',
                'is_show' => '0',
            ],
            [
                'menu_name' => '分类管理',
                'menu_key' => 'recycle_quote_spider_category',
                'menu_short_name' => '分类管理',
                'parent_select_key' => '',
                'menu_type' => '2',
                'icon' => '',
                'api_url' => 'recycle_quote_spider/category',
                'router_path' => '',
                'view_path' => '',
                'methods' => 'get',
                'sort' => '70',
                'status' => '1',
                'is_show' => '0',
            ],
            [
                'menu_name' => '报价项管理',
                'menu_key' => 'recycle_quote_spider_item',
                'menu_short_name' => '报价项管理',
                'parent_select_key' => '',
                'menu_type' => '2',
                'icon' => '',
                'api_url' => 'recycle_quote_spider/item',
                'router_path' => '',
                'view_path' => '',
                'methods' => 'get',
                'sort' => '60',
                'status' => '1',
                'is_show' => '0',
            ],
            [
                'menu_name' => '报价工作台汇总',
                'menu_key' => 'recycle_quote_spider_item_summary',
                'menu_short_name' => '报价汇总',
                'parent_select_key' => '',
                'menu_type' => '2',
                'icon' => '',
                'api_url' => 'recycle_quote_spider/item/summary',
                'router_path' => '',
                'view_path' => '',
                'methods' => 'get',
                'sort' => '55',
                'status' => '1',
                'is_show' => '0',
            ],
            [
                'menu_name' => 'Excel导入',
                'menu_key' => 'recycle_quote_spider_import',
                'menu_short_name' => 'Excel导入',
                'parent_select_key' => '',
                'menu_type' => '2',
                'icon' => '',
                'api_url' => 'recycle_quote_spider/import/upload',
                'router_path' => '',
                'view_path' => '',
                'methods' => 'post',
                'sort' => '50',
                'status' => '1',
                'is_show' => '0',
            ],
            [
                'menu_name' => '同步日志',
                'menu_key' => 'recycle_quote_spider_log',
                'menu_short_name' => '同步日志',
                'parent_select_key' => '',
                'menu_type' => '2',
                'icon' => '',
                'api_url' => 'recycle_quote_spider/log',
                'router_path' => '',
                'view_path' => '',
                'methods' => 'get',
                'sort' => '40',
                'status' => '1',
                'is_show' => '0',
            ],
        ],
    ],
];