<?php

return [[
    'name' => '项目推广分享海报',
    'type' => 'hsx_project_center_distribution',
    'data' => [
        'global' => [
            'bgType' => 'color',
            'bgColor' => '#FFFDF0',
            'bgUrl' => '',
            'width' => 750,
            'height' => 1334,
        ],
        'value' => [
            [
                'id' => 'project_cover', 'componentName' => 'ProjectCenterCover', 'componentTitle' => '项目封面',
                'type' => 'image', 'path' => 'image', 'uses' => 1, 'relate' => 'project_cover',
                'value' => 'addon/hsx_project_center/cover.png', 'width' => 690, 'height' => 400,
                'minWidth' => 120, 'minHeight' => 100, 'x' => 30, 'y' => 30, 'angle' => 0, 'zIndex' => 1,
            ],
            [
                'id' => 'poster_eyebrow', 'componentName' => 'Text', 'componentTitle' => '海报眉题',
                'type' => 'text', 'path' => 'text', 'uses' => 0, 'relate' => '',
                'value' => '项目合作邀请 · PROJECT PARTNER', 'width' => 640, 'height' => 40,
                'minWidth' => 120, 'minHeight' => 36, 'x' => 55, 'y' => 468, 'angle' => 0, 'zIndex' => 3,
                'fontFamily' => '', 'fontSize' => 23, 'weight' => true, 'space' => 1,
                'lineHeight' => 0, 'fontColor' => '#756500', 'textAlign' => 'left',
            ],
            [
                'id' => 'project_title', 'componentName' => 'ProjectCenterTitle', 'componentTitle' => '项目名称',
                'type' => 'text', 'path' => 'text', 'uses' => 1, 'relate' => 'project_title',
                'value' => '项目合作邀请', 'width' => 640, 'height' => 96,
                'minWidth' => 120, 'minHeight' => 50, 'x' => 55, 'y' => 525, 'angle' => 0, 'zIndex' => 3,
                'fontFamily' => '', 'fontSize' => 44, 'weight' => true, 'space' => 0,
                'lineHeight' => 1, 'fontColor' => '#181818', 'textAlign' => 'left',
            ],
            [
                'id' => 'project_subtitle', 'componentName' => 'ProjectCenterSubtitle', 'componentTitle' => '项目简介',
                'type' => 'text', 'path' => 'text', 'uses' => 1, 'relate' => 'project_subtitle',
                'value' => '了解项目规则、参与条件与资料办理流程', 'width' => 640, 'height' => 72,
                'minWidth' => 120, 'minHeight' => 44, 'x' => 55, 'y' => 635, 'angle' => 0, 'zIndex' => 3,
                'fontFamily' => '', 'fontSize' => 25, 'weight' => false, 'space' => 0,
                'lineHeight' => 1, 'fontColor' => '#667085', 'textAlign' => 'left',
            ],
            [
                'id' => 'inviter_text', 'componentName' => 'ProjectCenterInviter', 'componentTitle' => '推广人',
                'type' => 'text', 'path' => 'text', 'uses' => 1, 'relate' => 'inviter_text',
                'value' => '项目推广人：会员昵称', 'width' => 640, 'height' => 42,
                'minWidth' => 120, 'minHeight' => 36, 'x' => 55, 'y' => 735, 'angle' => 0, 'zIndex' => 3,
                'fontFamily' => '', 'fontSize' => 25, 'weight' => true, 'space' => 0,
                'lineHeight' => 0, 'fontColor' => '#344054', 'textAlign' => 'left',
            ],
            [
                'id' => 'level_text', 'componentName' => 'ProjectCenterLevel', 'componentTitle' => '推广身份',
                'type' => 'text', 'path' => 'text', 'uses' => 1, 'relate' => 'level_text',
                'value' => '合作伙伴 · 一级佣金系数 100%', 'width' => 640, 'height' => 42,
                'minWidth' => 120, 'minHeight' => 36, 'x' => 55, 'y' => 785, 'angle' => 0, 'zIndex' => 3,
                'fontFamily' => '', 'fontSize' => 23, 'weight' => false, 'space' => 0,
                'lineHeight' => 0, 'fontColor' => '#756500', 'textAlign' => 'left',
            ],
            [
                'id' => 'qrcode', 'componentName' => 'Qrcode', 'componentTitle' => '二维码',
                'type' => 'qrcode', 'path' => 'qrcode', 'uses' => 1, 'relate' => 'url', 'value' => '',
                'width' => 250, 'height' => 250, 'minWidth' => 100, 'minHeight' => 100,
                'x' => 55, 'y' => 875, 'angle' => 0, 'zIndex' => 5,
            ],
            [
                'id' => 'scan_text', 'componentName' => 'ProjectCenterScanText', 'componentTitle' => '扫码提示',
                'type' => 'text', 'path' => 'text', 'uses' => 1, 'relate' => 'scan_text',
                'value' => '长按识别二维码，查看项目详情', 'width' => 350, 'height' => 70,
                'minWidth' => 120, 'minHeight' => 44, 'x' => 340, 'y' => 915, 'angle' => 0, 'zIndex' => 3,
                'fontFamily' => '', 'fontSize' => 29, 'weight' => true, 'space' => 0,
                'lineHeight' => 1, 'fontColor' => '#181818', 'textAlign' => 'left',
            ],
            [
                'id' => 'scan_subtitle', 'componentName' => 'Text', 'componentTitle' => '分享提示',
                'type' => 'text', 'path' => 'text', 'uses' => 0, 'relate' => '',
                'value' => '分享给有需要的朋友\n对方进入项目页后自动确认邀请关系',
                'width' => 350, 'height' => 90, 'minWidth' => 120, 'minHeight' => 44,
                'x' => 340, 'y' => 1000, 'angle' => 0, 'zIndex' => 3,
                'fontFamily' => '', 'fontSize' => 23, 'weight' => false, 'space' => 0,
                'lineHeight' => 1, 'fontColor' => '#667085', 'textAlign' => 'left',
            ],
            [
                'id' => 'footer_text', 'componentName' => 'ProjectCenterFooter', 'componentTitle' => '海报说明',
                'type' => 'text', 'path' => 'text', 'uses' => 1, 'relate' => 'footer_text',
                'value' => '项目说明、参与条件及实际办理结果以项目页面为准', 'width' => 640, 'height' => 42,
                'minWidth' => 120, 'minHeight' => 36, 'x' => 55, 'y' => 1215, 'angle' => 0, 'zIndex' => 3,
                'fontFamily' => '', 'fontSize' => 21, 'weight' => false, 'space' => 0,
                'lineHeight' => 0, 'fontColor' => '#98A2B3', 'textAlign' => 'center',
            ],
        ],
    ],
]];
