-- ============================================================
-- hsx_erp clean install SQL
-- ERP 独立产品:采购/库存/销售/财务确认/折账/流水/集成事件
-- ============================================================

CREATE TABLE IF NOT EXISTS `{{prefix}}erp_capital_account` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `site_id` int NOT NULL DEFAULT 0 COMMENT '站点ID',
  `account_name` varchar(100) NOT NULL DEFAULT '' COMMENT '账户名称',
  `account_type` varchar(20) NOT NULL DEFAULT 'bank' COMMENT 'cash现金/wechat微信/alipay支付宝/bank银行卡/other其他',
  `bank_name` varchar(100) NOT NULL DEFAULT '' COMMENT '开户行',
  `account_no` varchar(100) NOT NULL DEFAULT '' COMMENT '账号/卡号',
  `holder` varchar(60) NOT NULL DEFAULT '' COMMENT '户名',
  `balance` decimal(14,2) NOT NULL DEFAULT 0.00 COMMENT '当前余额',
  `is_default` tinyint(1) NOT NULL DEFAULT 0 COMMENT '默认账户',
  `status` tinyint(1) NOT NULL DEFAULT 1 COMMENT '1启用/0停用',
  `sort` int NOT NULL DEFAULT 0,
  `remark` varchar(255) NOT NULL DEFAULT '',
  `create_at` int NOT NULL DEFAULT 0,
  `update_at` int NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_site_status` (`site_id`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='ERP-资金账户';

CREATE TABLE IF NOT EXISTS `{{prefix}}erp_warehouse` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `site_id` int NOT NULL DEFAULT 0 COMMENT '站点ID',
  `warehouse_name` varchar(100) NOT NULL DEFAULT '' COMMENT '仓库名称',
  `warehouse_code` varchar(60) NOT NULL DEFAULT '' COMMENT '仓库编码',
  `manager_uid` int NOT NULL DEFAULT 0 COMMENT '仓库负责人UID',
  `manager_name` varchar(60) NOT NULL DEFAULT '' COMMENT '仓库负责人名称快照',
  `warehouse_type` varchar(20) NOT NULL DEFAULT 'owned' COMMENT 'owned二手机/peer同行/consignment代卖/exception异常',
  `ownership_type` varchar(20) NOT NULL DEFAULT 'owned' COMMENT 'owned自有/consigned代卖/pending待定',
  `need_photo` tinyint(1) NOT NULL DEFAULT 0 COMMENT '是否需要拍照',
  `need_pricing` tinyint(1) NOT NULL DEFAULT 0 COMMENT '是否需要定价',
  `allow_direct_sale` tinyint(1) NOT NULL DEFAULT 1 COMMENT '是否允许直接销售',
  `allow_transfer` tinyint(1) NOT NULL DEFAULT 1 COMMENT '是否允许调拨',
  `default_sale_target` varchar(20) NOT NULL DEFAULT 'unset' COMMENT 'unset未定/peer同行/mall商城',
  `status` tinyint(1) NOT NULL DEFAULT 1 COMMENT '1启用/0停用',
  `is_default` tinyint(1) NOT NULL DEFAULT 0 COMMENT '默认入库仓',
  `sort` int NOT NULL DEFAULT 0,
  `remark` varchar(255) NOT NULL DEFAULT '',
  `create_at` int NOT NULL DEFAULT 0,
  `update_at` int NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_site_name` (`site_id`,`warehouse_name`),
  KEY `idx_site_status` (`site_id`,`status`,`sort`),
  KEY `idx_site_manager` (`site_id`,`manager_uid`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='ERP-仓库';

CREATE TABLE IF NOT EXISTS `{{prefix}}erp_warehouse_location` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `site_id` int NOT NULL DEFAULT 0 COMMENT '站点ID',
  `warehouse_id` int NOT NULL DEFAULT 0 COMMENT '仓库ID',
  `location_name` varchar(100) NOT NULL DEFAULT '' COMMENT '库位名称',
  `location_code` varchar(60) NOT NULL DEFAULT '' COMMENT '库位编码',
  `manager_uid` int NOT NULL DEFAULT 0 COMMENT '库位负责人UID，0表示继承仓库负责人',
  `manager_name` varchar(60) NOT NULL DEFAULT '' COMMENT '库位负责人名称快照',
  `status` tinyint(1) NOT NULL DEFAULT 1 COMMENT '1启用/0停用',
  `sort` int NOT NULL DEFAULT 0,
  `remark` varchar(255) NOT NULL DEFAULT '',
  `create_at` int NOT NULL DEFAULT 0,
  `update_at` int NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_warehouse_name` (`site_id`,`warehouse_id`,`location_name`),
  KEY `idx_site_warehouse` (`site_id`,`warehouse_id`,`status`,`sort`),
  KEY `idx_site_manager` (`site_id`,`manager_uid`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='ERP-仓库库位';

CREATE TABLE IF NOT EXISTS `{{prefix}}erp_party` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `site_id` int NOT NULL DEFAULT 0 COMMENT '站点ID',
  `party_no` varchar(40) NOT NULL DEFAULT '' COMMENT '往来单位编号',
  `party_name` varchar(100) NOT NULL DEFAULT '' COMMENT '往来单位名称',
  `party_type` varchar(20) NOT NULL DEFAULT 'customer' COMMENT 'customer客户/supplier供应商/channel渠道/other其他',
  `role_flags` varchar(255) NOT NULL DEFAULT '' COMMENT '多身份：purchase_supplier,sale_customer,recycle_customer,refurbish_provider',
  `group_keys` varchar(255) NOT NULL DEFAULT '' COMMENT '业务分组，逗号分隔',
  `credit_policy` varchar(20) NOT NULL DEFAULT 'inherit' COMMENT 'inherit跟随规则/normal正常/remind提醒/cash_only仅现结/blocked暂停交易',
  `credit_limit` decimal(14,2) NOT NULL DEFAULT 0.00 COMMENT '允许挂账的信用额度，0表示不限额',
  `credit_remark` varchar(255) NOT NULL DEFAULT '' COMMENT '信用限制原因或备注',
  `credit_update_uid` int NOT NULL DEFAULT 0 COMMENT '信用策略最后调整人UID',
  `credit_update_name` varchar(60) NOT NULL DEFAULT '' COMMENT '信用策略最后调整人名称',
  `credit_update_at` int NOT NULL DEFAULT 0 COMMENT '信用策略最后调整时间',
  `contact_name` varchar(60) NOT NULL DEFAULT '' COMMENT '联系人',
  `contact_mobile` varchar(30) NOT NULL DEFAULT '' COMMENT '联系电话',
  `m_no` varchar(64) NOT NULL DEFAULT '' COMMENT 'M号/会员号/业务编号',
  `remark` varchar(255) NOT NULL DEFAULT '',
  `status` tinyint(1) NOT NULL DEFAULT 1 COMMENT '1启用/0停用',
  `create_at` int NOT NULL DEFAULT 0,
  `update_at` int NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_site_no` (`site_id`,`party_no`),
  KEY `idx_site_name` (`site_id`,`party_name`),
  KEY `idx_site_mno` (`site_id`,`m_no`),
  KEY `idx_site_credit` (`site_id`,`credit_policy`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='ERP-往来单位';

CREATE TABLE IF NOT EXISTS `{{prefix}}erp_party_member` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `site_id` int NOT NULL DEFAULT 0 COMMENT '站点ID',
  `party_id` int NOT NULL DEFAULT 0 COMMENT '往来主体ID',
  `member_id` int NOT NULL DEFAULT 0 COMMENT '对接人会员ID',
  `relation_role` varchar(20) NOT NULL DEFAULT 'business' COMMENT 'owner/finance/business',
  `is_finance_contact` tinyint(1) NOT NULL DEFAULT 0 COMMENT '是否主要财务联系人',
  `status` tinyint(1) NOT NULL DEFAULT 1 COMMENT '1有效/0失效',
  `remark` varchar(255) NOT NULL DEFAULT '',
  `create_at` int NOT NULL DEFAULT 0,
  `update_at` int NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_site_member` (`site_id`,`member_id`),
  KEY `idx_party` (`site_id`,`party_id`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='ERP-往来主体对接人';

CREATE TABLE IF NOT EXISTS `{{prefix}}erp_kpi_rule` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `site_id` int NOT NULL DEFAULT 0,
  `metric_key` varchar(40) NOT NULL DEFAULT '' COMMENT '指标稳定编码',
  `metric_name` varchar(60) NOT NULL DEFAULT '' COMMENT '指标名称',
  `unit` varchar(20) NOT NULL DEFAULT '' COMMENT '元/笔/台',
  `target_value` decimal(14,2) NOT NULL DEFAULT 0.00 COMMENT '周期目标',
  `weight` decimal(6,2) NOT NULL DEFAULT 0.00 COMMENT '绩效权重',
  `enabled` tinyint(1) NOT NULL DEFAULT 1,
  `sort` int NOT NULL DEFAULT 0,
  `create_at` int NOT NULL DEFAULT 0,
  `update_at` int NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_site_metric` (`site_id`,`metric_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='ERP-员工KPI规则';

CREATE TABLE IF NOT EXISTS `{{prefix}}erp_catalog_product_master` (
  `master_product_id` int unsigned NOT NULL AUTO_INCREMENT,
  `created_site_id` int NOT NULL DEFAULT 0 COMMENT '首次写入站点，仅用于审计',
  `source_key` varchar(40) NOT NULL DEFAULT '' COMMENT '标准目录来源命名空间',
  `source_product_id` varchar(80) NOT NULL DEFAULT '' COMMENT '来源产品ID，不作为数据库主键',
  `category_source_id` varchar(80) NOT NULL DEFAULT '' COMMENT '来源末级品类ID',
  `category_path` varchar(255) NOT NULL DEFAULT '' COMMENT '来源品类路径',
  `brand_source_id` varchar(80) NOT NULL DEFAULT '' COMMENT '来源品牌ID',
  `brand_name` varchar(100) NOT NULL DEFAULT '' COMMENT '标准品牌名称',
  `series_name` varchar(100) NOT NULL DEFAULT '' COMMENT '标准系列名称',
  `product_name` varchar(150) NOT NULL DEFAULT '' COMMENT '标准产品型号',
  `data_hash` char(64) NOT NULL DEFAULT '' COMMENT '标准记录内容摘要',
  `create_at` int NOT NULL DEFAULT 0,
  `update_at` int NOT NULL DEFAULT 0,
  PRIMARY KEY (`master_product_id`),
  UNIQUE KEY `uk_source_product` (`source_key`,`source_product_id`),
  KEY `idx_product_name` (`product_name`),
  KEY `idx_brand_series` (`brand_name`,`series_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='ERP-平台标准产品模板';

CREATE TABLE IF NOT EXISTS `{{prefix}}erp_site_catalog_product` (
  `site_product_id` int unsigned NOT NULL AUTO_INCREMENT,
  `site_id` int NOT NULL DEFAULT 0,
  `master_product_id` int NOT NULL DEFAULT 0,
  `category_path` varchar(255) NOT NULL DEFAULT '' COMMENT '一级品类/可选一级子分类',
  `product_name` varchar(150) NOT NULL DEFAULT '' COMMENT '本站产品名称，可独立覆盖',
  `brand_name` varchar(100) NOT NULL DEFAULT '' COMMENT '本站品牌名称快照',
  `series_name` varchar(100) NOT NULL DEFAULT '' COMMENT '本站系列名称快照',
  `is_enabled` tinyint(1) NOT NULL DEFAULT 1,
  `sort` int NOT NULL DEFAULT 0,
  `create_at` int NOT NULL DEFAULT 0,
  `update_at` int NOT NULL DEFAULT 0,
  PRIMARY KEY (`site_product_id`),
  UNIQUE KEY `uk_site_master` (`site_id`,`master_product_id`),
  KEY `idx_site_category_path` (`site_id`,`category_path`(100),`is_enabled`),
  KEY `idx_site_brand_series` (`site_id`,`brand_name`,`series_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='ERP-站点产品目录绑定';

CREATE TABLE IF NOT EXISTS `{{prefix}}erp_catalog_import_task` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT '任务ID',
  `site_id` int NOT NULL DEFAULT 0 COMMENT '站点ID',
  `operator_uid` int NOT NULL DEFAULT 0 COMMENT '操作人UID',
  `operator_name` varchar(60) NOT NULL DEFAULT '' COMMENT '操作人名称',
  `source_key` varchar(40) NOT NULL DEFAULT 'excel_product_catalog' COMMENT '标准目录来源命名空间',
  `file_name` varchar(255) NOT NULL DEFAULT '' COMMENT '原始文件名',
  `file_path` varchar(500) NOT NULL DEFAULT '' COMMENT '服务端文件路径',
  `sheet_name` varchar(120) NOT NULL DEFAULT '' COMMENT '工作表名称',
  `status` varchar(20) NOT NULL DEFAULT 'pending' COMMENT 'pending/queued/processing/completed/partial/failed',
  `queue_enabled` tinyint(1) NOT NULL DEFAULT 0 COMMENT '创建时是否启用队列',
  `total_rows` int NOT NULL DEFAULT 0 COMMENT '数据总行数',
  `processed_rows` int NOT NULL DEFAULT 0 COMMENT '已处理行数',
  `created_count` int NOT NULL DEFAULT 0 COMMENT '本站新增产品数',
  `updated_count` int NOT NULL DEFAULT 0 COMMENT '本站更新产品数',
  `skipped_count` int NOT NULL DEFAULT 0 COMMENT '跳过数量',
  `error_count` int NOT NULL DEFAULT 0 COMMENT '错误数量',
  `result_json` longtext NULL COMMENT '统计、冲突与错误样例JSON',
  `message` varchar(500) NOT NULL DEFAULT '' COMMENT '任务提示',
  `error_message` varchar(1000) NOT NULL DEFAULT '' COMMENT '失败原因',
  `start_at` int NOT NULL DEFAULT 0 COMMENT '开始时间',
  `finish_at` int NOT NULL DEFAULT 0 COMMENT '完成时间',
  `create_at` int NOT NULL DEFAULT 0 COMMENT '创建时间',
  `update_at` int NOT NULL DEFAULT 0 COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_site_status` (`site_id`,`status`),
  KEY `idx_site_create` (`site_id`,`create_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='ERP-商品目录异步导入任务';

CREATE TABLE IF NOT EXISTS `{{prefix}}erp_channel_category_mapping` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `site_id` int NOT NULL DEFAULT 0 COMMENT '站点ID',
  `channel_key` varchar(40) NOT NULL DEFAULT '' COMMENT '渠道稳定编码',
  `erp_category_key` char(64) NOT NULL DEFAULT '' COMMENT 'ERP分类路径摘要',
  `erp_category_path` varchar(255) NOT NULL DEFAULT '' COMMENT 'ERP分类路径快照',
  `channel_category_id` varchar(80) NOT NULL DEFAULT '' COMMENT '渠道末级分类ID',
  `channel_category_path` text COMMENT '渠道分类ID路径JSON',
  `channel_category_name` varchar(255) NOT NULL DEFAULT '' COMMENT '渠道分类路径快照',
  `mapping_source` varchar(20) NOT NULL DEFAULT 'manual' COMMENT 'manual/projection',
  `status` varchar(20) NOT NULL DEFAULT 'active' COMMENT 'active/disabled',
  `operator_uid` int NOT NULL DEFAULT 0,
  `operator_name` varchar(60) NOT NULL DEFAULT '',
  `create_at` int NOT NULL DEFAULT 0,
  `update_at` int NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_site_channel_erp_category` (`site_id`,`channel_key`,`erp_category_key`),
  KEY `idx_channel_category` (`site_id`,`channel_key`,`channel_category_id`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='ERP-渠道分类映射';

CREATE TABLE IF NOT EXISTS `{{prefix}}erp_channel_attribute_mapping` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `site_id` int NOT NULL DEFAULT 0,
  `channel_key` varchar(40) NOT NULL DEFAULT '',
  `erp_attribute_id` int NOT NULL DEFAULT 0 COMMENT 'ERP规格分组ID，0为内置字段',
  `erp_attribute_key` varchar(100) NOT NULL DEFAULT '' COMMENT 'ERP规格稳定编码',
  `erp_attribute_name` varchar(100) NOT NULL DEFAULT '' COMMENT 'ERP规格名称快照',
  `channel_attribute_id` varchar(80) NOT NULL DEFAULT '' COMMENT '渠道参数ID/稳定编码',
  `channel_attribute_name` varchar(100) NOT NULL DEFAULT '' COMMENT '渠道参数名称快照',
  `mapping_source` varchar(20) NOT NULL DEFAULT 'manual',
  `status` varchar(20) NOT NULL DEFAULT 'active',
  `operator_uid` int NOT NULL DEFAULT 0,
  `operator_name` varchar(60) NOT NULL DEFAULT '',
  `create_at` int NOT NULL DEFAULT 0,
  `update_at` int NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_site_channel_erp_attribute` (`site_id`,`channel_key`,`erp_attribute_key`),
  KEY `idx_channel_attribute` (`site_id`,`channel_key`,`channel_attribute_id`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='ERP-渠道规格字段映射';

CREATE TABLE IF NOT EXISTS `{{prefix}}erp_channel_attribute_value_mapping` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `site_id` int NOT NULL DEFAULT 0,
  `channel_key` varchar(40) NOT NULL DEFAULT '',
  `erp_attribute_key` varchar(100) NOT NULL DEFAULT '',
  `erp_value_key` varchar(100) NOT NULL DEFAULT '' COMMENT 'ERP规格值摘要/稳定编码',
  `erp_value_name` varchar(150) NOT NULL DEFAULT '' COMMENT 'ERP规格值快照',
  `channel_attribute_id` varchar(80) NOT NULL DEFAULT '',
  `channel_value_id` varchar(100) NOT NULL DEFAULT '' COMMENT '渠道规格值ID/稳定编码',
  `channel_value_name` varchar(150) NOT NULL DEFAULT '' COMMENT '渠道规格值快照',
  `mapping_source` varchar(20) NOT NULL DEFAULT 'manual',
  `status` varchar(20) NOT NULL DEFAULT 'active',
  `operator_uid` int NOT NULL DEFAULT 0,
  `operator_name` varchar(60) NOT NULL DEFAULT '',
  `create_at` int NOT NULL DEFAULT 0,
  `update_at` int NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_site_channel_erp_value` (`site_id`,`channel_key`,`erp_attribute_key`,`erp_value_key`),
  KEY `idx_channel_value` (`site_id`,`channel_key`,`channel_attribute_id`,`channel_value_id`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='ERP-渠道规格值映射';

CREATE TABLE IF NOT EXISTS `{{prefix}}erp_channel_listing` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `site_id` int NOT NULL DEFAULT 0,
  `channel_key` varchar(40) NOT NULL DEFAULT '',
  `erp_asset_id` int NOT NULL DEFAULT 0 COMMENT 'ERP设备ID',
  `channel_item_id` varchar(80) NOT NULL DEFAULT '' COMMENT '渠道商品ID',
  `channel_intake_id` varchar(80) NOT NULL DEFAULT '' COMMENT '渠道待办/货源ID',
  `status` varchar(20) NOT NULL DEFAULT 'pending' COMMENT 'pending/published/offline/sold/error',
  `publish_mode` varchar(20) NOT NULL DEFAULT 'direct' COMMENT 'direct/manual',
  `mapping_snapshot` longtext COMMENT '上架时映射快照JSON',
  `payload_hash` char(64) NOT NULL DEFAULT '' COMMENT '上架载荷摘要',
  `last_error` varchar(1000) NOT NULL DEFAULT '',
  `published_at` int NOT NULL DEFAULT 0,
  `create_at` int NOT NULL DEFAULT 0,
  `update_at` int NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_site_channel_asset` (`site_id`,`channel_key`,`erp_asset_id`),
  KEY `idx_channel_item` (`site_id`,`channel_key`,`channel_item_id`),
  KEY `idx_site_status` (`site_id`,`channel_key`,`status`,`update_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='ERP-渠道商品关联';

CREATE TABLE IF NOT EXISTS `{{prefix}}erp_goods_spec_group` (
  `group_id` int unsigned NOT NULL AUTO_INCREMENT COMMENT '规格分组ID',
  `site_id` int NOT NULL DEFAULT 0 COMMENT '站点ID',
  `label` varchar(80) NOT NULL DEFAULT '' COMMENT '规格名称，如内存/容量',
  `title_part` tinyint(1) NOT NULL DEFAULT 1 COMMENT '是否参与型号标题',
  `sort` int NOT NULL DEFAULT 0 COMMENT '排序',
  `create_at` int NOT NULL DEFAULT 0,
  `update_at` int NOT NULL DEFAULT 0,
  PRIMARY KEY (`group_id`),
  UNIQUE KEY `uk_site_label` (`site_id`,`label`),
  KEY `idx_site_sort` (`site_id`,`sort`,`group_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='ERP-商品规格分组';

CREATE TABLE IF NOT EXISTS `{{prefix}}erp_goods_spec_item` (
  `item_id` int unsigned NOT NULL AUTO_INCREMENT COMMENT '规格项ID',
  `site_id` int NOT NULL DEFAULT 0 COMMENT '站点ID',
  `group_id` int NOT NULL DEFAULT 0 COMMENT '规格分组ID',
  `item_value` varchar(100) NOT NULL DEFAULT '' COMMENT '规格值',
  `sort` int NOT NULL DEFAULT 0 COMMENT '排序',
  `create_at` int NOT NULL DEFAULT 0,
  `update_at` int NOT NULL DEFAULT 0,
  PRIMARY KEY (`item_id`),
  UNIQUE KEY `uk_site_group_value` (`site_id`,`group_id`,`item_value`),
  KEY `idx_site_group` (`site_id`,`group_id`,`sort`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='ERP-商品规格项';

CREATE TABLE IF NOT EXISTS `{{prefix}}erp_goods_grade` (
  `grade_id` int unsigned NOT NULL AUTO_INCREMENT COMMENT '成色ID',
  `site_id` int NOT NULL DEFAULT 0 COMMENT '站点ID',
  `grade_name` varchar(100) NOT NULL DEFAULT '' COMMENT '成色名称',
  `sort` int NOT NULL DEFAULT 0 COMMENT '排序',
  `status` tinyint(1) NOT NULL DEFAULT 1 COMMENT '1启用/0禁用',
  `create_at` int NOT NULL DEFAULT 0,
  `update_at` int NOT NULL DEFAULT 0,
  PRIMARY KEY (`grade_id`),
  UNIQUE KEY `uk_site_grade` (`site_id`,`grade_name`),
  KEY `idx_site_sort` (`site_id`,`status`,`sort`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='ERP-商品成色';

CREATE TABLE IF NOT EXISTS `{{prefix}}erp_asset` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `site_id` int NOT NULL DEFAULT 0 COMMENT '站点ID',
  `asset_no` varchar(40) NOT NULL DEFAULT '' COMMENT '资产编号',
  `purchase_order_id` int NOT NULL DEFAULT 0 COMMENT '采购单ID',
  `purchase_item_id` int NOT NULL DEFAULT 0 COMMENT '采购明细ID',
  `sale_order_id` int NOT NULL DEFAULT 0 COMMENT '销售单ID',
  `sale_item_id` int NOT NULL DEFAULT 0 COMMENT '销售明细ID',
  `party_id` int NOT NULL DEFAULT 0 COMMENT '采购来源往来单位',
  `party_name` varchar(100) NOT NULL DEFAULT '' COMMENT '采购来源名称快照',
  `ownership_type` varchar(20) NOT NULL DEFAULT 'owned' COMMENT 'owned自有/consigned代卖/pending待确认',
  `owner_party_id` int NOT NULL DEFAULT 0 COMMENT '当前物权主体，0表示本公司',
  `owner_party_name` varchar(100) NOT NULL DEFAULT '' COMMENT '当前物权主体名称快照',
  `ownership_source_type` varchar(40) NOT NULL DEFAULT '' COMMENT '最近一次物权取得业务类型',
  `ownership_source_id` int NOT NULL DEFAULT 0 COMMENT '最近一次物权取得业务ID',
  `ownership_source_no` varchar(40) NOT NULL DEFAULT '' COMMENT '最近一次物权取得业务单号',
  `ownership_changed_at` int NOT NULL DEFAULT 0 COMMENT '最近一次物权变更时间',
  `warehouse_id` int NOT NULL DEFAULT 0 COMMENT '仓库ID',
  `warehouse_name` varchar(100) NOT NULL DEFAULT '' COMMENT '仓库名称快照',
  `location_id` int NOT NULL DEFAULT 0 COMMENT '库位ID',
  `location_name` varchar(100) NOT NULL DEFAULT '' COMMENT '库位名称快照',
  `imei` varchar(64) NOT NULL DEFAULT '',
  `sn` varchar(64) NOT NULL DEFAULT '',
  `model` varchar(255) NOT NULL DEFAULT '',
  `spec` varchar(255) NOT NULL DEFAULT '' COMMENT '容量/颜色/成色等',
  `spec_json` longtext COMMENT '结构化规格JSON',
  `color` varchar(50) NOT NULL DEFAULT '' COMMENT '颜色',
  `battery` tinyint NOT NULL DEFAULT 0 COMMENT '电池效率百分比',
  `warranty` int NOT NULL DEFAULT 0 COMMENT '保修截止时间',
  `catalog_product_id` int NOT NULL DEFAULT 0 COMMENT '本站ERP目录产品ID',
  `category_name` varchar(100) NOT NULL DEFAULT '' COMMENT '末级品类名称快照',
  `category_path` varchar(255) NOT NULL DEFAULT '' COMMENT '一级品类/可选一级子分类快照',
  `inspector_uid` int NOT NULL DEFAULT 0 COMMENT '质检员UID',
  `inspector_name` varchar(60) NOT NULL DEFAULT '' COMMENT '质检员名称快照',
  `estimate_sale_price` decimal(12,2) NOT NULL DEFAULT 0.00 COMMENT '入库预估售价',
  `retail_price` decimal(12,2) NOT NULL DEFAULT 0.00 COMMENT '零售价（上架商城定价，由库管设置）',
  `image_urls` text COMMENT '入库图片JSON/逗号分隔',
  `quality_remark` varchar(500) NOT NULL DEFAULT '' COMMENT '质检/外观备注',
  `qc_template_id` int NOT NULL DEFAULT 0 COMMENT '来源质检模板ID快照',
  `qc_report` longtext COMMENT '标准化质检报告JSON快照，供ERP与商城消费',
  `purchase_cost` decimal(12,2) NOT NULL DEFAULT 0.00 COMMENT '采购成本',
  `adjust_cost` decimal(12,2) NOT NULL DEFAULT 0.00 COMMENT '成本调整合计',
  `refurbish_cost` decimal(12,2) NOT NULL DEFAULT 0.00 COMMENT '整备成本合计',
  `total_cost` decimal(12,2) NOT NULL DEFAULT 0.00 COMMENT '当前总成本',
  `refurbish_status` varchar(20) NOT NULL DEFAULT 'none' COMMENT 'none无需/pending待整备/processing整备中/done已完成/failed整备异常',
  `refurbish_pending_at` int NOT NULL DEFAULT 0 COMMENT '进入待整备时间',
  `refurbish_batch_no` varchar(40) NOT NULL DEFAULT '' COMMENT '整备交接批次号',
  `refurbish_provider_id` int NOT NULL DEFAULT 0 COMMENT '当前外送整备商主体ID',
  `refurbish_provider_name` varchar(100) NOT NULL DEFAULT '' COMMENT '当前外送整备商名称快照',
  `refurbish_sent_at` int NOT NULL DEFAULT 0 COMMENT '送修/开始整备时间',
  `refurbish_sent_uid` int NOT NULL DEFAULT 0 COMMENT '送修经手人UID',
  `refurbish_sent_name` varchar(60) NOT NULL DEFAULT '' COMMENT '送修经手人名称',
  `refurbish_result` varchar(20) NOT NULL DEFAULT '' COMMENT 'success修复成功/partial部分修复/failed修复失败',
  `refurbish_completed_at` int NOT NULL DEFAULT 0 COMMENT '整备完成时间',
  `refurbish_completed_uid` int NOT NULL DEFAULT 0 COMMENT '整备完工登记人UID',
  `refurbish_completed_name` varchar(60) NOT NULL DEFAULT '' COMMENT '整备完工登记人名称',
  `refurbish_voucher_urls` text COMMENT '整备结果/费用凭证图片',
  `refurbish_remark` varchar(500) NOT NULL DEFAULT '' COMMENT '整备交接及结果说明',
  `sale_target` varchar(20) NOT NULL DEFAULT 'unset' COMMENT 'unset未定/peer卖同行/mall上商城',
  `listing_status` varchar(20) NOT NULL DEFAULT 'none' COMMENT 'none无需/need_photo待拍照/need_price待商城定价/need_material待完善资料/ready待上架/pending_shop待商城完善/listed已上架',
  `task_stage_key` varchar(40) NOT NULL DEFAULT '' COMMENT '当前ERP待办环节',
  `task_assignee_uid` int NOT NULL DEFAULT 0 COMMENT '当前待办责任人UID',
  `task_assignee_name` varchar(60) NOT NULL DEFAULT '' COMMENT '当前待办责任人名称快照',
  `task_assigner_uid` int NOT NULL DEFAULT 0 COMMENT '最近分配人UID',
  `task_assigner_name` varchar(60) NOT NULL DEFAULT '' COMMENT '最近分配人名称快照',
  `task_assigned_at` int NOT NULL DEFAULT 0 COMMENT '最近分配时间',
  `sale_price` decimal(12,2) NOT NULL DEFAULT 0.00 COMMENT '销售价快照',
  `profit` decimal(12,2) NOT NULL DEFAULT 0.00 COMMENT '毛利快照',
  `status` varchar(20) NOT NULL DEFAULT 'in_stock' COMMENT 'in_stock库存中/sold已售/returned已退/void作废',
  `source_plugin` varchar(40) NOT NULL DEFAULT 'erp' COMMENT '来源插件',
  `source_type` varchar(40) NOT NULL DEFAULT 'manual' COMMENT '来源类型',
  `source_id` varchar(64) NOT NULL DEFAULT '' COMMENT '来源ID',
  `remark` varchar(255) NOT NULL DEFAULT '',
  `remark_public` varchar(500) NOT NULL DEFAULT '' COMMENT '对外备注（展示给客户/商城）',
  `remark_internal` varchar(500) NOT NULL DEFAULT '' COMMENT '对内备注（员工内部，不对外展示）',
  `stock_in_at` int NOT NULL DEFAULT 0 COMMENT '实际入库时间戳（计算库龄，采购入库时写入）',
  `create_at` int NOT NULL DEFAULT 0,
  `update_at` int NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_site_no` (`site_id`,`asset_no`),
  KEY `idx_site_status` (`site_id`,`status`),
  KEY `idx_site_ownership` (`site_id`,`ownership_type`,`owner_party_id`,`status`),
  KEY `idx_site_refurbish` (`site_id`,`refurbish_status`,`refurbish_pending_at`),
  KEY `idx_site_refurbish_provider` (`site_id`,`refurbish_provider_id`,`refurbish_status`),
  KEY `idx_site_task_assignee` (`site_id`,`task_stage_key`,`task_assignee_uid`,`task_assigned_at`),
  KEY `idx_site_imei` (`site_id`,`imei`),
  KEY `idx_site_sn` (`site_id`,`sn`),
  KEY `idx_site_catalog_product` (`site_id`,`catalog_product_id`,`status`),
  KEY `idx_site_attr` (`site_id`,`color`,`battery`,`warranty`),
  KEY `idx_purchase` (`purchase_order_id`,`purchase_item_id`),
  KEY `idx_sale` (`sale_order_id`,`sale_item_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='ERP-库存资产';

CREATE TABLE IF NOT EXISTS `{{prefix}}erp_asset_ledger` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `site_id` int NOT NULL DEFAULT 0,
  `request_id` varchar(80) DEFAULT NULL COMMENT '客户端幂等请求ID',
  `ledger_no` varchar(40) NOT NULL DEFAULT '' COMMENT '流水号',
  `asset_id` int NOT NULL DEFAULT 0,
  `asset_no` varchar(40) NOT NULL DEFAULT '' COMMENT '设备资产号快照',
  `imei` varchar(80) NOT NULL DEFAULT '' COMMENT 'IMEI快照',
  `model` varchar(120) NOT NULL DEFAULT '' COMMENT '型号快照',
  `action` varchar(30) NOT NULL DEFAULT '' COMMENT 'inbound/sold/return/adjust/refurbish/void',
  `before_status` varchar(20) NOT NULL DEFAULT '',
  `after_status` varchar(20) NOT NULL DEFAULT '',
  `before_warehouse_id` int NOT NULL DEFAULT 0,
  `before_warehouse_name` varchar(100) NOT NULL DEFAULT '',
  `before_location_id` int NOT NULL DEFAULT 0,
  `before_location_name` varchar(100) NOT NULL DEFAULT '',
  `after_warehouse_id` int NOT NULL DEFAULT 0,
  `after_warehouse_name` varchar(100) NOT NULL DEFAULT '',
  `after_location_id` int NOT NULL DEFAULT 0,
  `after_location_name` varchar(100) NOT NULL DEFAULT '',
  `before_total_cost` decimal(12,2) NOT NULL DEFAULT 0.00 COMMENT '变化前成本',
  `after_total_cost` decimal(12,2) NOT NULL DEFAULT 0.00 COMMENT '变化后成本',
  `cost_delta` decimal(12,2) NOT NULL DEFAULT 0.00 COMMENT '成本变化',
  `party_id` int NOT NULL DEFAULT 0,
  `party_name` varchar(100) NOT NULL DEFAULT '',
  `source_type` varchar(40) NOT NULL DEFAULT '',
  `source_id` int NOT NULL DEFAULT 0,
  `source_no` varchar(40) NOT NULL DEFAULT '',
  `operator_uid` int NOT NULL DEFAULT 0,
  `operator_name` varchar(60) NOT NULL DEFAULT '',
  `remark` varchar(255) NOT NULL DEFAULT '',
  `extra_json` longtext COMMENT '扩展快照',
  `occurred_at` int NOT NULL DEFAULT 0,
  `create_at` int NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ledger_no` (`site_id`,`ledger_no`),
  UNIQUE KEY `uk_site_request` (`site_id`,`request_id`),
  KEY `idx_asset` (`site_id`,`asset_id`),
  KEY `idx_action` (`site_id`,`action`),
  KEY `idx_action_source_no` (`site_id`,`action`,`source_no`),
  KEY `idx_source` (`site_id`,`source_type`,`source_id`),
  KEY `idx_occurred` (`site_id`,`occurred_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='ERP-资产流水';

CREATE TABLE IF NOT EXISTS `{{prefix}}erp_purchase_order` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `site_id` int NOT NULL DEFAULT 0,
  `request_id` varchar(80) DEFAULT NULL COMMENT '客户端幂等请求ID',
  `purchase_no` varchar(40) NOT NULL DEFAULT '' COMMENT '采购单号',
  `party_id` int NOT NULL DEFAULT 0 COMMENT '采购渠道/供应商/客户',
  `party_name` varchar(100) NOT NULL DEFAULT '',
  `m_no` varchar(64) NOT NULL DEFAULT '' COMMENT 'M号',
  `purchase_channel` varchar(60) NOT NULL DEFAULT '' COMMENT '采购渠道',
  `settle_method` varchar(30) NOT NULL DEFAULT '' COMMENT '结算方式',
  `capital_account_id` int NOT NULL DEFAULT 0 COMMENT '本次付款账户',
  `capital_account_name` varchar(100) NOT NULL DEFAULT '' COMMENT '本次付款账户名称',
  `warehouse_id` int NOT NULL DEFAULT 0,
  `warehouse_name` varchar(100) NOT NULL DEFAULT '',
  `location_id` int NOT NULL DEFAULT 0,
  `location_name` varchar(100) NOT NULL DEFAULT '',
  `purchaser_uid` int NOT NULL DEFAULT 0,
  `purchaser_name` varchar(60) NOT NULL DEFAULT '',
  `inspector_uid` int NOT NULL DEFAULT 0,
  `inspector_name` varchar(60) NOT NULL DEFAULT '',
  `total_cost` decimal(12,2) NOT NULL DEFAULT 0.00,
  `paid_amount` decimal(12,2) NOT NULL DEFAULT 0.00 COMMENT '财务已确认付款',
  `payable_amount` decimal(12,2) NOT NULL DEFAULT 0.00 COMMENT '剩余应付',
  `finance_status` varchar(20) NOT NULL DEFAULT 'pending' COMMENT 'pending/partial/settled',
  `status` varchar(20) NOT NULL DEFAULT 'completed' COMMENT 'draft/completed/returned/void',
  `source_plugin` varchar(40) NOT NULL DEFAULT 'erp',
  `source_type` varchar(40) NOT NULL DEFAULT 'manual',
  `source_id` varchar(64) NOT NULL DEFAULT '',
  `origin_plugin` varchar(40) NOT NULL DEFAULT 'hsx_erp' COMMENT '真实业务来源插件',
  `origin_plugin_name` varchar(60) NOT NULL DEFAULT '二手机ERP' COMMENT '来源插件名称快照',
  `origin_type` varchar(80) NOT NULL DEFAULT 'hsx_erp.manual_purchase' COMMENT '业务来源稳定编码',
  `origin_name` varchar(80) NOT NULL DEFAULT 'ERP采购' COMMENT '业务来源名称快照',
  `origin_id` varchar(80) NOT NULL DEFAULT '' COMMENT '原系统业务ID',
  `origin_no` varchar(80) NOT NULL DEFAULT '' COMMENT '原系统业务单号',
  `origin_event_id` varchar(80) NOT NULL DEFAULT '' COMMENT '外部事件幂等键',
  `operator_uid` int NOT NULL DEFAULT 0,
  `operator_name` varchar(60) NOT NULL DEFAULT '',
  `purchase_at` int NOT NULL DEFAULT 0,
  `remark` varchar(255) NOT NULL DEFAULT '',
  `create_at` int NOT NULL DEFAULT 0,
  `update_at` int NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_site_no` (`site_id`,`purchase_no`),
  UNIQUE KEY `uk_site_request` (`site_id`,`request_id`),
  KEY `idx_party` (`site_id`,`party_id`,`finance_status`),
  KEY `idx_status` (`site_id`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='ERP-采购单';

CREATE TABLE IF NOT EXISTS `{{prefix}}erp_purchase_item` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `site_id` int NOT NULL DEFAULT 0,
  `purchase_order_id` int NOT NULL DEFAULT 0,
  `asset_id` int NOT NULL DEFAULT 0,
  `warehouse_id` int NOT NULL DEFAULT 0 COMMENT '明细入库仓库ID',
  `warehouse_name` varchar(100) NOT NULL DEFAULT '' COMMENT '明细入库仓库名称快照',
  `location_id` int NOT NULL DEFAULT 0 COMMENT '明细入库库位ID',
  `location_name` varchar(100) NOT NULL DEFAULT '' COMMENT '明细入库库位名称快照',
  `imei` varchar(64) NOT NULL DEFAULT '',
  `sn` varchar(64) NOT NULL DEFAULT '',
  `model` varchar(255) NOT NULL DEFAULT '',
  `spec` varchar(255) NOT NULL DEFAULT '',
  `spec_json` longtext COMMENT '结构化规格JSON',
  `color` varchar(50) NOT NULL DEFAULT '' COMMENT '颜色',
  `battery` tinyint NOT NULL DEFAULT 0 COMMENT '电池效率百分比',
  `warranty` int NOT NULL DEFAULT 0 COMMENT '保修截止时间',
  `catalog_product_id` int NOT NULL DEFAULT 0 COMMENT '本站ERP目录产品ID',
  `category_name` varchar(100) NOT NULL DEFAULT '' COMMENT '末级品类名称快照',
  `category_path` varchar(255) NOT NULL DEFAULT '' COMMENT '一级品类/可选一级子分类快照',
  `inspector_uid` int NOT NULL DEFAULT 0 COMMENT '质检员UID',
  `inspector_name` varchar(60) NOT NULL DEFAULT '' COMMENT '质检员名称快照',
  `estimate_sale_price` decimal(12,2) NOT NULL DEFAULT 0.00 COMMENT '入库预估售价',
  `retail_price` decimal(12,2) NOT NULL DEFAULT 0.00 COMMENT '零售价',
  `image_urls` text COMMENT '入库图片JSON/逗号分隔',
  `quality_remark` varchar(500) NOT NULL DEFAULT '' COMMENT '质检/外观备注',
  `qc_template_id` int NOT NULL DEFAULT 0 COMMENT '来源质检模板ID快照',
  `qc_report` longtext COMMENT '标准化质检报告JSON快照',
  `purchase_cost` decimal(12,2) NOT NULL DEFAULT 0.00,
  `adjust_cost` decimal(12,2) NOT NULL DEFAULT 0.00,
  `total_cost` decimal(12,2) NOT NULL DEFAULT 0.00,
  `status` varchar(20) NOT NULL DEFAULT 'in_stock',
  `remark` varchar(255) NOT NULL DEFAULT '',
  `create_at` int NOT NULL DEFAULT 0,
  `update_at` int NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_order` (`purchase_order_id`),
  KEY `idx_asset` (`asset_id`),
  KEY `idx_imei` (`site_id`,`imei`),
  KEY `idx_site_catalog_product` (`site_id`,`catalog_product_id`),
  KEY `idx_site_attr` (`site_id`,`color`,`battery`,`warranty`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='ERP-采购明细';

CREATE TABLE IF NOT EXISTS `{{prefix}}erp_sale_order` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `site_id` int NOT NULL DEFAULT 0,
  `request_id` varchar(80) DEFAULT NULL COMMENT '客户端/外部事件幂等请求ID',
  `sale_no` varchar(40) NOT NULL DEFAULT '' COMMENT '销售单号',
  `party_id` int NOT NULL DEFAULT 0 COMMENT '销售客户/渠道',
  `party_name` varchar(100) NOT NULL DEFAULT '',
  `sale_channel` varchar(60) NOT NULL DEFAULT '',
  `sale_channel_key` varchar(80) NOT NULL DEFAULT '' COMMENT '销售渠道稳定编码',
  `channel_source_plugin` varchar(40) NOT NULL DEFAULT '' COMMENT '渠道来源插件',
  `channel_source_key` varchar(80) NOT NULL DEFAULT '' COMMENT '插件内渠道编码',
  `origin_plugin` varchar(40) NOT NULL DEFAULT 'hsx_erp' COMMENT '真实业务来源插件',
  `origin_plugin_name` varchar(60) NOT NULL DEFAULT '二手机ERP' COMMENT '来源插件名称快照',
  `origin_type` varchar(80) NOT NULL DEFAULT 'hsx_erp.manual_sale' COMMENT '业务来源稳定编码',
  `origin_name` varchar(80) NOT NULL DEFAULT 'ERP销售' COMMENT '业务来源名称快照',
  `origin_id` varchar(80) NOT NULL DEFAULT '' COMMENT '原系统业务ID',
  `origin_no` varchar(80) NOT NULL DEFAULT '' COMMENT '原系统业务单号',
  `origin_event_id` varchar(80) NOT NULL DEFAULT '' COMMENT '外部事件幂等键',
  `settle_method` varchar(30) NOT NULL DEFAULT '',
  `salesman_uid` int NOT NULL DEFAULT 0,
  `salesman_name` varchar(60) NOT NULL DEFAULT '',
  `total_amount` decimal(12,2) NOT NULL DEFAULT 0.00,
  `total_cost` decimal(12,2) NOT NULL DEFAULT 0.00,
  `profit` decimal(12,2) NOT NULL DEFAULT 0.00,
  `received_amount` decimal(12,2) NOT NULL DEFAULT 0.00 COMMENT '财务已确认收款',
  `receivable_amount` decimal(12,2) NOT NULL DEFAULT 0.00 COMMENT '剩余应收',
  `finance_status` varchar(20) NOT NULL DEFAULT 'pending' COMMENT 'pending/partial/settled',
  `status` varchar(20) NOT NULL DEFAULT 'completed' COMMENT 'completed/returned/void',
  `operator_uid` int NOT NULL DEFAULT 0,
  `operator_name` varchar(60) NOT NULL DEFAULT '',
  `sale_at` int NOT NULL DEFAULT 0,
  `remark` varchar(255) NOT NULL DEFAULT '',
  `create_at` int NOT NULL DEFAULT 0,
  `update_at` int NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_site_no` (`site_id`,`sale_no`),
  UNIQUE KEY `uk_site_request` (`site_id`,`request_id`),
  KEY `idx_party` (`site_id`,`party_id`,`finance_status`),
  KEY `idx_status` (`site_id`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='ERP-销售单';

CREATE TABLE IF NOT EXISTS `{{prefix}}erp_sale_item` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `site_id` int NOT NULL DEFAULT 0,
  `sale_order_id` int NOT NULL DEFAULT 0,
  `asset_id` int NOT NULL DEFAULT 0,
  `imei` varchar(64) NOT NULL DEFAULT '',
  `model` varchar(255) NOT NULL DEFAULT '',
  `ownership_type` varchar(20) NOT NULL DEFAULT 'owned' COMMENT 'owned自有/consigned代卖',
  `owner_party_id` int NOT NULL DEFAULT 0 COMMENT '代卖货主主体ID',
  `owner_party_name` varchar(100) NOT NULL DEFAULT '' COMMENT '代卖货主名称快照',
  `cost` decimal(12,2) NOT NULL DEFAULT 0.00,
  `sale_price` decimal(12,2) NOT NULL DEFAULT 0.00,
  `profit` decimal(12,2) NOT NULL DEFAULT 0.00,
  `consignment_settlement_amount` decimal(12,2) NOT NULL DEFAULT 0.00 COMMENT '本台应付货主金额',
  `consignment_service_fee` decimal(12,2) NOT NULL DEFAULT 0.00 COMMENT '本台代卖服务收益',
  `consignment_payable_id` int NOT NULL DEFAULT 0 COMMENT '设备级代卖结算应付ID',
  `status` varchar(20) NOT NULL DEFAULT 'sold',
  `remark` varchar(255) NOT NULL DEFAULT '',
  `create_at` int NOT NULL DEFAULT 0,
  `update_at` int NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_order` (`sale_order_id`),
  KEY `idx_asset` (`asset_id`),
  KEY `idx_owner` (`site_id`,`owner_party_id`,`status`),
  KEY `idx_consignment_payable` (`site_id`,`consignment_payable_id`),
  KEY `idx_imei` (`site_id`,`imei`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='ERP-销售明细';

CREATE TABLE IF NOT EXISTS `{{prefix}}erp_payable` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `site_id` int NOT NULL DEFAULT 0,
  `payable_no` varchar(40) NOT NULL DEFAULT '',
  `party_id` int NOT NULL DEFAULT 0,
  `party_name` varchar(100) NOT NULL DEFAULT '',
  `source_type` varchar(40) NOT NULL DEFAULT '',
  `source_id` int NOT NULL DEFAULT 0,
  `source_no` varchar(40) NOT NULL DEFAULT '',
  `origin_plugin` varchar(40) NOT NULL DEFAULT 'hsx_erp' COMMENT '真实业务来源插件',
  `origin_plugin_name` varchar(60) NOT NULL DEFAULT '二手机ERP' COMMENT '来源插件名称快照',
  `origin_type` varchar(80) NOT NULL DEFAULT '' COMMENT '业务来源稳定编码',
  `origin_name` varchar(80) NOT NULL DEFAULT '' COMMENT '业务来源名称快照',
  `origin_id` varchar(80) NOT NULL DEFAULT '' COMMENT '原系统业务ID',
  `origin_no` varchar(80) NOT NULL DEFAULT '' COMMENT '原系统业务单号',
  `biz_scene` varchar(40) NOT NULL DEFAULT '' COMMENT '采购/整备/销售退款等业务场景',
  `category_key` varchar(80) NOT NULL DEFAULT '' COMMENT '财务分类稳定编码',
  `category_name` varchar(60) NOT NULL DEFAULT '' COMMENT '财务分类名称快照',
  `category_statement_group` varchar(40) NOT NULL DEFAULT '' COMMENT '经营报表分组',
  `category_source_plugin` varchar(40) NOT NULL DEFAULT '' COMMENT '分类提供插件',
  `category_source_key` varchar(80) NOT NULL DEFAULT '' COMMENT '插件内分类编码',
  `channel_code` varchar(80) NOT NULL DEFAULT '' COMMENT '业务渠道稳定编码',
  `channel_name` varchar(60) NOT NULL DEFAULT '' COMMENT '业务渠道名称快照',
  `business_reason` varchar(255) NOT NULL DEFAULT '' COMMENT '为什么形成该应付',
  `settlement_mode` varchar(20) NOT NULL DEFAULT '' COMMENT '开单时结算约定稳定编码',
  `settlement_mode_name` varchar(60) NOT NULL DEFAULT '' COMMENT '开单时结算约定名称快照',
  `business_operator_uid` int NOT NULL DEFAULT 0 COMMENT '业务开单/经办人UID',
  `business_operator_name` varchar(60) NOT NULL DEFAULT '' COMMENT '业务开单/经办人名称快照',
  `asset_id` int NOT NULL DEFAULT 0 COMMENT '设备级应付关联资产ID',
  `task_stage_key` varchar(40) NOT NULL DEFAULT '' COMMENT '当前财务待办环节',
  `task_assignee_uid` int NOT NULL DEFAULT 0 COMMENT '当前待办责任人UID',
  `task_assignee_name` varchar(60) NOT NULL DEFAULT '' COMMENT '当前待办责任人',
  `task_assigner_uid` int NOT NULL DEFAULT 0 COMMENT '分配人UID',
  `task_assigner_name` varchar(60) NOT NULL DEFAULT '' COMMENT '分配人',
  `task_assigned_at` int NOT NULL DEFAULT 0 COMMENT '最近分配时间',
  `amount` decimal(12,2) NOT NULL DEFAULT 0.00,
  `settled_amount` decimal(12,2) NOT NULL DEFAULT 0.00,
  `status` varchar(20) NOT NULL DEFAULT 'pending',
  `occurred_at` int NOT NULL DEFAULT 0,
  `remark` varchar(255) NOT NULL DEFAULT '',
  `create_at` int NOT NULL DEFAULT 0,
  `update_at` int NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_site_no` (`site_id`,`payable_no`),
  KEY `idx_party` (`site_id`,`party_id`,`status`),
  KEY `idx_source` (`site_id`,`source_type`,`source_id`),
  KEY `idx_asset` (`site_id`,`asset_id`),
  KEY `idx_task_assignee` (`site_id`,`task_stage_key`,`task_assignee_uid`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='ERP-应付款';

CREATE TABLE IF NOT EXISTS `{{prefix}}erp_receivable` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `site_id` int NOT NULL DEFAULT 0,
  `receivable_no` varchar(40) NOT NULL DEFAULT '',
  `party_id` int NOT NULL DEFAULT 0,
  `party_name` varchar(100) NOT NULL DEFAULT '',
  `source_type` varchar(40) NOT NULL DEFAULT '',
  `source_id` int NOT NULL DEFAULT 0,
  `source_no` varchar(40) NOT NULL DEFAULT '',
  `origin_plugin` varchar(40) NOT NULL DEFAULT 'hsx_erp' COMMENT '真实业务来源插件',
  `origin_plugin_name` varchar(60) NOT NULL DEFAULT '二手机ERP' COMMENT '来源插件名称快照',
  `origin_type` varchar(80) NOT NULL DEFAULT '' COMMENT '业务来源稳定编码',
  `origin_name` varchar(80) NOT NULL DEFAULT '' COMMENT '业务来源名称快照',
  `origin_id` varchar(80) NOT NULL DEFAULT '' COMMENT '原系统业务ID',
  `origin_no` varchar(80) NOT NULL DEFAULT '' COMMENT '原系统业务单号',
  `biz_scene` varchar(40) NOT NULL DEFAULT '' COMMENT '销售/采购退货等业务场景',
  `category_key` varchar(80) NOT NULL DEFAULT '' COMMENT '财务分类稳定编码',
  `category_name` varchar(60) NOT NULL DEFAULT '' COMMENT '财务分类名称快照',
  `category_statement_group` varchar(40) NOT NULL DEFAULT '' COMMENT '经营报表分组',
  `category_source_plugin` varchar(40) NOT NULL DEFAULT '' COMMENT '分类提供插件',
  `category_source_key` varchar(80) NOT NULL DEFAULT '' COMMENT '插件内分类编码',
  `channel_code` varchar(80) NOT NULL DEFAULT '' COMMENT '业务渠道稳定编码',
  `channel_name` varchar(60) NOT NULL DEFAULT '' COMMENT '业务渠道名称快照',
  `business_reason` varchar(255) NOT NULL DEFAULT '' COMMENT '为什么形成该应收',
  `settlement_mode` varchar(20) NOT NULL DEFAULT '' COMMENT '开单时结算约定稳定编码',
  `settlement_mode_name` varchar(60) NOT NULL DEFAULT '' COMMENT '开单时结算约定名称快照',
  `business_operator_uid` int NOT NULL DEFAULT 0 COMMENT '业务开单/经办人UID',
  `business_operator_name` varchar(60) NOT NULL DEFAULT '' COMMENT '业务开单/经办人名称快照',
  `asset_id` int NOT NULL DEFAULT 0 COMMENT '设备级应收关联资产ID',
  `task_stage_key` varchar(40) NOT NULL DEFAULT '' COMMENT '当前财务待办环节',
  `task_assignee_uid` int NOT NULL DEFAULT 0 COMMENT '当前待办责任人UID',
  `task_assignee_name` varchar(60) NOT NULL DEFAULT '' COMMENT '当前待办责任人',
  `task_assigner_uid` int NOT NULL DEFAULT 0 COMMENT '分配人UID',
  `task_assigner_name` varchar(60) NOT NULL DEFAULT '' COMMENT '分配人',
  `task_assigned_at` int NOT NULL DEFAULT 0 COMMENT '最近分配时间',
  `amount` decimal(12,2) NOT NULL DEFAULT 0.00,
  `settled_amount` decimal(12,2) NOT NULL DEFAULT 0.00,
  `status` varchar(20) NOT NULL DEFAULT 'pending',
  `occurred_at` int NOT NULL DEFAULT 0,
  `remark` varchar(255) NOT NULL DEFAULT '',
  `create_at` int NOT NULL DEFAULT 0,
  `update_at` int NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_site_no` (`site_id`,`receivable_no`),
  KEY `idx_party` (`site_id`,`party_id`,`status`),
  KEY `idx_source` (`site_id`,`source_type`,`source_id`),
  KEY `idx_asset` (`site_id`,`asset_id`),
  KEY `idx_task_assignee` (`site_id`,`task_stage_key`,`task_assignee_uid`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='ERP-应收款';

CREATE TABLE IF NOT EXISTS `{{prefix}}erp_settlement` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `site_id` int NOT NULL DEFAULT 0,
  `request_id` varchar(80) DEFAULT NULL COMMENT '客户端幂等请求ID',
  `settlement_no` varchar(40) NOT NULL DEFAULT '',
  `party_id` int NOT NULL DEFAULT 0,
  `party_name` varchar(100) NOT NULL DEFAULT '',
  `settlement_type` varchar(20) NOT NULL DEFAULT 'payment' COMMENT 'payment付款/receipt收款/refund退款/offset折账',
  `amount` decimal(12,2) NOT NULL DEFAULT 0.00,
  `cash_direction` varchar(10) NOT NULL DEFAULT 'none' COMMENT 'in收入/out支出/none无现金',
  `capital_account_id` int NOT NULL DEFAULT 0,
  `capital_account_name` varchar(100) NOT NULL DEFAULT '',
  `status` varchar(20) NOT NULL DEFAULT 'confirmed',
  `operator_uid` int NOT NULL DEFAULT 0,
  `operator_name` varchar(60) NOT NULL DEFAULT '',
  `confirmed_at` int NOT NULL DEFAULT 0,
  `voucher_urls` text COMMENT '收付款凭证图片JSON/逗号分隔',
  `remark` varchar(255) NOT NULL DEFAULT '',
  `create_at` int NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_site_no` (`site_id`,`settlement_no`),
  UNIQUE KEY `uk_site_request` (`site_id`,`request_id`),
  KEY `idx_party` (`site_id`,`party_id`),
  KEY `idx_type` (`site_id`,`settlement_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='ERP-财务确认结算单';

CREATE TABLE IF NOT EXISTS `{{prefix}}erp_settlement_link` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `site_id` int NOT NULL DEFAULT 0,
  `settlement_id` int NOT NULL DEFAULT 0,
  `target_type` varchar(20) NOT NULL DEFAULT '' COMMENT 'payable/receivable',
  `target_id` int NOT NULL DEFAULT 0,
  `asset_id` int NOT NULL DEFAULT 0 COMMENT '关联设备',
  `biz_scene` varchar(40) NOT NULL DEFAULT '' COMMENT '业务场景快照',
  `category_key` varchar(80) NOT NULL DEFAULT '' COMMENT '财务分类编码快照',
  `category_name` varchar(60) NOT NULL DEFAULT '' COMMENT '财务分类名称快照',
  `category_statement_group` varchar(40) NOT NULL DEFAULT '' COMMENT '经营报表分组',
  `category_source_plugin` varchar(40) NOT NULL DEFAULT '' COMMENT '分类提供插件',
  `category_source_key` varchar(80) NOT NULL DEFAULT '' COMMENT '插件内分类编码',
  `origin_plugin` varchar(40) NOT NULL DEFAULT '' COMMENT '真实业务来源插件',
  `origin_type` varchar(80) NOT NULL DEFAULT '' COMMENT '业务来源稳定编码',
  `origin_id` varchar(80) NOT NULL DEFAULT '' COMMENT '原系统业务ID',
  `applied_amount` decimal(12,2) NOT NULL DEFAULT 0.00,
  `create_at` int NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_settlement` (`settlement_id`),
  KEY `idx_target` (`site_id`,`target_type`,`target_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='ERP-结算核销明细';

CREATE TABLE IF NOT EXISTS `{{prefix}}erp_money_ledger` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `site_id` int NOT NULL DEFAULT 0,
  `ledger_no` varchar(40) NOT NULL DEFAULT '',
  `settlement_id` int NOT NULL DEFAULT 0,
  `capital_account_id` int NOT NULL DEFAULT 0,
  `capital_account_name` varchar(100) NOT NULL DEFAULT '',
  `direction` varchar(10) NOT NULL DEFAULT 'in',
  `category_key` varchar(80) NOT NULL DEFAULT '' COMMENT '收支分类稳定编码',
  `category_name` varchar(60) NOT NULL DEFAULT '' COMMENT '收支分类名称快照',
  `category_statement_group` varchar(40) NOT NULL DEFAULT '' COMMENT '经营报表分组',
  `category_source_plugin` varchar(40) NOT NULL DEFAULT '' COMMENT '分类来源插件',
  `category_source_key` varchar(80) NOT NULL DEFAULT '' COMMENT '插件内分类编码',
  `amount` decimal(12,2) NOT NULL DEFAULT 0.00,
  `balance_after` decimal(14,2) NOT NULL DEFAULT 0.00 COMMENT '记账后余额',
  `party_id` int NOT NULL DEFAULT 0,
  `party_name` varchar(100) NOT NULL DEFAULT '',
  `operator_uid` int NOT NULL DEFAULT 0,
  `operator_name` varchar(60) NOT NULL DEFAULT '',
  `occurred_at` int NOT NULL DEFAULT 0,
  `voucher_urls` text COMMENT '资金凭证图片JSON/逗号分隔',
  `remark` varchar(255) NOT NULL DEFAULT '',
  `create_at` int NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_site_no` (`site_id`,`ledger_no`),
  KEY `idx_account` (`site_id`,`capital_account_id`,`occurred_at`),
  KEY `idx_party` (`site_id`,`party_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='ERP-真实资金流水';

CREATE TABLE IF NOT EXISTS `{{prefix}}erp_account_ledger` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `site_id` int NOT NULL DEFAULT 0,
  `ledger_no` varchar(40) NOT NULL DEFAULT '',
  `biz_type` varchar(40) NOT NULL DEFAULT '' COMMENT 'purchase/sale/payment/receipt/offset/adjust/return',
  `direction` varchar(20) NOT NULL DEFAULT '' COMMENT 'increase/decrease/none',
  `amount` decimal(12,2) NOT NULL DEFAULT 0.00,
  `balance_after` decimal(14,2) NOT NULL DEFAULT 0.00 COMMENT '记账后余额',
  `party_id` int NOT NULL DEFAULT 0,
  `party_name` varchar(100) NOT NULL DEFAULT '',
  `asset_id` int NOT NULL DEFAULT 0,
  `source_type` varchar(40) NOT NULL DEFAULT '',
  `source_id` int NOT NULL DEFAULT 0,
  `source_no` varchar(40) NOT NULL DEFAULT '',
  `operator_uid` int NOT NULL DEFAULT 0,
  `operator_name` varchar(60) NOT NULL DEFAULT '',
  `occurred_at` int NOT NULL DEFAULT 0,
  `remark` varchar(255) NOT NULL DEFAULT '',
  `create_at` int NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_site_no` (`site_id`,`ledger_no`),
  KEY `idx_party` (`site_id`,`party_id`,`occurred_at`),
  KEY `idx_asset` (`site_id`,`asset_id`),
  KEY `idx_source` (`site_id`,`source_type`,`source_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='ERP-业务账目流水';

CREATE TABLE IF NOT EXISTS `{{prefix}}erp_operation_log` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `site_id` int NOT NULL DEFAULT 0,
  `action` varchar(60) NOT NULL DEFAULT '' COMMENT '操作动作',
  `source_type` varchar(40) NOT NULL DEFAULT '' COMMENT '业务类型',
  `source_id` int NOT NULL DEFAULT 0 COMMENT '业务ID',
  `source_no` varchar(40) NOT NULL DEFAULT '' COMMENT '业务单号',
  `operator_uid` int NOT NULL DEFAULT 0,
  `operator_name` varchar(60) NOT NULL DEFAULT '',
  `remark` varchar(500) NOT NULL DEFAULT '',
  `extra_json` longtext COMMENT '扩展快照',
  `create_at` int NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_source` (`site_id`,`source_type`,`source_id`),
  KEY `idx_action` (`site_id`,`action`,`create_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='ERP-操作日志';

CREATE TABLE IF NOT EXISTS `{{prefix}}erp_stocktake` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `site_id` int NOT NULL DEFAULT 0,
  `request_id` varchar(80) DEFAULT NULL COMMENT '客户端幂等请求ID',
  `stocktake_no` varchar(40) NOT NULL DEFAULT '' COMMENT '盘点单号',
  `warehouse_id` int NOT NULL DEFAULT 0,
  `warehouse_name` varchar(100) NOT NULL DEFAULT '',
  `location_id` int NOT NULL DEFAULT 0,
  `location_name` varchar(100) NOT NULL DEFAULT '',
  `scope_type` varchar(20) NOT NULL DEFAULT 'all' COMMENT 'all全盘/selected抽盘',
  `workflow_mode` varchar(20) NOT NULL DEFAULT 'simple' COMMENT 'simple小团队/team团队复核',
  `status` varchar(20) NOT NULL DEFAULT 'counting' COMMENT 'counting/pending_review/completed/cancelled',
  `snapshot_at` int NOT NULL DEFAULT 0,
  `expected_count` int NOT NULL DEFAULT 0,
  `scanned_count` int NOT NULL DEFAULT 0,
  `normal_count` int NOT NULL DEFAULT 0,
  `missing_count` int NOT NULL DEFAULT 0,
  `surplus_count` int NOT NULL DEFAULT 0,
  `location_mismatch_count` int NOT NULL DEFAULT 0,
  `status_abnormal_count` int NOT NULL DEFAULT 0,
  `unresolved_count` int NOT NULL DEFAULT 0,
  `counter_uid` int NOT NULL DEFAULT 0,
  `counter_name` varchar(60) NOT NULL DEFAULT '',
  `reviewer_uid` int NOT NULL DEFAULT 0,
  `reviewer_name` varchar(60) NOT NULL DEFAULT '',
  `creator_uid` int NOT NULL DEFAULT 0,
  `creator_name` varchar(60) NOT NULL DEFAULT '',
  `started_at` int NOT NULL DEFAULT 0,
  `submitted_at` int NOT NULL DEFAULT 0,
  `completed_at` int NOT NULL DEFAULT 0,
  `cancelled_at` int NOT NULL DEFAULT 0,
  `remark` varchar(500) NOT NULL DEFAULT '',
  `completion_remark` varchar(500) NOT NULL DEFAULT '',
  `create_at` int NOT NULL DEFAULT 0,
  `update_at` int NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_site_no` (`site_id`,`stocktake_no`),
  UNIQUE KEY `uk_site_request` (`site_id`,`request_id`),
  KEY `idx_site_status` (`site_id`,`status`,`create_at`),
  KEY `idx_scope` (`site_id`,`warehouse_id`,`location_id`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='ERP-库存盘点任务';

CREATE TABLE IF NOT EXISTS `{{prefix}}erp_stocktake_item` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `site_id` int NOT NULL DEFAULT 0,
  `stocktake_id` int NOT NULL DEFAULT 0,
  `identity_key` varchar(100) NOT NULL DEFAULT '' COMMENT '任务内设备/未知串号唯一键',
  `asset_id` int NOT NULL DEFAULT 0,
  `asset_no` varchar(40) NOT NULL DEFAULT '',
  `imei` varchar(80) NOT NULL DEFAULT '',
  `sn` varchar(80) NOT NULL DEFAULT '',
  `model` varchar(255) NOT NULL DEFAULT '',
  `spec` varchar(255) NOT NULL DEFAULT '',
  `expected_status` varchar(20) NOT NULL DEFAULT '',
  `expected_warehouse_id` int NOT NULL DEFAULT 0,
  `expected_warehouse_name` varchar(100) NOT NULL DEFAULT '',
  `expected_location_id` int NOT NULL DEFAULT 0,
  `expected_location_name` varchar(100) NOT NULL DEFAULT '',
  `actual_warehouse_id` int NOT NULL DEFAULT 0,
  `actual_warehouse_name` varchar(100) NOT NULL DEFAULT '',
  `actual_location_id` int NOT NULL DEFAULT 0,
  `actual_location_name` varchar(100) NOT NULL DEFAULT '',
  `result` varchar(30) NOT NULL DEFAULT 'pending' COMMENT 'pending/normal/missing/surplus/location_mismatch/status_abnormal',
  `resolution_status` varchar(20) NOT NULL DEFAULT 'pending' COMMENT 'pending/resolved/not_required',
  `resolution_action` varchar(40) NOT NULL DEFAULT '',
  `resolution_remark` varchar(500) NOT NULL DEFAULT '',
  `scan_code` varchar(100) NOT NULL DEFAULT '',
  `scan_count` int NOT NULL DEFAULT 0,
  `scanner_uid` int NOT NULL DEFAULT 0,
  `scanner_name` varchar(60) NOT NULL DEFAULT '',
  `scanned_at` int NOT NULL DEFAULT 0,
  `resolver_uid` int NOT NULL DEFAULT 0,
  `resolver_name` varchar(60) NOT NULL DEFAULT '',
  `resolved_at` int NOT NULL DEFAULT 0,
  `create_at` int NOT NULL DEFAULT 0,
  `update_at` int NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_task_identity` (`site_id`,`stocktake_id`,`identity_key`),
  KEY `idx_task_result` (`site_id`,`stocktake_id`,`result`,`resolution_status`),
  KEY `idx_asset` (`site_id`,`asset_id`),
  KEY `idx_scan_code` (`site_id`,`scan_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='ERP-库存盘点设备明细';

CREATE TABLE IF NOT EXISTS `{{prefix}}erp_offset` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `site_id` int NOT NULL DEFAULT 0,
  `offset_no` varchar(40) NOT NULL DEFAULT '',
  `settlement_id` int NOT NULL DEFAULT 0,
  `party_id` int NOT NULL DEFAULT 0,
  `party_name` varchar(100) NOT NULL DEFAULT '',
  `amount` decimal(12,2) NOT NULL DEFAULT 0.00,
  `operator_uid` int NOT NULL DEFAULT 0,
  `operator_name` varchar(60) NOT NULL DEFAULT '',
  `confirmed_at` int NOT NULL DEFAULT 0,
  `remark` varchar(255) NOT NULL DEFAULT '',
  `create_at` int NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_site_no` (`site_id`,`offset_no`),
  KEY `idx_party` (`site_id`,`party_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='ERP-折账记录';

CREATE TABLE IF NOT EXISTS `{{prefix}}erp_offset_link` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `site_id` int NOT NULL DEFAULT 0,
  `offset_id` int NOT NULL DEFAULT 0,
  `target_type` varchar(20) NOT NULL DEFAULT '' COMMENT 'payable/receivable',
  `target_id` int NOT NULL DEFAULT 0,
  `applied_amount` decimal(12,2) NOT NULL DEFAULT 0.00,
  `create_at` int NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_offset` (`offset_id`),
  KEY `idx_target` (`site_id`,`target_type`,`target_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='ERP-折账明细';

CREATE TABLE IF NOT EXISTS `{{prefix}}erp_inbox_event` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `site_id` int NOT NULL DEFAULT 0,
  `event_id` varchar(80) NOT NULL DEFAULT '' COMMENT '外部事件幂等键',
  `source_plugin` varchar(40) NOT NULL DEFAULT '' COMMENT '来源插件',
  `event_name` varchar(80) NOT NULL DEFAULT '',
  `payload_json` longtext COMMENT '事件内容',
  `status` varchar(20) NOT NULL DEFAULT 'pending',
  `occurred_at` int NOT NULL DEFAULT 0,
  `create_at` int NOT NULL DEFAULT 0,
  `update_at` int NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_site_event` (`site_id`,`event_id`),
  KEY `idx_status` (`site_id`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='ERP-外部事件收件箱';

CREATE TABLE IF NOT EXISTS `{{prefix}}erp_outbox_event` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `site_id` int NOT NULL DEFAULT 0,
  `event_id` varchar(80) NOT NULL DEFAULT '' COMMENT 'ERP事件幂等键',
  `event_name` varchar(80) NOT NULL DEFAULT '',
  `payload_json` longtext COMMENT '事件内容',
  `status` varchar(20) NOT NULL DEFAULT 'pending',
  `occurred_at` int NOT NULL DEFAULT 0,
  `create_at` int NOT NULL DEFAULT 0,
  `update_at` int NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_site_event` (`site_id`,`event_id`),
  KEY `idx_status` (`site_id`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='ERP-对外事件发件箱';

-- ─────────────────────────────────────────────────────────────────────────────
-- 退货闭环（P0-1）：采购退货 + 销售退货
-- 原则：已形成财务事实的退货走反向流水，禁止 UPDATE 历史流水
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS `{{prefix}}erp_purchase_return` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `site_id` int NOT NULL DEFAULT 0,
  `request_id` varchar(80) DEFAULT NULL COMMENT '客户端幂等请求ID',
  `return_no` varchar(40) NOT NULL DEFAULT '' COMMENT '退货单号',
  `purchase_order_id` int NOT NULL DEFAULT 0 COMMENT '关联原采购单ID',
  `purchase_no` varchar(40) NOT NULL DEFAULT '' COMMENT '原采购单号快照',
  `party_id` int NOT NULL DEFAULT 0 COMMENT '供应商ID',
  `party_name` varchar(100) NOT NULL DEFAULT '' COMMENT '供应商名称快照',
  `operator_id` int NOT NULL DEFAULT 0 COMMENT '操作员UID',
  `operator_name` varchar(60) NOT NULL DEFAULT '' COMMENT '操作员名称快照',
  `total_amount` decimal(12,2) NOT NULL DEFAULT 0.00 COMMENT '退货总金额',
  `settled_amount` decimal(12,2) NOT NULL DEFAULT 0.00 COMMENT '已结算金额',
  `status` varchar(20) NOT NULL DEFAULT 'pending' COMMENT 'pending待处理/confirmed已确认/cancelled已取消',
  `refund_mode` varchar(20) NOT NULL DEFAULT 'receivable' COMMENT '采购退货收款：cash当场到账/receivable记账待收/none无需收款',
  `capital_account_id` int NOT NULL DEFAULT 0 COMMENT '结算账户ID（现金退款时）',
  `remark` varchar(500) NOT NULL DEFAULT '',
  `occurred_at` int NOT NULL DEFAULT 0 COMMENT '退货发生时间',
  `create_at` int NOT NULL DEFAULT 0,
  `update_at` int NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_site_return_no` (`site_id`,`return_no`),
  UNIQUE KEY `uk_site_request` (`site_id`,`request_id`),
  KEY `idx_purchase` (`purchase_order_id`),
  KEY `idx_party` (`site_id`,`party_id`),
  KEY `idx_status` (`site_id`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='ERP-采购退货单';

CREATE TABLE IF NOT EXISTS `{{prefix}}erp_purchase_return_item` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `site_id` int NOT NULL DEFAULT 0,
  `return_id` int NOT NULL DEFAULT 0 COMMENT '退货单ID',
  `asset_id` int NOT NULL DEFAULT 0 COMMENT '退货设备ID',
  `asset_no` varchar(40) NOT NULL DEFAULT '' COMMENT '设备资产号快照',
  `imei` varchar(64) NOT NULL DEFAULT '' COMMENT 'IMEI快照',
  `model` varchar(255) NOT NULL DEFAULT '' COMMENT '型号快照',
  `purchase_item_id` int NOT NULL DEFAULT 0 COMMENT '原采购明细ID',
  `return_cost` decimal(12,2) NOT NULL DEFAULT 0.00 COMMENT '退货价（通常等于采购成本）',
  `paid_amount` decimal(12,2) NOT NULL DEFAULT 0.00 COMMENT '该设备已支付金额（决定退款方式）',
  `supplier_amount` decimal(12,2) NOT NULL DEFAULT 0.00 COMMENT '供应商结算成本快照',
  `unpaid_offset_amount` decimal(12,2) NOT NULL DEFAULT 0.00 COMMENT '冲销未付款金额',
  `refund_receivable_amount` decimal(12,2) NOT NULL DEFAULT 0.00 COMMENT '生成退款应收金额',
  `retained_payable_amount` decimal(12,2) NOT NULL DEFAULT 0.00 COMMENT '退货后仍保留应付金额',
  `internal_cost` decimal(12,2) NOT NULL DEFAULT 0.00 COMMENT '整备及内部成本快照',
  `policy_json` longtext COMMENT '退货决策快照',
  `reason` varchar(255) NOT NULL DEFAULT '' COMMENT '退货原因',
  `create_at` int NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_return` (`return_id`),
  KEY `idx_asset` (`asset_id`),
  KEY `idx_purchase_item` (`purchase_item_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='ERP-采购退货明细';

CREATE TABLE IF NOT EXISTS `{{prefix}}erp_sale_return` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `site_id` int NOT NULL DEFAULT 0,
  `request_id` varchar(80) DEFAULT NULL COMMENT '客户端幂等请求ID',
  `business_type` varchar(30) NOT NULL DEFAULT 'return_refund' COMMENT 'return_refund退货退款/after_sale_compensation售后补差',
  `return_no` varchar(40) NOT NULL DEFAULT '' COMMENT '退货单号',
  `sale_order_id` int NOT NULL DEFAULT 0 COMMENT '关联原销售单ID',
  `sale_no` varchar(40) NOT NULL DEFAULT '' COMMENT '原销售单号快照',
  `party_id` int NOT NULL DEFAULT 0 COMMENT '客户ID',
  `party_name` varchar(100) NOT NULL DEFAULT '' COMMENT '客户名称快照',
  `operator_id` int NOT NULL DEFAULT 0 COMMENT '操作员UID',
  `operator_name` varchar(60) NOT NULL DEFAULT '' COMMENT '操作员名称快照',
  `total_amount` decimal(12,2) NOT NULL DEFAULT 0.00 COMMENT '退款总金额',
  `settled_amount` decimal(12,2) NOT NULL DEFAULT 0.00 COMMENT '已结算金额',
  `status` varchar(20) NOT NULL DEFAULT 'pending' COMMENT 'pending待处理/confirmed已确认/cancelled已取消',
  `refund_mode` varchar(20) NOT NULL DEFAULT 'cash' COMMENT '退款方式：cash现金退回/offset应付冲减/balance余额',
  `capital_account_id` int NOT NULL DEFAULT 0 COMMENT '结算账户ID（现金退款时）',
  `return_to_warehouse_id` int NOT NULL DEFAULT 0 COMMENT '退回仓库ID',
  `return_to_location_id` int NOT NULL DEFAULT 0 COMMENT '退回库位ID',
  `remark` varchar(500) NOT NULL DEFAULT '',
  `occurred_at` int NOT NULL DEFAULT 0 COMMENT '退货发生时间',
  `create_at` int NOT NULL DEFAULT 0,
  `update_at` int NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_site_return_no` (`site_id`,`return_no`),
  UNIQUE KEY `uk_site_request` (`site_id`,`request_id`),
  KEY `idx_sale` (`sale_order_id`),
  KEY `idx_party` (`site_id`,`party_id`),
  KEY `idx_status` (`site_id`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='ERP-销售退货单';

CREATE TABLE IF NOT EXISTS `{{prefix}}erp_sale_return_item` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `site_id` int NOT NULL DEFAULT 0,
  `return_id` int NOT NULL DEFAULT 0 COMMENT '退货单ID',
  `asset_id` int NOT NULL DEFAULT 0 COMMENT '退货设备ID',
  `asset_no` varchar(40) NOT NULL DEFAULT '' COMMENT '设备资产号快照',
  `imei` varchar(64) NOT NULL DEFAULT '' COMMENT 'IMEI快照',
  `model` varchar(255) NOT NULL DEFAULT '' COMMENT '型号快照',
  `sale_item_id` int NOT NULL DEFAULT 0 COMMENT '原销售明细ID',
  `sale_price` decimal(12,2) NOT NULL DEFAULT 0.00 COMMENT '原销售价快照',
  `return_price` decimal(12,2) NOT NULL DEFAULT 0.00 COMMENT '实际退款价（可与销售价不同）',
  `received_amount` decimal(12,2) NOT NULL DEFAULT 0.00 COMMENT '该设备已收款金额（决定退款方式）',
  `reason` varchar(255) NOT NULL DEFAULT '' COMMENT '退货原因',
  `create_at` int NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_return` (`return_id`),
  KEY `idx_asset` (`asset_id`),
  KEY `idx_sale_item` (`sale_item_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='ERP-销售退货明细';
CREATE TABLE IF NOT EXISTS `{{prefix}}erp_printer` (
  `id` int unsigned NOT NULL AUTO_INCREMENT, `site_id` int NOT NULL DEFAULT 0,
  `printer_name` varchar(100) NOT NULL DEFAULT '', `driver` varchar(40) NOT NULL DEFAULT '',
  `connection_mode` varchar(20) NOT NULL DEFAULT 'cloud', `print_type` varchar(20) NOT NULL DEFAULT 'receipt',
  `paper_width` int NOT NULL DEFAULT 58, `config_json` longtext NULL, `capabilities_json` longtext NULL,
  `copies` tinyint NOT NULL DEFAULT 1, `is_default` tinyint(1) NOT NULL DEFAULT 0, `status` tinyint(1) NOT NULL DEFAULT 1,
  `sort` int NOT NULL DEFAULT 0, `remark` varchar(255) NOT NULL DEFAULT '', `create_at` int NOT NULL DEFAULT 0, `update_at` int NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`), KEY `idx_site_type` (`site_id`,`print_type`,`status`), KEY `idx_site_default` (`site_id`,`is_default`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='ERP-打印设备';

CREATE TABLE IF NOT EXISTS `{{prefix}}erp_print_template` (
  `id` int unsigned NOT NULL AUTO_INCREMENT, `site_id` int NOT NULL DEFAULT 0,
  `builtin_key` varchar(60) DEFAULT NULL, `template_name` varchar(100) NOT NULL DEFAULT '',
  `print_type` varchar(20) NOT NULL DEFAULT 'receipt', `layout_mode` varchar(20) NOT NULL DEFAULT 'native',
  `paper_width` int NOT NULL DEFAULT 58, `content` longtext NULL, `is_builtin` tinyint(1) NOT NULL DEFAULT 0,
  `is_default` tinyint(1) NOT NULL DEFAULT 0, `status` tinyint(1) NOT NULL DEFAULT 1, `sort` int NOT NULL DEFAULT 0,
  `create_at` int NOT NULL DEFAULT 0, `update_at` int NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`), UNIQUE KEY `uk_site_builtin` (`site_id`,`builtin_key`), KEY `idx_site_type` (`site_id`,`print_type`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='ERP-打印模板';

CREATE TABLE IF NOT EXISTS `{{prefix}}erp_print_scene` (
  `id` int unsigned NOT NULL AUTO_INCREMENT, `site_id` int NOT NULL DEFAULT 0,
  `scene_key` varchar(60) NOT NULL DEFAULT '', `scene_name` varchar(100) NOT NULL DEFAULT '', `trigger_key` varchar(80) NOT NULL DEFAULT '',
  `biz_type` varchar(40) NOT NULL DEFAULT '', `template_type` varchar(20) NOT NULL DEFAULT 'receipt', `description` varchar(500) NOT NULL DEFAULT '',
  `printer_id` int NOT NULL DEFAULT 0, `template_id` int NOT NULL DEFAULT 0, `auto_print` tinyint(1) NOT NULL DEFAULT 0,
  `enabled` tinyint(1) NOT NULL DEFAULT 0, `copies` tinyint NOT NULL DEFAULT 1, `granularity` varchar(20) NOT NULL DEFAULT 'order',
  `condition_json` longtext NULL, `sort` int NOT NULL DEFAULT 0, `create_at` int NOT NULL DEFAULT 0, `update_at` int NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`), UNIQUE KEY `uk_site_scene` (`site_id`,`scene_key`), KEY `idx_site_trigger` (`site_id`,`trigger_key`,`enabled`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='ERP-打印场景';

CREATE TABLE IF NOT EXISTS `{{prefix}}erp_print_job` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT, `site_id` int NOT NULL DEFAULT 0,
  `job_no` varchar(40) NOT NULL DEFAULT '', `request_id` varchar(80) DEFAULT NULL,
  `scene_key` varchar(60) NOT NULL DEFAULT '', `scene_name` varchar(100) NOT NULL DEFAULT '',
  `biz_type` varchar(40) NOT NULL DEFAULT '', `biz_id` int NOT NULL DEFAULT 0, `biz_no` varchar(80) NOT NULL DEFAULT '',
  `printer_id` int NOT NULL DEFAULT 0, `printer_name` varchar(100) NOT NULL DEFAULT '', `driver` varchar(40) NOT NULL DEFAULT '',
  `template_id` int NOT NULL DEFAULT 0, `template_name` varchar(100) NOT NULL DEFAULT '', `print_type` varchar(20) NOT NULL DEFAULT 'receipt',
  `copies` tinyint NOT NULL DEFAULT 1, `rendered_content` longtext NULL, `client_payload` longtext NULL,
  `status` varchar(20) NOT NULL DEFAULT 'queued', `attempts` int NOT NULL DEFAULT 0, `provider_job_no` varchar(100) NOT NULL DEFAULT '',
  `error_message` varchar(1000) NOT NULL DEFAULT '', `operator_uid` int NOT NULL DEFAULT 0, `operator_name` varchar(60) NOT NULL DEFAULT '',
  `start_at` int NOT NULL DEFAULT 0, `finish_at` int NOT NULL DEFAULT 0, `create_at` int NOT NULL DEFAULT 0, `update_at` int NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`), UNIQUE KEY `uk_site_job` (`site_id`,`job_no`), UNIQUE KEY `uk_site_request` (`site_id`,`request_id`),
  KEY `idx_site_status` (`site_id`,`status`,`create_at`), KEY `idx_site_biz` (`site_id`,`biz_type`,`biz_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='ERP-打印任务与日志';
