-- ============================================================
-- hsx_erp clean install SQL
-- ERP 独立产品:采购/库存/销售/财务确认/折账/流水/集成事件
-- ============================================================

CREATE TABLE IF NOT EXISTS `{{prefix}}erp_capital_account` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `site_id` int NOT NULL DEFAULT 0 COMMENT '站点ID',
  `account_name` varchar(100) NOT NULL DEFAULT '' COMMENT '账户名称',
  `account_type` varchar(20) NOT NULL DEFAULT 'bank' COMMENT 'cash现金/wechat微信/alipay支付宝/bank银行卡/other其他',
  `bank_name` varchar(100) NOT NULL DEFAULT '' COMMENT '开户行',
  `account_no` varchar(100) NOT NULL DEFAULT '' COMMENT '账号/卡号',
  `holder` varchar(60) NOT NULL DEFAULT '' COMMENT '户名',
  `balance` decimal(14,2) NOT NULL DEFAULT 0.00 COMMENT '当前余额',
  `is_default` tinyint(1) NOT NULL DEFAULT 0 COMMENT '默认账户',
  `status` tinyint(1) NOT NULL DEFAULT 1 COMMENT '1启用/0停用',
  `sort` int NOT NULL DEFAULT 0,
  `remark` varchar(255) NOT NULL DEFAULT '',
  `create_at` int NOT NULL DEFAULT 0,
  `update_at` int NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_site_status` (`site_id`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='ERP-资金账户';

CREATE TABLE IF NOT EXISTS `{{prefix}}erp_warehouse` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `site_id` int NOT NULL DEFAULT 0 COMMENT '站点ID',
  `warehouse_name` varchar(100) NOT NULL DEFAULT '' COMMENT '仓库名称',
  `warehouse_code` varchar(60) NOT NULL DEFAULT '' COMMENT '仓库编码',
  `status` tinyint(1) NOT NULL DEFAULT 1 COMMENT '1启用/0停用',
  `is_default` tinyint(1) NOT NULL DEFAULT 0 COMMENT '默认入库仓',
  `sort` int NOT NULL DEFAULT 0,
  `remark` varchar(255) NOT NULL DEFAULT '',
  `create_at` int NOT NULL DEFAULT 0,
  `update_at` int NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_site_name` (`site_id`,`warehouse_name`),
  KEY `idx_site_status` (`site_id`,`status`,`sort`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='ERP-仓库';

CREATE TABLE IF NOT EXISTS `{{prefix}}erp_warehouse_location` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `site_id` int NOT NULL DEFAULT 0 COMMENT '站点ID',
  `warehouse_id` int NOT NULL DEFAULT 0 COMMENT '仓库ID',
  `location_name` varchar(100) NOT NULL DEFAULT '' COMMENT '库位名称',
  `location_code` varchar(60) NOT NULL DEFAULT '' COMMENT '库位编码',
  `status` tinyint(1) NOT NULL DEFAULT 1 COMMENT '1启用/0停用',
  `sort` int NOT NULL DEFAULT 0,
  `remark` varchar(255) NOT NULL DEFAULT '',
  `create_at` int NOT NULL DEFAULT 0,
  `update_at` int NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_warehouse_name` (`site_id`,`warehouse_id`,`location_name`),
  KEY `idx_site_warehouse` (`site_id`,`warehouse_id`,`status`,`sort`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='ERP-仓库库位';

CREATE TABLE IF NOT EXISTS `{{prefix}}erp_party` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `site_id` int NOT NULL DEFAULT 0 COMMENT '站点ID',
  `party_no` varchar(40) NOT NULL DEFAULT '' COMMENT '往来单位编号',
  `party_name` varchar(100) NOT NULL DEFAULT '' COMMENT '往来单位名称',
  `party_type` varchar(20) NOT NULL DEFAULT 'customer' COMMENT 'customer客户/supplier供应商/channel渠道/other其他',
  `contact_name` varchar(60) NOT NULL DEFAULT '' COMMENT '联系人',
  `contact_mobile` varchar(30) NOT NULL DEFAULT '' COMMENT '联系电话',
  `m_no` varchar(64) NOT NULL DEFAULT '' COMMENT 'M号/会员号/业务编号',
  `remark` varchar(255) NOT NULL DEFAULT '',
  `status` tinyint(1) NOT NULL DEFAULT 1 COMMENT '1启用/0停用',
  `create_at` int NOT NULL DEFAULT 0,
  `update_at` int NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_site_no` (`site_id`,`party_no`),
  KEY `idx_site_name` (`site_id`,`party_name`),
  KEY `idx_site_mno` (`site_id`,`m_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='ERP-往来单位';

CREATE TABLE IF NOT EXISTS `{{prefix}}erp_party_member` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `site_id` int NOT NULL DEFAULT 0 COMMENT '站点ID',
  `party_id` int NOT NULL DEFAULT 0 COMMENT '往来主体ID',
  `member_id` int NOT NULL DEFAULT 0 COMMENT '对接人会员ID',
  `relation_role` varchar(20) NOT NULL DEFAULT 'business' COMMENT 'owner/finance/business',
  `is_finance_contact` tinyint(1) NOT NULL DEFAULT 0 COMMENT '是否主要财务联系人',
  `status` tinyint(1) NOT NULL DEFAULT 1 COMMENT '1有效/0失效',
  `remark` varchar(255) NOT NULL DEFAULT '',
  `create_at` int NOT NULL DEFAULT 0,
  `update_at` int NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_site_member` (`site_id`,`member_id`),
  KEY `idx_party` (`site_id`,`party_id`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='ERP-往来主体对接人';

CREATE TABLE IF NOT EXISTS `{{prefix}}erp_asset` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `site_id` int NOT NULL DEFAULT 0 COMMENT '站点ID',
  `asset_no` varchar(40) NOT NULL DEFAULT '' COMMENT '资产编号',
  `purchase_order_id` int NOT NULL DEFAULT 0 COMMENT '采购单ID',
  `purchase_item_id` int NOT NULL DEFAULT 0 COMMENT '采购明细ID',
  `sale_order_id` int NOT NULL DEFAULT 0 COMMENT '销售单ID',
  `sale_item_id` int NOT NULL DEFAULT 0 COMMENT '销售明细ID',
  `party_id` int NOT NULL DEFAULT 0 COMMENT '采购来源往来单位',
  `party_name` varchar(100) NOT NULL DEFAULT '' COMMENT '采购来源名称快照',
  `warehouse_id` int NOT NULL DEFAULT 0 COMMENT '仓库ID',
  `warehouse_name` varchar(100) NOT NULL DEFAULT '' COMMENT '仓库名称快照',
  `location_id` int NOT NULL DEFAULT 0 COMMENT '库位ID',
  `location_name` varchar(100) NOT NULL DEFAULT '' COMMENT '库位名称快照',
  `imei` varchar(64) NOT NULL DEFAULT '',
  `sn` varchar(64) NOT NULL DEFAULT '',
  `model` varchar(255) NOT NULL DEFAULT '',
  `spec` varchar(255) NOT NULL DEFAULT '' COMMENT '容量/颜色/成色等',
  `purchase_cost` decimal(12,2) NOT NULL DEFAULT 0.00 COMMENT '采购成本',
  `adjust_cost` decimal(12,2) NOT NULL DEFAULT 0.00 COMMENT '成本调整合计',
  `refurbish_cost` decimal(12,2) NOT NULL DEFAULT 0.00 COMMENT '整备成本合计',
  `total_cost` decimal(12,2) NOT NULL DEFAULT 0.00 COMMENT '当前总成本',
  `sale_price` decimal(12,2) NOT NULL DEFAULT 0.00 COMMENT '销售价快照',
  `profit` decimal(12,2) NOT NULL DEFAULT 0.00 COMMENT '毛利快照',
  `status` varchar(20) NOT NULL DEFAULT 'in_stock' COMMENT 'in_stock库存中/sold已售/returned已退/void作废',
  `source_plugin` varchar(40) NOT NULL DEFAULT 'erp' COMMENT '来源插件',
  `source_type` varchar(40) NOT NULL DEFAULT 'manual' COMMENT '来源类型',
  `source_id` varchar(64) NOT NULL DEFAULT '' COMMENT '来源ID',
  `remark` varchar(255) NOT NULL DEFAULT '',
  `create_at` int NOT NULL DEFAULT 0,
  `update_at` int NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_site_no` (`site_id`,`asset_no`),
  KEY `idx_site_status` (`site_id`,`status`),
  KEY `idx_site_imei` (`site_id`,`imei`),
  KEY `idx_purchase` (`purchase_order_id`,`purchase_item_id`),
  KEY `idx_sale` (`sale_order_id`,`sale_item_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='ERP-库存资产';

CREATE TABLE IF NOT EXISTS `{{prefix}}erp_asset_ledger` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `site_id` int NOT NULL DEFAULT 0,
  `asset_id` int NOT NULL DEFAULT 0,
  `action` varchar(30) NOT NULL DEFAULT '' COMMENT 'inbound/sold/return/adjust/refurbish/void',
  `before_status` varchar(20) NOT NULL DEFAULT '',
  `after_status` varchar(20) NOT NULL DEFAULT '',
  `source_type` varchar(40) NOT NULL DEFAULT '',
  `source_id` int NOT NULL DEFAULT 0,
  `operator_uid` int NOT NULL DEFAULT 0,
  `operator_name` varchar(60) NOT NULL DEFAULT '',
  `remark` varchar(255) NOT NULL DEFAULT '',
  `create_at` int NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_asset` (`site_id`,`asset_id`),
  KEY `idx_action` (`site_id`,`action`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='ERP-资产流水';

CREATE TABLE IF NOT EXISTS `{{prefix}}erp_purchase_order` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `site_id` int NOT NULL DEFAULT 0,
  `purchase_no` varchar(40) NOT NULL DEFAULT '' COMMENT '采购单号',
  `party_id` int NOT NULL DEFAULT 0 COMMENT '采购渠道/供应商/客户',
  `party_name` varchar(100) NOT NULL DEFAULT '',
  `m_no` varchar(64) NOT NULL DEFAULT '' COMMENT 'M号',
  `purchase_channel` varchar(60) NOT NULL DEFAULT '' COMMENT '采购渠道',
  `settle_method` varchar(30) NOT NULL DEFAULT '' COMMENT '结算方式',
  `capital_account_id` int NOT NULL DEFAULT 0 COMMENT '本次付款账户',
  `capital_account_name` varchar(100) NOT NULL DEFAULT '' COMMENT '本次付款账户名称',
  `warehouse_id` int NOT NULL DEFAULT 0,
  `warehouse_name` varchar(100) NOT NULL DEFAULT '',
  `location_id` int NOT NULL DEFAULT 0,
  `location_name` varchar(100) NOT NULL DEFAULT '',
  `purchaser_uid` int NOT NULL DEFAULT 0,
  `purchaser_name` varchar(60) NOT NULL DEFAULT '',
  `inspector_uid` int NOT NULL DEFAULT 0,
  `inspector_name` varchar(60) NOT NULL DEFAULT '',
  `total_cost` decimal(12,2) NOT NULL DEFAULT 0.00,
  `paid_amount` decimal(12,2) NOT NULL DEFAULT 0.00 COMMENT '财务已确认付款',
  `payable_amount` decimal(12,2) NOT NULL DEFAULT 0.00 COMMENT '剩余应付',
  `finance_status` varchar(20) NOT NULL DEFAULT 'pending' COMMENT 'pending/partial/settled',
  `status` varchar(20) NOT NULL DEFAULT 'completed' COMMENT 'draft/completed/returned/void',
  `source_plugin` varchar(40) NOT NULL DEFAULT 'erp',
  `source_type` varchar(40) NOT NULL DEFAULT 'manual',
  `source_id` varchar(64) NOT NULL DEFAULT '',
  `operator_uid` int NOT NULL DEFAULT 0,
  `operator_name` varchar(60) NOT NULL DEFAULT '',
  `purchase_at` int NOT NULL DEFAULT 0,
  `remark` varchar(255) NOT NULL DEFAULT '',
  `create_at` int NOT NULL DEFAULT 0,
  `update_at` int NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_site_no` (`site_id`,`purchase_no`),
  KEY `idx_party` (`site_id`,`party_id`,`finance_status`),
  KEY `idx_status` (`site_id`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='ERP-采购单';

CREATE TABLE IF NOT EXISTS `{{prefix}}erp_purchase_item` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `site_id` int NOT NULL DEFAULT 0,
  `purchase_order_id` int NOT NULL DEFAULT 0,
  `asset_id` int NOT NULL DEFAULT 0,
  `imei` varchar(64) NOT NULL DEFAULT '',
  `sn` varchar(64) NOT NULL DEFAULT '',
  `model` varchar(255) NOT NULL DEFAULT '',
  `spec` varchar(255) NOT NULL DEFAULT '',
  `purchase_cost` decimal(12,2) NOT NULL DEFAULT 0.00,
  `adjust_cost` decimal(12,2) NOT NULL DEFAULT 0.00,
  `total_cost` decimal(12,2) NOT NULL DEFAULT 0.00,
  `status` varchar(20) NOT NULL DEFAULT 'in_stock',
  `remark` varchar(255) NOT NULL DEFAULT '',
  `create_at` int NOT NULL DEFAULT 0,
  `update_at` int NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_order` (`purchase_order_id`),
  KEY `idx_asset` (`asset_id`),
  KEY `idx_imei` (`site_id`,`imei`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='ERP-采购明细';

CREATE TABLE IF NOT EXISTS `{{prefix}}erp_sale_order` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `site_id` int NOT NULL DEFAULT 0,
  `sale_no` varchar(40) NOT NULL DEFAULT '' COMMENT '销售单号',
  `party_id` int NOT NULL DEFAULT 0 COMMENT '销售客户/渠道',
  `party_name` varchar(100) NOT NULL DEFAULT '',
  `sale_channel` varchar(60) NOT NULL DEFAULT '',
  `settle_method` varchar(30) NOT NULL DEFAULT '',
  `salesman_uid` int NOT NULL DEFAULT 0,
  `salesman_name` varchar(60) NOT NULL DEFAULT '',
  `total_amount` decimal(12,2) NOT NULL DEFAULT 0.00,
  `total_cost` decimal(12,2) NOT NULL DEFAULT 0.00,
  `profit` decimal(12,2) NOT NULL DEFAULT 0.00,
  `received_amount` decimal(12,2) NOT NULL DEFAULT 0.00 COMMENT '财务已确认收款',
  `receivable_amount` decimal(12,2) NOT NULL DEFAULT 0.00 COMMENT '剩余应收',
  `finance_status` varchar(20) NOT NULL DEFAULT 'pending' COMMENT 'pending/partial/settled',
  `status` varchar(20) NOT NULL DEFAULT 'completed' COMMENT 'completed/returned/void',
  `operator_uid` int NOT NULL DEFAULT 0,
  `operator_name` varchar(60) NOT NULL DEFAULT '',
  `sale_at` int NOT NULL DEFAULT 0,
  `remark` varchar(255) NOT NULL DEFAULT '',
  `create_at` int NOT NULL DEFAULT 0,
  `update_at` int NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_site_no` (`site_id`,`sale_no`),
  KEY `idx_party` (`site_id`,`party_id`,`finance_status`),
  KEY `idx_status` (`site_id`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='ERP-销售单';

CREATE TABLE IF NOT EXISTS `{{prefix}}erp_sale_item` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `site_id` int NOT NULL DEFAULT 0,
  `sale_order_id` int NOT NULL DEFAULT 0,
  `asset_id` int NOT NULL DEFAULT 0,
  `imei` varchar(64) NOT NULL DEFAULT '',
  `model` varchar(255) NOT NULL DEFAULT '',
  `cost` decimal(12,2) NOT NULL DEFAULT 0.00,
  `sale_price` decimal(12,2) NOT NULL DEFAULT 0.00,
  `profit` decimal(12,2) NOT NULL DEFAULT 0.00,
  `status` varchar(20) NOT NULL DEFAULT 'sold',
  `remark` varchar(255) NOT NULL DEFAULT '',
  `create_at` int NOT NULL DEFAULT 0,
  `update_at` int NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_order` (`sale_order_id`),
  KEY `idx_asset` (`asset_id`),
  KEY `idx_imei` (`site_id`,`imei`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='ERP-销售明细';

CREATE TABLE IF NOT EXISTS `{{prefix}}erp_payable` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `site_id` int NOT NULL DEFAULT 0,
  `payable_no` varchar(40) NOT NULL DEFAULT '',
  `party_id` int NOT NULL DEFAULT 0,
  `party_name` varchar(100) NOT NULL DEFAULT '',
  `source_type` varchar(40) NOT NULL DEFAULT '',
  `source_id` int NOT NULL DEFAULT 0,
  `source_no` varchar(40) NOT NULL DEFAULT '',
  `amount` decimal(12,2) NOT NULL DEFAULT 0.00,
  `settled_amount` decimal(12,2) NOT NULL DEFAULT 0.00,
  `status` varchar(20) NOT NULL DEFAULT 'pending',
  `occurred_at` int NOT NULL DEFAULT 0,
  `remark` varchar(255) NOT NULL DEFAULT '',
  `create_at` int NOT NULL DEFAULT 0,
  `update_at` int NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_site_no` (`site_id`,`payable_no`),
  KEY `idx_party` (`site_id`,`party_id`,`status`),
  KEY `idx_source` (`site_id`,`source_type`,`source_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='ERP-应付款';

CREATE TABLE IF NOT EXISTS `{{prefix}}erp_receivable` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `site_id` int NOT NULL DEFAULT 0,
  `receivable_no` varchar(40) NOT NULL DEFAULT '',
  `party_id` int NOT NULL DEFAULT 0,
  `party_name` varchar(100) NOT NULL DEFAULT '',
  `source_type` varchar(40) NOT NULL DEFAULT '',
  `source_id` int NOT NULL DEFAULT 0,
  `source_no` varchar(40) NOT NULL DEFAULT '',
  `amount` decimal(12,2) NOT NULL DEFAULT 0.00,
  `settled_amount` decimal(12,2) NOT NULL DEFAULT 0.00,
  `status` varchar(20) NOT NULL DEFAULT 'pending',
  `occurred_at` int NOT NULL DEFAULT 0,
  `remark` varchar(255) NOT NULL DEFAULT '',
  `create_at` int NOT NULL DEFAULT 0,
  `update_at` int NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_site_no` (`site_id`,`receivable_no`),
  KEY `idx_party` (`site_id`,`party_id`,`status`),
  KEY `idx_source` (`site_id`,`source_type`,`source_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='ERP-应收款';

CREATE TABLE IF NOT EXISTS `{{prefix}}erp_settlement` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `site_id` int NOT NULL DEFAULT 0,
  `settlement_no` varchar(40) NOT NULL DEFAULT '',
  `party_id` int NOT NULL DEFAULT 0,
  `party_name` varchar(100) NOT NULL DEFAULT '',
  `settlement_type` varchar(20) NOT NULL DEFAULT 'payment' COMMENT 'payment付款/receipt收款/refund退款/offset折账',
  `amount` decimal(12,2) NOT NULL DEFAULT 0.00,
  `cash_direction` varchar(10) NOT NULL DEFAULT 'none' COMMENT 'in收入/out支出/none无现金',
  `capital_account_id` int NOT NULL DEFAULT 0,
  `capital_account_name` varchar(100) NOT NULL DEFAULT '',
  `status` varchar(20) NOT NULL DEFAULT 'confirmed',
  `operator_uid` int NOT NULL DEFAULT 0,
  `operator_name` varchar(60) NOT NULL DEFAULT '',
  `confirmed_at` int NOT NULL DEFAULT 0,
  `remark` varchar(255) NOT NULL DEFAULT '',
  `create_at` int NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_site_no` (`site_id`,`settlement_no`),
  KEY `idx_party` (`site_id`,`party_id`),
  KEY `idx_type` (`site_id`,`settlement_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='ERP-财务确认结算单';

CREATE TABLE IF NOT EXISTS `{{prefix}}erp_settlement_link` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `site_id` int NOT NULL DEFAULT 0,
  `settlement_id` int NOT NULL DEFAULT 0,
  `target_type` varchar(20) NOT NULL DEFAULT '' COMMENT 'payable/receivable',
  `target_id` int NOT NULL DEFAULT 0,
  `applied_amount` decimal(12,2) NOT NULL DEFAULT 0.00,
  `create_at` int NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_settlement` (`settlement_id`),
  KEY `idx_target` (`site_id`,`target_type`,`target_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='ERP-结算核销明细';

CREATE TABLE IF NOT EXISTS `{{prefix}}erp_money_ledger` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `site_id` int NOT NULL DEFAULT 0,
  `ledger_no` varchar(40) NOT NULL DEFAULT '',
  `settlement_id` int NOT NULL DEFAULT 0,
  `capital_account_id` int NOT NULL DEFAULT 0,
  `capital_account_name` varchar(100) NOT NULL DEFAULT '',
  `direction` varchar(10) NOT NULL DEFAULT 'in',
  `amount` decimal(12,2) NOT NULL DEFAULT 0.00,
  `balance_after` decimal(14,2) NOT NULL DEFAULT 0.00 COMMENT '记账后余额',
  `party_id` int NOT NULL DEFAULT 0,
  `party_name` varchar(100) NOT NULL DEFAULT '',
  `operator_uid` int NOT NULL DEFAULT 0,
  `operator_name` varchar(60) NOT NULL DEFAULT '',
  `occurred_at` int NOT NULL DEFAULT 0,
  `remark` varchar(255) NOT NULL DEFAULT '',
  `create_at` int NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_site_no` (`site_id`,`ledger_no`),
  KEY `idx_account` (`site_id`,`capital_account_id`,`occurred_at`),
  KEY `idx_party` (`site_id`,`party_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='ERP-真实资金流水';

CREATE TABLE IF NOT EXISTS `{{prefix}}erp_account_ledger` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `site_id` int NOT NULL DEFAULT 0,
  `ledger_no` varchar(40) NOT NULL DEFAULT '',
  `biz_type` varchar(40) NOT NULL DEFAULT '' COMMENT 'purchase/sale/payment/receipt/offset/adjust/return',
  `direction` varchar(20) NOT NULL DEFAULT '' COMMENT 'increase/decrease/none',
  `amount` decimal(12,2) NOT NULL DEFAULT 0.00,
  `party_id` int NOT NULL DEFAULT 0,
  `party_name` varchar(100) NOT NULL DEFAULT '',
  `asset_id` int NOT NULL DEFAULT 0,
  `source_type` varchar(40) NOT NULL DEFAULT '',
  `source_id` int NOT NULL DEFAULT 0,
  `source_no` varchar(40) NOT NULL DEFAULT '',
  `operator_uid` int NOT NULL DEFAULT 0,
  `operator_name` varchar(60) NOT NULL DEFAULT '',
  `occurred_at` int NOT NULL DEFAULT 0,
  `remark` varchar(255) NOT NULL DEFAULT '',
  `create_at` int NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_site_no` (`site_id`,`ledger_no`),
  KEY `idx_party` (`site_id`,`party_id`,`occurred_at`),
  KEY `idx_asset` (`site_id`,`asset_id`),
  KEY `idx_source` (`site_id`,`source_type`,`source_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='ERP-业务账目流水';

CREATE TABLE IF NOT EXISTS `{{prefix}}erp_offset` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `site_id` int NOT NULL DEFAULT 0,
  `offset_no` varchar(40) NOT NULL DEFAULT '',
  `settlement_id` int NOT NULL DEFAULT 0,
  `party_id` int NOT NULL DEFAULT 0,
  `party_name` varchar(100) NOT NULL DEFAULT '',
  `amount` decimal(12,2) NOT NULL DEFAULT 0.00,
  `operator_uid` int NOT NULL DEFAULT 0,
  `operator_name` varchar(60) NOT NULL DEFAULT '',
  `confirmed_at` int NOT NULL DEFAULT 0,
  `remark` varchar(255) NOT NULL DEFAULT '',
  `create_at` int NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_site_no` (`site_id`,`offset_no`),
  KEY `idx_party` (`site_id`,`party_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='ERP-折账记录';

CREATE TABLE IF NOT EXISTS `{{prefix}}erp_offset_link` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `site_id` int NOT NULL DEFAULT 0,
  `offset_id` int NOT NULL DEFAULT 0,
  `target_type` varchar(20) NOT NULL DEFAULT '' COMMENT 'payable/receivable',
  `target_id` int NOT NULL DEFAULT 0,
  `applied_amount` decimal(12,2) NOT NULL DEFAULT 0.00,
  `create_at` int NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_offset` (`offset_id`),
  KEY `idx_target` (`site_id`,`target_type`,`target_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='ERP-折账明细';

CREATE TABLE IF NOT EXISTS `{{prefix}}erp_inbox_event` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `site_id` int NOT NULL DEFAULT 0,
  `event_id` varchar(80) NOT NULL DEFAULT '' COMMENT '外部事件幂等键',
  `source_plugin` varchar(40) NOT NULL DEFAULT '' COMMENT '来源插件',
  `event_name` varchar(80) NOT NULL DEFAULT '',
  `payload_json` longtext COMMENT '事件内容',
  `status` varchar(20) NOT NULL DEFAULT 'pending',
  `occurred_at` int NOT NULL DEFAULT 0,
  `create_at` int NOT NULL DEFAULT 0,
  `update_at` int NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_site_event` (`site_id`,`event_id`),
  KEY `idx_status` (`site_id`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='ERP-外部事件收件箱';

CREATE TABLE IF NOT EXISTS `{{prefix}}erp_outbox_event` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `site_id` int NOT NULL DEFAULT 0,
  `event_id` varchar(80) NOT NULL DEFAULT '' COMMENT 'ERP事件幂等键',
  `event_name` varchar(80) NOT NULL DEFAULT '',
  `payload_json` longtext COMMENT '事件内容',
  `status` varchar(20) NOT NULL DEFAULT 'pending',
  `occurred_at` int NOT NULL DEFAULT 0,
  `create_at` int NOT NULL DEFAULT 0,
  `update_at` int NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_site_event` (`site_id`,`event_id`),
  KEY `idx_status` (`site_id`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='ERP-对外事件发件箱';
