<template>
    <div class="main-container"><el-card class="!border-none" shadow="never"><div class="page">
        <div class="page-head"><div><div class="text-page-title">开卡订单</div><p>每张卡都能追溯开单人、收款状态、权益和操作记录。</p></div><el-button type="primary" @click="issueVisible=true"><el-icon><Plus/></el-icon>快速开卡</el-button></div>
        <el-tabs v-model="query.finance_status" @tab-change="reload"><el-tab-pane label="全部订单" name=""/><el-tab-pane label="待收款" name="pending"/><el-tab-pane label="部分收款" name="partial"/><el-tab-pane label="已结清" name="settled"/><el-tab-pane label="处理失败" name="failed"/></el-tabs>
        <div class="toolbar"><el-input v-model="query.keyword" clearable placeholder="订单号 / 姓名 / 手机号 / 卡种" @keyup.enter="reload"/><el-button type="primary" @click="reload">查询</el-button><el-button @click="reset">重置</el-button></div>
        <el-table :data="rows" v-loading="loading" @row-click="openDetail"><el-table-column label="客户与卡种" min-width="260"><template #default="{row}"><b>{{ row.holder_name }}</b><span class="mobile">{{ mask(row.holder_mobile) }}</span><div class="sub">{{ row.product_name }}</div></template></el-table-column><el-table-column label="订单" min-width="210"><template #default="{row}"><span>{{ row.order_no }}</span><div class="sub">{{ time(row.create_at) }} · {{ row.issuer_name }}</div></template></el-table-column><el-table-column label="金额" width="140"><template #default="{row}"><b>¥{{ money(row.order_amount) }}</b><div class="sub">已收 ¥{{ money(row.paid_amount) }}</div></template></el-table-column><el-table-column label="业务状态" width="110"><template #default="{row}"><MemberCardStatusTag :value="row.business_status"/></template></el-table-column><el-table-column label="收款状态" width="110"><template #default="{row}"><MemberCardStatusTag :value="row.finance_status"/></template></el-table-column><el-table-column label="结算方式" width="110"><template #default="{row}">{{ row.settlement_mode==='immediate'?'现场收款':'ERP 应收' }}</template></el-table-column><el-table-column label="操作" width="120" align="right"><template #default="{row}"><el-button link type="primary" @click.stop="openDetail(row)">查看</el-button></template></el-table-column></el-table>
        <div class="pagination"><el-pagination v-model:current-page="query.page" v-model:page-size="query.limit" layout="total,prev,pager,next" :total="total" @current-change="load"/></div>
        <el-drawer v-model="detailVisible" size="min(760px,92vw)" title="开卡订单详情"><div v-if="detail" v-loading="detailLoading"><div class="detail-hero"><div><span>购卡客户</span><h3>{{ detail.holder_name }} <small>{{ mask(detail.holder_mobile) }}</small></h3><p>{{ detail.order_no }}</p></div><div class="hero-amount"><span>订单金额</span><strong>¥{{ money(detail.order_amount) }}</strong><MemberCardStatusTag :value="detail.finance_status"/></div></div><div class="info-grid"><div><span>卡种</span><b>{{ detail.product_name }}</b></div><div><span>卡号</span><b>{{ detail.card?.card_no||'—' }}</b></div><div><span>开单人</span><b>{{ detail.issuer_name||'—' }}</b></div><div><span>收款账户</span><b>{{ detail.capital_account_name||'—' }}</b></div></div><h4>卡内权益</h4><el-table :data="detail.card_items||[]" size="small"><el-table-column prop="item_name" label="服务"/><el-table-column label="次数"><template #default="{row}">{{ row.usage_mode==='unlimited'?'不限次':`${row.used_times}/${row.granted_times}，剩 ${row.remaining_times}` }}</template></el-table-column><el-table-column prop="recognized_amount" label="已确认收入"><template #default="{row}">¥{{ money(row.recognized_amount) }}</template></el-table-column></el-table><h4>处理记录</h4><el-timeline><el-timeline-item v-for="log in detail.operation_logs||[]" :key="log.id" :timestamp="time(log.occurred_at)">{{ actionText(log.action) }} · {{ log.operator_name||'系统' }}</el-timeline-item></el-timeline><el-alert v-if="detail.last_error" :title="detail.last_error" type="error" :closable="false" show-icon/><div class="drawer-actions"><el-button v-if="detail.finance_status==='failed'" type="warning" @click="retryFinance">重试财务处理</el-button><el-button v-if="canCancel" @click="cancelOrder">取消开卡</el-button><el-button v-if="canRefund" type="danger" plain @click="refundVisible=true">整卡退款</el-button></div></div></el-drawer>
        <el-dialog v-model="refundVisible" title="整卡退款" width="520px"><el-alert title="仅支持已结清且没有有效核销的整卡退款。财务退款会生成 ERP 应付，现场退款需要选择出款账户。" type="warning" :closable="false"/><el-form label-width="90px" class="dialog-form"><el-form-item label="退款方式"><el-radio-group v-model="refund.refund_mode"><el-radio-button value="finance">财务退款</el-radio-button><el-radio-button value="immediate">现场退款</el-radio-button></el-radio-group></el-form-item><el-form-item v-if="refund.refund_mode==='immediate'" label="出款账户"><el-select v-model="refund.capital_account_id" class="w-full"><el-option v-for="a in accounts" :key="a.id" :label="a.name" :value="a.id"/></el-select></el-form-item><el-form-item label="退款原因"><el-input v-model="refund.reason" type="textarea" :rows="3"/></el-form-item></el-form><template #footer><el-button @click="refundVisible=false">取消</el-button><el-button type="danger" :loading="actionLoading" @click="submitRefund">确认发起退款</el-button></template></el-dialog>
        <MemberCardIssueDialog v-model="issueVisible" @success="reload"/>
    </div></el-card></div>
</template>
<script setup lang="ts">
import { computed,onMounted,reactive,ref } from 'vue';import { ElMessage,ElMessageBox } from 'element-plus';import { Plus } from '@element-plus/icons-vue';import { applyCardRefund,cancelCardOrder,getCardOrder,getCardOrders,getMemberCardConfig,memberCardRequestId,retryCardOrderFinance } from '../../api';import MemberCardStatusTag from '../../components/MemberCardStatusTag.vue';import MemberCardIssueDialog from '../../components/MemberCardIssueDialog.vue'
const query=reactive({keyword:'',finance_status:'',page:1,limit:15}),rows=ref<any[]>([]),total=ref(0),loading=ref(false),issueVisible=ref(false),detailVisible=ref(false),detailLoading=ref(false),detail=ref<any>(null),refundVisible=ref(false),actionLoading=ref(false),accounts=ref<any[]>([]),refund=reactive<any>({refund_mode:'finance',capital_account_id:undefined,reason:''});
const money=(v:any)=>Number(v||0).toFixed(2),time=(v:any)=>v?new Date(Number(v)*1000).toLocaleString('zh-CN',{hour12:false}):'—',mask=(v:string)=>/^\d{11}$/.test(v||'')?`${v.slice(0,3)}****${v.slice(-4)}`:(v||'—'); const canCancel=computed(()=>detail.value&&Number(detail.value.paid_amount||0)<=0&&!["cancelled","refunded"].includes(detail.value.business_status));const canRefund=computed(()=>detail.value?.finance_status==='settled'&&detail.value?.business_status==='active');const actionText=(v:string)=>({create:'创建开卡单',activate:'开卡生效',cancel:'取消开卡',refund_apply:'申请退款'}[v]||v);
const load=async()=>{loading.value=true;try{const d:any=(await getCardOrders(query)).data||{};rows.value=d.data||[];total.value=d.total||0}finally{loading.value=false}};const reload=()=>{query.page=1;load()};const reset=()=>{query.keyword='';query.finance_status='';reload()};const openDetail=async(row:any)=>{detailVisible.value=true;detailLoading.value=true;try{detail.value=(await getCardOrder(row.id) as any).data||null}finally{detailLoading.value=false}};
const retryFinance=async()=>{await ElMessageBox.confirm('系统会按原订单重新创建或确认 ERP 财务事实，确认继续？','重试财务处理',{type:'warning'});await retryCardOrderFinance(detail.value.id);ElMessage.success('已重试');await openDetail(detail.value);load()};const cancelOrder=async()=>{const {value}=await ElMessageBox.prompt('请填写取消原因，原单和操作记录会保留。','取消开卡',{inputValidator:v=>!!String(v||'').trim()||'必须填写原因',type:'warning'});await cancelCardOrder(detail.value.id,value);ElMessage.success('开卡已取消');await openDetail(detail.value);load()};const submitRefund=async()=>{if(!refund.reason.trim())return ElMessage.warning('请填写退款原因');if(refund.refund_mode==='immediate'&&!refund.capital_account_id)return ElMessage.warning('请选择实际出款账户');actionLoading.value=true;try{await ElMessageBox.confirm('退款属于资金敏感操作，确认客户未消费且退款信息正确？','确认整卡退款',{type:'warning'});await applyCardRefund(detail.value.id,{...refund,request_id:memberCardRequestId('refund'),voucher_urls:[]});ElMessage.success(refund.refund_mode==='finance'?'已生成 ERP 应付':'现场退款已登记');refundVisible.value=false;await openDetail(detail.value);load()}finally{actionLoading.value=false}};
onMounted(async()=>{load();const c:any=(await getMemberCardConfig()).data||{};accounts.value=c.capital_account_options||[];refund.capital_account_id=c.default_capital_account_id||undefined})
</script>
<style scoped>.page-head,.toolbar,.detail-hero,.drawer-actions{display:flex;align-items:center;justify-content:space-between;gap:12px}.page-head{align-items:flex-start;margin-bottom:12px}.page-head p{margin:6px 0 0;color:var(--el-text-color-secondary)}.toolbar{justify-content:flex-start;margin:4px 0 14px;padding:14px 16px;border-radius:4px;background:var(--el-fill-color-lighter)}.toolbar .el-input{width:340px}.mobile{margin-left:10px;color:var(--el-text-color-secondary)}.sub{margin-top:5px;color:var(--el-text-color-secondary);font-size:12px}.pagination{display:flex;justify-content:flex-end;margin-top:16px}.detail-hero{padding:18px;border-radius:4px;background:var(--el-fill-color-light)}.detail-hero span,.info-grid span{color:var(--el-text-color-secondary);font-size:12px}.detail-hero h3{margin:6px 0}.detail-hero h3 small{font-weight:400;color:var(--el-text-color-secondary)}.detail-hero p{margin:0;color:var(--el-text-color-secondary)}.hero-amount{text-align:right}.hero-amount>*{display:block;margin:4px 0}.hero-amount strong{font-size:24px}.info-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:1px;margin:16px 0;background:var(--el-border-color-lighter);border:1px solid var(--el-border-color-lighter)}.info-grid div{display:flex;min-height:62px;padding:12px;background:var(--el-bg-color);flex-direction:column;gap:8px}h4{margin:22px 0 10px}.drawer-actions{justify-content:flex-end;margin-top:20px;padding-top:16px;border-top:1px solid var(--el-border-color-lighter)}.dialog-form{margin-top:18px}.w-full{width:100%}</style>
