<?php
return [
    [
        'menu_name' => '家政系统',
        'menu_key' => 'home_service',
        'menu_short_name' => '家政',
        'parent_select_key' => '',
        'parent_key' => '',
        'menu_type' => '0',
        'icon' => 'iconfont iconshangmenfuwu',
        'api_url' => '',
        'router_path' => '',
        'view_path' => '',
        'methods' => '',
        'sort' => '100',
        'status' => '1',
        'is_show' => '1',
        'children' => [
            [
                'menu_name' => '数据预览',
                'menu_key' => 'home_service_index',
                'menu_short_name' => '统计',
                'parent_select_key' => '',
                'menu_type' => '0',
                'icon' => 'iconfont icongaikuang1',
                'api_url' => '',
                'router_path' => '',
                'view_path' => '',
                'methods' => '',
                'sort' => '100',
                'status' => '1',
                'is_show' => '1',
                'children' => [
                    [
                        'menu_name' => '数据预览',
                        'menu_key' => 'home_service_report',
                        'menu_short_name' => '数据预览',
                        'parent_select_key' => '',
                        'menu_type' => '1',
                        'icon' => 'iconfont iconxiangmuguanli',
                        'api_url' => '',
                        'router_path' => 'home_service/index',
                        'view_path' => 'index',
                        'methods' => 'get',
                        'sort' => '100',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                    [
                        'menu_name' => '师傅报表',
                        'menu_key' => 'home_service_technician_report',
                        'menu_short_name' => '师傅报表',
                        'parent_select_key' => '',
                        'menu_type' => '1',
                        'icon' => 'iconfont iconxiangmuguanli',
                        'api_url' => '',
                        'router_path' => 'home_service/report/technician_report',
                        'view_path' => 'report/technician_report',
                        'methods' => 'get',
                        'sort' => '99',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                    [
                        'menu_name' => '机构报表',
                        'menu_key' => 'home_service_store_report',
                        'menu_short_name' => '机构报表',
                        'parent_select_key' => '',
                        'menu_type' => '1',
                        'icon' => 'iconfont iconxiangmuguanli',
                        'api_url' => '',
                        'router_path' => 'home_service/report/store_report',
                        'view_path' => 'report/store_report',
                        'methods' => 'get',
                        'sort' => '98',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                    [
                        'menu_name' => '财务报表',
                        'menu_key' => 'home_service_financial_report',
                        'menu_short_name' => '财务报表',
                        'parent_select_key' => '',
                        'menu_type' => '1',
                        'icon' => 'iconfont iconxiangmuguanli',
                        'api_url' => '',
                        'router_path' => 'home_service/report/financial_report',
                        'view_path' => 'report/financial_report',
                        'methods' => 'get',
                        'sort' => '97',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                    [
                        'menu_name' => '客户报表',
                        'menu_key' => 'home_service_customer_report',
                        'menu_short_name' => '客户报表',
                        'parent_select_key' => '',
                        'menu_type' => '1',
                        'icon' => 'iconfont iconxiangmuguanli',
                        'api_url' => '',
                        'router_path' => 'home_service/report/customer_report',
                        'view_path' => 'report/customer_report',
                        'methods' => 'get',
                        'sort' => '96',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                ],
            ],
            [
                'menu_name' => '服务项目',
                'menu_key' => 'home_service_goods',
                'menu_short_name' => '项目',
                'parent_select_key' => '',
                'menu_type' => '0',
                'icon' => 'iconfont iconkaxiangchanpin',
                'api_url' => '',
                'router_path' => '',
                'view_path' => '',
                'methods' => '',
                'sort' => '95',
                'status' => '1',
                'is_show' => '1',
                'children' => [
                    [
                        'menu_name' => '服务管理',
                        'menu_key' => 'home_service_goods_service',
                        'menu_short_name' => '服务管理',
                        'parent_select_key' => '',
                        'menu_type' => '1',
                        'icon' => 'iconfont iconxiangmuguanli',
                        'api_url' => '',
                        'router_path' => 'home_service/goods/list',
                        'view_path' => 'goods/list',
                        'methods' => 'get',
                        'sort' => '100',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                    [
                        'menu_name' => '次卡套餐',
                        'menu_key' => 'once_card_list',
                        'menu_short_name' => '次卡套餐',
                        'parent_select_key' => '',
                        'menu_type' => '1',
                        'icon' => 'iconfont iconxiangmuguanli',
                        'api_url' => '',
                        'router_path' => 'home_service/card/list',
                        'view_path' => 'card/list',
                        'methods' => 'get',
                        'sort' => '100',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                    [
                        'menu_name' => '编辑套餐',
                        'menu_key' => 'once_card_edit',
                        'menu_short_name' => '编辑套餐',
                        'parent_select_key' => '',
                        'menu_type' => '1',
                        'icon' => 'iconfont iconxiangmuguanli',
                        'api_url' => '',
                        'router_path' => 'home_service/card/edit',
                        'view_path' => 'card/edit',
                        'methods' => 'get',
                        'sort' => '100',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '删除服务',
                        'menu_key' => 'home_service_service_delete',
                        'menu_short_name' => '删除服务',
                        'parent_select_key' => '',
                        'menu_type' => '1',
                        'icon' => 'element House',
                        'api_url' => 'home_service/goods/<id>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'delete',
                        'sort' => '99',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '添加/编辑服务',
                        'menu_key' => 'home_service_service_add',
                        'menu_short_name' => '添加/编辑服务',
                        'parent_select_key' => '',
                        'menu_type' => '1',
                        'icon' => 'element House',
                        'api_url' => '',
                        'router_path' => 'home_service/goods/edit',
                        'view_path' => 'goods/edit',
                        'methods' => 'get',
                        'sort' => '99',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '服务详情',
                        'menu_key' => 'home_service_service_record_detail',
                        'menu_short_name' => '服务详情',
                        'parent_select_key' => '',
                        'menu_type' => '1',
                        'icon' => 'element House',
                        'api_url' => '',
                        'router_path' => 'home_service/goods/record_info',
                        'view_path' => 'goods/record_info',
                        'methods' => 'get',
                        'sort' => '99',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '服务分类',
                        'menu_key' => 'home_service_goods_category',
                        'menu_short_name' => '服务分类',
                        'parent_select_key' => '',
                        'menu_type' => '1',
                        'icon' => 'iconfont iconxiangmufenlei',
                        'api_url' => '',
                        'router_path' => 'home_service/goods/category',
                        'view_path' => 'goods/category',
                        'methods' => 'get',
                        'sort' => '99',
                        'status' => '1',
                        'is_show' => '1',
                        'children' => [
                            [
                                'menu_name' => '添加/编辑分类',
                                'menu_key' => 'home_service_goods_category_edit',
                                'menu_short_name' => '添加/编辑分类',
                                'parent_select_key' => '',
                                'menu_type' => '2',
                                'icon' => 'element House',
                                'api_url' => '',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'get',
                                'sort' => '99',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                            [
                                'menu_name' => '删除分类',
                                'menu_key' => 'home_service_goods_category_delete',
                                'menu_short_name' => '删除分类',
                                'parent_select_key' => '',
                                'menu_type' => '2',
                                'icon' => 'element House',
                                'api_url' => 'home_service/category/<id>',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'delete',
                                'sort' => '99',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                        ],
                    ],
                    [
                        'menu_name' => '服务保障',
                        'menu_key' => 'home_service_service_guarantee',
                        'menu_short_name' => '服务保障',
                        'parent_select_key' => '',
                        'menu_type' => '1',
                        'icon' => 'element House',
                        'api_url' => '',
                        'router_path' => 'home_service/goods/guarantee',
                        'view_path' => 'goods/guarantee',
                        'methods' => 'get',
                        'sort' => '99',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                    [
                        'menu_name' => '城市管理',
                        'menu_key' => 'home_service_service_city',
                        'menu_short_name' => '城市管理',
                        'parent_select_key' => '',
                        'menu_type' => '1',
                        'icon' => 'element House',
                        'api_url' => '',
                        'router_path' => 'home_service/goods/city',
                        'view_path' => 'goods/city',
                        'methods' => 'get',
                        'sort' => '98',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                ],
            ],
            [
                'menu_name' => '服务订单',
                'menu_key' => 'home_service_order',
                'menu_short_name' => '订单',
                'parent_select_key' => '',
                'menu_type' => '0',
                'icon' => 'iconfont iconkaxiangdingdan',
                'api_url' => '',
                'router_path' => '',
                'view_path' => '',
                'methods' => '',
                'sort' => '90',
                'status' => '1',
                'is_show' => '1',
                'children' => [
                    [
                        'menu_name' => '订单列表',
                        'menu_key' => 'home_service_order_list',
                        'menu_short_name' => '订单列表',
                        'parent_select_key' => '',
                        'menu_type' => '1',
                        'icon' => 'iconfont icona-dingdanliebiao',
                        'api_url' => '',
                        'router_path' => 'home_service/order/list',
                        'view_path' => 'order/order',
                        'methods' => 'get',
                        'sort' => '99',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                    [
                        'menu_name' => '退款详情',
                        'menu_key' => 'home_service_refund_detail',
                        'menu_short_name' => '退款详情',
                        'parent_select_key' => '',
                        'menu_type' => '1',
                        'icon' => 'element House',
                        'api_url' => '',
                        'router_path' => 'home_service/order/refund/detail',
                        'view_path' => 'refund/detail',
                        'methods' => 'get',
                        'sort' => '99',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '订单详情',
                        'menu_key' => 'home_service_order_info',
                        'menu_short_name' => '订单详情',
                        'parent_select_key' => '',
                        'menu_type' => '1',
                        'icon' => '',
                        'api_url' => '',
                        'router_path' => 'home_service/order/detail',
                        'view_path' => 'order/order_detail',
                        'methods' => 'get',
                        'sort' => '98',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '退款/售后',
                        'menu_key' => 'home_service_refuned_list',
                        'menu_short_name' => '退款/售后',
                        'parent_select_key' => '',
                        'menu_type' => '1',
                        'icon' => 'iconfont icona-dingdanliebiao',
                        'api_url' => '',
                        'router_path' => 'home_service/order/refuned',
                        'view_path' => 'refund/refund',
                        'methods' => 'get',
                        'sort' => '90',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                    [
                        'menu_name' => '评价列表',
                        'menu_key' => 'home_service_evaluate_list',
                        'menu_short_name' => '评价列表',
                        'parent_select_key' => '',
                        'menu_type' => '1',
                        'icon' => 'iconfont iconjiaoyishezhi',
                        'api_url' => 'order/evaluate',
                        'router_path' => 'home_service/order/evaluate',
                        'view_path' => 'order/evaluate',
                        'methods' => '',
                        'sort' => '90',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                    [
                        'menu_name' => '订单回访',
                        'menu_key' => 'home_service_return_visit_list',
                        'menu_short_name' => '订单回访',
                        'parent_select_key' => '',
                        'menu_type' => '1',
                        'icon' => 'iconfont icona-dingdanliebiao',
                        'api_url' => '',
                        'router_path' => 'home_service/order/return_visit',
                        'view_path' => 'order/return_visit',
                        'methods' => 'get',
                        'sort' => '89',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                    [
                        'menu_name' => '标签管理',
                        'menu_key' => 'home_service_tags_list',
                        'menu_short_name' => '标签管理',
                        'parent_select_key' => '',
                        'menu_type' => '1',
                        'icon' => 'iconfont icona-dingdanliebiao',
                        'api_url' => '',
                        'router_path' => 'home_service/order/tags',
                        'view_path' => 'order/tags',
                        'methods' => 'get',
                        'sort' => '87',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                    [
                        'menu_name' => '订单设置',
                        'menu_key' => 'home_service_config_order',
                        'menu_short_name' => '订单设置',
                        'parent_select_key' => '',
                        'menu_type' => '1',
                        'icon' => 'iconfont iconjiaoyishezhi',
                        'api_url' => 'order/config',
                        'router_path' => 'home_service/order/order/config',
                        'view_path' => 'order/config',
                        'methods' => '',
                        'sort' => '86',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                    [
                        'menu_name' => '维权设置',
                        'menu_key' => 'home_service_protectionSettings_order',
                        'menu_short_name' => '维权设置',
                        'parent_select_key' => '',
                        'menu_type' => '1',
                        'icon' => 'iconfont iconjiaoyishezhi',
                        'api_url' => 'order/config',
                        'router_path' => 'home_service/order/protection_settings',
                        'view_path' => 'order/protection_settings',
                        'methods' => '',
                        'sort' => '85',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                    [
                        'menu_name' => '评价设置',
                        'menu_key' => 'home_service_evaluate_config',
                        'menu_short_name' => '评价设置',
                        'parent_select_key' => '',
                        'menu_type' => '1',
                        'icon' => 'iconfont iconjiaoyishezhi',
                        'api_url' => 'order/config',
                        'router_path' => 'home_service/order/evaluate_config',
                        'view_path' => 'order/evaluate_config',
                        'methods' => '',
                        'sort' => '85',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                    [
                        'menu_name' => '代客下单',
                        'menu_key' => 'home_service_lesson_order',
                        'menu_short_name' => '代客下单',
                        'parent_select_key' => '',
                        'menu_type' => '1',
                        'icon' => 'iconfont iconjiaoyishezhi',
                        'api_url' => 'order/lesson_order',
                        'router_path' => 'home_service/order/lesson_order',
                        'view_path' => 'order/lesson_order',
                        'methods' => '',
                        'sort' => '85',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                    [
                        'menu_name' => '确认订单',
                        'menu_key' => 'home_service_lesson_order_confirm',
                        'menu_short_name' => '确认订单',
                        'parent_select_key' => '',
                        'menu_type' => '1',
                        'icon' => 'iconfont iconjiaoyishezhi',
                        'api_url' => 'order/lesson_order_confirm',
                        'router_path' => 'home_service/order/lesson_order_confirm',
                        'view_path' => 'order/lesson_order_confirm',
                        'methods' => '',
                        'sort' => '85',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                ],
            ],
            [
                'menu_name' => '服务人员',
                'menu_key' => 'home_service_technician',
                'menu_short_name' => '人员',
                'parent_select_key' => '',
                'menu_type' => '0',
                'icon' => 'iconfont iconhuiyuanliebiao1',
                'api_url' => '',
                'router_path' => '',
                'view_path' => '',
                'methods' => '',
                'sort' => '85',
                'status' => '1',
                'is_show' => '1',
                'children' => [
                    [
                        'menu_name' => '删除人员',
                        'menu_key' => 'home_service_technician_delete',
                        'menu_short_name' => '删除人员',
                        'parent_select_key' => '',
                        'menu_type' => '1',
                        'icon' => 'element House',
                        'api_url' => 'home_service/technician/<id>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'delete',
                        'sort' => '99',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '人员列表',
                        'menu_key' => 'home_service_technician_list',
                        'menu_short_name' => '人员列表',
                        'parent_select_key' => '',
                        'menu_type' => '1',
                        'icon' => 'iconfont iconjishiguanli',
                        'api_url' => '',
                        'router_path' => 'home_service/technician/list',
                        'view_path' => 'technician/list',
                        'methods' => 'get',
                        'sort' => '98',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                    [
                        'menu_name' => '人员等级',
                        'menu_key' => 'home_service_technician_level_list',
                        'menu_short_name' => '人员等级',
                        'parent_select_key' => '',
                        'menu_type' => '1',
                        'icon' => 'iconfont iconjishiguanli',
                        'api_url' => '',
                        'router_path' => 'home_service/technician/level',
                        'view_path' => 'technician/level',
                        'methods' => 'get',
                        'sort' => '98',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                    [
                        'menu_name' => '编辑等级',
                        'menu_key' => 'home_service_technician_level_edit',
                        'menu_short_name' => '编辑等级',
                        'parent_select_key' => '',
                        'menu_type' => '1',
                        'icon' => 'iconfont iconjishiguanli',
                        'api_url' => '',
                        'router_path' => 'home_service/technician/level_edit',
                        'view_path' => 'technician/level_edit',
                        'methods' => 'get',
                        'sort' => '98',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '人员审核',
                        'menu_key' => 'home_service_goods_examine',
                        'menu_short_name' => '人员审核',
                        'parent_select_key' => '',
                        'menu_type' => '1',
                        'icon' => 'iconfont iconxiangmuguanli',
                        'api_url' => '',
                        'router_path' => 'home_service/technician/examine',
                        'view_path' => 'technician/examine',
                        'methods' => 'get',
                        'sort' => '97',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                    [
                        'menu_name' => '审核详情',
                        'menu_key' => 'home_service_goods_examine_edit',
                        'menu_short_name' => '审核详情',
                        'parent_select_key' => '',
                        'menu_type' => '1',
                        'icon' => 'iconfont iconxiangmuguanli',
                        'api_url' => '',
                        'router_path' => 'home_service/technician/examine_edit',
                        'view_path' => 'technician/examine_edit',
                        'methods' => 'get',
                        'sort' => '97',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '人员详情',
                        'menu_key' => 'home_service_technician_info',
                        'menu_short_name' => '人员详情',
                        'parent_select_key' => '',
                        'menu_type' => '1',
                        'icon' => '',
                        'api_url' => '',
                        'router_path' => 'home_service/technician/detail',
                        'view_path' => 'technician/detail',
                        'methods' => 'get',
                        'sort' => '50',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '添加/编辑人员',
                        'menu_key' => 'home_service_technician_edit',
                        'menu_short_name' => '添加/编辑人员',
                        'parent_select_key' => '',
                        'menu_type' => '1',
                        'icon' => '',
                        'api_url' => '',
                        'router_path' => 'home_service/technician/edit',
                        'view_path' => 'technician/edit',
                        'methods' => 'get',
                        'sort' => '50',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                ],
            ],
            [
                'menu_name' => '服务机构',
                'menu_key' => 'home_service_store',
                'menu_short_name' => '机构',
                'parent_select_key' => '',
                'menu_type' => '0',
                'icon' => 'iconfont iconhuiyuanliebiao1',
                'api_url' => '',
                'router_path' => '',
                'view_path' => '',
                'methods' => '',
                'sort' => '84',
                'status' => '1',
                'is_show' => '1',
                'children' => [
                    [
                        'menu_name' => '机构列表',
                        'menu_key' => 'home_service_store_list',
                        'menu_short_name' => '机构列表',
                        'parent_select_key' => '',
                        'menu_type' => '1',
                        'icon' => 'iconfont iconjishiguanli',
                        'api_url' => '',
                        'router_path' => 'home_service/store/list',
                        'view_path' => 'store/list',
                        'methods' => 'get',
                        'sort' => '98',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                    [
                        'menu_name' => '机构详情',
                        'menu_key' => 'home_service_store_detail',
                        'menu_short_name' => '机构详情',
                        'parent_select_key' => '',
                        'menu_type' => '1',
                        'icon' => 'iconfont iconjishiguanli',
                        'api_url' => '',
                        'router_path' => 'home_service/store/detail',
                        'view_path' => 'store/detail',
                        'methods' => 'get',
                        'sort' => '98',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '添加机构',
                        'menu_key' => 'home_service_store_add',
                        'menu_short_name' => '添加机构',
                        'parent_select_key' => '',
                        'menu_type' => '1',
                        'icon' => 'iconfont iconjishiguanli',
                        'api_url' => '',
                        'router_path' => 'home_service/store/add',
                        'view_path' => 'store/add',
                        'methods' => 'get',
                        'sort' => '98',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '编辑机构',
                        'menu_key' => 'home_service_store_edit',
                        'menu_short_name' => '编辑机构',
                        'parent_select_key' => '',
                        'menu_type' => '1',
                        'icon' => 'iconfont iconjishiguanli',
                        'api_url' => '',
                        'router_path' => 'home_service/store/edit',
                        'view_path' => 'store/edit',
                        'methods' => 'get',
                        'sort' => '98',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '机构管理',
                        'menu_key' => 'home_service_store_technician',
                        'menu_short_name' => '机构管理',
                        'parent_select_key' => '',
                        'menu_type' => '1',
                        'icon' => 'iconfont iconjishiguanli',
                        'api_url' => '',
                        'router_path' => 'home_service/store/technician',
                        'view_path' => 'store/technician',
                        'methods' => 'get',
                        'sort' => '98',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '机构审核',
                        'menu_key' => 'home_service_store_examine',
                        'menu_short_name' => '机构审核',
                        'parent_select_key' => '',
                        'menu_type' => '1',
                        'icon' => 'iconfont iconjishiguanli',
                        'api_url' => '',
                        'router_path' => 'home_service/store/examine',
                        'view_path' => 'store/examine',
                        'methods' => 'get',
                        'sort' => '98',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                    [
                        'menu_name' => '审核详情',
                        'menu_key' => 'home_service_store_examine_edit',
                        'menu_short_name' => '审核详情',
                        'parent_select_key' => '',
                        'menu_type' => '1',
                        'icon' => 'iconfont iconjishiguanli',
                        'api_url' => '',
                        'router_path' => 'home_service/store/examine_edit',
                        'view_path' => 'store/examine_edit',
                        'methods' => 'get',
                        'sort' => '98',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                ],
            ],
            [
                'menu_name' => '营销活动',
                'menu_key' => 'home_service_marketing',
                'menu_short_name' => '营销',
                'parent_select_key' => '',
                'menu_type' => '0',
                'icon' => 'iconfont iconkaxiangdingdan',
                'api_url' => '',
                'router_path' => '',
                'view_path' => '',
                'methods' => '',
                'sort' => '83',
                'status' => '1',
                'is_show' => '1',
                'children' => [
                    [
                        'menu_name' => '优惠券列表',
                        'menu_key' => 'home_service_goods_coupon_list',
                        'menu_short_name' => '优惠券',
                        'parent_select_key' => '',
                        'menu_type' => '1',
                        'icon' => 'iconfont iconyouhuiquan',
                        'api_url' => '',
                        'router_path' => 'home_service/marketing/coupon/list',
                        'view_path' => 'marketing/coupon/list',
                        'methods' => 'get',
                        'sort' => '90',
                        'status' => '1',
                        'is_show' => '1',
                        'children' => [
                            [
                                'menu_name' => '优惠券删除',
                                'menu_key' => 'home_service_goods_coupon_delete',
                                'menu_short_name' => '优惠券删除',
                                'parent_select_key' => '',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'home_service/goods/coupon/delete',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'post',
                                'sort' => '0',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                            [
                                'menu_name' => '优惠券设置状态',
                                'menu_key' => 'home_service_goods_coupon_set_status',
                                'menu_short_name' => '优惠券设置状态',
                                'parent_select_key' => '',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'home_service/goods/coupon/setstatus/<status>',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'put',
                                'sort' => '0',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                            [
                                'menu_name' => '发券记录',
                                'menu_key' => 'home_service_goods_coupon_send_list',
                                'menu_short_name' => '发券记录',
                                'parent_select_key' => '',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'home_service/goods/coupon/send/pages/<coupon_id>',
                                'router_path' => 'home_service/marketing/coupon/send_list',
                                'view_path' => 'marketing/coupon/send_list',
                                'methods' => 'get',
                                'sort' => '0',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                            [
                                'menu_name' => '发券',
                                'menu_key' => 'home_service_goods_coupon_send',
                                'menu_short_name' => '发券',
                                'parent_select_key' => '',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'home_service/goods/coupon/send/<coupon_id>',
                                'router_path' => 'home_service/marketing/coupon/send',
                                'view_path' => 'marketing/coupon/send',
                                'methods' => 'post',
                                'sort' => '0',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                        ],
                    ],
                    [
                        'menu_name' => '优惠券添加',
                        'menu_key' => 'home_service_goods_coupon_add',
                        'menu_short_name' => '优惠券添加',
                        'parent_select_key' => 'home_service_goods_coupon_list',
                        'menu_type' => '1',
                        'icon' => '',
                        'api_url' => 'home_service/goods/coupon',
                        'router_path' => 'home_service/marketing/coupon/add',
                        'view_path' => 'marketing/coupon/add',
                        'methods' => 'post',
                        'sort' => '0',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '优惠券编辑',
                        'menu_key' => 'home_service_goods_coupon_edit',
                        'menu_short_name' => '优惠券编辑',
                        'parent_select_key' => 'home_service_goods_coupon_list',
                        'menu_type' => '1',
                        'icon' => '',
                        'api_url' => 'home_service/goods/coupon/edit/<id>',
                        'router_path' => 'home_service/marketing/coupon/edit',
                        'view_path' => 'marketing/coupon/edit',
                        'methods' => 'put',
                        'sort' => '0',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '优惠券领取记录',
                        'menu_key' => 'home_service_goods_coupon_collection',
                        'menu_short_name' => '优惠券领取记录',
                        'parent_select_key' => 'home_service_goods_coupon_list',
                        'menu_type' => '1',
                        'icon' => '',
                        'api_url' => 'home_service/goods/coupon/records',
                        'router_path' => 'home_service/marketing/coupon/collection',
                        'view_path' => 'marketing/coupon/collection',
                        'methods' => 'get',
                        'sort' => '0',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                ],
            ],
            [
                'menu_name' => '帮助反馈',
                'menu_key' => 'home_service_help',
                'menu_short_name' => '帮助',
                'parent_select_key' => '',
                'menu_type' => '0',
                'icon' => 'iconfont iconwenzhangguanli1',
                'api_url' => '',
                'router_path' => 'home_service/help/list',
                'view_path' => '',
                'methods' => '',
                'sort' => '82',
                'status' => '1',
                'is_show' => '1',
                'children' => [
                    [
                        'menu_name' => '帮助列表',
                        'menu_key' => 'home_service_help_list',
                        'menu_short_name' => '帮助列表',
                        'parent_select_key' => '',
                        'menu_type' => '1',
                        'icon' => 'element ChatDotSquare',
                        'api_url' => 'home_service/help',
                        'router_path' => 'home_service/help/list',
                        'view_path' => 'help/list',
                        'methods' => 'get',
                        'sort' => '100',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                    [
                        'menu_name' => '帮助分类',
                        'menu_key' => 'home_service_help_category',
                        'menu_short_name' => '帮助分类',
                        'parent_select_key' => '',
                        'menu_type' => '1',
                        'icon' => 'element CollectionTag',
                        'api_url' => 'help/category',
                        'router_path' => 'home_service/help/category',
                        'view_path' => 'help/category',
                        'methods' => 'get',
                        'sort' => '99',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                    [
                        'menu_name' => '反馈列表',
                        'menu_key' => 'home_service_feedback',
                        'menu_short_name' => '反馈列表',
                        'parent_select_key' => '',
                        'menu_type' => '1',
                        'icon' => 'element ChatDotSquare',
                        'api_url' => 'home_service/feedback',
                        'router_path' => 'home_service/feedback/list',
                        'view_path' => 'feedback/list',
                        'methods' => 'get',
                        'sort' => '98',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                    [
                        'menu_name' => '帮助添加/编辑',
                        'menu_key' => 'home_service_help_edit',
                        'menu_short_name' => '帮助添加/编辑',
                        'parent_select_key' => '',
                        'menu_type' => '1',
                        'icon' => '',
                        'api_url' => 'home_service/help',
                        'router_path' => 'home_service/help/edit',
                        'view_path' => 'help/edit',
                        'methods' => 'post',
                        'sort' => '90',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                ],
            ],
            [
                'menu_name' => '财务数据',
                'menu_key' => 'home_service_finance',
                'menu_short_name' => '财务',
                'parent_select_key' => '',
                'menu_type' => '0',
                'icon' => 'iconfont iconcaiwu1',
                'api_url' => '',
                'router_path' => 'home_service/invoice/list',
                'view_path' => '',
                'methods' => '',
                'sort' => '81',
                'status' => '1',
                'is_show' => '1',
                'children' => [
                    [
                        'menu_name' => '发票管理',
                        'menu_key' => 'home_service_invoice',
                        'menu_short_name' => '发票管理',
                        'parent_select_key' => '',
                        'menu_type' => '1',
                        'icon' => 'element ChatDotSquare',
                        'api_url' => 'home_service/invoice',
                        'router_path' => 'home_service/finance/invoice',
                        'view_path' => 'finance/invoice',
                        'methods' => 'get',
                        'sort' => '100',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                    [
                        'menu_name' => '技师结算详情',
                        'menu_key' => 'home_service_technician_detail',
                        'menu_short_name' => '技师结算详情',
                        'parent_select_key' => '',
                        'menu_type' => '1',
                        'icon' => 'element ChatDotSquare',
                        'api_url' => 'home_service/technician_detail',
                        'router_path' => 'home_service/finance/technician_detail',
                        'view_path' => 'finance/technician_detail',
                        'methods' => 'get',
                        'sort' => '100',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '门店结算详情',
                        'menu_key' => 'home_service_store_detail_finance',
                        'menu_short_name' => '门店结算详情',
                        'parent_select_key' => '',
                        'menu_type' => '1',
                        'icon' => 'element ChatDotSquare',
                        'api_url' => 'home_service/store_detail',
                        'router_path' => 'home_service/finance/store_detail',
                        'view_path' => 'finance/store_detail',
                        'methods' => 'get',
                        'sort' => '100',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '技师结算',
                        'menu_key' => 'home_service_technician_finance',
                        'menu_short_name' => '技师结算',
                        'parent_select_key' => '',
                        'menu_type' => '1',
                        'icon' => 'element ChatDotSquare',
                        'api_url' => 'home_service/technician_finance',
                        'router_path' => 'home_service/finance/technician_finance',
                        'view_path' => 'finance/technician_finance',
                        'methods' => 'get',
                        'sort' => '99',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                    [
                        'menu_name' => '门店结算',
                        'menu_key' => 'home_service_store_finance',
                        'menu_short_name' => '门店结算',
                        'parent_select_key' => '',
                        'menu_type' => '1',
                        'icon' => 'element ChatDotSquare',
                        'api_url' => 'home_service/store_finance',
                        'router_path' => 'home_service/finance/store_finance',
                        'view_path' => 'finance/store_finance',
                        'methods' => 'get',
                        'sort' => '98',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                    [
                        'menu_name' => '提现审核',
                        'menu_key' => 'home_service_withdrawal_review',
                        'menu_short_name' => '提现审核',
                        'parent_select_key' => '',
                        'menu_type' => '1',
                        'icon' => 'element ChatDotSquare',
                        'api_url' => 'home_service/withdrawal_review',
                        'router_path' => 'home_service/finance/withdrawal_review',
                        'view_path' => 'finance/withdrawal_review',
                        'methods' => 'get',
                        'sort' => '98',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                ],
            ],
        ],
    ],
];