<?php
return [
    [
        'menu_name' => '手机回收系统',
        'menu_key' => 'recycle',
        'menu_short_name' => '回收',
        'parent_select_key' => '',
        'parent_key' => '',
        'menu_type' => '0',
        'icon' => 'nc-iconfont nc-icon-youhuiV6xx1',
        'api_url' => '',
        'router_path' => '',
        'view_path' => '',
        'methods' => '',
        'sort' => '110',
        'status' => '1',
        'is_show' => '1',
        'children' => [
            [
                'menu_name' => '概况',
                'menu_key' => 'recycle_overview',
                'menu_short_name' => '概况',
                'parent_select_key' => '',
                'menu_type' => '1',
                'icon' => 'iconfont icongaikuang1',
                'api_url' => 'recycle/recycle_overview',
                'router_path' => 'recycle_overview',
                'view_path' => 'stats/dashboard',
                'methods' => 'get',
                'sort' => '90',
                'status' => '1',
                'is_show' => '1',
            ],
            [
                'menu_name' => '设备查询',
                'menu_key' => 'device_query',
                'menu_short_name' => '设备查询',
                'parent_select_key' => '',
                'menu_type' => '0',
                'icon' => 'nc-iconfont nc-icon-sousuo-duanV6xx1',
                'api_url' => '',
                'router_path' => '',
                'view_path' => '',
                'methods' => '',
                'sort' => '89',
                'status' => '1',
                'is_show' => '1',
                'children' => [
                    [
                        'menu_name' => '查询结果',
                        'menu_key' => 'device_query_result_list',
                        'menu_short_name' => '查询结果',
                        'parent_select_key' => '',
                        'menu_type' => '1',
                        'icon' => '',
                        'api_url' => 'recycle/device_query_result/lists',
                        'router_path' => 'device_query/result',
                        'view_path' => 'device_query/result',
                        'methods' => 'get',
                        'sort' => '3',
                        'status' => '1',
                        'is_show' => '1',
                        'children' => [
                            [
                                'menu_name' => '导出查询结果',
                                'menu_key' => 'device_query_result_export',
                                'menu_short_name' => '导出查询结果',
                                'parent_select_key' => '',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'recycle/device_query_result/export',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'post',
                                'sort' => '7',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                            [
                                'menu_name' => '重新查询',
                                'menu_key' => 'device_query_result_requery',
                                'menu_short_name' => '重新查询',
                                'parent_select_key' => '',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'recycle/device_query_result/requery/<id>',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'post',
                                'sort' => '6',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                            [
                                'menu_name' => '清理缓存',
                                'menu_key' => 'device_query_result_clean_cache',
                                'menu_short_name' => '清理缓存',
                                'parent_select_key' => '',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'recycle/device_query_result/clean_cache',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'post',
                                'sort' => '5',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                            [
                                'menu_name' => '查询统计',
                                'menu_key' => 'device_query_result_stats',
                                'menu_short_name' => '查询统计',
                                'parent_select_key' => '',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'recycle/device_query_result/stats',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'get',
                                'sort' => '4',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                            [
                                'menu_name' => '批量删除查询结果',
                                'menu_key' => 'device_query_result_batch_delete',
                                'menu_short_name' => '批量删除查询结果',
                                'parent_select_key' => '',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'recycle/device_query_result/batch_del',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'post',
                                'sort' => '3',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                            [
                                'menu_name' => '删除查询结果',
                                'menu_key' => 'device_query_result_delete',
                                'menu_short_name' => '删除查询结果',
                                'parent_select_key' => '',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'recycle/device_query_result/<id>',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'delete',
                                'sort' => '2',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                            [
                                'menu_name' => '查询结果详情',
                                'menu_key' => 'device_query_result_info',
                                'menu_short_name' => '查询结果详情',
                                'parent_select_key' => '',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'recycle/device_query_result/<id>',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'get',
                                'sort' => '1',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                        ],
                    ],
                    [
                        'menu_name' => 'API接口清单',
                        'menu_key' => 'device_query_api_list',
                        'menu_short_name' => 'API接口清单',
                        'parent_select_key' => '',
                        'menu_type' => '1',
                        'icon' => '',
                        'api_url' => 'recycle/device_query_api/lists',
                        'router_path' => 'device_query/api',
                        'view_path' => 'device_query/api',
                        'methods' => 'get',
                        'sort' => '2',
                        'status' => '1',
                        'is_show' => '1',
                        'children' => [
                            [
                                'menu_name' => '获取分类API列表',
                                'menu_key' => 'device_query_api_by_category',
                                'menu_short_name' => '获取分类API列表',
                                'parent_select_key' => '',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'recycle/device_query_api/by_category',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'get',
                                'sort' => '9',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                            [
                                'menu_name' => '根据端点获取API信息',
                                'menu_key' => 'device_query_api_by_endpoint',
                                'menu_short_name' => '根据端点获取API信息',
                                'parent_select_key' => '',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'recycle/device_query_api/by_endpoint',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'get',
                                'sort' => '8',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                            [
                                'menu_name' => '初始化默认API清单',
                                'menu_key' => 'device_query_api_init',
                                'menu_short_name' => '初始化默认API清单',
                                'parent_select_key' => '',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'recycle/device_query_api/init',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'post',
                                'sort' => '7',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                            [
                                'menu_name' => '获取默认API清单',
                                'menu_key' => 'device_query_api_default',
                                'menu_short_name' => '获取默认API清单',
                                'parent_select_key' => '',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'recycle/device_query_api/default',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'get',
                                'sort' => '6',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                            [
                                'menu_name' => '修改状态',
                                'menu_key' => 'device_query_api_status',
                                'menu_short_name' => '修改状态',
                                'parent_select_key' => '',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'recycle/device_query_api/status/<id>',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'put',
                                'sort' => '5',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                            [
                                'menu_name' => '接口清单详情',
                                'menu_key' => 'device_query_api_info',
                                'menu_short_name' => '接口清单详情',
                                'parent_select_key' => '',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'recycle/device_query_api/<id>',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'get',
                                'sort' => '4',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                            [
                                'menu_name' => '删除接口清单',
                                'menu_key' => 'device_query_api_delete',
                                'menu_short_name' => '删除接口清单',
                                'parent_select_key' => '',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'recycle/device_query_api/<id>',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'delete',
                                'sort' => '3',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                            [
                                'menu_name' => '编辑接口清单',
                                'menu_key' => 'device_query_api_edit',
                                'menu_short_name' => '编辑接口清单',
                                'parent_select_key' => '',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'recycle/device_query_api/<id>',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'put',
                                'sort' => '2',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                            [
                                'menu_name' => '添加接口清单',
                                'menu_key' => 'device_query_api_add',
                                'menu_short_name' => '添加接口清单',
                                'parent_select_key' => '',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'recycle/device_query_api',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'post',
                                'sort' => '1',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                        ],
                    ],
                    [
                        'menu_name' => '查询配置',
                        'menu_key' => 'device_query_config_list',
                        'menu_short_name' => '查询配置',
                        'parent_select_key' => '',
                        'menu_type' => '1',
                        'icon' => '',
                        'api_url' => 'recycle/device_query_config/lists',
                        'router_path' => 'device_query/config',
                        'view_path' => 'device_query/config',
                        'methods' => 'get',
                        'sort' => '1',
                        'status' => '1',
                        'is_show' => '1',
                        'children' => [
                            [
                                'menu_name' => '查询统计',
                                'menu_key' => 'device_query_config_stats',
                                'menu_short_name' => '查询统计',
                                'parent_select_key' => '',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'recycle/device_query_config/stats/<id>',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'get',
                                'sort' => '7',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                            [
                                'menu_name' => '测试连接',
                                'menu_key' => 'device_query_config_test',
                                'menu_short_name' => '测试连接',
                                'parent_select_key' => '',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'recycle/device_query_config/test/<id>',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'post',
                                'sort' => '6',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                            [
                                'menu_name' => '修改状态',
                                'menu_key' => 'device_query_config_status',
                                'menu_short_name' => '修改状态',
                                'parent_select_key' => '',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'recycle/device_query_config/status/<id>',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'put',
                                'sort' => '5',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                            [
                                'menu_name' => '配置详情',
                                'menu_key' => 'device_query_config_info',
                                'menu_short_name' => '配置详情',
                                'parent_select_key' => '',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'recycle/device_query_config/<id>',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'get',
                                'sort' => '4',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                            [
                                'menu_name' => '删除配置',
                                'menu_key' => 'device_query_config_delete',
                                'menu_short_name' => '删除配置',
                                'parent_select_key' => '',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'recycle/device_query_config/<id>',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'delete',
                                'sort' => '3',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                            [
                                'menu_name' => '编辑配置',
                                'menu_key' => 'device_query_config_edit',
                                'menu_short_name' => '编辑配置',
                                'parent_select_key' => '',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'recycle/device_query_config/<id>',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'put',
                                'sort' => '2',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                            [
                                'menu_name' => '添加配置',
                                'menu_key' => 'device_query_config_add',
                                'menu_short_name' => '添加配置',
                                'parent_select_key' => '',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'recycle/device_query_config',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'post',
                                'sort' => '1',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                        ],
                    ],
                ],
            ],
            [
                'menu_name' => '报价分类',
                'menu_key' => 'recycle_category_list',
                'menu_short_name' => '报价分类',
                'parent_select_key' => '',
                'menu_type' => '1',
                'icon' => 'nc-iconfont nc-icon-fenleiV6xx',
                'api_url' => 'recycle/recycle_category',
                'router_path' => 'recycle_category/recycle_category',
                'view_path' => 'recycle_category/recycle_category',
                'methods' => 'get',
                'sort' => '88',
                'status' => '1',
                'is_show' => '1',
            ],
            [
                'menu_name' => '分类列表等级获取',
                'menu_key' => 'recycle_category',
                'menu_short_name' => '分类列表等级获取',
                'parent_select_key' => '',
                'menu_type' => '2',
                'icon' => '',
                'api_url' => 'recycle/recycle_category',
                'router_path' => '',
                'view_path' => '',
                'methods' => 'get',
                'sort' => '88',
                'status' => '1',
                'is_show' => '1',
            ],
            [
                'menu_name' => '回收订单',
                'menu_key' => 'recycle_order',
                'menu_short_name' => '订单',
                'parent_select_key' => '',
                'menu_type' => '0',
                'icon' => 'nc-iconfont nc-icon-wendangV6xx',
                'api_url' => '',
                'router_path' => '',
                'view_path' => '',
                'methods' => '',
                'sort' => '87',
                'status' => '1',
                'is_show' => '1',
                'children' => [
                    [
                        'menu_name' => '订单列表',
                        'menu_key' => 'recycle_order_list',
                        'menu_short_name' => '订单列表',
                        'parent_select_key' => '',
                        'menu_type' => '1',
                        'icon' => '',
                        'api_url' => 'recycle/recycle_order/lists',
                        'router_path' => 'recycle_order/list',
                        'view_path' => 'recycle_order/list',
                        'methods' => 'get',
                        'sort' => '88',
                        'status' => '1',
                        'is_show' => '1',
                        'children' => [
                            [
                                'menu_name' => '删除订单',
                                'menu_key' => 'recycle_order_delete',
                                'menu_short_name' => '删除订单',
                                'parent_select_key' => '',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'recycle/recycle_order/<id>',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'delete',
                                'sort' => '3',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                            [
                                'menu_name' => '重新定价',
                                'menu_key' => 'recycle_device_re_confirm_price',
                                'menu_short_name' => '重新定价',
                                'parent_select_key' => '',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'recycle_device/<id>/confirm_price',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'put',
                                'sort' => '3',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                            [
                                'menu_name' => '编辑订单',
                                'menu_key' => 'recycle_order_edit',
                                'menu_short_name' => '编辑订单',
                                'parent_select_key' => '',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'recycle/recycle_order/<id>',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'put',
                                'sort' => '2',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                            [
                                'menu_name' => '添加订单',
                                'menu_key' => 'recycle_order_add',
                                'menu_short_name' => '添加订单',
                                'parent_select_key' => '',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'recycle/recycle_order/create',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'post',
                                'sort' => '1',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                            [
                                'menu_name' => '批量回收设备',
                                'menu_key' => 'recycle_device_batch_recycle',
                                'menu_short_name' => '批量回收设备',
                                'parent_select_key' => '',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'recycle/recycle_device/batch_recycle',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'post',
                                'sort' => '1',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                            [
                                'menu_name' => '订单详情',
                                'menu_key' => 'recycle_order_detail',
                                'menu_short_name' => '订单详情',
                                'parent_select_key' => '',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'recycle/recycle_order/detail/<id>',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'get',
                                'sort' => '1',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                            [
                                'menu_name' => '获取商户收款信息',
                                'menu_key' => 'recycle_order_merchant_pay_info',
                                'menu_short_name' => '获取商户收款信息',
                                'parent_select_key' => '',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'recycle/recycle_order/merchant_pay_info/<id>',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'get',
                                'sort' => '1',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                            [
                                'menu_name' => '打印设备标签',
                                'menu_key' => 'recycle_printer_device_label',
                                'menu_short_name' => '打印设备标签',
                                'parent_select_key' => '',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'recycle/printer/print_device_label/<id>',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'post',
                                'sort' => '1',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                            [
                                'menu_name' => '获取订单状态',
                                'menu_key' => 'recycle_order_status',
                                'menu_short_name' => '获取订单状态',
                                'parent_select_key' => '',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'recycle/recycle_order/status',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'get',
                                'sort' => '1',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                            [
                                'menu_name' => '设备定价',
                                'menu_key' => 'recycle_device_confirm_price',
                                'menu_short_name' => '设备定价',
                                'parent_select_key' => '',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'recycle/recycle_device/<id>/confirm_price',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'put',
                                'sort' => '1',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                            [
                                'menu_name' => '确认打款',
                                'menu_key' => 'recycle_order_payment_confirm',
                                'menu_short_name' => '确认打款',
                                'parent_select_key' => '',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'recycle/recycle_order/<id>/payment_confirm',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'put',
                                'sort' => '1',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                            [
                                'menu_name' => '获取设备信息',
                                'menu_key' => 'recycle_device_info',
                                'menu_short_name' => '获取设备信息',
                                'parent_select_key' => '',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'recycle/recycle_device/<id>',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'get',
                                'sort' => '1',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                            [
                                'menu_name' => '批量退回设备',
                                'menu_key' => 'recycle_device_batch_return',
                                'menu_short_name' => '批量退回设备',
                                'parent_select_key' => '',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'recycle/recycle_device/batch_return',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'post',
                                'sort' => '1',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                            [
                                'menu_name' => '更新设备信息',
                                'menu_key' => 'recycle_device_update',
                                'menu_short_name' => '更新设备信息',
                                'parent_select_key' => '',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'recycle/recycle_device/<id>',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'put',
                                'sort' => '1',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                        ],
                    ],
                    [
                        'menu_name' => '设备导出',
                        'menu_key' => 'recycle_device_export',
                        'menu_short_name' => '设备导出',
                        'parent_select_key' => '',
                        'menu_type' => '1',
                        'icon' => 'nc-iconfont nc-icon-fenxiangV6xx-1',
                        'api_url' => 'recycle/device_export/list',
                        'router_path' => 'device_export/list',
                        'view_path' => 'device_export/list',
                        'methods' => 'get',
                        'sort' => '86',
                        'status' => '1',
                        'is_show' => '1',
                        'children' => [
                            [
                                'menu_name' => '导出设备',
                                'menu_key' => 'recycle_device_export_action',
                                'menu_short_name' => '导出设备',
                                'parent_select_key' => '',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'recycle/device_export/export',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'post',
                                'sort' => '1',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                        ],
                    ],
                    [
                        'menu_name' => '商家地址',
                        'menu_key' => 'recycle_address',
                        'menu_short_name' => '商家地址',
                        'parent_select_key' => '',
                        'menu_type' => '1',
                        'icon' => '',
                        'api_url' => '',
                        'router_path' => 'recycle/address',
                        'view_path' => 'address/list',
                        'methods' => '',
                        'sort' => '0',
                        'status' => '1',
                        'is_show' => '1',
                        'children' => [
                            [
                                'menu_name' => '商家地址列表',
                                'menu_key' => 'recycle_address_list',
                                'menu_short_name' => '商家地址列表',
                                'parent_select_key' => '',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'recycle/shop_address',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'get',
                                'sort' => '0',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                            [
                                'menu_name' => '删除商家地址库',
                                'menu_key' => 'recycle_address_delete',
                                'menu_short_name' => '删除商家地址库',
                                'parent_select_key' => '',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'recycle/shop_address/<id>',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'delete',
                                'sort' => '0',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                            [
                                'menu_name' => '商家地址详情',
                                'menu_key' => 'recycle_address_info',
                                'menu_short_name' => '商家地址详情',
                                'parent_select_key' => '',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'recycle/shop_address/<id>',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'get',
                                'sort' => '0',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                        ],
                    ],
                    [
                        'menu_name' => '添加/编辑地址库',
                        'menu_key' => 'recycle_address_add_edit',
                        'menu_short_name' => '添加/编辑地址库',
                        'parent_select_key' => '',
                        'menu_type' => '1',
                        'icon' => '',
                        'api_url' => '',
                        'router_path' => 'recycle/address/edit',
                        'view_path' => 'address/edit',
                        'methods' => 'get',
                        'sort' => '0',
                        'status' => '1',
                        'is_show' => '0',
                        'children' => [
                            [
                                'menu_name' => '地址库添加',
                                'menu_key' => 'recycle_address_add',
                                'menu_short_name' => '地址库添加',
                                'parent_select_key' => '',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'recycle/shop_address',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'post',
                                'sort' => '0',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                            [
                                'menu_name' => '地址库编辑',
                                'menu_key' => 'recycle_address_edit',
                                'menu_short_name' => '地址库编辑',
                                'parent_select_key' => '',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'recycle/shop_address/<id>',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'put',
                                'sort' => '0',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                            [
                                'menu_name' => '获取默认发货地址',
                                'menu_key' => 'recycle_address_default_delivery',
                                'menu_short_name' => '获取默认发货地址',
                                'parent_select_key' => '',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'recycle/shop_address/default/delivery',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'get',
                                'sort' => '0',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                        ],
                    ],
                ],
            ],
            [
                'menu_name' => '退回订单',
                'menu_key' => 'recycle_return_order',
                'menu_short_name' => '退回订单',
                'parent_select_key' => '',
                'menu_type' => '0',
                'icon' => 'nc-iconfont nc-icon-daifahuoV6xx',
                'api_url' => '',
                'router_path' => '',
                'view_path' => '',
                'methods' => '',
                'sort' => '85',
                'status' => '1',
                'is_show' => '1',
                'children' => [
                    [
                        'menu_name' => '退回订单列表',
                        'menu_key' => 'recycle_return_order_list',
                        'menu_short_name' => '退回订单列表',
                        'parent_select_key' => '',
                        'menu_type' => '1',
                        'icon' => '',
                        'api_url' => 'recycle/recycle_return_order/lists',
                        'router_path' => 'recycle_return_order/list',
                        'view_path' => 'recycle_return_order/list',
                        'methods' => 'get',
                        'sort' => '1',
                        'status' => '1',
                        'is_show' => '1',
                        'children' => [
                            [
                                'menu_name' => '获取退回订单状态统计',
                                'menu_key' => 'recycle_return_order_status',
                                'menu_short_name' => '获取退回订单状态统计',
                                'parent_select_key' => '',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'recycle/recycle_return_order/status',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'get',
                                'sort' => '7',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                            [
                                'menu_name' => '删除退回订单',
                                'menu_key' => 'recycle_return_order_delete',
                                'menu_short_name' => '删除退回订单',
                                'parent_select_key' => '',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'recycle/recycle_return_order/<id>',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'delete',
                                'sort' => '6',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                            [
                                'menu_name' => '取消退回订单',
                                'menu_key' => 'recycle_return_order_cancel',
                                'menu_short_name' => '取消退回订单',
                                'parent_select_key' => '',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'recycle/recycle_return_order/<id>/cancel',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'put',
                                'sort' => '5',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                            [
                                'menu_name' => '更新退回订单状态',
                                'menu_key' => 'recycle_return_order_update_status',
                                'menu_short_name' => '更新退回订单状态',
                                'parent_select_key' => '',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'recycle/recycle_return_order/<id>',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'put',
                                'sort' => '4',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                            [
                                'menu_name' => '批量创建退回订单',
                                'menu_key' => 'recycle_return_order_batch_create',
                                'menu_short_name' => '批量创建退回订单',
                                'parent_select_key' => '',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'recycle/recycle_return_order/batch_create',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'post',
                                'sort' => '3',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                            [
                                'menu_name' => '创建退回订单',
                                'menu_key' => 'recycle_return_order_create',
                                'menu_short_name' => '创建退回订单',
                                'parent_select_key' => '',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'recycle/recycle_return_order',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'post',
                                'sort' => '2',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                            [
                                'menu_name' => '退回订单详情',
                                'menu_key' => 'recycle_return_order_detail',
                                'menu_short_name' => '退回订单详情',
                                'parent_select_key' => '',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'recycle/recycle_return_order/<id>',
                                'router_path' => 'recycle_return_order/detail/:id',
                                'view_path' => 'recycle_return_order/detail',
                                'methods' => 'get',
                                'sort' => '1',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                        ],
                    ],
                    [
                        'menu_name' => '用户退货地址',
                        'menu_key' => 'recycle_user_address',
                        'menu_short_name' => '用户退货地址',
                        'parent_select_key' => '',
                        'menu_type' => '1',
                        'icon' => '',
                        'api_url' => 'recycle/recycle_user_address',
                        'router_path' => 'recycle/recycle_user_address',
                        'view_path' => 'recycle_user_address/recycle_user_address',
                        'methods' => 'get',
                        'sort' => '1',
                        'status' => '1',
                        'is_show' => '1',
                    ],
                ],
            ],
            [
                'menu_name' => '打印机管理',
                'menu_key' => 'recycle_printer',
                'menu_short_name' => '打印机',
                'parent_select_key' => '',
                'menu_type' => '0',
                'icon' => 'nc-iconfont nc-icon-dakaixinxiV6xx',
                'api_url' => '',
                'router_path' => '',
                'view_path' => '',
                'methods' => '',
                'sort' => '80',
                'status' => '1',
                'is_show' => '1',
                'children' => [
                    [
                        'menu_name' => '模板列表',
                        'menu_key' => 'recycle_printer_template_list',
                        'menu_short_name' => '模板列表',
                        'parent_select_key' => '',
                        'menu_type' => '1',
                        'icon' => '',
                        'api_url' => 'recycle/printer_template/lists',
                        'router_path' => 'recycle/printer_template/list',
                        'view_path' => 'printer_template/list',
                        'methods' => 'get',
                        'sort' => '2',
                        'status' => '1',
                        'is_show' => '1',
                        'children' => [
                            [
                                'menu_name' => '获取默认模板',
                                'menu_key' => 'recycle_printer_template_get_default',
                                'menu_short_name' => '获取默认模板',
                                'parent_select_key' => '',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'recycle/printer_template/default',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'get',
                                'sort' => '10',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                            [
                                'menu_name' => '获取模板类型列表',
                                'menu_key' => 'recycle_printer_template_type_list',
                                'menu_short_name' => '获取模板类型列表',
                                'parent_select_key' => '',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'recycle/printer_template/type_list',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'get',
                                'sort' => '9',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                            [
                                'menu_name' => '测试打印模板',
                                'menu_key' => 'recycle_printer_template_test',
                                'menu_short_name' => '测试打印模板',
                                'parent_select_key' => '',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'recycle/printer_template/test_print/<id>',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'post',
                                'sort' => '8',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                            [
                                'menu_name' => '预览模板',
                                'menu_key' => 'recycle_printer_template_preview',
                                'menu_short_name' => '预览模板',
                                'parent_select_key' => '',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'recycle/printer_template/preview/<id>',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'get',
                                'sort' => '7',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                            [
                                'menu_name' => '设置默认模板',
                                'menu_key' => 'recycle_printer_template_default',
                                'menu_short_name' => '设置默认模板',
                                'parent_select_key' => '',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'recycle/printer_template/default/<id>',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'post',
                                'sort' => '6',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                            [
                                'menu_name' => '修改模板状态',
                                'menu_key' => 'recycle_printer_template_status',
                                'menu_short_name' => '修改模板状态',
                                'parent_select_key' => '',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'recycle/printer_template/status/<id>',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'post',
                                'sort' => '5',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                            [
                                'menu_name' => '删除模板',
                                'menu_key' => 'recycle_printer_template_delete',
                                'menu_short_name' => '删除模板',
                                'parent_select_key' => '',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'recycle/printer_template/<id>',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'delete',
                                'sort' => '4',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                            [
                                'menu_name' => '编辑模板',
                                'menu_key' => 'recycle_printer_template_edit',
                                'menu_short_name' => '编辑模板',
                                'parent_select_key' => '',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'recycle/printer_template/<id>',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'put',
                                'sort' => '3',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                            [
                                'menu_name' => '添加模板',
                                'menu_key' => 'recycle_printer_template_add',
                                'menu_short_name' => '添加模板',
                                'parent_select_key' => '',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'recycle/printer_template',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'post',
                                'sort' => '2',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                            [
                                'menu_name' => '模板详情',
                                'menu_key' => 'recycle_printer_template_info',
                                'menu_short_name' => '模板详情',
                                'parent_select_key' => '',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'recycle/printer_template/<id>',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'get',
                                'sort' => '1',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                        ],
                    ],
                    [
                        'menu_name' => '打印机列表',
                        'menu_key' => 'recycle_printer_list',
                        'menu_short_name' => '打印机列表',
                        'parent_select_key' => '',
                        'menu_type' => '1',
                        'icon' => '',
                        'api_url' => 'recycle/printer',
                        'router_path' => 'recycle/printer/list',
                        'view_path' => 'printer/list',
                        'methods' => 'get',
                        'sort' => '1',
                        'status' => '1',
                        'is_show' => '1',
                        'children' => [
                            [
                                'menu_name' => '设置打印机状态',
                                'menu_key' => 'recycle_printer_status',
                                'menu_short_name' => '设置打印机状态',
                                'parent_select_key' => '',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'recycle/printer/status/<printer_id>',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'post',
                                'sort' => '7',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                            [
                                'menu_name' => '测试打印机',
                                'menu_key' => 'recycle_printer_test',
                                'menu_short_name' => '测试打印机',
                                'parent_select_key' => '',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'recycle/printer/test/<printer_id>',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'post',
                                'sort' => '6',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                            [
                                'menu_name' => '获取打印机品牌列表',
                                'menu_key' => 'recycle_printer_brand_list',
                                'menu_short_name' => '获取打印机品牌列表',
                                'parent_select_key' => '',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'recycle/printer/brand_list',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'get',
                                'sort' => '5',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                            [
                                'menu_name' => '删除打印机',
                                'menu_key' => 'recycle_printer_delete',
                                'menu_short_name' => '删除打印机',
                                'parent_select_key' => '',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'recycle/printer/<printer_id>',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'delete',
                                'sort' => '4',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                            [
                                'menu_name' => '编辑打印机',
                                'menu_key' => 'recycle_printer_edit',
                                'menu_short_name' => '编辑打印机',
                                'parent_select_key' => '',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'recycle/printer/<printer_id>',
                                'router_path' => 'recycle/printer/edit/:printer_id',
                                'view_path' => 'printer/edit',
                                'methods' => 'put',
                                'sort' => '3',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                            [
                                'menu_name' => '添加打印机',
                                'menu_key' => 'recycle_printer_add',
                                'menu_short_name' => '添加打印机',
                                'parent_select_key' => '',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'recycle/printer',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'post',
                                'sort' => '2',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                            [
                                'menu_name' => '打印机详情',
                                'menu_key' => 'recycle_printer_info',
                                'menu_short_name' => '打印机详情',
                                'parent_select_key' => '',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'recycle/printer/<printer_id>',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'get',
                                'sort' => '1',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                        ],
                    ],
                    [
                        'menu_name' => '编辑打印机',
                        'menu_key' => 'recycle_printer_edit_page',
                        'menu_short_name' => '编辑打印机',
                        'parent_select_key' => '',
                        'menu_type' => '1',
                        'icon' => '',
                        'api_url' => '',
                        'router_path' => 'recycle/printer/edit/:printer_id',
                        'view_path' => 'printer/edit',
                        'methods' => '',
                        'sort' => '0',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '添加打印机',
                        'menu_key' => 'recycle_printer_add_page',
                        'menu_short_name' => '添加打印机',
                        'parent_select_key' => '',
                        'menu_type' => '1',
                        'icon' => '',
                        'api_url' => '',
                        'router_path' => 'recycle/printer/add',
                        'view_path' => 'printer/add',
                        'methods' => '',
                        'sort' => '0',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '添加模板',
                        'menu_key' => 'recycle_printer_template_add_page',
                        'menu_short_name' => '添加模板',
                        'parent_select_key' => '',
                        'menu_type' => '1',
                        'icon' => '',
                        'api_url' => '',
                        'router_path' => 'recycle/printer_template/add',
                        'view_path' => 'printer_template/editor',
                        'methods' => '',
                        'sort' => '0',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '编辑模板',
                        'menu_key' => 'recycle_printer_template_edit_page',
                        'menu_short_name' => '编辑模板',
                        'parent_select_key' => '',
                        'menu_type' => '1',
                        'icon' => '',
                        'api_url' => '',
                        'router_path' => 'recycle/printer_template/edit/:id',
                        'view_path' => 'printer_template/editor',
                        'methods' => '',
                        'sort' => '0',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                ],
            ],
            [
                'menu_name' => '二手机分类添加',
                'menu_key' => 'recycle_category_add',
                'menu_short_name' => '二手机分类添加',
                'parent_select_key' => '',
                'menu_type' => '2',
                'icon' => '',
                'api_url' => 'recycle/recycle_category',
                'router_path' => '',
                'view_path' => '',
                'methods' => 'post',
                'sort' => '70',
                'status' => '1',
                'is_show' => '0',
            ],
            [
                'menu_name' => '二手机分类编辑',
                'menu_key' => 'recycle_category_edit',
                'menu_short_name' => '二手机分类编辑',
                'parent_select_key' => '',
                'menu_type' => '2',
                'icon' => '',
                'api_url' => 'recycle/recycle_category/<id>',
                'router_path' => '',
                'view_path' => '',
                'methods' => 'put',
                'sort' => '60',
                'status' => '1',
                'is_show' => '0',
            ],
            [
                'menu_name' => '二手机分类删除',
                'menu_key' => 'recycle_category_delete',
                'menu_short_name' => '二手机分类删除',
                'parent_select_key' => '',
                'menu_type' => '2',
                'icon' => '',
                'api_url' => 'recycle/recycle_category/<id>',
                'router_path' => '',
                'view_path' => '',
                'methods' => 'delete',
                'sort' => '50',
                'status' => '1',
                'is_show' => '0',
            ],
        ],
    ],
];