CREATE TABLE IF NOT EXISTS `{{prefix}}recycle_quotation_v2_dataset` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `site_id` int unsigned NOT NULL DEFAULT 0,
  `quotation_id` int unsigned NOT NULL DEFAULT 0,
  `price_name` varchar(120) NOT NULL DEFAULT '',
  `dataset_name` varchar(120) NOT NULL DEFAULT '',
  `channel_key` varchar(50) NOT NULL DEFAULT 'chaoniu',
  `nav_image` varchar(500) NOT NULL DEFAULT '',
  `sort` int NOT NULL DEFAULT 0,
  `status` tinyint NOT NULL DEFAULT 1,
  `follow_crawler` tinyint NOT NULL DEFAULT 1,
  `sync_enabled` tinyint NOT NULL DEFAULT 0,
  `sync_interval` int NOT NULL DEFAULT 86400,
  `request_params` json DEFAULT NULL,
  `parse_rule` json DEFAULT NULL,
  `remark` varchar(500) NOT NULL DEFAULT '',
  `last_sync_at` int unsigned NOT NULL DEFAULT 0,
  `last_sync_status` tinyint NOT NULL DEFAULT 0,
  `last_sync_message` varchar(500) NOT NULL DEFAULT '',
  `last_sync_summary` json DEFAULT NULL,
  `create_at` int unsigned NOT NULL DEFAULT 0,
  `update_at` int unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_site_status_sort` (`site_id`,`status`,`sort`),
  KEY `idx_site_quotation` (`site_id`,`quotation_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='DH速收报价数据集';

CREATE TABLE IF NOT EXISTS `{{prefix}}recycle_quotation_v2_model` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `site_id` int unsigned NOT NULL DEFAULT 0,
  `dataset_id` int unsigned NOT NULL DEFAULT 0,
  `quotation_id` int unsigned NOT NULL DEFAULT 0,
  `price_name` varchar(120) NOT NULL DEFAULT '',
  `channel_key` varchar(50) NOT NULL DEFAULT 'chaoniu',
  `external_goods_id` int unsigned NOT NULL DEFAULT 0,
  `model_name` varchar(180) NOT NULL DEFAULT '',
  `model_label` varchar(180) NOT NULL DEFAULT '',
  `group_key` int NOT NULL DEFAULT 0,
  `series_name` varchar(120) NOT NULL DEFAULT '',
  `is_hot` tinyint NOT NULL DEFAULT 0,
  `sort` int NOT NULL DEFAULT 0,
  `status` tinyint NOT NULL DEFAULT 1,
  `raw_data` json DEFAULT NULL,
  `create_at` int unsigned NOT NULL DEFAULT 0,
  `update_at` int unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_dataset_goods` (`site_id`,`dataset_id`,`external_goods_id`),
  KEY `idx_dataset_status_sort` (`site_id`,`dataset_id`,`status`,`sort`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='DH速收报价型号';

CREATE TABLE IF NOT EXISTS `{{prefix}}recycle_quotation_v2_capacity` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `site_id` int unsigned NOT NULL DEFAULT 0,
  `dataset_id` int unsigned NOT NULL DEFAULT 0,
  `quotation_id` int unsigned NOT NULL DEFAULT 0,
  `model_id` int unsigned NOT NULL DEFAULT 0,
  `external_goods_id` int unsigned NOT NULL DEFAULT 0,
  `capacity_answer_id` int unsigned NOT NULL DEFAULT 0,
  `capacity_name` varchar(180) NOT NULL DEFAULT '',
  `capacity_label` varchar(180) NOT NULL DEFAULT '',
  `group_key` int NOT NULL DEFAULT 0,
  `sort` int NOT NULL DEFAULT 0,
  `status` tinyint NOT NULL DEFAULT 1,
  `raw_data` json DEFAULT NULL,
  `create_at` int unsigned NOT NULL DEFAULT 0,
  `update_at` int unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_model_capacity` (`site_id`,`dataset_id`,`model_id`,`capacity_answer_id`),
  KEY `idx_dataset_model` (`site_id`,`dataset_id`,`model_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='DH速收报价容量';

CREATE TABLE IF NOT EXISTS `{{prefix}}recycle_quotation_v2_field` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `site_id` int unsigned NOT NULL DEFAULT 0,
  `dataset_id` int unsigned NOT NULL DEFAULT 0,
  `quotation_id` int unsigned NOT NULL DEFAULT 0,
  `question_id` int unsigned NOT NULL DEFAULT 0,
  `field_name` varchar(180) NOT NULL DEFAULT '',
  `field_type` varchar(30) NOT NULL DEFAULT 'price',
  `sort` int NOT NULL DEFAULT 0,
  `status` tinyint NOT NULL DEFAULT 1,
  `raw_data` json DEFAULT NULL,
  `create_at` int unsigned NOT NULL DEFAULT 0,
  `update_at` int unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_dataset_question_type` (`site_id`,`dataset_id`,`question_id`,`field_type`),
  KEY `idx_dataset_type_sort` (`site_id`,`dataset_id`,`field_type`,`sort`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='DH速收报价字段';

CREATE TABLE IF NOT EXISTS `{{prefix}}recycle_quotation_v2_price` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `site_id` int unsigned NOT NULL DEFAULT 0,
  `dataset_id` int unsigned NOT NULL DEFAULT 0,
  `quotation_id` int unsigned NOT NULL DEFAULT 0,
  `model_id` int unsigned NOT NULL DEFAULT 0,
  `capacity_id` int unsigned NOT NULL DEFAULT 0,
  `field_id` int unsigned NOT NULL DEFAULT 0,
  `external_goods_id` int unsigned NOT NULL DEFAULT 0,
  `capacity_answer_id` int unsigned NOT NULL DEFAULT 0,
  `field_name` varchar(180) NOT NULL DEFAULT '',
  `crawler_price` decimal(12,2) NOT NULL DEFAULT 0.00,
  `adjust_type` tinyint NOT NULL DEFAULT 1,
  `adjust_value` decimal(12,2) NOT NULL DEFAULT 0.00,
  `final_price` decimal(12,2) NOT NULL DEFAULT 0.00,
  `price_date` varchar(20) NOT NULL DEFAULT '',
  `is_current` tinyint NOT NULL DEFAULT 1,
  `locked` tinyint NOT NULL DEFAULT 0,
  `raw_item` json DEFAULT NULL,
  `create_at` int unsigned NOT NULL DEFAULT 0,
  `update_at` int unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_dataset_model_capacity_field_date` (`site_id`,`dataset_id`,`model_id`,`capacity_id`,`field_id`,`price_date`),
  KEY `idx_dataset_current` (`site_id`,`dataset_id`,`is_current`),
  KEY `idx_model_capacity` (`site_id`,`model_id`,`capacity_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='DH速收报价价格';

CREATE TABLE IF NOT EXISTS `{{prefix}}recycle_quotation_v2_note` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `site_id` int unsigned NOT NULL DEFAULT 0,
  `dataset_id` int unsigned NOT NULL DEFAULT 0,
  `quotation_id` int unsigned NOT NULL DEFAULT 0,
  `model_id` int unsigned NOT NULL DEFAULT 0,
  `capacity_id` int unsigned NOT NULL DEFAULT 0,
  `field_id` int unsigned NOT NULL DEFAULT 0,
  `external_goods_id` int unsigned NOT NULL DEFAULT 0,
  `capacity_answer_id` int unsigned NOT NULL DEFAULT 0,
  `field_name` varchar(180) NOT NULL DEFAULT '',
  `content_text` text,
  `content_html` text,
  `merge_items` json DEFAULT NULL,
  `follow_crawler` tinyint NOT NULL DEFAULT 1,
  `status` tinyint NOT NULL DEFAULT 1,
  `raw_item` json DEFAULT NULL,
  `create_at` int unsigned NOT NULL DEFAULT 0,
  `update_at` int unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_dataset_model_capacity` (`site_id`,`dataset_id`,`model_id`,`capacity_id`),
  KEY `idx_dataset_field` (`site_id`,`dataset_id`,`field_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='DH速收报价说明';

CREATE TABLE IF NOT EXISTS `{{prefix}}recycle_quotation_v2_sync_log` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `site_id` int unsigned NOT NULL DEFAULT 0,
  `dataset_id` int unsigned NOT NULL DEFAULT 0,
  `quotation_id` int unsigned NOT NULL DEFAULT 0,
  `channel_key` varchar(50) NOT NULL DEFAULT 'chaoniu',
  `request_url` varchar(1000) NOT NULL DEFAULT '',
  `request_params` json DEFAULT NULL,
  `http_code` int NOT NULL DEFAULT 0,
  `duration` int NOT NULL DEFAULT 0,
  `sync_source` varchar(20) NOT NULL DEFAULT 'manual',
  `raw_response` json DEFAULT NULL,
  `parsed_preview` json DEFAULT NULL,
  `stats` json DEFAULT NULL,
  `warnings` json DEFAULT NULL,
  `status` tinyint NOT NULL DEFAULT 0,
  `imported` tinyint NOT NULL DEFAULT 0,
  `error_message` varchar(500) NOT NULL DEFAULT '',
  `create_at` int unsigned NOT NULL DEFAULT 0,
  `update_at` int unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_dataset_time` (`site_id`,`dataset_id`,`create_at`),
  KEY `idx_status` (`site_id`,`status`),
  KEY `idx_source` (`site_id`,`sync_source`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='DH速收报价同步日志';
