<?php
return [
    [
        'menu_name' => '设备桥下载',
        'menu_key' => 'hsx_recycle_device_bridge',
        'menu_short_name' => '设备桥',
        'parent_select_key' => '',
        'parent_key' => 'setting_manage',
        'menu_type' => '1',
        'icon' => 'element Connection',
        'api_url' => 'recycle/platform/device_bridge',
        'router_path' => 'recycle/device-bridge',
        'view_path' => 'device_bridge/settings',
        'methods' => 'get',
        'sort' => '119',
        'status' => '1',
        'is_show' => '1',
        'children' => [
            [
                'menu_name' => '保存设备桥配置',
                'menu_key' => 'hsx_recycle_device_bridge_save',
                'menu_short_name' => '保存',
                'parent_select_key' => '',
                'menu_type' => '2',
                'icon' => '',
                'api_url' => 'recycle/platform/device_bridge',
                'router_path' => '',
                'view_path' => '',
                'methods' => 'post',
                'sort' => '1',
                'status' => '1',
                'is_show' => '0',
            ],
        ],
    ],
];