<?php
return [
    [
        'menu_name' => '二手机财务',
        'menu_key' => 'hsx_finance_manage',
        'menu_short_name' => '财务',
        'parent_select_key' => '',
        'parent_key' => '',
        'menu_type' => '0',
        'icon' => 'nc-iconfont nc-icon-qianbao',
        'api_url' => '',
        'router_path' => 'hsx_finance',
        'view_path' => '',
        'methods' => '',
        'sort' => '78',
        'status' => '1',
        'is_show' => '1',
        'children' => [
            [
                'menu_name' => '往来对账·折账',
                'menu_key' => 'hsx_finance_settlement_board',
                'menu_short_name' => '往来对账',
                'parent_select_key' => '',
                'menu_type' => '1',
                'icon' => 'nc-iconfont nc-icon-duizhang',
                'api_url' => 'finance/balance/board',
                'router_path' => 'hsx_finance/settlement',
                'view_path' => 'settlement/board',
                'methods' => 'get',
                'sort' => '100',
                'status' => '1',
                'is_show' => '1',
                'children' => [
                    [
                        'menu_name' => '应付列表',
                        'menu_key' => 'hsx_finance_payable_lists',
                        'menu_short_name' => '应付列表',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'finance/payable/lists',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'get',
                        'sort' => '95',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '应收列表',
                        'menu_key' => 'hsx_finance_receivable_lists',
                        'menu_short_name' => '应收列表',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'finance/receivable/lists',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'get',
                        'sort' => '90',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '应付待结',
                        'menu_key' => 'hsx_finance_payable_outstanding',
                        'menu_short_name' => '应付待结',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'finance/payable/outstanding',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'get',
                        'sort' => '85',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '应收待结',
                        'menu_key' => 'hsx_finance_receivable_outstanding',
                        'menu_short_name' => '应收待结',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'finance/receivable/outstanding',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'get',
                        'sort' => '80',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '结算预演',
                        'menu_key' => 'hsx_finance_settlement_preview',
                        'menu_short_name' => '结算预演',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'finance/settlement/preview',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '75',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '确认结算',
                        'menu_key' => 'hsx_finance_settlement_settle',
                        'menu_short_name' => '确认结算',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'finance/settlement/settle',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '70',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                ],
            ],
        ],
    ],
];
