<?php

return [
    'DIY_SD_XIAOYUAN_INDEX' => [
        'sd_xiaoyuan_index_default' => [
            'title' => '校园帮首页',
            'cover' => '',
            'preview' => '',
            'desc' => '校园帮首页默认模板',
            'mode' => 'diy',
            'data' => [
                'global' => [
                    'title' => '校园帮',
                    'pageStartBgColor' => '#f7f7f7',
                    'pageEndBgColor' => '#f7f7f7',
                    'pageGradientAngle' => 'to bottom',
                    'bgUrl' => '',
                    'bgHeightScale' => 100,
                    'imgWidth' => '',
                    'imgHeight' => '',
                    'topStatusBar' => [
                        'control' => true,
                        'isShow' => true,
                        'bgColor' => '#c0fe95',
                        'isTransparent' => false,
                        'style' => 'style-1',
                        'textColor' => '#333333',
                        'textAlign' => 'center'
                    ],
                    'bottomTabBar' => [
                        'isShow' => true,
                        'control' => true
                    ],
                    'popWindow' => [
                        'imgUrl' => '',
                        'imgWidth' => '',
                        'imgHeight' => '',
                        'count' => -1,
                        'show' => 0,
                        'link' => [
                            'name' => ''
                        ]
                    ],
                    'template' => [
                        'textColor' => '#303133',
                        'pageStartBgColor' => '',
                        'pageEndBgColor' => '',
                        'pageGradientAngle' => 'to bottom',
                        'componentBgUrl' => '',
                        'componentBgAlpha' => 2,
                        'componentStartBgColor' => '',
                        'componentEndBgColor' => '',
                        'componentGradientAngle' => 'to bottom',
                        'topRounded' => 0,
                        'bottomRounded' => 0,
                        'elementBgColor' => '',
                        'topElementRounded' => 0,
                        'bottomElementRounded' => 0,
                        'margin' => [
                            'top' => 0,
                            'bottom' => 0,
                            'both' => 12
                        ]
                    ]
                ],
                'value' => [
                    [
                        'path' => 'edit-xiaoyuan-header',
                        'uses' => 1,
                        'id' => 'xiaoyuan_header_1',
                        'componentName' => 'XiaoyuanHeader',
                        'componentTitle' => '顶部导航',
                        'bgStartColor' => '#c0fe95',
                        'bgEndColor' => '#e8ffcc',
                        'schoolName' => '北京大学',
                        'schoolUrl' => '/addon/sd_xiaoyuan/pages/school/select',
                        'taskCount' => 0,
                        'taskLabel' => '今日任务',
                        'taskUrl' => '/addon/sd_xiaoyuan/pages/order/hall',
                        'earningAmount' => '0.00',
                        'earningLabel' => '累计佣金',
                        'earningUrl' => '/addon/sd_xiaoyuan/pages/runner/index',
                        'searchPlaceholder' => '搜索任务/服务',
                        'searchUrl' => '/addon/sd_xiaoyuan/pages/search/index',
                        'messageUrl' => '/addon/sd_xiaoyuan/pages/message/index',
                        'showPromoCard' => true,
                        'promoTitle' => '校园帮实名认证',
                        'promoSubtitle' => '安全可靠，快速认证',
                        'promoBtnText' => 'GO',
                        'promoIcon' => 'account-fill',
                        'promoUrl' => '/addon/sd_xiaoyuan/pages/campus/auth',
                        'pageStartBgColor' => '',
                        'pageEndBgColor' => '',
                        'pageGradientAngle' => 'to bottom',
                        'componentBgUrl' => '',
                        'componentBgAlpha' => 2,
                        'componentStartBgColor' => '',
                        'componentEndBgColor' => '',
                        'componentGradientAngle' => 'to bottom',
                        'topRounded' => 0,
                        'bottomRounded' => 0,
                        'elementBgColor' => '',
                        'topElementRounded' => 0,
                        'bottomElementRounded' => 0,
                        'margin' => ['top' => 0, 'bottom' => 0, 'both' => 0]
                    ],
                    [
                        'path' => 'edit-xiaoyuan-notice',
                        'uses' => 1,
                        'id' => 'xiaoyuan_notice_1',
                        'componentName' => 'XiaoyuanNotice',
                        'componentTitle' => '公告栏',
                        'text' => '欢迎使用校园帮，有问题请联系客服~',
                        'bgColor' => '#fff7e6',
                        'textColor' => '#ff9500',
                        'isShow' => true,
                        'pageStartBgColor' => '',
                        'pageEndBgColor' => '',
                        'pageGradientAngle' => 'to bottom',
                        'componentBgUrl' => '',
                        'componentBgAlpha' => 2,
                        'componentStartBgColor' => '',
                        'componentEndBgColor' => '',
                        'componentGradientAngle' => 'to bottom',
                        'topRounded' => 0,
                        'bottomRounded' => 0,
                        'elementBgColor' => '',
                        'topElementRounded' => 0,
                        'bottomElementRounded' => 0,
                        'margin' => ['top' => 0, 'bottom' => 10, 'both' => 10]
                    ],
                    [
                        'path' => 'edit-xiaoyuan-menu-grid',
                        'uses' => 1,
                        'id' => 'xiaoyuan_menu_grid_1',
                        'componentName' => 'XiaoyuanMenuGrid',
                        'componentTitle' => '功能菜单',
                        'style' => 'style-1',
                        'column' => 5,
                        'list' => [
                            ['name' => '帮我买', 'icon' => 'shopping-cart-fill', 'iconColor' => '#ff6b00', 'bgColor' => '#fff4e6', 'url' => '/addon/sd_xiaoyuan/pages/buy/create', 'isShow' => true],
                            ['name' => '帮我送', 'icon' => 'car', 'iconColor' => '#13c2c2', 'bgColor' => '#e6fffb', 'url' => '/addon/sd_xiaoyuan/pages/send/create', 'isShow' => true],
                            ['name' => '代取快递', 'icon' => 'gift-fill', 'iconColor' => '#52c41a', 'bgColor' => '#f6ffed', 'url' => '/addon/sd_xiaoyuan/pages/express/pickup', 'isShow' => true],
                            ['name' => '帮打印', 'icon' => 'file-text-fill', 'iconColor' => '#ff9800', 'bgColor' => '#fff8e1', 'url' => '/addon/sd_xiaoyuan/pages/print/create', 'isShow' => true],
                            ['name' => '扔垃圾', 'icon' => 'trash-fill', 'iconColor' => '#9c27b0', 'bgColor' => '#f3e5f5', 'url' => '/addon/sd_xiaoyuan/pages/trash/create', 'isShow' => true],
                            ['name' => '帮搬运', 'icon' => 'car-fill', 'iconColor' => '#4caf50', 'bgColor' => '#e8f5e9', 'url' => '/addon/sd_xiaoyuan/pages/carry/create', 'isShow' => true],
                            ['name' => '代清洁', 'icon' => 'star-fill', 'iconColor' => '#2196f3', 'bgColor' => '#e3f2fd', 'url' => '/addon/sd_xiaoyuan/pages/clean/create', 'isShow' => true],
                            ['name' => '帮帮忙', 'icon' => 'question-circle-fill', 'iconColor' => '#e91e63', 'bgColor' => '#fce4ec', 'url' => '/addon/sd_xiaoyuan/pages/help/create', 'isShow' => true],
                            ['name' => '代占座', 'icon' => 'bookmark-fill', 'iconColor' => '#673ab7', 'bgColor' => '#ede7f6', 'url' => '/addon/sd_xiaoyuan/pages/seat/create', 'isShow' => true],
                            ['name' => '表白墙', 'icon' => 'heart-fill', 'iconColor' => '#fa709a', 'bgColor' => '#fff0f5', 'url' => '/addon/sd_xiaoyuan/pages/confession/index', 'isShow' => true],
                            ['name' => '游戏陪练', 'icon' => 'red-packet-fill', 'iconColor' => '#ff7243', 'bgColor' => '#fff3e0', 'url' => '/addon/sd_xiaoyuan/pages/game/publish', 'isShow' => true]
                        ],
                        'pageStartBgColor' => '',
                        'pageEndBgColor' => '',
                        'pageGradientAngle' => 'to bottom',
                        'componentBgUrl' => '',
                        'componentBgAlpha' => 2,
                        'componentStartBgColor' => '#ffffff',
                        'componentEndBgColor' => '#ffffff',
                        'componentGradientAngle' => 'to bottom',
                        'topRounded' => 12,
                        'bottomRounded' => 12,
                        'elementBgColor' => '',
                        'topElementRounded' => 0,
                        'bottomElementRounded' => 0,
                        'margin' => ['top' => 10, 'bottom' => 10, 'both' => 10]
                    ],
                    [
                        'path' => 'edit-xiaoyuan-banner',
                        'uses' => 0,
                        'id' => 'xiaoyuan_banner_1',
                        'componentName' => 'XiaoyuanBanner',
                        'componentTitle' => '功能入口',
                        'style' => 'style-1',
                        'column' => 3,
                        'list' => [
                            ['title' => '房屋租赁', 'desc' => '校园周边好房', 'icon' => 'home-fill', 'bgColor' => 'linear-gradient(135deg, #7c5cfc, #a78bfa)', 'url' => '/addon/sd_xiaoyuan/pages/house/index', 'isShow' => true],
                            ['title' => '课程表', 'desc' => '查看课程安排', 'icon' => 'calendar-fill', 'bgColor' => 'linear-gradient(135deg, #1890ff, #40a9ff)', 'url' => '/addon/sd_xiaoyuan/pages/schedule/index', 'isShow' => true],
                            ['title' => '拼单好饭', 'desc' => '一起拼更划算', 'icon' => 'coupon-fill', 'bgColor' => 'linear-gradient(135deg, #ff6b35, #ff9a5c)', 'url' => '/addon/sd_xiaoyuan/pages/group/index', 'isShow' => true],
                            ['title' => '闲置市场', 'desc' => '好物低价转', 'icon' => 'bag-fill', 'bgColor' => 'linear-gradient(135deg, #13c2c2, #36d6b7)', 'url' => '/addon/sd_xiaoyuan/pages/secondhand/index', 'isShow' => true],
                            ['title' => '失物招领', 'desc' => '帮你找回来', 'icon' => 'search', 'bgColor' => 'linear-gradient(135deg, #ff4d6a, #ff7eb3)', 'url' => '/addon/sd_xiaoyuan/pages/lost_found/index', 'isShow' => true],
                            ['title' => '校园树洞', 'desc' => '匿名说心事', 'icon' => 'chat-fill', 'bgColor' => 'linear-gradient(135deg, #722ed1, #b37feb)', 'url' => '/addon/sd_xiaoyuan/pages/community/index', 'isShow' => true]
                        ],
                        'pageStartBgColor' => '',
                        'pageEndBgColor' => '',
                        'pageGradientAngle' => 'to bottom',
                        'componentBgUrl' => '',
                        'componentBgAlpha' => 2,
                        'componentStartBgColor' => '',
                        'componentEndBgColor' => '',
                        'componentGradientAngle' => 'to bottom',
                        'topRounded' => 0,
                        'bottomRounded' => 0,
                        'elementBgColor' => '',
                        'topElementRounded' => 12,
                        'bottomElementRounded' => 12,
                        'margin' => ['top' => 0, 'bottom' => 10, 'both' => 10]
                    ],
                    [
                        'path' => 'edit-xiaoyuan-order-hall',
                        'uses' => 1,
                        'id' => 'xiaoyuan_order_hall_1',
                        'componentName' => 'XiaoyuanOrderHall',
                        'componentTitle' => '订单大厅',
                        'title' => '任务大厅',
                        'showMore' => true,
                        'moreText' => '查看更多',
                        'moreUrl' => '/addon/sd_xiaoyuan/pages/order/hall',
                        'num' => 10,
                        'tabs' => [
                            ['name' => '全部', 'type' => 'all', 'isShow' => true],
                            ['name' => '代取快递', 'type' => 'EXPRESS', 'isShow' => true],
                            ['name' => '帮我买', 'type' => 'BUY', 'isShow' => true],
                            ['name' => '代打印', 'type' => 'PRINT', 'isShow' => true],
                            ['name' => '扔垃圾', 'type' => 'TRASH', 'isShow' => true],
                            ['name' => '帮搬运', 'type' => 'CARRY', 'isShow' => true],
                            ['name' => '代清洁', 'type' => 'CLEAN', 'isShow' => true],
                            ['name' => '帮帮忙', 'type' => 'HELP', 'isShow' => true],
                            ['name' => '游戏陪玩', 'type' => 'GAME', 'isShow' => true]
                        ],
                        'pageStartBgColor' => '',
                        'pageEndBgColor' => '',
                        'pageGradientAngle' => 'to bottom',
                        'componentBgUrl' => '',
                        'componentBgAlpha' => 2,
                        'componentStartBgColor' => '#ffffff',
                        'componentEndBgColor' => '#ffffff',
                        'componentGradientAngle' => 'to bottom',
                        'topRounded' => 12,
                        'bottomRounded' => 12,
                        'elementBgColor' => '',
                        'topElementRounded' => 0,
                        'bottomElementRounded' => 0,
                        'margin' => ['top' => 10, 'bottom' => 10, 'both' => 10]
                    ]
                ]
            ]
        ]
    ]
];
