<template>
    <el-drawer v-model="visible" title="分类映射工作台" size="86%" destroy-on-close>
        <div class="mapping-head">
            <div><div class="text-[16px] font-semibold text-[#1f2937]">主站 {{ masterSiteId }} → 子站 {{ agentSiteId }}</div><div class="mt-[5px] text-[12px] text-[#64748b]">分类各自独立，仅记录等价关系；有歧义时由管理员决定，不会自动复制或覆盖分类。</div></div>
            <el-button type="primary" :loading="scanLoading" @click="scan">扫描并校准</el-button>
        </div>
        <div class="mt-[14px] grid grid-cols-2 gap-[10px] lg:grid-cols-5"><div v-for="item in summaryCards" :key="item.key" class="summary-card"><span>{{ item.label }}</span><strong :class="item.className">{{ summary[item.key] || 0 }}</strong></div></div>
        <div class="mt-[14px] flex flex-wrap gap-[10px]"><el-select v-model="filters.status" class="!w-[160px]" @change="loadList(1)"><el-option label="全部状态" value="" /><el-option label="待人工处理" value="pending" /><el-option label="映射失效" value="broken" /><el-option label="已关联" value="mapped" /><el-option label="已忽略" value="ignored" /><el-option label="主站已删除" value="source_deleted" /></el-select><el-input v-model="filters.keyword" clearable class="!w-[260px]" placeholder="搜索主站或子站分类" @keyup.enter="loadList(1)" /><el-button @click="loadList(1)">查询</el-button></div>
        <el-table v-loading="loading" :data="rows" class="mt-[12px]" size="large"><template #empty><span>{{ loading ? '' : '暂无映射记录，请点击“扫描并校准”' }}</span></template><el-table-column label="主站分类" min-width="220"><template #default="{ row }"><div class="font-medium text-[#1f2937]">{{ row.master_name }}</div><div class="mt-[3px] text-[12px] text-[#94a3b8]">ID {{ row.master_category_id }} · {{ row.master_level }} 级</div></template></el-table-column><el-table-column label="当前子站分类" min-width="220"><template #default="{ row }"><template v-if="row.agent_category_id"><div>{{ row.agent_name || '分类已删除' }}</div><div class="mt-[3px] text-[12px] text-[#94a3b8]">ID {{ row.agent_category_id }}</div></template><span v-else class="text-[#94a3b8]">尚未关联</span></template></el-table-column><el-table-column label="状态" width="125"><template #default="{ row }"><el-tag :type="statusMeta(row.status).type">{{ statusMeta(row.status).label }}</el-tag></template></el-table-column><el-table-column label="系统判断" min-width="240"><template #default="{ row }"><div class="text-[13px] text-[#475569]">{{ row.problem_reason || matchTypeName(row.match_type) }}</div><div v-if="row.candidate_options?.length" class="mt-[5px] text-[12px] text-[#d97706]">候选：{{ candidateNames(row) }}</div></template></el-table-column><el-table-column label="操作" width="245" fixed="right"><template #default="{ row }"><el-button v-if="row.status !== 'source_deleted'" type="primary" link @click="openMap(row)">{{ row.status === 'mapped' ? '重新关联' : '关联已有' }}</el-button><el-button v-if="row.status !== 'source_deleted'" type="success" link @click="createCategory(row)">新建并关联</el-button><el-button v-if="row.status !== 'source_deleted' && row.status !== 'ignored'" type="warning" link @click="ignore(row)">忽略</el-button></template></el-table-column></el-table>
        <div class="mt-[16px] flex justify-end"><el-pagination v-model:current-page="page" v-model:page-size="limit" layout="total, prev, pager, next" :total="total" @current-change="loadList" /></div>
        <el-dialog v-model="mapVisible" title="关联已有子站分类" width="520px" append-to-body><div class="mb-[14px] rounded-[8px] bg-[#f8fafc] px-[14px] py-[12px] text-[13px]">主站分类：<strong>{{ currentRow?.master_name }}</strong></div><el-form label-width="100px"><el-form-item label="子站分类" required><el-select v-model="selectedCategoryId" filterable class="w-full" placeholder="输入名称搜索子站现有分类"><el-option v-for="item in availableOptions" :key="item.category_id" :label="optionName(item)" :value="item.category_id" /></el-select><div class="mt-[6px] text-[12px] text-[#94a3b8]">仅显示与主站分类层级一致的分类，父级关系会在保存时再次校验。</div></el-form-item></el-form><template #footer><el-button @click="mapVisible = false">取消</el-button><el-button type="primary" :loading="actionLoading" @click="submitMap">确认关联</el-button></template></el-dialog>
    </el-drawer>
</template>
<script lang="ts" setup>
import { computed, reactive, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { createAgentCategoryMapping, getAgentCategoryMappingSummary, getAgentCategoryMappings, getAgentCategoryOptions, ignoreAgentCategoryMapping, mapAgentCategory, scanAgentCategoryMappings } from '@/addon/phone_shop/api/agent'
const visible=ref(false),loading=ref(false),scanLoading=ref(false),actionLoading=ref(false),agentSiteId=ref(0),masterSiteId=ref(0),rows=ref<any[]>([]),options=ref<any[]>([])
const summary=reactive<any>({mapped:0,pending:0,broken:0,ignored:0,source_deleted:0}),filters=reactive({status:'',keyword:''}),page=ref(1),limit=ref(15),total=ref(0),mapVisible=ref(false),currentRow=ref<any>(null),selectedCategoryId=ref<number|undefined>()
const summaryCards=[{key:'mapped',label:'已安全关联',className:'text-[#16a34a]'},{key:'pending',label:'待人工处理',className:'text-[#d97706]'},{key:'broken',label:'映射失效',className:'text-[#dc2626]'},{key:'ignored',label:'已忽略',className:'text-[#64748b]'},{key:'source_deleted',label:'主站已删除',className:'text-[#64748b]'}]
const availableOptions=computed(()=>options.value.filter(item=>Number(item.level)===Number(currentRow.value?.master_level||0))),optionName=(item:any)=>`${item.category_full_name||item.category_name}（ID ${item.category_id}）`
const candidateNames=(row:any)=>(row.candidate_options||[]).map((item:any)=>item.name).join('、')
const statusMeta=(status:string)=>({mapped:{label:'已关联',type:'success'},pending:{label:'待处理',type:'warning'},broken:{label:'已失效',type:'danger'},ignored:{label:'已忽略',type:'info'},source_deleted:{label:'主站已删除',type:'info'}} as any)[status]||{label:status||'-',type:'info'}
const matchTypeName=(type:string)=>({legacy_copy:'已接管历史同步分类',auto_exact:'系统唯一匹配',manual:'管理员手动关联',manual_created:'管理员新建后关联'} as any)[type]||'-'
const loadSummary=async()=>{const res:any=await getAgentCategoryMappingSummary({agent_site_id:agentSiteId.value});Object.assign(summary,res.data||{});masterSiteId.value=Number(res.data?.master_site_id||0)}
const loadOptions=async()=>{const res:any=await getAgentCategoryOptions({agent_site_id:agentSiteId.value});options.value=res.data||[]}
const loadList=async(p=page.value)=>{loading.value=true;page.value=Number(p||1);try{const res:any=await getAgentCategoryMappings({agent_site_id:agentSiteId.value,status:filters.status,keyword:filters.keyword,page:page.value,limit:limit.value});rows.value=res.data?.data||[];total.value=Number(res.data?.total||0);masterSiteId.value=Number(res.data?.master_site_id||masterSiteId.value)}finally{loading.value=false}}
const refresh=async()=>{await Promise.all([loadSummary(),loadList(1),loadOptions()])}
const open=async(siteId:number)=>{agentSiteId.value=Number(siteId||0);filters.status='';filters.keyword='';visible.value=true;await Promise.all([loadSummary(),loadList(1),loadOptions()]);const count=['mapped','pending','broken','ignored','source_deleted'].reduce((sum,key)=>sum+Number(summary[key]||0),0);if(count===0)await scan()}
const scan=async()=>{scanLoading.value=true;try{await scanAgentCategoryMappings({agent_site_id:agentSiteId.value});ElMessage.success('扫描完成；无法唯一判断的分类已进入待处理');await refresh()}finally{scanLoading.value=false}}
const openMap=(row:any)=>{currentRow.value=row;selectedCategoryId.value=row.agent_category_id||row.candidate_options?.[0]?.category_id||undefined;mapVisible.value=true}
const submitMap=async()=>{if(!selectedCategoryId.value)return ElMessage.warning('请选择子站分类');actionLoading.value=true;try{await mapAgentCategory(currentRow.value.mapping_id,selectedCategoryId.value);ElMessage.success('关联成功，受影响商品将重新校准');mapVisible.value=false;await refresh()}finally{actionLoading.value=false}}
const createCategory=(row:any)=>{ElMessageBox.confirm(`将在子站创建“${row.master_name}”并立即建立映射。只有确认子站没有可复用分类时才继续。`,'创建子站分类',{type:'warning'}).then(async()=>{await createAgentCategoryMapping(row.mapping_id);ElMessage.success('已创建并关联，商品将重新校准');await refresh()}).catch(()=>{})}
const ignore=(row:any)=>{ElMessageBox.confirm('忽略后，该主站分类下的代理商品不会在子站上架，确认继续？','忽略分类',{type:'warning'}).then(async()=>{await ignoreAgentCategoryMapping(row.mapping_id);ElMessage.success('已忽略');await refresh()}).catch(()=>{})}
defineExpose({open})
</script>
<style lang="scss" scoped>.mapping-head{@apply flex flex-wrap items-center justify-between gap-[12px] rounded-[10px] border border-[#dbeafe] bg-[#eff6ff] px-[16px] py-[14px];}.summary-card{@apply flex min-h-[70px] flex-col justify-center rounded-[10px] border border-[#e5e7eb] bg-white px-[14px];span{@apply text-[12px] text-[#94a3b8];}strong{@apply mt-[6px] text-[22px] font-semibold;}}</style>
