<?php
return [
    [
        'menu_name' => '二手机 ERP',
        'menu_key' => 'hsx_erp_manage',
        'menu_short_name' => 'ERP',
        'parent_select_key' => '',
        'parent_key' => '',
        'menu_type' => '0',
        'icon' => 'nc-iconfont nc-icon-cangku',
        'api_url' => '',
        'router_path' => 'hsx_erp',
        'view_path' => '',
        'methods' => '',
        'sort' => '80',
        'status' => '1',
        'is_show' => '1',
        'children' => [
            [
                'menu_name' => '账实校验',
                'menu_key' => 'hsx_erp_reconciliation_scan',
                'menu_short_name' => '账实校验',
                'parent_select_key' => '',
                'menu_type' => '2',
                'icon' => '',
                'api_url' => 'erp/reconciliation/scan',
                'router_path' => '',
                'view_path' => '',
                'methods' => 'get',
                'sort' => '130',
                'status' => '1',
                'is_show' => '0',
            ],
            [
                'menu_name' => '基础配置',
                'menu_key' => 'hsx_erp_config_group',
                'menu_short_name' => '基础配置',
                'parent_select_key' => '',
                'menu_type' => '0',
                'icon' => 'nc-iconfont nc-icon-shezhi',
                'api_url' => '',
                'router_path' => '',
                'view_path' => '',
                'methods' => '',
                'sort' => '60',
                'status' => '1',
                'is_show' => '1',
                'children' => [
            [
                'menu_name' => '往来单位',
                'menu_key' => 'hsx_erp_counterparty_list',
                'menu_short_name' => '往来单位',
                'parent_select_key' => '',
                'menu_type' => '1',
                'icon' => 'nc-iconfont nc-icon-huiyuan',
                'api_url' => 'erp/counterparty/lists',
                'router_path' => 'hsx_erp/counterparty',
                'view_path' => 'counterparty/list',
                'methods' => 'get',
                'sort' => '125',
                'status' => '1',
                'is_show' => '1',
                'children' => [
                    [
                        'menu_name' => '往来单位选项',
                        'menu_key' => 'hsx_erp_counterparty_options',
                        'menu_short_name' => '往来单位选项',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'erp/counterparty/options',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'get',
                        'sort' => '100',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '保存往来单位',
                        'menu_key' => 'hsx_erp_counterparty_save',
                        'menu_short_name' => '保存往来单位',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'erp/counterparty/save/<id>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '90',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                ],
            ],
            [
                'menu_name' => '仓库与库位',
                'menu_key' => 'hsx_erp_warehouse_list',
                'menu_short_name' => '仓库与库位',
                'parent_select_key' => '',
                'menu_type' => '1',
                'icon' => 'nc-iconfont nc-icon-cangku',
                'api_url' => 'erp/warehouse/lists',
                'router_path' => 'hsx_erp/warehouse',
                'view_path' => 'warehouse/list',
                'methods' => 'get',
                'sort' => '120',
                'status' => '1',
                'is_show' => '1',
                'children' => [
                    [
                        'menu_name' => '仓库选项',
                        'menu_key' => 'hsx_erp_warehouse_options',
                        'menu_short_name' => '仓库选项',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'erp/warehouse/options',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'get',
                        'sort' => '110',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '保存仓库与库位',
                        'menu_key' => 'hsx_erp_warehouse_save',
                        'menu_short_name' => '保存仓库与库位',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'erp/warehouse/save/<id>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '100',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '保存库位',
                        'menu_key' => 'hsx_erp_warehouse_location_save',
                        'menu_short_name' => '保存库位',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'erp/warehouse/<warehouse_id>/location/save/<id>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '90',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '删除仓库',
                        'menu_key' => 'hsx_erp_warehouse_delete',
                        'menu_short_name' => '删除仓库',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'erp/warehouse/<id>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'delete',
                        'sort' => '80',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '删除库位',
                        'menu_key' => 'hsx_erp_warehouse_location_delete',
                        'menu_short_name' => '删除库位',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'erp/warehouse/location/<id>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'delete',
                        'sort' => '70',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                ],
            ],
                ],
            ],
            [
                'menu_name' => '入库工作台',
                'menu_key' => 'hsx_erp_stock_order_list',
                'menu_short_name' => '入库工作台',
                'parent_select_key' => '',
                'menu_type' => '1',
                'icon' => 'nc-iconfont nc-icon-cangku',
                'api_url' => 'erp/stock_order/lists',
                'router_path' => 'hsx_erp/stock_order',
                'view_path' => 'stock_order/list',
                'methods' => 'get',
                'sort' => '110',
                'status' => '1',
                'is_show' => '1',
                'children' => [
                    [
                        'menu_name' => '入库单详情',
                        'menu_key' => 'hsx_erp_stock_order_info',
                        'menu_short_name' => '入库单详情',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'erp/stock_order/<id>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'get',
                        'sort' => '100',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '确认入库明细',
                        'menu_key' => 'hsx_erp_stock_order_confirm_items',
                        'menu_short_name' => '确认入库明细',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'erp/stock_order/<id>/confirm_items',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '90',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '驳回入库明细',
                        'menu_key' => 'hsx_erp_stock_order_reject_items',
                        'menu_short_name' => '驳回入库明细',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'erp/stock_order/<id>/reject_items',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '80',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '修正并重提',
                        'menu_key' => 'hsx_erp_stock_order_resubmit_item',
                        'menu_short_name' => '修正并重提',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'erp/stock_order/<id>/item/<item_id>/resubmit',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '70',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                ],
            ],
            [
                'menu_name' => '整备工作台',
                'menu_key' => 'hsx_erp_refurbishment_list',
                'menu_short_name' => '整备工作台',
                'parent_select_key' => '',
                'menu_type' => '1',
                'icon' => 'nc-iconfont nc-icon-shezhi',
                'api_url' => 'erp/refurbishment/lists',
                'router_path' => 'hsx_erp/refurbishment',
                'view_path' => 'refurbishment/list',
                'methods' => 'get',
                'sort' => '105',
                'status' => '1',
                'is_show' => '1',
                'children' => [
                    [
                        'menu_name' => '整备详情',
                        'menu_key' => 'hsx_erp_refurbishment_info',
                        'menu_short_name' => '整备详情',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'erp/refurbishment/<id>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'get',
                        'sort' => '100',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '发起整备',
                        'menu_key' => 'hsx_erp_refurbishment_create',
                        'menu_short_name' => '发起整备',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'erp/refurbishment/create',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '90',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '整备完工',
                        'menu_key' => 'hsx_erp_refurbishment_complete',
                        'menu_short_name' => '整备完工',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'erp/refurbishment/<id>/complete',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '80',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '取消整备',
                        'menu_key' => 'hsx_erp_refurbishment_cancel',
                        'menu_short_name' => '取消整备',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'erp/refurbishment/<id>/cancel',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '70',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '跳过整备',
                        'menu_key' => 'hsx_erp_refurbishment_skip',
                        'menu_short_name' => '跳过整备',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'erp/refurbishment/asset/<asset_id>/skip',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '60',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '整备负责人选项',
                        'menu_key' => 'hsx_erp_refurbishment_user_options',
                        'menu_short_name' => '整备负责人选项',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'erp/refurbishment/user_options',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'get',
                        'sort' => '50',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                ],
            ],
            [
                'menu_name' => '设备流转',
                'menu_key' => 'hsx_erp_asset_list',
                'menu_short_name' => '设备流转',
                'parent_select_key' => '',
                'menu_type' => '1',
                'icon' => 'nc-iconfont nc-icon-dingdanV6xx',
                'api_url' => 'erp/asset/lists',
                'router_path' => 'hsx_erp/asset',
                'view_path' => 'asset/list',
                'methods' => 'get',
                'sort' => '100',
                'status' => '1',
                'is_show' => '1',
                'children' => [
                    [
                        'menu_name' => '手工建档入库',
                        'menu_key' => 'hsx_erp_asset_manual_inbound',
                        'menu_short_name' => '手工建档入库',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'erp/asset/manual_inbound',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '95',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '设备详情',
                        'menu_key' => 'hsx_erp_asset_info',
                        'menu_short_name' => '设备详情',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'erp/asset/<id>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'get',
                        'sort' => '90',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '确认入库',
                        'menu_key' => 'hsx_erp_confirm_inbound',
                        'menu_short_name' => '确认入库',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'erp/stock_order/<id>/confirm_inbound',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '80',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '按设备确认入库',
                        'menu_key' => 'hsx_erp_asset_confirm_inbound',
                        'menu_short_name' => '按设备确认入库',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'erp/asset/<id>/confirm_inbound',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '70',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '批量确认入库',
                        'menu_key' => 'hsx_erp_asset_batch_confirm_inbound',
                        'menu_short_name' => '批量确认入库',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'erp/asset/batch_confirm_inbound',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '60',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                ],
            ],
            [
                'menu_name' => '销售定价',
                'menu_key' => 'hsx_erp_pricing_list',
                'menu_short_name' => '销售定价',
                'parent_select_key' => '',
                'menu_type' => '1',
                'icon' => 'nc-iconfont nc-icon-jifen',
                'api_url' => 'erp/pricing/lists',
                'router_path' => 'hsx_erp/pricing',
                'view_path' => 'pricing/list',
                'methods' => 'get',
                'sort' => '95',
                'status' => '1',
                'is_show' => '1',
                'children' => [
                    [
                        'menu_name' => '定价详情',
                        'menu_key' => 'hsx_erp_pricing_info',
                        'menu_short_name' => '定价详情',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'erp/pricing/asset/<asset_id>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'get',
                        'sort' => '90',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '保存销售定价',
                        'menu_key' => 'hsx_erp_pricing_save',
                        'menu_short_name' => '保存销售定价',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'erp/pricing/asset/<asset_id>/price',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '80',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                ],
            ],
        ],
    ],
];
