<?php
return [
    [
        'menu_name' => '二手机 ERP',
        'menu_key' => 'hsx_erp_manage',
        'menu_short_name' => 'ERP',
        'parent_select_key' => '',
        'parent_key' => '',
        'menu_type' => '0',
        'icon' => 'nc-iconfont nc-icon-yueV6xx1',
        'api_url' => '',
        'router_path' => 'hsx_erp',
        'view_path' => '',
        'methods' => '',
        'sort' => '90',
        'status' => '1',
        'is_show' => '1',
        'children' => [
            [
                'menu_name' => '运营看板',
                'menu_key' => 'hsx_erp_dashboard',
                'menu_short_name' => '运营看板',
                'parent_select_key' => '',
                'menu_type' => '1',
                'icon' => 'nc-iconfont nc-icon-tongji',
                'api_url' => 'erp/dashboard/data',
                'router_path' => 'hsx_erp/dashboard',
                'view_path' => 'dashboard/index',
                'methods' => 'get',
                'sort' => '200',
                'status' => '1',
                'is_show' => '1',
            ],
            [
                'menu_name' => '账实校验',
                'menu_key' => 'hsx_erp_reconciliation_scan',
                'menu_short_name' => '账实校验',
                'parent_select_key' => '',
                'menu_type' => '2',
                'icon' => '',
                'api_url' => 'erp/reconciliation/scan',
                'router_path' => '',
                'view_path' => '',
                'methods' => 'get',
                'sort' => '130',
                'status' => '1',
                'is_show' => '0',
            ],
            [
                'menu_name' => '入库工作台',
                'menu_key' => 'hsx_erp_stock_order_list',
                'menu_short_name' => '入库工作台',
                'parent_select_key' => '',
                'menu_type' => '1',
                'icon' => 'nc-iconfont nc-icon-cangku',
                'api_url' => 'erp/stock_order/lists',
                'router_path' => 'hsx_erp/stock_order',
                'view_path' => 'stock_order/list',
                'methods' => 'get',
                'sort' => '110',
                'status' => '1',
                'is_show' => '0',
                'children' => [
                    [
                        'menu_name' => '入库单详情',
                        'menu_key' => 'hsx_erp_stock_order_info',
                        'menu_short_name' => '入库单详情',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'erp/stock_order/<id>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'get',
                        'sort' => '100',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '确认入库明细',
                        'menu_key' => 'hsx_erp_stock_order_confirm_items',
                        'menu_short_name' => '确认入库明细',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'erp/stock_order/<id>/confirm_items',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '90',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '驳回入库明细',
                        'menu_key' => 'hsx_erp_stock_order_reject_items',
                        'menu_short_name' => '驳回入库明细',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'erp/stock_order/<id>/reject_items',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '80',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '修正并重提',
                        'menu_key' => 'hsx_erp_stock_order_resubmit_item',
                        'menu_short_name' => '修正并重提',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'erp/stock_order/<id>/item/<item_id>/resubmit',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '70',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                ],
            ],
            [
                'menu_name' => '整备工作台',
                'menu_key' => 'hsx_erp_refurbishment_list',
                'menu_short_name' => '整备工作台',
                'parent_select_key' => '',
                'menu_type' => '1',
                'icon' => 'nc-iconfont nc-icon-shezhi',
                'api_url' => 'erp/refurbishment/lists',
                'router_path' => 'hsx_erp/refurbishment',
                'view_path' => 'refurbishment/list',
                'methods' => 'get',
                'sort' => '90',
                'status' => '1',
                'is_show' => '1',
                'children' => [
                    [
                        'menu_name' => '整备详情',
                        'menu_key' => 'hsx_erp_refurbishment_info',
                        'menu_short_name' => '整备详情',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'erp/refurbishment/<id>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'get',
                        'sort' => '100',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '发起整备',
                        'menu_key' => 'hsx_erp_refurbishment_create',
                        'menu_short_name' => '发起整备',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'erp/refurbishment/create',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '90',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '整备完工',
                        'menu_key' => 'hsx_erp_refurbishment_complete',
                        'menu_short_name' => '整备完工',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'erp/refurbishment/<id>/complete',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '80',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '取消整备',
                        'menu_key' => 'hsx_erp_refurbishment_cancel',
                        'menu_short_name' => '取消整备',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'erp/refurbishment/<id>/cancel',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '70',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '跳过整备',
                        'menu_key' => 'hsx_erp_refurbishment_skip',
                        'menu_short_name' => '跳过整备',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'erp/refurbishment/asset/<asset_id>/skip',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '60',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '整备负责人选项',
                        'menu_key' => 'hsx_erp_refurbishment_user_options',
                        'menu_short_name' => '整备负责人选项',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'erp/refurbishment/user_options',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'get',
                        'sort' => '50',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                ],
            ],
            [
                'menu_name' => '设备中心',
                'menu_key' => 'hsx_erp_asset_list',
                'menu_short_name' => '设备中心',
                'parent_select_key' => '',
                'menu_type' => '1',
                'icon' => 'nc-iconfont nc-icon-dingdanV6xx',
                'api_url' => 'erp/asset/lists',
                'router_path' => 'hsx_erp/asset',
                'view_path' => 'asset/list',
                'methods' => 'get',
                'sort' => '100',
                'status' => '1',
                'is_show' => '1',
                'children' => [
                    [
                        'menu_name' => '库存概览',
                        'menu_key' => 'hsx_erp_asset_overview',
                        'menu_short_name' => '库存概览',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'erp/asset/overview',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'get',
                        'sort' => '101',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '手工建档入库',
                        'menu_key' => 'hsx_erp_asset_manual_inbound',
                        'menu_short_name' => '手工建档入库',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'erp/asset/manual_inbound',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '95',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '调成本',
                        'menu_key' => 'hsx_erp_asset_adjust_cost',
                        'menu_short_name' => '调成本',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'erp/asset/<id>/adjust_cost',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '93',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '设备详情',
                        'menu_key' => 'hsx_erp_asset_info',
                        'menu_short_name' => '设备详情',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'erp/asset/<id>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'get',
                        'sort' => '90',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '确认入库',
                        'menu_key' => 'hsx_erp_confirm_inbound',
                        'menu_short_name' => '确认入库',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'erp/stock_order/<id>/confirm_inbound',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '80',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '按设备确认入库',
                        'menu_key' => 'hsx_erp_asset_confirm_inbound',
                        'menu_short_name' => '按设备确认入库',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'erp/asset/<id>/confirm_inbound',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '70',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '批量确认入库',
                        'menu_key' => 'hsx_erp_asset_batch_confirm_inbound',
                        'menu_short_name' => '批量确认入库',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'erp/asset/batch_confirm_inbound',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '60',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                ],
            ],
            [
                'menu_name' => '销售定价',
                'menu_key' => 'hsx_erp_pricing_list',
                'menu_short_name' => '销售定价',
                'parent_select_key' => '',
                'menu_type' => '1',
                'icon' => 'nc-iconfont nc-icon-jifen',
                'api_url' => 'erp/pricing/lists',
                'router_path' => 'hsx_erp/pricing',
                'view_path' => 'pricing/list',
                'methods' => 'get',
                'sort' => '95',
                'status' => '1',
                // 独立"销售定价"页已并入「设备流转」内联定价/调价，菜单不再展示（保留节点维持定价接口权限）
                'is_show' => '0',
                'children' => [
                    [
                        'menu_name' => '定价详情',
                        'menu_key' => 'hsx_erp_pricing_info',
                        'menu_short_name' => '定价详情',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'erp/pricing/asset/<asset_id>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'get',
                        'sort' => '90',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '保存销售定价',
                        'menu_key' => 'hsx_erp_pricing_save',
                        'menu_short_name' => '保存销售定价',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'erp/pricing/asset/<asset_id>/price',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '80',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                ],
            ],
            [
                'menu_name' => '卖同行待办',
                'menu_key' => 'hsx_erp_peer_sale_todo',
                'menu_short_name' => '卖同行待办',
                'parent_select_key' => '',
                'menu_type' => '1',
                'icon' => 'nc-iconfont nc-icon-dingdan',
                'api_url' => 'erp/outbound/peer_sale_todo',
                'router_path' => 'hsx_erp/peer_sale_todo',
                'view_path' => 'peer_sale_todo/index',
                'methods' => 'get',
                'sort' => '63',
                'status' => '1',
                'is_show' => '1',
            ],
            [
                'menu_name' => '出库管理',
                'menu_key' => 'hsx_erp_outbound_list',
                'menu_short_name' => '出库管理',
                'parent_select_key' => '',
                'menu_type' => '1',
                'icon' => 'nc-iconfont nc-icon-chuku',
                'api_url' => 'erp/outbound/lists',
                'router_path' => 'hsx_erp/outbound',
                'view_path' => 'outbound/list',
                'methods' => 'get',
                'sort' => '65',
                'status' => '1',
                'is_show' => '1',
                'children' => [
                    [
                        'menu_name' => '出库单详情',
                        'menu_key' => 'hsx_erp_outbound_info',
                        'menu_short_name' => '出库单详情',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'erp/outbound/<id>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'get',
                        'sort' => '95',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '新建出库',
                        'menu_key' => 'hsx_erp_outbound_create',
                        'menu_short_name' => '新建出库',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'erp/outbound/create',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '90',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '回填价格',
                        'menu_key' => 'hsx_erp_outbound_fill_price',
                        'menu_short_name' => '回填价格',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'erp/outbound/<id>/fill_price',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '85',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '设备调拨',
                        'menu_key' => 'hsx_erp_outbound_transfer',
                        'menu_short_name' => '设备调拨',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'erp/outbound/transfer',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '80',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '出库退回',
                        'menu_key' => 'hsx_erp_outbound_cancel',
                        'menu_short_name' => '出库退回',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'erp/outbound/<id>/cancel',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '78',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                ],
            ],
            [
                'menu_name' => '基础配置',
                'menu_key' => 'hsx_erp_config_group',
                'menu_short_name' => '基础配置',
                'parent_select_key' => '',
                'menu_type' => '0',
                'icon' => 'nc-iconfont nc-icon-shezhi',
                'api_url' => '',
                'router_path' => '',
                'view_path' => '',
                'methods' => '',
                'sort' => '60',
                'status' => '1',
                'is_show' => '1',
                'children' => [
                    [
                        'menu_name' => '角色与权限',
                        'menu_key' => 'hsx_erp_role_preset',
                        'menu_short_name' => '角色与权限',
                        'parent_select_key' => '',
                        'menu_type' => '1',
                        'icon' => 'nc-iconfont nc-icon-quanxian',
                        'api_url' => 'erp/role_preset/preview',
                        'router_path' => 'hsx_erp/role_preset',
                        'view_path' => 'role_preset/index',
                        'methods' => 'get',
                        'sort' => '130',
                        'status' => '1',
                        'is_show' => '1',
                        'children' => [
                            [
                                'menu_name' => '一键生成推荐角色',
                                'menu_key' => 'hsx_erp_role_preset_generate',
                                'menu_short_name' => '一键生成推荐角色',
                                'parent_select_key' => '',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'erp/role_preset/generate',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'post',
                                'sort' => '10',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                        ],
                    ],
                    [
                        'menu_name' => '往来单位',
                        'menu_key' => 'hsx_erp_counterparty_list',
                        'menu_short_name' => '往来单位',
                        'parent_select_key' => '',
                        'menu_type' => '1',
                        'icon' => 'nc-iconfont nc-icon-huiyuan',
                        'api_url' => 'erp/counterparty/lists',
                        'router_path' => 'hsx_erp/counterparty',
                        'view_path' => 'counterparty/list',
                        'methods' => 'get',
                        'sort' => '125',
                        'status' => '1',
                        'is_show' => '1',
                        'children' => [
                            [
                                'menu_name' => '往来单位选项',
                                'menu_key' => 'hsx_erp_counterparty_options',
                                'menu_short_name' => '往来单位选项',
                                'parent_select_key' => '',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'erp/counterparty/options',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'get',
                                'sort' => '100',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                            [
                                'menu_name' => '保存往来单位',
                                'menu_key' => 'hsx_erp_counterparty_save',
                                'menu_short_name' => '保存往来单位',
                                'parent_select_key' => '',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'erp/counterparty/save/<id>',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'post',
                                'sort' => '90',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                        ],
                    ],
                    [
                        'menu_name' => '仓库与库位',
                        'menu_key' => 'hsx_erp_warehouse_list',
                        'menu_short_name' => '仓库与库位',
                        'parent_select_key' => '',
                        'menu_type' => '1',
                        'icon' => 'nc-iconfont nc-icon-cangku',
                        'api_url' => 'erp/warehouse/lists',
                        'router_path' => 'hsx_erp/warehouse',
                        'view_path' => 'warehouse/list',
                        'methods' => 'get',
                        'sort' => '120',
                        'status' => '1',
                        'is_show' => '1',
                        'children' => [
                            [
                                'menu_name' => '仓库选项',
                                'menu_key' => 'hsx_erp_warehouse_options',
                                'menu_short_name' => '仓库选项',
                                'parent_select_key' => '',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'erp/warehouse/options',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'get',
                                'sort' => '110',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                            [
                                'menu_name' => '保存仓库与库位',
                                'menu_key' => 'hsx_erp_warehouse_save',
                                'menu_short_name' => '保存仓库与库位',
                                'parent_select_key' => '',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'erp/warehouse/save/<id>',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'post',
                                'sort' => '100',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                            [
                                'menu_name' => '保存库位',
                                'menu_key' => 'hsx_erp_warehouse_location_save',
                                'menu_short_name' => '保存库位',
                                'parent_select_key' => '',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'erp/warehouse/<warehouse_id>/location/save/<id>',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'post',
                                'sort' => '90',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                            [
                                'menu_name' => '删除仓库',
                                'menu_key' => 'hsx_erp_warehouse_delete',
                                'menu_short_name' => '删除仓库',
                                'parent_select_key' => '',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'erp/warehouse/<id>',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'delete',
                                'sort' => '80',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                            [
                                'menu_name' => '删除库位',
                                'menu_key' => 'hsx_erp_warehouse_location_delete',
                                'menu_short_name' => '删除库位',
                                'parent_select_key' => '',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'erp/warehouse/location/<id>',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'delete',
                                'sort' => '70',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                        ],
                    ],
                    [
                        'menu_name' => '库位责任',
                        'menu_key' => 'hsx_erp_location_assign_list',
                        'menu_short_name' => '库位责任',
                        'parent_select_key' => '',
                        'menu_type' => '1',
                        'icon' => 'nc-iconfont nc-icon-yonghu',
                        'api_url' => 'erp/location_assign/lists',
                        'router_path' => 'hsx_erp/location_assign',
                        'view_path' => 'location_assign/list',
                        'methods' => 'get',
                        'sort' => '115',
                        'status' => '1',
                        'is_show' => '1',
                        'children' => [
                            [
                                'menu_name' => '仓库库位树',
                                'menu_key' => 'hsx_erp_location_assign_tree',
                                'menu_short_name' => '仓库库位树',
                                'parent_select_key' => '',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'erp/location_assign/tree',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'get',
                                'sort' => '100',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                            [
                                'menu_name' => '可分配员工',
                                'menu_key' => 'hsx_erp_location_assign_staff_options',
                                'menu_short_name' => '可分配员工',
                                'parent_select_key' => '',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'erp/location_assign/staff_options',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'get',
                                'sort' => '90',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                            [
                                'menu_name' => '设置库位负责人',
                                'menu_key' => 'hsx_erp_location_assign_set_location',
                                'menu_short_name' => '设置库位负责人',
                                'parent_select_key' => '',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'erp/location_assign/location/<location_id>/staff',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'post',
                                'sort' => '80',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                            [
                                'menu_name' => '设置员工负责库位',
                                'menu_key' => 'hsx_erp_location_assign_set_staff',
                                'menu_short_name' => '设置员工负责库位',
                                'parent_select_key' => '',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'erp/location_assign/staff/<uid>/locations',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'post',
                                'sort' => '70',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                        ],
                    ],
                ],
            ],
            [
                'menu_name' => '设备追溯',
                'menu_key' => 'hsx_erp_device_trace',
                'menu_short_name' => '设备追溯',
                'parent_select_key' => '',
                'menu_type' => '1',
                'icon' => 'nc-iconfont nc-icon-sousuo',
                'api_url' => 'erp/device_trace/search',
                'router_path' => 'hsx_erp/device_trace',
                'view_path' => 'device_trace/index',
                'methods' => 'get',
                'sort' => '58',
                'status' => '1',
                'is_show' => '1',
                'children' => [
                    [
                        'menu_name' => '追溯详情',
                        'menu_key' => 'hsx_erp_device_trace_detail',
                        'menu_short_name' => '追溯详情',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'erp/device_trace/detail',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'get',
                        'sort' => '90',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                ],
            ],
            [
                'menu_name' => '库存盘点',
                'menu_key' => 'hsx_erp_stocktake_list',
                'menu_short_name' => '库存盘点',
                'parent_select_key' => '',
                'menu_type' => '1',
                'icon' => 'nc-iconfont nc-icon-pandian',
                'api_url' => 'erp/stocktake/lists',
                'router_path' => 'hsx_erp/stocktake',
                'view_path' => 'stocktake/list',
                'methods' => 'get',
                'sort' => '63',
                'status' => '1',
                'is_show' => '1',
                'children' => [
                    [
                        'menu_name' => '盘点单详情',
                        'menu_key' => 'hsx_erp_stocktake_info',
                        'menu_short_name' => '盘点单详情',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'erp/stocktake/<id>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'get',
                        'sort' => '95',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '新建盘点',
                        'menu_key' => 'hsx_erp_stocktake_create',
                        'menu_short_name' => '新建盘点',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'erp/stocktake/create',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '90',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '录入实物',
                        'menu_key' => 'hsx_erp_stocktake_scan',
                        'menu_short_name' => '录入实物',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'erp/stocktake/<id>/scan',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '85',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '完成盘点',
                        'menu_key' => 'hsx_erp_stocktake_finish',
                        'menu_short_name' => '完成盘点',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'erp/stocktake/<id>/finish',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '80',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                ],
            ],
            [
                'menu_name' => '按设备对账',
                'menu_key' => 'hsx_erp_finance_reconciliation',
                'menu_short_name' => '按设备对账',
                'parent_select_key' => '',
                'menu_type' => '1',
                'icon' => 'nc-iconfont nc-icon-duizhang',
                'api_url' => 'erp/finance/reconciliation',
                'router_path' => 'hsx_erp/finance_reconciliation',
                'view_path' => 'finance/reconciliation',
                'methods' => 'get',
                'sort' => '58',
                'status' => '1',
                'is_show' => '1',
            ],
            [
                'menu_name' => '财务中心',
                'menu_key' => 'hsx_erp_finance_board',
                'menu_short_name' => '财务中心',
                'parent_select_key' => '',
                'menu_type' => '1',
                'icon' => 'nc-iconfont nc-icon-qianbao',
                'api_url' => 'erp/finance/board',
                'router_path' => 'hsx_erp/finance',
                'view_path' => 'finance/board',
                'methods' => 'get',
                'sort' => '60',
                'status' => '1',
                'is_show' => '1',
                'children' => [
                    [
                        'menu_name' => '应付列表',
                        'menu_key' => 'hsx_erp_finance_payable_lists',
                        'menu_short_name' => '应付列表',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'erp/finance/payable/lists',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'get',
                        'sort' => '95',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '应收列表',
                        'menu_key' => 'hsx_erp_finance_receivable_lists',
                        'menu_short_name' => '应收列表',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'erp/finance/receivable/lists',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'get',
                        'sort' => '90',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '应付待结',
                        'menu_key' => 'hsx_erp_finance_payable_outstanding',
                        'menu_short_name' => '应付待结',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'erp/finance/payable/outstanding',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'get',
                        'sort' => '85',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '应收待结',
                        'menu_key' => 'hsx_erp_finance_receivable_outstanding',
                        'menu_short_name' => '应收待结',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'erp/finance/receivable/outstanding',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'get',
                        'sort' => '80',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '结算预演',
                        'menu_key' => 'hsx_erp_finance_settlement_preview',
                        'menu_short_name' => '结算预演',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'erp/finance/settlement/preview',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '75',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '确认结算',
                        'menu_key' => 'hsx_erp_finance_settlement_settle',
                        'menu_short_name' => '确认结算',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'erp/finance/settlement/settle',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '70',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                ],
            ],
            [
                'menu_name' => '资金账户',
                'menu_key' => 'hsx_erp_capital_account_list',
                'menu_short_name' => '资金账户',
                'parent_select_key' => '',
                'menu_type' => '1',
                'icon' => 'nc-iconfont nc-icon-yinhangqia',
                'api_url' => 'erp/capital_account/lists',
                'router_path' => 'hsx_erp/capital_account',
                'view_path' => 'capital_account/list',
                'methods' => 'get',
                'sort' => '55',
                'status' => '1',
                'is_show' => '1',
                'children' => [
                    [
                        'menu_name' => '保存账户',
                        'menu_key' => 'hsx_erp_capital_account_save',
                        'menu_short_name' => '保存账户',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'erp/capital_account/save/<id>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '90',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '删除账户',
                        'menu_key' => 'hsx_erp_capital_account_delete',
                        'menu_short_name' => '删除账户',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'erp/capital_account/<id>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'delete',
                        'sort' => '85',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '记一笔收付',
                        'menu_key' => 'hsx_erp_capital_account_entry',
                        'menu_short_name' => '记一笔收付',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'erp/capital_account/entry',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '80',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '账目往来流水',
                        'menu_key' => 'hsx_erp_capital_account_ledger',
                        'menu_short_name' => '账目往来流水',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'erp/capital_account/ledger',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'get',
                        'sort' => '75',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                ],
            ],
            [
                'menu_name' => 'AI 助手',
                'menu_key' => 'hsx_erp_ai',
                'menu_short_name' => 'AI 助手',
                'parent_select_key' => '',
                'menu_type' => '0',
                'icon' => '',
                'api_url' => '',
                'router_path' => 'hsx_erp/ai',
                'view_path' => '',
                'methods' => '',
                'sort' => '70',
                'status' => '1',
                'is_show' => '1',
                'children' => [
                    [
                        'menu_name' => 'AI 测试对话',
                        'menu_key' => 'hsx_erp_ai_chat',
                        'menu_short_name' => 'AI 对话',
                        'parent_select_key' => '',
                        'menu_type' => '1',
                        'icon' => '',
                        'api_url' => '',
                        'router_path' => 'hsx_erp/ai_chat',
                        'view_path' => 'ai/chat',
                        'methods' => '',
                        'sort' => '70',
                        'status' => '1',
                        'is_show' => '1',
                        'children' => [
                            [
                                'menu_name' => '发起对话',
                                'menu_key' => 'hsx_erp_ai_chat_send',
                                'menu_short_name' => '发起对话',
                                'parent_select_key' => '',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'erp/ai/chat',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'post',
                                'sort' => '70',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                            [
                                'menu_name' => '读取模型列表',
                                'menu_key' => 'hsx_erp_ai_models',
                                'menu_short_name' => '读取模型',
                                'parent_select_key' => '',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'erp/ai/models',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'get',
                                'sort' => '65',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                        ],
                    ],
                    [
                        'menu_name' => 'AI 配置',
                        'menu_key' => 'hsx_erp_ai_config',
                        'menu_short_name' => 'AI 配置',
                        'parent_select_key' => '',
                        'menu_type' => '1',
                        'icon' => '',
                        'api_url' => '',
                        'router_path' => 'hsx_erp/ai_config',
                        'view_path' => 'ai/config',
                        'methods' => '',
                        'sort' => '60',
                        'status' => '1',
                        'is_show' => '1',
                        'children' => [
                            [
                                'menu_name' => '读取AI配置',
                                'menu_key' => 'hsx_erp_ai_config_get',
                                'menu_short_name' => '读取配置',
                                'parent_select_key' => '',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'erp/ai/config',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'get',
                                'sort' => '60',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                            [
                                'menu_name' => '保存AI配置',
                                'menu_key' => 'hsx_erp_ai_config_save',
                                'menu_short_name' => '保存配置',
                                'parent_select_key' => '',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'erp/ai/config',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'post',
                                'sort' => '55',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                            [
                                'menu_name' => '连通性测试',
                                'menu_key' => 'hsx_erp_ai_ping',
                                'menu_short_name' => '连通测试',
                                'parent_select_key' => '',
                                'menu_type' => '2',
                                'icon' => '',
                                'api_url' => 'erp/ai/ping',
                                'router_path' => '',
                                'view_path' => '',
                                'methods' => 'post',
                                'sort' => '50',
                                'status' => '1',
                                'is_show' => '0',
                            ],
                        ],
                    ],
                    [
                        'menu_name' => '场景清单',
                        'menu_key' => 'hsx_erp_ai_scenes',
                        'menu_short_name' => '场景清单',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'erp/ai/scenes',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'get',
                        'sort' => '45',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => 'AI场景执行',
                        'menu_key' => 'hsx_erp_ai_run',
                        'menu_short_name' => '场景执行',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'erp/ai/run',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '44',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => 'AI流式执行',
                        'menu_key' => 'hsx_erp_ai_stream',
                        'menu_short_name' => '流式执行',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'erp/ai/stream',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '43',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => 'AI总结(按钮)',
                        'menu_key' => 'hsx_erp_ai_summary',
                        'menu_short_name' => 'AI总结',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => '',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => '',
                        'sort' => '43',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => 'AI财务分析(按钮)',
                        'menu_key' => 'hsx_erp_ai_finance',
                        'menu_short_name' => 'AI财务',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => '',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => '',
                        'sort' => '42',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => 'AI经营分析(按钮)',
                        'menu_key' => 'hsx_erp_ai_report',
                        'menu_short_name' => 'AI经营',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => '',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => '',
                        'sort' => '41',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => 'AI验机(按钮)',
                        'menu_key' => 'hsx_erp_ai_inspect',
                        'menu_short_name' => 'AI验机',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => '',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => '',
                        'sort' => '40',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '对话历史列表',
                        'menu_key' => 'hsx_erp_ai_conv_list',
                        'menu_short_name' => '对话历史',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'erp/ai/conversations',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'get',
                        'sort' => '39',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '对话详情',
                        'menu_key' => 'hsx_erp_ai_conv_detail',
                        'menu_short_name' => '对话详情',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'erp/ai/conversation/<id>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'get',
                        'sort' => '38',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '保存对话',
                        'menu_key' => 'hsx_erp_ai_conv_save',
                        'menu_short_name' => '保存对话',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'erp/ai/conversation/save',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'post',
                        'sort' => '37',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                    [
                        'menu_name' => '删除对话',
                        'menu_key' => 'hsx_erp_ai_conv_delete',
                        'menu_short_name' => '删除对话',
                        'parent_select_key' => '',
                        'menu_type' => '2',
                        'icon' => '',
                        'api_url' => 'erp/ai/conversation/<id>',
                        'router_path' => '',
                        'view_path' => '',
                        'methods' => 'delete',
                        'sort' => '36',
                        'status' => '1',
                        'is_show' => '0',
                    ],
                ],
            ],
        ],
    ],
];