<?php
return [
    [
        'menu_name' => 'DH速收报价',
        'menu_key' => 'recycle_daheng_quote',
        'menu_short_name' => 'DH报价',
        'parent_select_key' => '',
        'parent_key' => 'recycle_category_manage',
        'menu_type' => '0',
        'icon' => 'nc-iconfont nc-icon-liebiaoV6xx',
        'api_url' => '',
        'router_path' => '',
        'view_path' => '',
        'methods' => '',
        'sort' => '98',
        'status' => '1',
        'is_show' => '0',
    ],
    [
        'menu_name' => 'DH报价工作台',
        'menu_key' => 'recycle_daheng_quote_workbench',
        'menu_short_name' => '报价工作台',
        'parent_select_key' => '',
        'parent_key' => 'recycle_category_manage',
        'menu_type' => '1',
        'icon' => '',
        'api_url' => 'recycle_daheng_quote/quotation_v2/dataset',
        'router_path' => 'recycle_daheng_quote/v2_workbench',
        'view_path' => 'v2_workbench',
        'methods' => 'get',
        'sort' => '98',
        'status' => '1',
        'is_show' => '1',
        'children' => [
            [
                'menu_name' => '报价源管理',
                'menu_key' => 'recycle_daheng_quote_dataset',
                'menu_short_name' => '报价源管理',
                'parent_select_key' => '',
                'menu_type' => '2',
                'icon' => '',
                'api_url' => 'recycle_daheng_quote/quotation_v2/dataset',
                'router_path' => '',
                'view_path' => '',
                'methods' => 'get',
                'sort' => '90',
                'status' => '1',
                'is_show' => '0',
            ],
            [
                'menu_name' => '保存报价源',
                'menu_key' => 'recycle_daheng_quote_dataset_save',
                'menu_short_name' => '保存报价源',
                'parent_select_key' => '',
                'menu_type' => '2',
                'icon' => '',
                'api_url' => 'recycle_daheng_quote/quotation_v2/dataset',
                'router_path' => '',
                'view_path' => '',
                'methods' => 'post',
                'sort' => '89',
                'status' => '1',
                'is_show' => '0',
            ],
            [
                'menu_name' => '同步报价',
                'menu_key' => 'recycle_daheng_quote_sync',
                'menu_short_name' => '同步报价',
                'parent_select_key' => '',
                'menu_type' => '2',
                'icon' => '',
                'api_url' => 'recycle_daheng_quote/quotation_v2/sync/now/<datasetId>',
                'router_path' => '',
                'view_path' => '',
                'methods' => 'post',
                'sort' => '80',
                'status' => '1',
                'is_show' => '0',
            ],
            [
                'menu_name' => '报价数据维护',
                'menu_key' => 'recycle_daheng_quote_manage',
                'menu_short_name' => '报价数据维护',
                'parent_select_key' => '',
                'menu_type' => '2',
                'icon' => '',
                'api_url' => 'recycle_daheng_quote/quotation_v2/model',
                'router_path' => '',
                'view_path' => '',
                'methods' => 'get',
                'sort' => '70',
                'status' => '1',
                'is_show' => '0',
            ],
        ],
    ],
    [
        'menu_name' => 'DH爬虫配置',
        'menu_key' => 'recycle_daheng_quote_config',
        'menu_short_name' => '爬虫配置',
        'parent_select_key' => '',
        'parent_key' => 'recycle_category_manage',
        'menu_type' => '1',
        'icon' => '',
        'api_url' => 'recycle_daheng_quote/quotation_crawler_config',
        'router_path' => 'recycle_daheng_quote/config',
        'view_path' => 'config',
        'methods' => 'get',
        'sort' => '97',
        'status' => '1',
        'is_show' => '1',
        'children' => [
            [
                'menu_name' => '保存爬虫配置',
                'menu_key' => 'recycle_daheng_quote_config_save',
                'menu_short_name' => '保存爬虫配置',
                'parent_select_key' => '',
                'menu_type' => '2',
                'icon' => '',
                'api_url' => 'recycle_daheng_quote/quotation_crawler_config',
                'router_path' => '',
                'view_path' => '',
                'methods' => 'post',
                'sort' => '2',
                'status' => '1',
                'is_show' => '0',
            ],
            [
                'menu_name' => '默认爬虫配置',
                'menu_key' => 'recycle_daheng_quote_config_default',
                'menu_short_name' => '默认爬虫配置',
                'parent_select_key' => '',
                'menu_type' => '2',
                'icon' => '',
                'api_url' => 'recycle_daheng_quote/quotation_crawler_config/default',
                'router_path' => '',
                'view_path' => '',
                'methods' => 'get',
                'sort' => '1',
                'status' => '1',
                'is_show' => '0',
            ],
        ],
    ],
];