<?php

return [
    [
        'menu_name' => '校园帮',
        'menu_key' => 'sd_xiaoyuan',
        'menu_type' => 1,
        'icon' => 'iconfont-xiaoyuan',
        'api_url' => '',
        'router_path' => '',
        'view_path' => '',
        'methods' => '',
        'sort' => 100,
        'status' => 1,
        'is_show' => 1,
        'children' => [
            [
                'menu_name' => '数据概览',
                'menu_key' => 'sd_xiaoyuan_dashboard',
                'menu_type' => 1,
                'icon' => 'icon-chart-line',
                'api_url' => '',
                'router_path' => 'sd_xiaoyuan/dashboard',
                'view_path' => 'addon/sd_xiaoyuan/views/dashboard/index',
                'methods' => 'GET',
                'sort' => 1,
                'status' => 1,
                'is_show' => 1
            ],
            [
                'menu_name' => '订单管理',
                'menu_key' => 'sd_xiaoyuan_order',
                'menu_type' => 1,
                'icon' => 'icon-file-list',
                'api_url' => '',
                'router_path' => 'sd_xiaoyuan/order',
                'view_path' => 'addon/sd_xiaoyuan/views/order/list',
                'methods' => 'GET',
                'sort' => 2,
                'status' => 1,
                'is_show' => 1
            ],
            [
                'menu_name' => '接单员管理',
                'menu_key' => 'sd_xiaoyuan_runner',
                'menu_type' => 1,
                'icon' => 'icon-user-group',
                'api_url' => '',
                'router_path' => 'sd_xiaoyuan/runner',
                'view_path' => 'addon/sd_xiaoyuan/views/runner/list',
                'methods' => 'GET',
                'sort' => 3,
                'status' => 1,
                'is_show' => 1
            ],
            [
                'menu_name' => '校园认证',
                'menu_key' => 'sd_xiaoyuan_campus_auth',
                'menu_type' => 1,
                'icon' => 'icon-shield-check',
                'api_url' => '',
                'router_path' => 'sd_xiaoyuan/campus_auth',
                'view_path' => 'addon/sd_xiaoyuan/views/campus_auth/list',
                'methods' => 'GET',
                'sort' => 4,
                'status' => 1,
                'is_show' => 1
            ],
            [
                'menu_name' => '提现管理',
                'menu_key' => 'sd_xiaoyuan_withdraw',
                'menu_type' => 1,
                'icon' => 'icon-money-withdraw',
                'api_url' => '',
                'router_path' => 'sd_xiaoyuan/withdraw',
                'view_path' => 'addon/sd_xiaoyuan/views/withdraw/list',
                'methods' => 'GET',
                'sort' => 5,
                'status' => 1,
                'is_show' => 1
            ],
            [
                'menu_name' => '评价管理',
                'menu_key' => 'sd_xiaoyuan_evaluate',
                'menu_type' => 1,
                'icon' => 'icon-star',
                'api_url' => '',
                'router_path' => 'sd_xiaoyuan/evaluate',
                'view_path' => 'addon/sd_xiaoyuan/views/evaluate/list',
                'methods' => 'GET',
                'sort' => 6,
                'status' => 1,
                'is_show' => 1
            ],
            [
                'menu_name' => '申诉管理',
                'menu_key' => 'sd_xiaoyuan_appeal',
                'menu_type' => 1,
                'icon' => 'icon-message-warning',
                'api_url' => '',
                'router_path' => 'sd_xiaoyuan/appeal',
                'view_path' => 'addon/sd_xiaoyuan/views/appeal/list',
                'methods' => 'GET',
                'sort' => 7,
                'status' => 1,
                'is_show' => 1
            ],
            [
                'menu_name' => '优惠券管理',
                'menu_key' => 'sd_xiaoyuan_coupon',
                'menu_type' => 1,
                'icon' => 'icon-ticket',
                'api_url' => '',
                'router_path' => 'sd_xiaoyuan/coupon',
                'view_path' => 'addon/sd_xiaoyuan/views/coupon/list',
                'methods' => 'GET',
                'sort' => 8,
                'status' => 1,
                'is_show' => 1
            ],
            [
                'menu_name' => '系统配置',
                'menu_key' => 'sd_xiaoyuan_config',
                'menu_type' => 1,
                'icon' => 'icon-setting',
                'api_url' => '',
                'router_path' => 'sd_xiaoyuan/config',
                'view_path' => 'addon/sd_xiaoyuan/views/config/index',
                'methods' => 'GET',
                'sort' => 9,
                'status' => 1,
                'is_show' => 1
            ],
            [
                'menu_name' => '树洞管理',
                'menu_key' => 'sd_xiaoyuan_community',
                'menu_type' => 1,
                'icon' => 'icon-message-circle',
                'api_url' => '',
                'router_path' => 'sd_xiaoyuan/community',
                'view_path' => 'addon/sd_xiaoyuan/views/community/list',
                'methods' => 'GET',
                'sort' => 10,
                'status' => 1,
                'is_show' => 1
            ],
            [
                'menu_name' => '表白墙管理',
                'menu_key' => 'sd_xiaoyuan_confession',
                'menu_type' => 1,
                'icon' => 'icon-heart',
                'api_url' => '',
                'router_path' => 'sd_xiaoyuan/confession',
                'view_path' => 'addon/sd_xiaoyuan/views/confession/list',
                'methods' => 'GET',
                'sort' => 11,
                'status' => 1,
                'is_show' => 1
            ],
            [
                'menu_name' => '签到管理',
                'menu_key' => 'sd_xiaoyuan_sign',
                'menu_type' => 1,
                'icon' => 'icon-calendar-check',
                'api_url' => '',
                'router_path' => 'sd_xiaoyuan/sign',
                'view_path' => 'addon/sd_xiaoyuan/views/sign/index',
                'methods' => 'GET',
                'sort' => 12,
                'status' => 1,
                'is_show' => 1
            ],
            [
                'menu_name' => '邀请分销',
                'menu_key' => 'sd_xiaoyuan_invite',
                'menu_type' => 1,
                'icon' => 'icon-share',
                'api_url' => '',
                'router_path' => 'sd_xiaoyuan/invite',
                'view_path' => 'addon/sd_xiaoyuan/views/invite/index',
                'methods' => 'GET',
                'sort' => 13,
                'status' => 1,
                'is_show' => 1
            ],
            [
                'menu_name' => '房屋租赁',
                'menu_key' => 'sd_xiaoyuan_house',
                'menu_type' => 1,
                'icon' => 'icon-home',
                'api_url' => '',
                'router_path' => 'sd_xiaoyuan/house',
                'view_path' => 'addon/sd_xiaoyuan/views/house/list',
                'methods' => 'GET',
                'sort' => 14,
                'status' => 1,
                'is_show' => 1
            ],
            [
                'menu_name' => '树洞分类',
                'menu_key' => 'sd_xiaoyuan_community_category',
                'menu_type' => 1,
                'icon' => 'icon-folder',
                'api_url' => '',
                'router_path' => 'sd_xiaoyuan/community_category',
                'view_path' => 'addon/sd_xiaoyuan/views/community/category',
                'methods' => 'GET',
                'sort' => 15,
                'status' => 1,
                'is_show' => 1
            ],
            [
                'menu_name' => '评论管理',
                'menu_key' => 'sd_xiaoyuan_comment',
                'menu_type' => 1,
                'icon' => 'icon-message',
                'api_url' => '',
                'router_path' => 'sd_xiaoyuan/comment',
                'view_path' => 'addon/sd_xiaoyuan/views/comment/list',
                'methods' => 'GET',
                'sort' => 16,
                'status' => 1,
                'is_show' => 1
            ],
            [
                'menu_name' => '接单员等级',
                'menu_key' => 'sd_xiaoyuan_runner_level',
                'menu_type' => 1,
                'icon' => 'icon-medal',
                'api_url' => '',
                'router_path' => 'sd_xiaoyuan/runner_level',
                'view_path' => 'addon/sd_xiaoyuan/views/runner/level',
                'methods' => 'GET',
                'sort' => 17,
                'status' => 1,
                'is_show' => 1
            ],
            [
                'menu_name' => '数据统计',
                'menu_key' => 'sd_xiaoyuan_stat',
                'menu_type' => 1,
                'icon' => 'icon-bar-chart',
                'api_url' => '',
                'router_path' => 'sd_xiaoyuan/stat',
                'view_path' => 'addon/sd_xiaoyuan/views/stat/index',
                'methods' => 'GET',
                'sort' => 18,
                'status' => 1,
                'is_show' => 1
            ],
            [
                'menu_name' => '学校管理',
                'menu_key' => 'sd_xiaoyuan_school',
                'menu_type' => 1,
                'icon' => 'icon-school',
                'api_url' => '',
                'router_path' => 'sd_xiaoyuan/school',
                'view_path' => 'addon/sd_xiaoyuan/views/school/list',
                'methods' => 'GET',
                'sort' => 19,
                'status' => 1,
                'is_show' => 1
            ],
            [
                'menu_name' => '任务悬赏',
                'menu_key' => 'sd_xiaoyuan_task',
                'menu_type' => 1,
                'icon' => 'icon-task',
                'api_url' => '',
                'router_path' => 'sd_xiaoyuan/task',
                'view_path' => 'addon/sd_xiaoyuan/views/task/list',
                'methods' => 'GET',
                'sort' => 20,
                'status' => 1,
                'is_show' => 1
            ],
            [
                'menu_name' => '拼单好饭',
                'menu_key' => 'sd_xiaoyuan_group_order',
                'menu_type' => 1,
                'icon' => 'icon-food',
                'api_url' => '',
                'router_path' => 'sd_xiaoyuan/group_order',
                'view_path' => 'addon/sd_xiaoyuan/views/group_order/list',
                'methods' => 'GET',
                'sort' => 21,
                'status' => 1,
                'is_show' => 1
            ],
            [
                'menu_name' => '二手交易',
                'menu_key' => 'sd_xiaoyuan_secondhand',
                'menu_type' => 1,
                'icon' => 'icon-shopping',
                'api_url' => '',
                'router_path' => 'sd_xiaoyuan/secondhand',
                'view_path' => 'addon/sd_xiaoyuan/views/secondhand/list',
                'methods' => 'GET',
                'sort' => 22,
                'status' => 1,
                'is_show' => 1
            ],
            [
                'menu_name' => '失物招领',
                'menu_key' => 'sd_xiaoyuan_lost_found',
                'menu_type' => 1,
                'icon' => 'icon-search',
                'api_url' => '',
                'router_path' => 'sd_xiaoyuan/lost_found',
                'view_path' => 'addon/sd_xiaoyuan/views/lost_found/list',
                'methods' => 'GET',
                'sort' => 23,
                'status' => 1,
                'is_show' => 1
            ],
            [
                'menu_name' => '系统消息',
                'menu_key' => 'sd_xiaoyuan_message',
                'menu_type' => 1,
                'icon' => 'icon-notification',
                'api_url' => '',
                'router_path' => 'sd_xiaoyuan/message',
                'view_path' => 'addon/sd_xiaoyuan/views/message/list',
                'methods' => 'GET',
                'sort' => 24,
                'status' => 1,
                'is_show' => 1
            ],
            [
                'menu_name' => '信誉分管理',
                'menu_key' => 'sd_xiaoyuan_credit',
                'menu_type' => 1,
                'icon' => 'icon-credit',
                'api_url' => '',
                'router_path' => 'sd_xiaoyuan/credit',
                'view_path' => 'addon/sd_xiaoyuan/views/credit/list',
                'methods' => 'GET',
                'sort' => 25,
                'status' => 1,
                'is_show' => 1
            ],
            [
                'menu_name' => '积分商城',
                'menu_key' => 'sd_xiaoyuan_points',
                'menu_type' => 1,
                'icon' => 'icon-gift',
                'api_url' => '',
                'router_path' => 'sd_xiaoyuan/points',
                'view_path' => 'addon/sd_xiaoyuan/views/points/goods',
                'methods' => 'GET',
                'sort' => 26,
                'status' => 1,
                'is_show' => 1
            ],
            [
                'menu_name' => '积分兑换订单',
                'menu_key' => 'sd_xiaoyuan_points_orders',
                'menu_type' => 1,
                'icon' => 'icon-order-list',
                'api_url' => '',
                'router_path' => 'sd_xiaoyuan/points_orders',
                'view_path' => 'addon/sd_xiaoyuan/views/points/orders',
                'methods' => 'GET',
                'sort' => 27,
                'status' => 1,
                'is_show' => 1
            ]
        ]
    ]
];
